# Generated by Django 5.1.15 on 2026-09-19 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0032_customuser_calendrier_hegirien'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.CharField(max_length=60)),
                ('object_id', models.PositiveBigIntegerField()),
                ('features_json', models.JSONField(blank=True, default=dict)),
                ('calcule_le', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Vecteur de features',
                'verbose_name_plural': 'Vecteurs de features',
                'ordering': ['content_type', 'object_id'],
                'indexes': [models.Index(fields=['company', 'content_type'], name='mlops_featvec_co_ct_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'content_type', 'object_id'), name='uniq_mlops_featvec_co_ct_obj')],
            },
        ),
        migrations.CreateModel(
            name='ModeleML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(choices=[('churn', 'Risque de churn'), ('win_proba', 'Probabilité de gain (devis)'), ('retard_paiement', 'Retard de paiement'), ('reappro', 'Réapprovisionnement (seuil stock)'), ('anomalie', "Détection d'anomalie")], max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text="Numéro de version (le PLUS RÉCENT n'est pas forcément l'actif — voir « actif »).")),
                ('params_json', models.JSONField(blank=True, default=dict, help_text='Hyperparamètres/seuils de CETTE version (schéma libre, propre à chaque scorer — interprété par lui seul).')),
                ('actif', models.BooleanField(default=False, help_text='Version RÉELLEMENT utilisée par le scorer pour cette société (au plus une par scorer).')),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Version de modèle ML',
                'verbose_name_plural': 'Versions de modèle ML',
                'ordering': ['nom', '-version'],
                'indexes': [models.Index(fields=['company', 'nom'], name='mlops_modele_co_nom_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'nom', 'version'), name='uniq_mlops_modele_co_nom_ver'), models.UniqueConstraint(condition=models.Q(('actif', True)), fields=('company', 'nom'), name='uniq_mlops_modele_actif')],
            },
        ),
    ]
