# Generated by Django 5.1.4 on 2026-07-09 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_odx9_marketing_split'),
        ('notifications', '0025_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='whatsapp_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campagnes_marketing', to='notifications.whatsapptemplate', verbose_name='Gabarit WhatsApp (BSP)'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='email', max_length=8, verbose_name='Canal'),
        ),
    ]
