# Generated by Django 5.1.4 on 2026-07-10 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('marketing', '0002_campagne_whatsapp_template_alter_campagne_canal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseau', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('autre', 'Autre')], default='facebook', max_length=12, verbose_name='Réseau')),
                ('texte', models.TextField(blank=True, default='', verbose_name='Texte du post')),
                ('media_key', models.CharField(blank=True, default='', max_length=512, verbose_name='Média (clé MinIO)')),
                ('date_planifiee', models.DateTimeField(blank=True, null=True, verbose_name='Publication planifiée le')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifie', 'Planifié'), ('publie', 'Publié'), ('echec', 'Échec')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('rappel_envoye', models.BooleanField(default=False, verbose_name='Rappel manuel envoyé')),
                ('publie_le', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
                ('external_id', models.CharField(blank=True, default='', max_length=255, verbose_name='ID externe Meta')),
                ('erreur', models.CharField(blank=True, default='', max_length=255, verbose_name='Erreur (échec)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_sociaux', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Post réseau social',
                'verbose_name_plural': 'Posts réseaux sociaux',
                'ordering': ['-date_planifiee', '-id'],
                'indexes': [models.Index(fields=['company', 'statut', 'date_planifiee'], name='mkt_postsocial_co_st_date_idx')],
            },
        ),
    ]
