# Generated by Django 5.1.4 on 2026-08-13 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('marketing', '0003_postsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscriptionsequence',
            name='noeud_depuis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entrée sur le nœud courant'),
        ),
        migrations.AlterField(
            model_name='executionetapesequence',
            name='etape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='marketing.etapesequence', verbose_name='Étape'),
        ),
        migrations.CreateModel(
            name='NoeudJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_noeud', models.CharField(choices=[('declencheur', 'Déclencheur'), ('attente', 'Attente (J+n)'), ('attente_jusqu_a', "Attente jusqu'à"), ('action', 'Action (message / CRM)'), ('branche', 'Branche'), ('sortie', 'Sortie')], default='action', max_length=20, verbose_name='Type de nœud')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('position_x', models.IntegerField(default=0, verbose_name='Position X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Position Y')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Config')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noeuds', to='marketing.sequencerelance', verbose_name='Séquence')),
            ],
            options={
                'verbose_name': 'Nœud de journey',
                'verbose_name_plural': 'Nœuds de journey',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ArcJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('toujours', 'Toujours'), ('a_ouvert', 'A ouvert'), ('a_clique', 'A cliqué'), ('score_seuil', 'Score >= seuil'), ('tag_present', 'Tag présent')], default='toujours', max_length=20, verbose_name='Condition')),
                ('valeur', models.CharField(blank=True, default='', max_length=200, verbose_name='Valeur')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name="Ordre d'évaluation")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs_entrants', to='marketing.noeudjourney', verbose_name='Nœud cible')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs_sortants', to='marketing.noeudjourney', verbose_name='Nœud source')),
            ],
            options={
                'verbose_name': 'Arc de journey',
                'verbose_name_plural': 'Arcs de journey',
                'ordering': ['source', 'ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='executionetapesequence',
            name='noeud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='marketing.noeudjourney', verbose_name='Nœud (journey)'),
        ),
        migrations.AddField(
            model_name='inscriptionsequence',
            name='noeud_courant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_en_cours', to='marketing.noeudjourney', verbose_name='Nœud courant (journey)'),
        ),
        migrations.CreateModel(
            name='VersionFormulaireIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('titre', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre de la page')),
                ('pitch', models.TextField(blank=True, default='', verbose_name='Pitch / corps de page')),
                ('image_key', models.CharField(blank=True, default='', max_length=512, verbose_name="Image d'en-tête (clé MinIO)")),
                ('publie', models.BooleanField(default=False, verbose_name='Publiée')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Publiée le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marketing.formulaireintake', verbose_name='Formulaire')),
            ],
            options={
                'verbose_name': 'Version de landing page',
                'verbose_name_plural': 'Versions de landing page',
                'ordering': ['-version', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BlocContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du bloc')),
                ('type_bloc', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('cta', 'Bouton (CTA)')], default='texte', max_length=10, verbose_name='Type de bloc')),
                ('contenu', models.TextField(blank=True, default='', verbose_name='Fragment HTML')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Bloc de contenu',
                'verbose_name_plural': 'Blocs de contenu',
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('company', 'nom'), name='uniq_bloc_contenu_nom_par_societe')],
            },
        ),
        migrations.CreateModel(
            name='ModeleJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('categorie', models.CharField(blank=True, default='', max_length=80, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('graphe', models.JSONField(blank=True, default=dict, verbose_name='Graphe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Modèle de journey',
                'verbose_name_plural': 'Modèles de journey',
                'ordering': ['categorie', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('company', 'nom'), name='uniq_modele_journey_nom_par_societe')],
            },
        ),
        migrations.AddIndex(
            model_name='noeudjourney',
            index=models.Index(fields=['company', 'sequence'], name='mkt_noeudjrn_co_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='arcjourney',
            index=models.Index(fields=['company', 'source'], name='mkt_arcjrn_co_src_idx'),
        ),
        migrations.AddConstraint(
            model_name='versionformulaireintake',
            constraint=models.UniqueConstraint(fields=('formulaire', 'version'), name='uniq_version_formulaire_intake'),
        ),
    ]
