# Generated by Django 5.1.4 on 2026-08-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('marketing', '0004_ntmkt12_25_journey_landing_blocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='approbationenvoicampagne',
            name='rappel_envoye_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rappel de relance envoyé le'),
        ),
        migrations.CreateModel(
            name='ParametresMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expediteur_nom', models.CharField(blank=True, default='', max_length=120, verbose_name="Nom de l'expéditeur par défaut")),
                ('expediteur_email', models.EmailField(blank=True, default='', max_length=254, verbose_name="Email de l'expéditeur par défaut")),
                ('expediteur_domaine', models.CharField(blank=True, default='', max_length=120, verbose_name="Domaine d'envoi par défaut (XMKT33)")),
                ('silence_heure_debut', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aucun envoi avant (heure locale)')),
                ('silence_heure_fin', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Aucun envoi après (heure locale)')),
                ('plafond_envois_jour', models.PositiveIntegerField(blank=True, null=True, verbose_name="Plafond d'envois par jour (anti-spam)")),
                ('langue_defaut_templates', models.CharField(blank=True, default='fr', max_length=10, verbose_name='Langue par défaut des templates (XMKT11)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Paramètres marketing',
                'verbose_name_plural': 'Paramètres marketing',
                'constraints': [models.UniqueConstraint(fields=('company',), name='uniq_parametres_marketing_par_societe')],
            },
        ),
    ]
