# Generated by Django 5.1.4 on 2026-08-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('marketing', '0004_ntmkt12_journey_graphe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('categorie', models.CharField(blank=True, default='', max_length=80, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('graphe', models.JSONField(blank=True, default=dict, verbose_name='Graphe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_journey', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Modèle de journey',
                'verbose_name_plural': 'Modèles de journey',
                'ordering': ['categorie', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('company', 'nom'), name='uniq_modele_journey_nom_par_societe')],
            },
        ),
    ]
