# Generated by Django 5.1.4 on 2026-08-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('marketing', '0005_ntmkt15_modele_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionFormulaireIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('titre', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre de la page')),
                ('pitch', models.TextField(blank=True, default='', verbose_name='Pitch / corps de page')),
                ('image_key', models.CharField(blank=True, default='', max_length=512, verbose_name="Image d'en-tête (clé MinIO)")),
                ('publie', models.BooleanField(default=False, verbose_name='Publiée')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Publiée le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions_formulaire_intake', to='authentication.company', verbose_name='Société')),
                ('formulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='marketing.formulaireintake', verbose_name='Formulaire')),
            ],
            options={
                'verbose_name': 'Version de landing page',
                'verbose_name_plural': 'Versions de landing page',
                'ordering': ['-version', '-id'],
                'constraints': [models.UniqueConstraint(fields=('formulaire', 'version'), name='uniq_version_formulaire_intake')],
            },
        ),
    ]
