# Generated by Django 5.1.4 on 2026-08-13 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('marketing', '0006_ntmkt16_version_landing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du bloc')),
                ('type_bloc', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('cta', 'Bouton (CTA)')], default='texte', max_length=10, verbose_name='Type de bloc')),
                ('contenu', models.TextField(blank=True, default='', verbose_name='Fragment HTML')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocs_contenu', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Bloc de contenu',
                'verbose_name_plural': 'Blocs de contenu',
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('company', 'nom'), name='uniq_bloc_contenu_nom_par_societe')],
            },
        ),
    ]
