# Generated by Django 5.1.4 on 2026-08-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotmigration',
            name='fichier_source_cle',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage du fichier source'),
        ),
        migrations.AddField(
            model_name='lotmigration',
            name='fichier_source_nom',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name="Nom du fichier source d'origine"),
        ),
        migrations.AddField(
            model_name='projetmigration',
            name='fichiers_purges',
            field=models.BooleanField(default=False, verbose_name='Fichiers source purgés'),
        ),
    ]
