# Generated by Django 5.1.4 on 2026-08-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_ntmig35_fichiers_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotmigration',
            name='fichier_offset_lignes',
            field=models.PositiveIntegerField(default=0, verbose_name='Lignes source déjà chargées (reprise)'),
        ),
    ]
