# Generated by Django 5.1.4 (hand-written, mirrors Django's own output —
# XPLT21, local Python env pinned to Django 6.x could not run makemigrations
# against this Django 5.1.4 project; structure verified against
# apps/voip/models.py field-by-field).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0020_company_benchmarking_opt_in'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoipParametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.CharField(choices=[('noop', 'Aucun (softphone désactivé)'), ('sip_generique', 'SIP/WebRTC générique')], default='noop', max_length=20)),
                ('actif', models.BooleanField(default=False, verbose_name='Actif')),
                ('serveur_sip', models.CharField(blank=True, default='', max_length=255)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voip_parametres', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Paramètres VoIP',
                'verbose_name_plural': 'Paramètres VoIP',
            },
        ),
        migrations.CreateModel(
            name='VoipIdentifiantUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifiant_sip', models.CharField(blank=True, default='', max_length=120)),
                ('secret', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voip_identifiants', to='authentication.company')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voip_identifiant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identifiant VoIP utilisateur',
                'verbose_name_plural': 'Identifiants VoIP utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('sortant', 'Sortant'), ('entrant', 'Entrant')], max_length=10)),
                ('numero', models.CharField(max_length=40, verbose_name='Numéro (brut)')),
                ('numero_normalise', models.CharField(blank=True, default='', max_length=40)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('sonnant', 'Sonnant'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('manque', 'Manqué')], default='initie', max_length=10)),
                ('issue', models.CharField(blank=True, default='', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duree_secondes', models.PositiveIntegerField(blank=True, null=True)),
                ('fournisseur', models.CharField(blank=True, default='', max_length=20)),
                ('external_call_id', models.CharField(blank=True, default='', max_length=120)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voip_appels', to='authentication.company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voip_appels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appel VoIP',
                'verbose_name_plural': 'Appels VoIP',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='voipidentifiantutilisateur',
            index=models.Index(fields=['company', 'utilisateur'], name='voip_voipid_company_f0ec36_idx'),
        ),
        migrations.AddIndex(
            model_name='appel',
            index=models.Index(fields=['company', 'started_at'], name='voip_appel_company_420040_idx'),
        ),
        migrations.AddIndex(
            model_name='appel',
            index=models.Index(fields=['company', 'content_type', 'object_id'], name='voip_appel_company_884d7d_idx'),
        ),
    ]
