"""Nom CANONIQUE d'affichage par clé du gazetier — GÉNÉRÉ.

Généré par ``scripts/build_villes_canoniques.py`` le 2026-09-07 depuis
les exports GeoNames MA+EH (licence CC-BY 4.0), apparié par
coordonnées au gazetier ``villes_maroc`` ; exonymes français
appliqués (Marrakech, Fès, Tanger…). Aucun nom inventé : une clé
sans ligne GeoNames appariée porte son propre ``title()``.
"""

VILLES_CANONIQUES = {
    'aauamara': 'Laouamra',
    'ac ckhirat': 'Skhirate',
    'ad dakhla': 'Ad Dakhla',
    'ad darwa': 'Ad Darwa',
    'adzdir': 'Ajdir',
    'afouraire': 'Afourer',
    'afourar': 'Afourer',
    'afourer': 'Afourer',
    'afran': 'Ifrane',
    'agadair': 'Agadir',
    'agadileu': 'Agadir',
    'agadir': 'Agadir',
    'agadir akadyr': 'Agadir',
    'agadir ighir': 'Agadir',
    'agadira': 'Agadir',
    'agadiras': 'Agadir',
    'agadiru': 'Agadir',
    'agadyr': 'Agadir',
    'agdz': 'Agdz',
    'aghadyr': 'Agadir',
    'aghbala': 'Aghbala',
    'agourai': 'Agouraï',
    'aguelmous': 'Aguelmous',
    'aguelmouss': 'Aguelmous',
    'ahfir': 'Ahfir',
    'ahl sahel': 'Mirleft',
    'ai zi lu': 'Azrou',
    'ain aicha': 'Ain Aicha',
    'ain al awda': 'Ain El Aouda',
    'ain alcha': 'Ain Aicha',
    'ain attig': 'Aïn Attig',
    'ain beni mathar': 'Aïn Beni Mathar',
    'ain cheggag': 'Aïn Cheggag',
    'ain el aouda': 'Ain El Aouda',
    'ain el apuda': 'Ain El Aouda',
    'ain el harrouda': 'Aïn Harrouda',
    'ain harrouda': 'Aïn Harrouda',
    'ain karma': 'Ain Karma',
    'ain leuh': 'Aïn Leuh',
    'ain taoudjad': 'Aïn Taoujdat',
    'ain taoudjat': 'Aïn Taoujdat',
    'ain taoujat': 'Aïn Taoujdat',
    'ain taoujdat': 'Aïn Taoujdat',
    'ain taoujdate': 'Aïn Taoujdat',
    'ain tendrara': 'Tendrara',
    'ain zoren': 'Imzouren',
    'aioun sidi mellouk': 'El Aïoun',
    'ait ichek': 'Zaouïa Aït Ishak',
    'ait isehak': 'Zaouïa Aït Ishak',
    'ait ishak': 'Zaouïa Aït Ishak',
    'ait issehak': 'Zaouïa Aït Ishak',
    'ait lazza': 'Ait Yazza',
    'ait melloul': 'Ait Melloul',
    'ait ouaoumana': 'Aït Ouaoumana',
    'ait ourir': 'Ait Ourir',
    'ait shak': 'Zaouïa Aït Ishak',
    'ait taoujdate': 'Aïn Taoujdat',
    'ait urir': 'Ait Ourir',
    'ait yazza': 'Ait Yazza',
    'ajddir': 'Ajdir',
    'ajdir': 'Ajdir',
    'ajdyr': 'Ajdir',
    'ajn bni matar': 'Aïn Beni Mathar',
    'ajn ljokh': 'Aïn Leuh',
    'akadyr': 'Agadir',
    'akka': 'Akka',
    'akka centre': 'Akka',
    'aklim': 'Aklim',
    'al aaroui': 'Al Aaroui',
    'al araisz': 'Larache',
    'al brouj': 'Al Brouj',
    'al djadida': 'El Jadida',
    'al dzadida': 'El Jadida',
    'al fqih ben calah': 'Al Fqih Ben Çalah',
    'al hoceima': 'Al Hoceïma',
    'al huceima': 'Al Hoceïma',
    'al husajma': 'Al Hoceïma',
    'al husaymat': 'Al Hoceïma',
    'al jadida': 'El Jadida',
    'al khmissat': 'Khemisset',
    'al kunajtira': 'Kénitra',
    'al luwayziyah': 'Beni Yakhlef',
    'al lwiziya': 'Beni Yakhlef',
    'al m aziz': 'Al M’aziz',
    'al machouar stinia': 'Al Machouar - Stinia',
    'al mancouriya': 'El Mansouria',
    'al mediq': 'Mdiq',
    'al muhammadijja': 'Mohammedia',
    'al muhammadiyah': 'Mohammedia',
    'al qbab': 'Al Qbab',
    'al qunaytirah': 'Kénitra',
    'al rashidiyya': 'Errachidia',
    'al yadida': 'El Jadida',
    'al youn': 'El Aïoun',
    'alcazarquebir': 'Ksar El Kebir',
    'alcazarquivir': 'Ksar El Kebir',
    'alcazquivir': 'Ksar El Kebir',
    'alhacemas': 'Al Hoceïma',
    'alhrawyyn': 'Mohammedia',
    'alhsymt': 'Al Hoceïma',
    'alhucemas': 'Al Hoceïma',
    'aljdydh': 'El Jadida',
    'aljdydt': 'El Jadida',
    'allal tazi': 'Sidi Allal Tazi',
    'almachouarstinia': 'Al Machouar - Stinia',
    'almaziz': 'Al M’aziz',
    'almhmdyt': 'Mohammedia',
    'almis': 'Almis du Guigou',
    'almis du guigou': 'Almis du Guigou',
    'alnazwr': 'Nador',
    'alnif': 'Alnif',
    'alqnytrt': 'Kénitra',
    'alrbat': 'Rabat',
    'alrshydyt': 'Errachidia',
    'alsmarh': 'Smara',
    'alsmart': 'Smara',
    'alswyrt': 'Essaouira',
    'alwsrd': 'Aousserd',
    'amegdul': 'Essaouira',
    'amimiz': 'Amizmiz',
    'amismiz': 'Amizmiz',
    'amizmiz': 'Amizmiz',
    'amzourhen khemis mrabten': 'Imzouren',
    'anafi': 'Casablanca',
    'ankantir': 'Agadir',
    'aouamara': 'Laouamra',
    'aoulouz': 'Aoulouz',
    'aounat': 'Arbaa Laaounate',
    'aounate': 'Arbaa Laaounate',
    'aourir': 'Aourir',
    'aousred': 'Aousserd',
    'aousserd': 'Aousserd',
    'ar rachidiya': 'Errachidia',
    'ar raszidijja': 'Errachidia',
    'ar rommani': 'Ar Rommani',
    'ar rumman': 'Ar Rommani',
    'araishu': 'Larache',
    'arba aounate': 'Arbaa Laaounate',
    'arba laazib midar': 'Midar',
    'arbaa du aounates': 'Arbaa Laaounate',
    'arbaa laaounate': 'Arbaa Laaounate',
    'arbala': 'Aghbala',
    'arcila': 'Asilah',
    'arcilas': 'Asilah',
    'arfoud': 'Arfoud',
    'arhabala': 'Aghbala',
    'arhbala': 'Aghbala',
    'arilal': 'Azilal',
    'arsila': 'Asilah',
    'arzila': 'Asilah',
    'arzilah': 'Asilah',
    'as sawira': 'Essaouira',
    'as shawirah': 'Essaouira',
    'as suwayrah': 'Essaouira',
    'asafi': 'Safi',
    'asfy mraksh': 'Safi',
    'ashira': 'Asilah',
    'asila': 'Azilal',
    'asilah': 'Asilah',
    'asilakh': 'Asilah',
    'asilal': 'Azilal',
    'asilla': 'Asilah',
    'asmara': 'Smara',
    'asni': 'Asni',
    'assa': 'Assa',
    'assila': 'Asilah',
    'assilah': 'Asilah',
    'asylh': 'Asilah',
    'asylt': 'Asilah',
    'atzntir': 'Ajdir',
    'augusta zilil': 'Asilah',
    'aumara': 'Laouamra',
    'auserd': 'Aousserd',
    'ausert': 'Aousserd',
    'ausserd': 'Aousserd',
    'aussert': 'Aousserd',
    'awlmas': 'Oulmes',
    'awsard': 'Aousserd',
    'awsrd': 'Aousserd',
    'axdir': 'Ajdir',
    'ayt mellal': 'Beni Mellal',
    'azamor': 'Azemmour',
    'azemmour': 'Azemmour',
    'azettad': 'Settat',
    'azib de midar': 'Midar',
    'azilal': 'Azilal',
    'azimur': 'Azemmour',
    'azla': 'Azla',
    'azrou': 'Azrou',
    'azzegour': 'Azemmour',
    'bab berret': 'Boureït',
    'bab tasa': 'Bab Taza',
    'bab taza': 'Bab Taza',
    'bab tazza': 'Bab Taza',
    'badriouene': 'Gueznaia',
    'bahlil': 'Bhalil',
    'bai er kan': 'Berkane',
    'bani mallal': 'Beni Mellal',
    'barrechid': 'Berrechid',
    'behalil': 'Bhalil',
    'bejaad': 'Bejaâd',
    'bellaa': 'Bellaa',
    'ben ahmed': 'Ben Ahmed',
    'ben carrich': 'Ben Qarrich',
    'ben guerir': 'Ben Guerir',
    'ben jerra': 'Ben Jerrar',
    'ben jerrar': 'Ben Jerrar',
    'ben karrich': 'Ben Qarrich',
    'ben qarrich': 'Ben Qarrich',
    'ben sliman': 'Benslimane',
    'ben taieb': 'Ben Taieb',
    'ben tib': 'Ben Taieb',
    'ben tieb': 'Ben Taieb',
    'benahmed': 'Ben Ahmed',
    'benguerir': 'Ben Guerir',
    'beni anzar': 'Beni Enzar',
    'beni drar': 'Bni Drar',
    'beni ensar': 'Beni Enzar',
    'beni enzar': 'Beni Enzar',
    'beni gorfet': 'Sebt Bni Garfett',
    'beni melal': 'Beni Mellal',
    'beni melala': 'Beni Mellal',
    'beni melalis': 'Beni Mellal',
    'beni mellal': 'Beni Mellal',
    'beni mellal centre': 'Beni Mellal',
    'beni millal': 'Beni Mellal',
    'beni tadjit': 'Bni Tajjit',
    'beni tajit': 'Bni Tajjit',
    'beni tajjite': 'Bni Tajjit',
    'beni yakhlef': 'Beni Yakhlef',
    'beni zarfet': 'Sebt Bni Garfett',
    'benimellal': 'Beni Mellal',
    'benslimane': 'Benslimane',
    'berguent': 'Aïn Beni Mathar',
    'berkan': 'Berkane',
    'berkane': 'Berkane',
    'berkawe': 'Berkane',
    'berrechid': 'Berrechid',
    'berteaux': 'Melqa el Ouidane',
    'bev rechid': 'Berrechid',
    'bhalil': 'Bhalil',
    'bir ghandouz': 'Bir Ghandouz',
    'bir jdid': 'Bir Jdid',
    'bir jdid chavent': 'Bir Jdid',
    'bir jedid chavent': 'Bir Jdid',
    'birkani': 'Berkane',
    'bni bojazh': 'Bni Bouayach',
    'bni bouayach': 'Bni Bouayach',
    'bni drar': 'Bni Drar',
    'bni garfett': 'Sebt Bni Garfett',
    'bni tajjit': 'Bni Tajjit',
    'bny mlal': 'Beni Mellal',
    'bny mll': 'Beni Mellal',
    'bojador': 'Bojador',
    'bou arfa': 'Bouarfa',
    'bou fekrane': 'Bou Fekrane',
    'bou izakaren': 'Bou Izakarn',
    'bou izakarene': 'Bou Izakarn',
    'bou izakarn': 'Bou Izakarn',
    'bou knadel': 'Bouknadel',
    'bou malem': 'Boumalne Dades',
    'bouarfa': 'Bouarfa',
    'boucheron': 'El Gara',
    'boudenib': 'Boudenib',
    'boudenib centre': 'Boudenib',
    'bouderbala': 'Bouderbala',
    'bouhault': 'Benslimane',
    'bouizazarene ihaddadene': 'Bouizazarene Ihaddadene',
    'boujdour': 'Boujdour',
    'boujniba': 'Boujniba',
    'bouknadel': 'Bouknadel',
    'boulemane': 'Boulemane',
    'boulhaut': 'Benslimane',
    'boulhout': 'Benslimane',
    'boulmane': 'Boulemane',
    'boumalne': 'Boumalne Dades',
    'boumalne dades': 'Boumalne Dades',
    'boumia': 'Boumia',
    'boureit': 'Boureït',
    'bouret': 'Boureït',
    'bouskoura': 'Bouskoura',
    'bouzhika': 'Bouznika',
    'bouznika': 'Bouznika',
    'bouzniqa': 'Bouznika',
    'brkan': 'Berkane',
    'bu isacarn': 'Bou Izakarn',
    'buarfa': 'Bouarfa',
    'buknadel': 'Bouknadel',
    'buznike': 'Bouznika',
    'cabo juby': 'Tarfaya',
    'cabo negro': 'Cap Negro II',
    'cabo yubi': 'Tarfaya',
    'camara': 'Smara',
    'camp berteau': 'Melqa el Ouidane',
    'camp berteaux': 'Melqa el Ouidane',
    'camp boulhaut': 'Benslimane',
    'cap juby': 'Tarfaya',
    'cap negro ii': 'Cap Negro II',
    'casa branca': 'Casablanca',
    'casablanca': 'Casablanca',
    'casabranca': 'Casablanca',
    'castilho real': 'El Jadida',
    'castillejos': 'Fnidek',
    'chaouen': 'Chefchaouen',
    'chauen': 'Chefchaouen',
    'chechaouen': 'Chefchaouen',
    'chechaouene': 'Chefchaouen',
    'chefchaouen': 'Chefchaouen',
    'chefchaouene': 'Chefchaouen',
    'chemaia': 'Echemmaia Est',
    'chenifra': 'Khenifra',
    'chichaoua': 'Chichaoua',
    'chichaouene': 'Chefchaouen',
    'chichaua': 'Chichaoua',
    'chunajfira': 'Khenifra',
    'dabdou': 'Debdou',
    'dajla': 'Dakhla',
    'dakhla': 'Dakhla',
    'dar al gaddari': 'Douar el Caïd el Gueddari',
    'dar ben karrich': 'Ben Qarrich',
    'dar bouazza': 'Dar Bouazza',
    'dar caid': 'Aoulouz',
    'dar driuch': 'Driouch',
    'dar drius': 'Driouch',
    'dar el beida': 'Casablanca',
    'dar el gueddari': 'Douar el Caïd el Gueddari',
    'dar guedari': 'Douar el Caïd el Gueddari',
    'dar gueddari': 'Douar el Caïd el Gueddari',
    'dar oould zidouh': 'Dar Ould Zidouh',
    'dar oulad zidouh': 'Dar Ould Zidouh',
    'dar ould zidouh': 'Dar Ould Zidouh',
    'dar toulal': 'Douar Toulal',
    'dar uel beyda': 'Casablanca',
    'dar ul beyda': 'Casablanca',
    'daralbyda': 'Casablanca',
    'darul baidha': 'Casablanca',
    'dcheira el jihadia': 'Dchira El Jihadia',
    'dchira el jihadia': 'Dchira El Jihadia',
    'de tu an': 'Tétouan',
    'debdau': 'Debdou',
    'debdou': 'Debdou',
    'debdu': 'Debdou',
    'dechra maamar': 'Tirhassaline',
    'dechra ouaoumana': 'Aït Ouaoumana',
    'demnat': 'Demnate',
    'demnate': 'Demnate',
    'demnot': 'Demnate',
    'deroua': 'Ad Darwa',
    'derroua': 'Ad Darwa',
    'dhar souk': 'Dhar Souk',
    'djedid': 'New Fes',
    'djemaa de mrirt': 'Mrirt',
    'djerada': 'Jerada',
    'djorf': 'Jorf',
    'douar el caid el gueddari': 'Douar el Caïd el Gueddari',
    'douar toulal': 'Douar Toulal',
    'driouch': 'Driouch',
    'dubdu': 'Debdou',
    'dzadida': 'El Jadida',
    'dzherada': 'Jerada',
    'ech chaouene': 'Chefchaouen',
    'echemmaia est': 'Echemmaia Est',
    'ehl dzhadida': 'El Jadida',
    'ehl dzhadzida': 'El Jadida',
    'ehr rashidija': 'Errachidia',
    'ehrfud': 'Arfoud',
    'ehs suvejra': 'Essaouira',
    'ehssuehjra': 'Essaouira',
    'eimoren': 'Imzouren',
    'einzoren': 'Imzouren',
    'einzorene': 'Imzouren',
    'ej jema sahim': 'Jamaat Shaim',
    'el aaiun': 'El Aaiun',
    'el aaraich': 'Larache',
    'el aargub': 'El Aargub',
    'el aioun': 'El Aïoun',
    'el aouamra': 'Laouamra',
    'el araish': 'Larache',
    'el arba': 'Kariat Arkmane',
    'el arbaa': 'Kariat Arkmane',
    'el arbaa soko': 'Kariat Arkmane',
    'el ayba tahalla': 'Tahla',
    'el borch': 'Al Brouj',
    'el borouj': 'Al Brouj',
    'el djema sahim': 'Jamaat Shaim',
    'el djemaa sahim': 'Jamaat Shaim',
    'el gara': 'El Gara',
    'el guara': 'El Gara',
    'el gueddari': 'Douar el Caïd el Gueddari',
    'el guerdane': 'El Guerdane',
    'el had': 'Oulad Frej',
    'el had kourt': 'Had Kourt',
    'el hajeb': 'El Hajeb',
    'el harhoura': 'El Harhoura',
    'el jadid': 'El Jadida',
    'el jadida': 'El Jadida',
    'el jema sahim': 'Jamaat Shaim',
    'el jmis': 'Khemis Sahel',
    'el kbab': 'Al Qbab',
    'el kebab': 'Al Qbab',
    'el kelaa': 'Kelaat Mgouna',
    'el kelaa des srarhna': 'El Kelaa des Srarhna',
    'el khemis': 'Zemamra',
    'el ksiba': 'El Ksiba',
    'el maaziz': 'Al M’aziz',
    'el mansouria': 'El Mansouria',
    'el marsa': 'El Marsa',
    'el medik': 'Mdiq',
    'el mennzel': 'El Menzel',
    'el menzel': 'El Menzel',
    'el oualidia': 'Oualidia',
    'el ouatia': 'El Ouatia',
    'el rincon': 'Mdiq',
    'el suvaira': 'Essaouira',
    'el yadida': 'El Jadida',
    'ela jadida': 'El Jadida',
    'eljadida': 'El Jadida',
    'ellouizia': 'Beni Yakhlef',
    'elluoizia': 'Beni Yakhlef',
    'er rachidia': 'Errachidia',
    'erfoud': 'Arfoud',
    'errachidia': 'Errachidia',
    'es sa ura': 'Essaouira',
    'es sebt': 'Souq Sebt Oulad Nemma',
    'es sebt gzoula': 'Sebt Gzoula',
    'es semara': 'Smara',
    'es smara': 'Smara',
    'es suira': 'Essaouira',
    'es suvejra': 'Essaouira',
    'esau ila': 'Essaouira',
    'esauira': 'Essaouira',
    'esmara': 'Smara',
    'essaouira': 'Essaouira',
    'essauira': 'Essaouira',
    'et tleta': 'Ait Ourir',
    'et tleta hanchene': 'Tlet El Hanchane',
    'fadalah': 'Mohammedia',
    'fam el hisn': 'Fam El Hisn',
    'fdala': 'Mohammedia',
    'fedala': 'Mohammedia',
    'fedalah': 'Mohammedia',
    'fedhala': 'Mohammedia',
    'fes': 'Fès',
    'fes al bali': 'Fès al Bali',
    'fes djedid': 'New Fes',
    'fes jdid': 'New Fes',
    'fes jedid': 'New Fes',
    'fes l ancien': 'Fès al Bali',
    'fes le neuf': 'New Fes',
    'fes le nouveau': 'New Fes',
    'fes le vieux': 'Fès al Bali',
    'figuig': 'Figuig',
    'figuiq': 'Figuig',
    'fkih ben salah': 'Al Fqih Ben Çalah',
    'fm zkyd': 'Foum Zguid',
    'fnidek': 'Fnidek',
    'fnideq': 'Fnidek',
    'fnides': 'Fnidek',
    'foucald': 'Jem’at Oulad ’Abbou',
    'foucauld': 'Jem’at Oulad ’Abbou',
    'foucault': 'Jem’at Oulad ’Abbou',
    'foum ej jemaa': 'Foum Jam’a',
    'foum jam a': 'Foum Jam’a',
    'foum zguid': 'Foum Zguid',
    'foumjama': 'Foum Jam’a',
    'fquih ben salah': 'Al Fqih Ben Çalah',
    'gai lei min': 'Guelmim',
    'garsif': 'Guercif',
    'gel mim': 'Guelmim',
    'gelmim': 'Guelmim',
    'gelmima': 'Guelmim',
    'gelmimas': 'Guelmim',
    'gerumin': 'Guelmim',
    'ghafsai': 'Ghafsaï',
    'goulimine': 'Guelmim',
    'goulmima': 'Goulmima',
    'goulmina': 'Goulmima',
    'gourrama': 'Gourrama',
    'gu elamima': 'Guelmim',
    'guelmim': 'Guelmim',
    'guelmina': 'Goulmima',
    'gueltat zemmour': 'Gueltat Zemmour',
    'guercif': 'Guercif',
    'gueznaia': 'Gueznaia',
    'gulimimi': 'Guelmim',
    'gulimin': 'Guelmim',
    'guyelamima': 'Guelmim',
    'gwlmym': 'Guelmim',
    'gzanaia': 'Gueznaia',
    'gzennaia': 'Gueznaia',
    'gzoula': 'Sebt Gzoula',
    'had hourt': 'Had Kourt',
    'had kourt': 'Had Kourt',
    'had kurt': 'Had Kourt',
    'had oulad frej': 'Oulad Frej',
    'had oulad zbair': 'Had Oulad Zbair',
    'had soualem': 'Had Soualem',
    'hadj kaddour': 'Haj Kaddour',
    'haj kaddour': 'Haj Kaddour',
    'hattane': 'Hattane',
    'hsymh': 'Al Hoceïma',
    'ifran': 'Ifrane',
    'ifranas': 'Ifrane',
    'ifrane': 'Ifrane',
    'ighram laalam': 'Ighram Laalam',
    'imezgane': 'Inezgane',
    'imi n tanout': 'Imi-n-Tanout',
    'imi n tanoute': 'Imi-n-Tanout',
    'imintanout': 'Imi-n-Tanout',
    'immouzer': 'Imouzzer Kandar',
    'imouzzer': 'Imouzzer Kandar',
    'imouzzer du kandar': 'Imouzzer Kandar',
    'imouzzer kandar': 'Imouzzer Kandar',
    'imsouren': 'Imzouren',
    'imzouren': 'Imzouren',
    'imzourene': 'Imzouren',
    'inezgane': 'Inezgane',
    'insgane': 'Inezgane',
    'ipeulan': 'Ifrane',
    'irhir': 'Agadir',
    'itzer': 'Itzer',
    'izourene': 'Imzouren',
    'jamaat shaim': 'Jamaat Shaim',
    'jarada': 'Jerada',
    'jem at oulad abbou': 'Jem’at Oulad ’Abbou',
    'jema de mrirt': 'Mrirt',
    'jema sahim': 'Jamaat Shaim',
    'jemaa de mrirt': 'Mrirt',
    'jemaa del mrirt': 'Mrirt',
    'jemaa shaim': 'Jamaat Shaim',
    'jematouladabbou': 'Jem’at Oulad ’Abbou',
    'jemis del sahel': 'Khemis Sahel',
    'jenichet': 'Khenichet-sur Ouerrha',
    'jenifra': 'Khenifra',
    'jerada': 'Jerada',
    'jie di dai': 'El Jadida',
    'jorf': 'Jorf',
    'jorf el melha': 'Souk et Tnine Jorf el Mellah',
    'kabo negro': 'Cap Negro II',
    'kacapilanka': 'Casablanca',
    'kahf nssar': 'Kahf Nssar',
    'karia arakmane afso': 'Kariat Arkmane',
    'karia arkeman': 'Kariat Arkmane',
    'karia ba mohamed': 'Karia Ba Mohamed',
    'karia ba mohammed': 'Karia Ba Mohamed',
    'karia d arkemane': 'Kariat Arkmane',
    'karia da arkeman': 'Kariat Arkmane',
    'karia de arkeman': 'Kariat Arkmane',
    'karia de arkenan': 'Kariat Arkmane',
    'kariat akmane': 'Kariat Arkmane',
    'kariat arekmam': 'Kariat Arkmane',
    'kariat arkmane': 'Kariat Arkmane',
    'kariet arkmane': 'Kariat Arkmane',
    'kasabalanka': 'Casablanca',
    'kasabeullangka': 'Casablanca',
    'kasabilanika': 'Casablanca',
    'kasablank': 'Casablanca',
    'kasablanka': 'Casablanca',
    'kasablankae': 'Casablanca',
    'kasaburanka': 'Casablanca',
    'kasba ben ahmed': 'Ben Ahmed',
    'kasba bou znika': 'Bouznika',
    'kasba el chemaia': 'Echemmaia Est',
    'kasba goundafa': 'Talat-n-Ya’qoub',
    'kasba goundala': 'Talat-n-Ya’qoub',
    'kasba kahira': 'Imi-n-Tanout',
    'kasba mansouriah': 'El Mansouria',
    'kasba oualidia': 'Oualidia',
    'kasba skira': 'Skhirate',
    'kasba tadla': 'Kasba Tadla',
    'kasba temara': 'Témara',
    'kasba zaida': 'Zayda',
    'kasbah tadla': 'Kasba Tadla',
    'kazablanka': 'Casablanca',
    'kazablanko': 'Casablanca',
    'kazamplan ka': 'Casablanca',
    'kebbab': 'Al Qbab',
    'kelaa': 'El Kelaa des Srarhna',
    'kelaa des srarhna': 'El Kelaa des Srarhna',
    'kelaat mgouna': 'Kelaat Mgouna',
    'kelaat mguna': 'Kelaat Mgouna',
    'keniteula': 'Kénitra',
    'kenitira': 'Kénitra',
    'kenitora': 'Kénitra',
    'kenitra': 'Kénitra',
    'kenitre': 'Kénitra',
    'kenitro': 'Kénitra',
    'khemichet': 'Khenichet-sur Ouerrha',
    'khemis des zemamra': 'Zemamra',
    'khemis du sahel': 'Khemis Sahel',
    'khemis sahel': 'Khemis Sahel',
    'khemisset': 'Khemisset',
    'khenichet': 'Khenichet-sur Ouerrha',
    'khenichet sur ouerrha': 'Khenichet-sur Ouerrha',
    'khenichetsurouerrha': 'Khenichet-sur Ouerrha',
    'khenifra': 'Khenifra',
    'khmis village': 'Zemamra',
    'khmys alsahl': 'Khemis Sahel',
    'khnyfrh': 'Khenifra',
    'khnyfrt': 'Khenifra',
    'khouribga': 'Khouribga',
    'khouribja': 'Khouribga',
    'khrybkt': 'Khouribga',
    'kimisset': 'Khemisset',
    'klmym': 'Guelmim',
    'klmymt': 'Goulmima',
    'knytra': 'Kénitra',
    'koudia oualidia': 'Oualidia',
    'kouriga': 'Khouribga',
    'kourigha': 'Khouribga',
    'ksar agdz': 'Agdz',
    'ksar el kebir': 'Ksar El Kebir',
    'ksar es souk': 'Errachidia',
    'ksar oulad abbou': 'Oulad Barhil',
    'ksiba': 'El Ksiba',
    'ksiri': 'Mechraa Bel Ksiri',
    'kulmim': 'Guelmim',
    'kulmima': 'Goulmima',
    'la ba': 'Rabat',
    'la ba te': 'Rabat',
    'la la shen': 'Larache',
    'la rach': 'Larache',
    'laattaouia': 'Laâttaouia',
    'laayoune': 'Laayoune',
    'labateu': 'Rabat',
    'lahraouyine': 'Lahraouyine',
    'lakhsas': 'Lakhsas',
    'lal la mimuna': 'Lalla Mimouna',
    'lalasyu': 'Larache',
    'lalla mimouna': 'Lalla Mimouna',
    'lalla miouna adachra': 'Lalla Mimouna',
    'laouamra': 'Laouamra',
    'larache': 'Larache',
    'larasas': 'Larache',
    'larash': 'Larache',
    'larasha': 'Larache',
    'laraso': 'Larache',
    'laraxe': 'Larache',
    'larraix': 'Larache',
    'lavache': 'Larache',
    'lemhaya': 'Lemhaya',
    'lfrane': 'Ifrane',
    'los castillejos': 'Fnidek',
    'loudaya': 'Loudaya',
    'louis gentil': 'Youssoufia',
    'louizia': 'Beni Yakhlef',
    'loulad': 'Souq at Tlata des Loulad',
    'lqliaa': 'Lqoliaa',
    'lqoliaa': 'Lqoliaa',
    'lyautey': 'Kénitra',
    'm dia': 'Mdiq',
    'm dik': 'Mdiq',
    'm diq': 'Mdiq',
    'maama': 'Tirhassaline',
    'maaziz': 'Al M’aziz',
    'magador': 'Essaouira',
    'mahdia plage': 'Mehdya',
    'mammar': 'Tirhassaline',
    'mamorah': 'Moulay Bousselham',
    'mansoriyeh': 'El Mansouria',
    'mansouria': 'El Mansouria',
    'mansouriah': 'El Mansouria',
    'marakes': 'Marrakech',
    'marakesa': 'Marrakech',
    'marakesh': 'Marrakech',
    'marakeshi': 'Marrakech',
    'marakeshu': 'Marrakech',
    'marakeso': 'Marrakech',
    'maraksh': 'Marrakech',
    'marchand': 'Ar Rommani',
    'markaz fikik': 'Figuig',
    'marrakech': 'Marrakech',
    'marrakes': 'Marrakech',
    'marrakesch': 'Marrakech',
    'marrakesh': 'Marrakech',
    'marrakesz': 'Marrakech',
    'marraqueix': 'Marrakech',
    'marraquexe': 'Marrakech',
    'marrokesh': 'Marrakech',
    'martil': 'Martil',
    'martimprey du kiss': 'Ahfir',
    'mazagan': 'El Jadida',
    'mazagao': 'El Jadida',
    'mazaghan': 'El Jadida',
    'mazargan': 'El Jadida',
    'mdiq': 'Mdiq',
    'mechouar fes jdid': 'New Fes',
    'mechouar kasba': 'Méchouar-Kasba',
    'mechouarkasba': 'Méchouar-Kasba',
    'mechra al ksiri': 'Mechraa Bel Ksiri',
    'mechra bel kairi': 'Mechraa Bel Ksiri',
    'mechra belqsiri': 'Mechraa Bel Ksiri',
    'mechraa bel ksiri': 'Mechraa Bel Ksiri',
    'media': 'Mehdya',
    'medino de esauiro': 'Essaouira',
    'mediouna': 'Mediouna',
    'meharrize': 'Meharrize',
    'mehdaia': 'Mehdya',
    'mehdia': 'Mehdya',
    'mehdia plage': 'Mehdya',
    'mehdiya': 'Mehdya',
    'mehdya': 'Mehdya',
    'mehdya port': 'Mehdya',
    'mehedia': 'Mehdya',
    'mehediya': 'Mehdya',
    'mehediyah': 'Mehdya',
    'mehedyia': 'Mehdya',
    'mekinez': 'Meknès',
    'meknes': 'Meknès',
    'mekunesu': 'Meknès',
    'melg el ouidane': 'Melqa el Ouidane',
    'melga al widane': 'Melqa el Ouidane',
    'melga el ouidane': 'Melqa el Ouidane',
    'melqa el ouidane': 'Melqa el Ouidane',
    'melqu el ouidane': 'Melqa el Ouidane',
    'mendiya plage': 'Mehdya',
    'merrakex': 'Marrakech',
    'mers el kheir': 'Mers El Kheir',
    'mhamid': 'Mhamid',
    'mhmdyh': 'Mohammedia',
    'midar': 'Midar',
    'midelt': 'Midelt',
    'mighleft': 'Mirleft',
    'mina hassan tani': 'Kénitra',
    'minaret de mansuria': 'El Mansouria',
    'minaret de skhirat': 'Skhirate',
    'miramar': 'El Harhoura',
    'mirhlef': 'Mirleft',
    'mirhleft': 'Mirleft',
    'mirleft': 'Mirleft',
    'misour': 'Missour',
    'missour': 'Missour',
    'mkhamid': 'Mhamid',
    'mknas': 'Meknès',
    'mogadar': 'Essaouira',
    'mogador': 'Essaouira',
    'mohamedia': 'Mohammedia',
    'mohamedija': 'Mohammedia',
    'mohamedio': 'Mohammedia',
    'mohammadia': 'Mohammedia',
    'mohammedia': 'Mohammedia',
    'mokhammedija': 'Mohammedia',
    'monod': 'Sidi Allal El Bahraoui',
    'mont aroui': 'Al Aaroui',
    'mont arrouit': 'Al Aaroui',
    'mont arruit': 'Al Aaroui',
    'monte arrouit': 'Al Aaroui',
    'monte arruit': 'Al Aaroui',
    'morocco city': 'Marrakech',
    'moulay abdallah': 'Moulay Abdallah',
    'moulay ali cherif': 'Moulay Ali Cherif',
    'moulay bou azza': 'Moulay Bou ’azza',
    'moulay bou selham': 'Moulay Bousselham',
    'moulay bousselham': 'Moulay Bousselham',
    'moulay driss zerhoun': 'Moulay Driss Zerhoun',
    'moulay idris': 'Moulay Driss Zerhoun',
    'moulay idriss': 'Moulay Driss Zerhoun',
    'moulay yacoub': 'Moulay Yacoub',
    'moulay yakoub': 'Moulay Yacoub',
    'moulaybouazza': 'Moulay Bou ’azza',
    'mraksh': 'Marrakech',
    'mrirt': 'Mrirt',
    'mrkz fkyk': 'Figuig',
    'muhammediye': 'Mohammedia',
    'muley yacub': 'Moulay Yacoub',
    'mwghadwr': 'Essaouira',
    'mwkadwr': 'Essaouira',
    'my drarga': 'My Drarga',
    'mzala chichaoua': 'Chichaoua',
    'na zu er': 'Nador',
    'nad xr': 'Nador',
    'nadoleu': 'Nador',
    'nador': 'Nador',
    'nadora': 'Nador',
    'nadoras': 'Nador',
    'nazwr': 'Nador',
    'new fes': 'New Fes',
    'nglmym': 'Guelmim',
    'nnadur': 'Nador',
    'nouaceur': 'Nouaceur',
    'nouaseur': 'Nouaceur',
    'nwacer': 'Nouaceur',
    'o ben slimane': 'Benslimane',
    'oadar temsia': 'Oadar Temsia',
    'old fes': 'Fès al Bali',
    'oualidia': 'Oualidia',
    'oualidiya': 'Oualidia',
    'ouaouizeght': 'Ouaouizeght',
    'ouaoumana': 'Aït Ouaoumana',
    'ouarzazat': 'Ouarzazate',
    'ouarzazate': 'Ouarzazate',
    'ouarzazte': 'Ouarzazate',
    'ouazzane': 'Ouezzane',
    'oudja': 'Oujda',
    'oudjda': 'Oujda',
    'oued amlil': 'Oued Amlil',
    'oued lahou': 'Oued Laou',
    'oued lao': 'Oued Laou',
    'oued laou': 'Oued Laou',
    'oued lou': 'Oued Laou',
    'oued zem': 'Oued Zem',
    'ouezzane': 'Ouezzane',
    'ouislane': 'Ouislane',
    'oujda': 'Oujda',
    'oujda angad': 'Oujda',
    'oulad abbou': 'Oulad Barhil',
    'oulad ayad': 'Oulad Ayad',
    'oulad barhil': 'Oulad Barhil',
    'oulad barrehil': 'Oulad Barhil',
    'oulad ber rehil': 'Oulad Barhil',
    'oulad el rhadabne': 'Oulad El Rhadabne',
    'oulad embarek': 'Oulad Embarek',
    'oulad frej': 'Oulad Frej',
    'oulad m rah': "Oulad M'Rah",
    'oulad mbarek': 'Oulad Embarek',
    'oulad tayeb': 'Oulad Tayeb',
    'oulad teima': 'Oulad Teïma',
    'oulad yaich': 'Oulad Yaïch',
    'oulad yaiche': 'Oulad Yaïch',
    'ouladmrah': "Oulad M'Rah",
    'ouled aich': 'Oulad Yaïch',
    'ouled teima': 'Oulad Teïma',
    'oulmes': 'Oulmes',
    'oulmes les thermes': 'Oulmes',
    'ouorzazate': 'Ouarzazate',
    'outat el hadj': 'Outat Oulad Al Haj',
    'outat el haj': 'Outat Oulad Al Haj',
    'outat el hajj': 'Outat Oulad Al Haj',
    'outat oulad al haj': 'Outat Oulad Al Haj',
    'petitjean': 'Sidi Kacem',
    'pettijean': 'Sidi Kacem',
    'phesa': 'Fès',
    'plage de mehdia': 'Mehdya',
    'port laoti': 'Kénitra',
    'port lyautey': 'Kénitra',
    'qala at mgouna': 'Kelaat Mgouna',
    'qasbah al walidiyah': 'Oualidia',
    'qnytrh': 'Kénitra',
    'qualidia': 'Oualidia',
    'quazzane': 'Ouezzane',
    'qzblnqh': 'Casablanca',
    'raba t': 'Rabat',
    'rabat': 'Rabat',
    'rabata': 'Rabat',
    'rabatas': 'Rabat',
    'rabato': 'Rabat',
    'rabatum': 'Rabat',
    'rabot': 'Rabat',
    'rabota': 'Rabat',
    'rachidia': 'Errachidia',
    'rafsai': 'Ghafsaï',
    'rampat': 'Rabat',
    'rapat': 'Rabat',
    'ras el ma': 'Ras el Ma',
    'ras kebdana': 'Ras Kebdana',
    'rasidija': 'Errachidia',
    'rasoa goundafa': 'Talat-n-Ya’qoub',
    'rasse ma': 'Ras el Ma',
    'recani': 'Reçani',
    'ribat al khayr': 'Ribat Al Khayr',
    'ribat al kheir': 'Ribat Al Khayr',
    'ribat el kheir': 'Ribat Al Khayr',
    'rich': 'Rich',
    'ricon el medik': 'Mdiq',
    'rincon': 'Mdiq',
    'rincon de medik': 'Mdiq',
    'rincon del medik': 'Mdiq',
    'rincon el madik': 'Mdiq',
    'rio martin': 'Martil',
    'rio martine': 'Martil',
    'risani': 'Reçani',
    'rissani': 'Reçani',
    'romani': 'Ar Rommani',
    'rommani': 'Ar Rommani',
    'sa fei': 'Safi',
    'sabaa aiyoun': 'Sabaa Aiyoun',
    'safi': 'Safi',
    'safim': 'Safi',
    'sai ta te': 'Settat',
    'saida': 'Saidia',
    'saidia': 'Saidia',
    'saidia du kiss': 'Saidia',
    'saidija': 'Saidia',
    'sale': 'Salé',
    'sale al jadida': 'Salé Al Jadida',
    'sallee': 'Salé',
    'santa cruz': 'Agadir',
    'sattat': 'Settat',
    'savira': 'Essaouira',
    'scheschauen': 'Chefchaouen',
    'sdy qasm': 'Sidi Kacem',
    'sebt bni garfett': 'Sebt Bni Garfett',
    'sebt des gzoula': 'Sebt Gzoula',
    'sebt gzoula': 'Sebt Gzoula',
    'sedala': 'Mohammedia',
    'sefrou': 'Sefrou',
    'sefru': 'Sefrou',
    'segangan': 'Zeghanghane',
    'segangane': 'Zeghanghane',
    'selouane': 'Selouane',
    'semara': 'Smara',
    'setatas': 'Settat',
    'setateu': 'Settat',
    'settat': 'Settat',
    'sette fatna': 'Setti Fatma',
    'setti fadma': 'Setti Fatma',
    'setti fatma': 'Setti Fatma',
    'seumala': 'Smara',
    'sgouennaia': 'Gueznaia',
    'shefshauen': 'Chefchaouen',
    'shfshawn': 'Chefchaouen',
    'si ma la': 'Smara',
    'sidi ahmed': 'Sidi Ahmed',
    'sidi ali ben hamdouche': 'Sidi Ali Ben Hamdouche',
    'sidi allal bahraoui': 'Sidi Allal El Bahraoui',
    'sidi allal el bahraoui': 'Sidi Allal El Bahraoui',
    'sidi allal tazi': 'Sidi Allal Tazi',
    'sidi bennour': 'Sidi Bennour',
    'sidi bibi': 'Sidi Bibi',
    'sidi bidi': 'Sidi Bibi',
    'sidi bou knadel': 'Bouknadel',
    'sidi bou lanouar': 'Sidi Bou Lanouar',
    'sidi bou othmane': 'Sidi Bou Othmane',
    'sidi bou otmane': 'Sidi Bou Othmane',
    'sidi bouqnadel': 'Bouknadel',
    'sidi bouzid': 'Sidi Bouzid',
    'sidi bu osman': 'Sidi Bou Othmane',
    'sidi ifni': 'Sidi Ifni',
    'sidi ifnis': 'Sidi Ifni',
    'sidi jaber': 'Sidi Jaber',
    'sidi jabeur': 'Sidi Jaber',
    'sidi kacem': 'Sidi Kacem',
    'sidi lmokhtar': 'Sidi Lmokhtar',
    'sidi mojtar': 'Sidi Lmokhtar',
    'sidi mokhtar': 'Sidi Lmokhtar',
    'sidi moktar': 'Sidi Lmokhtar',
    'sidi qacem': 'Sidi Kacem',
    'sidi qasim': 'Sidi Kacem',
    'sidi rahal': 'Sidi Rahal',
    'sidi rahhal': 'Sidi Rahhal',
    'sidi slamain': 'Sidi Slimane',
    'sidi sliman': 'Sidi Slimane',
    'sidi slimane': 'Sidi Slimane',
    'sidi slimane echcharaa': 'Sidi Slimane Echcharaa',
    'sidi smai il': 'Sidi Smai’il',
    'sidi smail': 'Sidi Smai’il',
    'sidi smain': 'Sidi Smai’il',
    'sidi smaine': 'Sidi Smai’il',
    'sidi taibi': 'Sidi Taibi',
    'sidi yahia': 'Sidi Yahya Zaer',
    'sidi yahia el gharb': 'Sidi Yahia El Gharb',
    'sidi yahia zaer': 'Sidi Yahya Zaer',
    'sidi yahia zaire': 'Sidi Yahya Zaer',
    'sidi yahya': 'Sidi Yahya Zaer',
    'sidi yahya zaer': 'Sidi Yahya Zaer',
    'sidi zouina': 'Sidi Zouine',
    'sidi zouine': 'Sidi Zouine',
    'sidi zuin': 'Sidi Zouine',
    'sidifni': 'Sidi Ifni',
    'sidiipeuni': 'Sidi Ifni',
    'sidismaiil': 'Sidi Smai’il',
    'skhirat': 'Skhirate',
    'skhirate': 'Skhirate',
    'skhour des rehamna': 'Skhour Rehamna',
    'skhour rehamna': 'Skhour Rehamna',
    'sltat': 'Settat',
    'sma ra': 'Smara',
    'smara': 'Smara',
    'smarh': 'Smara',
    'soko el arbaa': 'Kariat Arkmane',
    'soko el jemis': 'Khemis Sahel',
    'souk el arba des ait baha': 'Souk El Arba Des Aït Baha',
    'souk el arbaa': 'Souk El Arbaa',
    'souk el had': 'Oulad Frej',
    'souk es sebt': 'Souq Sebt Oulad Nemma',
    'souk et tnine jorf el mellah': 'Souk et Tnine Jorf el Mellah',
    'souk tleta loulad': 'Souq at Tlata des Loulad',
    'souq al had bradya': 'Souq Al Had Bradya',
    'souq at tlata des loulad': 'Souq at Tlata des Loulad',
    'souq khmis ait yadine': 'Souq Khmis Aït Yadine',
    'souq larb a al gharb': 'Souq Larb’a al Gharb',
    'souq sebt oulad nemma': 'Souq Sebt Oulad Nemma',
    'souqlarbaalgharb': 'Souq Larb’a al Gharb',
    'sti fadma': 'Setti Fatma',
    'suira': 'Essaouira',
    'sumara': 'Smara',
    'suo wei la': 'Essaouira',
    'suvayr': 'Essaouira',
    'swyrh': 'Essaouira',
    'sydy afny': 'Sidi Ifni',
    'szavira': 'Essaouira',
    'ta zha': 'Taza',
    'tabount': 'Tabount',
    'tadjit': 'Bni Tajjit',
    'tadla': 'Kasba Tadla',
    'tafraout': 'Tafraout',
    'tafraoute': 'Tafraout',
    'tafraut': 'Tafraout',
    'taghazout': 'Taghazout',
    'taghjicht': 'Tarhjicht',
    'tagjist': 'Tarhjicht',
    'tahala': 'Tahla',
    'tahanaout': 'Tahannout',
    'tahanaoute': 'Tahannout',
    'tahanaut': 'Tahannout',
    'tahannaout': 'Tahannout',
    'tahannawt': 'Tahannout',
    'tahannout': 'Tahannout',
    'tahar souk': 'Dhar Souk',
    'tahla': 'Tahla',
    'tahnaout': 'Tahannout',
    'tahr souk': 'Dhar Souk',
    'talaat n yakoub': 'Talat-n-Ya’qoub',
    'talat n ya qoub': 'Talat-n-Ya’qoub',
    'talate n yakoub': 'Talat-n-Ya’qoub',
    'talate n yakour': 'Talat-n-Ya’qoub',
    'talatnyaqoub': 'Talat-n-Ya’qoub',
    'talfaia': 'Tarfaya',
    'taliouine': 'Taliouine',
    'talioune': 'Taliouine',
    'talsinnt': 'Talsint',
    'talsint': 'Talsint',
    'tamallalt': 'Tamallalt',
    'tamanar': 'Tamanar',
    'tamansourt': 'Tamansourt',
    'tamelelt': 'Tamallalt',
    'tamelelt el jedid': 'Tamallalt',
    'tamelelt jdida': 'Tamallalt',
    'tamelelte el djedid': 'Tamallalt',
    'tamelet ej jdid': 'Tamallalt',
    'tamelet el djedid': 'Tamallalt',
    'tamelit ej jedid': 'Tamallalt',
    'tamesloht': 'Tameslouht',
    'tameslouht': 'Tameslouht',
    'tameslout': 'Tameslouht',
    'tamesna': 'Tamesna',
    'tamslwht': 'Tameslouht',
    'tan ji ya': 'Tanger',
    'tan tan': 'Tan-Tan',
    'tanca': 'Tanger',
    'tanger': 'Tanger',
    'tangeri': 'Tanger',
    'tangero': 'Tanger',
    'tangier': 'Tanger',
    'tangiers': 'Tanger',
    'tanijeri': 'Tanger',
    'tanje': 'Tanger',
    'tanjer': 'Tanger',
    'tanji ara': 'Tanger',
    'tanji e': 'Tanger',
    'tanjiyara': 'Tanger',
    'tantan': 'Tan-Tan',
    'tantanas': 'Tan-Tan',
    'tanzha': 'Tanger',
    'tanzher': 'Tanger',
    'taounat': 'Taounate',
    'taounate': 'Taounate',
    'taourirt': 'Taourirt',
    'tarfaia': 'Tarfaya',
    'tarfaja': 'Tarfaya',
    'tarfaya': 'Tarfaya',
    'targuist': 'Targuist',
    'targvist': 'Targuist',
    'tarhazoute': 'Taghazout',
    'tarhjicht': 'Tarhjicht',
    'tarhjijt': 'Tarhjicht',
    'tarjicht': 'Tarhjicht',
    'taroudannt': 'Taroudant',
    'taroudant': 'Taroudant',
    'tarudant': 'Taroudant',
    'tarudantas': 'Taroudant',
    'tarudante': 'Taroudant',
    'tarufaya': 'Tarfaya',
    'tarwdant': 'Taroudant',
    'tassila': 'Tassila',
    'tata': 'Tata',
    'tatta': 'Tata',
    'taunat': 'Taounate',
    'tawnat': 'Taounate',
    'taza': 'Taza',
    'tazenakht': 'Taznakht',
    'tazenskht': 'Taznakht',
    'taznakht': 'Taznakht',
    'tehtuan': 'Tétouan',
    'temara': 'Témara',
    'temsia': 'Oadar Temsia',
    'tendrara': 'Tendrara',
    'teto una': 'Tétouan',
    'tetouan': 'Tétouan',
    'tetuan': 'Tétouan',
    'tetuanas': 'Tétouan',
    'tetuano': 'Tétouan',
    'tetuao': 'Tétouan',
    'tichla': 'Tichla',
    'tiflet': 'Tiflet',
    'tigemmi tamellalt': 'Casablanca',
    'tighassaline': 'Tirhassaline',
    'tinajdad': 'Tinajdad',
    'tindjad': 'Tinajdad',
    'tindjadj': 'Tinajdad',
    'tine biougra': 'Tine Biougra',
    'tineghir': 'Tinghir',
    'tinejad': 'Tinajdad',
    'tinejdad': 'Tinajdad',
    'tinerhir': 'Tinghir',
    'tinghir': 'Tinghir',
    'tingis': 'Tanger',
    'tinjdad': 'Tinajdad',
    'tinrhir': 'Tinghir',
    'tirhanimine': 'Tirhanimîne',
    'tirhassaline': 'Tirhassaline',
    'tissa': 'Tissa',
    'tissila exterieur': 'Tassila',
    'tissila interieur': 'Tassila',
    'tistoutine': 'Tiztoutine',
    'tistutin': 'Tiztoutine',
    'tit mellil': 'Tit Mellil',
    'tiznit': 'Tiznit',
    'tiznitas': 'Tiznit',
    'tiztoutine': 'Tiztoutine',
    'tlata hanchane': 'Tlet El Hanchane',
    'tlate n yacoub': 'Talat-n-Ya’qoub',
    'tlet el hanchane': 'Tlet El Hanchane',
    'tleta hanchen': 'Tlet El Hanchane',
    'tleta hannchene': 'Tlet El Hanchane',
    'toulal': 'Douar Toulal',
    'toumiat zaio': 'Zaïo',
    'tounfit': 'Tounfit',
    'tounfite': 'Tounfit',
    'tounfite centre': 'Tounfit',
    'trfayh': 'Tarfaya',
    'trfayt': 'Tarfaya',
    'ttwan': 'Tétouan',
    'tumiat': 'Zaïo',
    'tumiat zaio': 'Zaïo',
    'tznyt': 'Tiznit',
    'uad lau': 'Oued Laou',
    'ualidija': 'Oualidia',
    'uarzazat': 'Ouarzazate',
    'uarzazatas': 'Ouarzazate',
    'uazan': 'Ouezzane',
    'udzda': 'Oujda',
    'udzhda': 'Oujda',
    'ujada': 'Oujda',
    'ujida': 'Oujda',
    'ul mes': 'Oulmes',
    'ulad embarek': 'Oulad Embarek',
    'ulad tajib': 'Oulad Tayeb',
    'uzhda': 'Oujda',
    'varzazat': 'Ouarzazate',
    'venet ville': 'Souq at Tlata des Loulad',
    'villa alhucemas': 'Al Hoceïma',
    'villa bens': 'Tarfaya',
    'villa cisneros': 'Dakhla',
    'villa nador': 'Nador',
    'villa sanjurjo': 'Al Hoceïma',
    'village de tissa': 'Tissa',
    'ville d arcila': 'Asilah',
    'ville de chechaouen': 'Chefchaouen',
    'ville de kenitra': 'Kénitra',
    'wad martin': 'Martil',
    'wad zm': 'Oued Zem',
    'wadi zam': 'Oued Zem',
    'wady lw': 'Oued Laou',
    'wady zm': 'Oued Zem',
    'wadzda': 'Oujda',
    'warzazat': 'Ouarzazate',
    'wazzan': 'Ouezzane',
    'wejda': 'Oujda',
    'white house': 'Casablanca',
    'wjdt anjad': 'Oujda',
    'wjdt ankad': 'Oujda',
    'wlmas': 'Oulmes',
    'wrzazat': 'Ouarzazate',
    'wrzzat': 'Ouarzazate',
    'wu ji da': 'Oujda',
    'xauen': 'Chefchaouen',
    'xexauen': 'Chefchaouen',
    'xnifra': 'Khenifra',
    'yazza': 'Ait Yazza',
    'yi fu lan': 'Ifrane',
    'youssoufia': 'Youssoufia',
    'zag': 'Zag',
    'zagora': 'Zagora',
    'zaida': 'Zayda',
    'zaio': 'Zaïo',
    'zaouia ait ishak': 'Zaouïa Aït Ishak',
    'zaouia ait issehak': 'Zaouïa Aït Ishak',
    'zaouia assa': 'Assa',
    'zaouia ben jerrar': 'Ben Jerrar',
    'zaouia ech cheikh': 'Zawyat ech Cheïkh',
    'zaouia sidi moktar': 'Sidi Lmokhtar',
    'zaouia sidi rahal': 'Sidi Rahhal',
    'zaouia sidi rahhal': 'Sidi Rahhal',
    'zaouia sidi rahkal': 'Sidi Rahhal',
    'zaouia sidi smain': 'Sidi Smai’il',
    'zaouia sti fatma': 'Setti Fatma',
    'zavijja ash shejkh': 'Zawyat ech Cheïkh',
    'zawit al bour': 'Zawit Al Bour',
    'zawyat ait ishag': 'Zaouïa Aït Ishak',
    'zawyat ait ishaq': 'Zaouïa Aït Ishak',
    'zawyat an nwacer': 'Nouaceur',
    'zawyat ech cheikh': 'Zawyat ech Cheïkh',
    'zayda': 'Zayda',
    'zeghanghane': 'Zeghanghane',
    'zeida': 'Zayda',
    'zelaun': 'Selouane',
    'zelouan': 'Selouane',
    'zelouane': 'Selouane',
    'zeluan': 'Selouane',
    'zemamra': 'Zemamra',
    'zirara': 'Zirara',
    'zoco el arbaa': 'Kariat Arkmane',
    'zoco el jemis': 'Khemis Sahel',
    'zoualet': 'Zoualet',
    'zouiat ech cheikh': 'Zawyat ech Cheïkh',
}
