# Generated by Django 5.1.4 on 2026-07-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('immobilier', '0008_bail_created_at_bail_updated_at_batiment_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercice', models.PositiveIntegerField(verbose_name='Exercice (année)')),
                ('poste', models.CharField(choices=[('ascenseur', 'Ascenseur'), ('nettoyage', 'Nettoyage'), ('gardiennage', 'Gardiennage'), ('electricite_communs', 'Électricité communs'), ('eau_communs', 'Eau communs'), ('assurance_immeuble', 'Assurance immeuble'), ('entretien_espaces_verts', 'Entretien espaces verts'), ('autre', 'Autre')], max_length=30, verbose_name='Poste')),
                ('montant_budgete_annuel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant budgété annuel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets_charges', to='immobilier.batiment', verbose_name='Bâtiment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilier_budgets_charges', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Budget de charges',
                'verbose_name_plural': 'Budgets de charges',
                'ordering': ['-exercice', 'poste', 'id'],
                'unique_together': {('batiment', 'exercice', 'poste')},
            },
        ),
    ]
