# Generated by Django 5.1.4 on 2026-07-17 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('immobilier', '0009_budgetcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('montant_reel', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant réel')),
                ('facture_fournisseur_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID pièce d'achat fournisseur")),
                ('ged_document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID justificatif GED')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('budget_charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='immobilier.budgetcharges', verbose_name='Budget de charges')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilier_depenses_charges', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Dépense de charges',
                'verbose_name_plural': 'Dépenses de charges',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
