# Generated by Django 5.1.4 on 2026-07-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0010_depensecharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='mode_repartition',
            field=models.CharField(choices=[('tantiemes', 'Tantièmes'), ('surface', 'Surface')], default='tantiemes', max_length=10, verbose_name='Mode de répartition des charges'),
        ),
    ]
