# Generated by Django 5.1.4 on 2026-07-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('immobilier', '0011_batiment_mode_repartition'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularisationCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercice', models.PositiveIntegerField(verbose_name='Exercice (année)')),
                ('provisions_encaissees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Provisions encaissées')),
                ('quote_part_reelle', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Quote-part réelle')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Solde (provisions - quote-part)')),
                ('sens', models.CharField(choices=[('a_rembourser', 'À rembourser'), ('a_facturer', 'À facturer'), ('neutre', 'Neutre (solde nul)')], default='neutre', max_length=12, verbose_name='Sens')),
                ('facture_ventes_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID facture ventes (à facturer)')),
                ('avoir_ventes_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID avoir ventes (à rembourser — facture négative)')),
                ('date_emission', models.DateTimeField(blank=True, null=True, verbose_name="Date d'émission du document")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularisations_charges', to='immobilier.bail', verbose_name='Bail')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilier_regularisations_charges', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Régularisation de charges',
                'verbose_name_plural': 'Régularisations de charges',
                'ordering': ['-exercice', '-id'],
                'unique_together': {('bail', 'exercice')},
            },
        ),
    ]
