# Generated by Django 5.1.4 on 2026-07-17 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('immobilier', '0012_regularisationcharges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatLieuxImmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moment', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10, verbose_name='Moment')),
                ('date', models.DateField(verbose_name='Date')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('signe', 'Signé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('bail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_lieux', to='immobilier.bail', verbose_name='Bail')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilier_etats_lieux', to='authentication.company', verbose_name='Société')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etats_lieux_immo_realises', to=settings.AUTH_USER_MODEL, verbose_name='Technicien')),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PieceEtatLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_piece', models.CharField(max_length=120, verbose_name='Pièce')),
                ('etat_general', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon'), ('usage_normal', 'Usage normal'), ('degrade', 'Dégradé')], default='bon', max_length=15, verbose_name='État général')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilier_pieces_etat_lieux', to='authentication.company', verbose_name='Société')),
                ('etat_lieux', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='immobilier.etatlieuximmo', verbose_name='État des lieux')),
            ],
            options={
                'verbose_name': 'Pièce (état des lieux)',
                'verbose_name_plural': 'Pièces (état des lieux)',
                'ordering': ['etat_lieux_id', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ElementEtatLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element', models.CharField(max_length=60, verbose_name='Élément (ex. sol/murs/plafond)')),
                ('etat', models.CharField(choices=[('neuf', 'Neuf'), ('bon', 'Bon'), ('usage_normal', 'Usage normal'), ('degrade', 'Dégradé')], default='bon', max_length=15, verbose_name='État')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilier_elements_etat_lieux', to='authentication.company', verbose_name='Société')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='immobilier.pieceetatlieux', verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Élément (état des lieux)',
                'verbose_name_plural': 'Éléments (état des lieux)',
                'ordering': ['piece_id', 'ordre', 'id'],
            },
        ),
    ]
