# Generated by Django 5.1.4 on 2026-07-17 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('immobilier', '0013_etatlieuximmo_pieceetatlieux_elementetatlieux'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEtatLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_key', models.CharField(max_length=500)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('mime', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobilier_photos_etat_lieux', to='authentication.company', verbose_name='Société')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='immobilier.elementetatlieux', verbose_name='Élément')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_etat_lieux_immo', to=settings.AUTH_USER_MODEL, verbose_name='Déposée par')),
            ],
            options={
                'verbose_name': 'Photo (état des lieux)',
                'verbose_name_plural': 'Photos (état des lieux)',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
