# Generated by Django 5.1.4 on 2026-09-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0003_ntp2p11_plafond_delai_escalade'),
    ]

    operations = [
        migrations.AddField(
            model_name='notefrais',
            name='justificatif_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='notefrais',
            name='justificatif_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='notefrais',
            name='justificatif_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='notefrais',
            name='justificatif_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AlterField(
            model_name='notefrais',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='notes_frais/justificatifs/%Y/%m/', verbose_name='Justificatif (photo, legacy hors MinIO)'),
        ),
    ]
