# Generated by Django 5.1.4 on 2026-07-17 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('hospitality', '0008_chambre_created_at_chambre_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCourante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('reservation', 'Réservation'), ('incident', 'Incident'), ('consigne', 'Consigne'), ('finance', 'Finance'), ('autre', 'Autre')], default='autre', max_length=15)),
                ('texte', models.TextField()),
                ('cible_type', models.CharField(blank=True, default='', max_length=30)),
                ('cible_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_note', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitality_main_courante_notes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitality_main_courante', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Main courante',
                'verbose_name_plural': 'Main courante',
                'ordering': ['-date_note'],
            },
        ),
    ]
