# Generated by Django 5.1.4 on 2026-07-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('hospitality', '0009_maincourante'),
        ('stock', '0080_odx19_achats_split_repoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_plat', models.CharField(max_length=150, verbose_name='Nom du plat')),
                ('categorie_menu', models.CharField(choices=[('entree', 'Entrée'), ('plat', 'Plat'), ('dessert', 'Dessert'), ('boisson', 'Boisson')], default='plat', max_length=10)),
                ('prix_vente_ht', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente HT')),
                ('description', models.TextField(blank=True, default='')),
                ('allergenes', models.JSONField(blank=True, default=list)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitality_recettes', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Recette',
                'verbose_name_plural': 'Recettes',
                'ordering': ['nom_plat'],
            },
        ),
        migrations.CreateModel(
            name='IngredientRecette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unite', models.CharField(default='unite', max_length=20)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospitality_ingredients_recette', to='stock.produit', verbose_name='Produit (stock)')),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='hospitality.recette')),
            ],
            options={
                'verbose_name': 'Ingrédient de recette',
                'verbose_name_plural': 'Ingrédients de recette',
                'ordering': ['id'],
            },
        ),
    ]
