# Generated by Django 5.1.4 on 2026-07-17 18:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
        ('hospitality', '0010_recette_ingredientrecette'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalleEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('capacite_max', models.PositiveIntegerField(default=0)),
                ('types_amenagement_disponibles', models.JSONField(blank=True, default=list)),
                ('tarif_location_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitality_salles_evenement', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Salle événementielle',
                'verbose_name_plural': 'Salles événementielles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EvenementBanquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_evenement', models.CharField(max_length=150)),
                ('date_debut', models.DateTimeField(verbose_name='Début du créneau')),
                ('date_fin', models.DateTimeField(verbose_name='Fin du créneau')),
                ('nb_convives', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='brouillon', max_length=10)),
                ('devis_ventes_id', models.PositiveIntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitality_evenements_banquet', to='crm.client', verbose_name='Client CRM')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitality_evenements_banquet', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitality_evenements_banquet_crees', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitality_evenements_banquet', to='crm.lead', verbose_name='Lead')),
                ('menu_recettes', models.ManyToManyField(blank=True, related_name='evenements_banquet', to='hospitality.recette')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='hospitality.salleevenement', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Événement / banquet',
                'verbose_name_plural': 'Événements / banquets',
                'ordering': ['-date_debut'],
            },
        ),
    ]
