# Generated by Django 5.1.4 on 2026-07-17 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('hospitality', '0011_salleevenement_evenementbanquet'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='formule_pension',
            field=models.CharField(choices=[('aucune', 'Aucune'), ('petit_dejeuner', 'Petit-déjeuner'), ('demi_pension', 'Demi-pension'), ('pension_complete', 'Pension complète')], default='aucune', max_length=16),
        ),
        migrations.CreateModel(
            name='TicketPension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type_repas', models.CharField(choices=[('petit_dejeuner', 'Petit-déjeuner'), ('dejeuner', 'Déjeuner'), ('diner', 'Dîner')], max_length=15)),
                ('consomme', models.BooleanField(default=False)),
                ('date_consommation', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitality_tickets_pension', to='authentication.company', verbose_name='Société')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_pension', to='hospitality.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Ticket pension',
                'verbose_name_plural': 'Tickets pension',
                'ordering': ['date', 'type_repas'],
                'constraints': [models.UniqueConstraint(fields=('reservation', 'date', 'type_repas'), name='hospitality_ticket_pension_unique_par_jour_repas')],
            },
        ),
    ]
