# Generated by Django 5.1.4 on 2026-06-13 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_mark_owner_protected'),
        ('crm', '0010_client_cin_client_if_fiscal_client_rc_and_more'),
        ('ventes', '0007_lignefacture_taux_tva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('site_adresse', models.TextField(blank=True, null=True)),
                ('site_ville', models.CharField(blank=True, max_length=120, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('puissance_installee_kwc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('raccordement', models.CharField(blank=True, choices=[('monophase', 'Monophasé'), ('triphase', 'Triphasé')], max_length=12, null=True)),
                ('type_installation', models.CharField(blank=True, choices=[('residentiel', 'Résidentiel'), ('industriel', 'Industriel / Commercial'), ('agricole', 'Agricole (pompage)')], max_length=20, null=True)),
                ('statut', models.CharField(choices=[('a_planifier', 'À planifier'), ('planifie', 'Planifié'), ('pose_en_cours', 'Pose en cours'), ('pose', 'Posé'), ('raccordement_onee', 'Raccordement ONEE'), ('mise_en_service', 'Mise en service'), ('cloture', 'Clôturé')], default='a_planifier', max_length=20)),
                ('annule', models.BooleanField(default=False)),
                ('motif_annulation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_pose_prevue', models.DateField(blank=True, null=True)),
                ('date_pose_reelle', models.DateField(blank=True, null=True)),
                ('date_mise_en_service', models.DateField(blank=True, null=True)),
                ('mes_pv_notes', models.TextField(blank=True, null=True)),
                ('mes_production_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mes_tension', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='ventes.boncommande')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations', to='crm.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_creees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='ventes.devis')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='crm.lead')),
                ('technicien_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_techniques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chantier',
                'verbose_name_plural': 'Chantiers',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='InstallationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('note', 'Note')], max_length=15)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('field_label', models.CharField(blank=True, max_length=150, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installation_activities', to='authentication.company')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='installations.installation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité chantier',
                'verbose_name_plural': 'Activités chantier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_intervention', models.CharField(choices=[('pose', 'Pose'), ('raccordement', 'Raccordement'), ('mise_en_service', 'Mise en service'), ('controle', 'Contrôle'), ('depannage', 'Dépannage')], max_length=20)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_realisee', models.DateField(blank=True, null=True)),
                ('compte_rendu', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions_creees', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='installations.installation')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordre de travail',
                'verbose_name_plural': 'Ordres de travail',
                'ordering': ['-date_prevue', '-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='installation',
            index=models.Index(fields=['company', 'statut'], name='installatio_company_85ba38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installation',
            unique_together={('company', 'reference')},
        ),
        migrations.AddIndex(
            model_name='installationactivity',
            index=models.Index(fields=['installation', '-created_at'], name='installatio_install_021707_idx'),
        ),
    ]
