# Generated by Django 5.1.4 on 2026-06-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
        ('sav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='sav.ticket'),
        ),
    ]
