# Generated by Django 5.1.4 on 2026-06-16 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("installations", "0003_typeintervention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="bom",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="installation",
            name="date_cloture",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="date_materiel_commande",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="date_reception",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="date_signature",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="labour_jours_estimes",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="labour_jours_reels",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="parc_actif",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("signe", "Signé"),
                    ("materiel_commande", "Matériel commandé"),
                    ("planifie", "Planifié"),
                    ("en_cours", "En cours"),
                    ("installe", "Installé"),
                    ("receptionne", "Réceptionné"),
                    ("cloture", "Clôturé"),
                    ("a_planifier", "À planifier"),
                    ("pose_en_cours", "Pose en cours"),
                    ("pose", "Posé"),
                    ("raccordement_onee", "Raccordement ONEE"),
                    ("mise_en_service", "Mise en service"),
                ],
                default="signe",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ChantierChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=120)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("capture_serie", models.BooleanField(default=False)),
                ("fait", models.BooleanField(default=False)),
                ("fait_le", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="authentication.company",
                    ),
                ),
                (
                    "fait_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_items_faits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="installations.installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de checklist (chantier)",
                "verbose_name_plural": "Étapes de checklist (chantier)",
                "ordering": ["ordre", "id"],
                "unique_together": {("installation", "cle")},
            },
        ),
        migrations.CreateModel(
            name="ChecklistEtapeModele",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=120)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("capture_serie", models.BooleanField(default=False)),
                ("actif", models.BooleanField(default=True)),
                ("protege", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_etapes",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de checklist chantier",
                "verbose_name_plural": "Étapes de checklist chantier",
                "ordering": ["ordre", "libelle"],
                "unique_together": {("company", "cle")},
            },
        ),
    ]
