# Generated by Django 5.1.4 on 2026-06-16 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("installations", "0004_backfill_typeintervention"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                ("ordre", models.PositiveIntegerField(default=100)),
                ("done", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="authentication.company",
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checklist_items_faits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="installations.installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de checklist",
                "verbose_name_plural": "Étapes de checklist",
                "ordering": ["ordre", "id"],
                "indexes": [
                    models.Index(
                        fields=["installation", "ordre"],
                        name="installatio_install_4aec6d_idx",
                    )
                ],
            },
        ),
    ]
