# Generated by Django 5.1.4 on 2026-06-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0004_installation_bom_installation_date_cloture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="art33_regularisation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="installation",
            name="dossier_date_approbation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="dossier_date_depot",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="dossier_operateur",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="dossier_reference",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="dossier_statut",
            field=models.CharField(
                choices=[
                    ("non_concerne", "Non concerné"),
                    ("a_deposer", "À déposer"),
                    ("depose", "Déposé"),
                    ("approuve", "Approuvé"),
                    ("compteur_pose", "Compteur posé"),
                ],
                default="non_concerne",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="regime_8221",
            field=models.CharField(
                choices=[
                    ("non_concerne", "Non concerné"),
                    ("declaration_bt", "Déclaration (< 11 kW, BT)"),
                    ("accord_raccordement", "Accord de raccordement"),
                    ("autorisation_anre", "Autorisation ANRE (> 1 MW)"),
                ],
                default="non_concerne",
                max_length=24,
            ),
        ),
    ]
