# Generated by Django 5.1.4 on 2026-06-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0005_checklistitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="date_reception",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="parc_actif",
            field=models.BooleanField(default=True),
        ),
    ]
