# Generated by Django 5.1.4 on 2026-06-19 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("installations", "0008_stockreservation"),
        ("outillage", "0001_initial"),
        ("stock", "0019_retourfournisseur_ligneretourfournisseur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="arrivee_gps_lat",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="arrivee_gps_lng",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="arrivee_site_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="depart_depot_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="retour_depot_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="InterventionPreparation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tout_charge", models.BooleanField(default=False)),
                ("confirme_le", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intervention_preparations",
                        to="authentication.company",
                    ),
                ),
                (
                    "confirme_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preparations_confirmees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervention",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparation",
                        to="installations.intervention",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preparations",
                        to="outillage.kitoutillage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préparation d'intervention",
                "verbose_name_plural": "Préparations d'intervention",
                "ordering": ["intervention_id"],
            },
        ),
        migrations.CreateModel(
            name="PreparationMaterielLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=255)),
                ("quantite_requise", models.PositiveIntegerField(default=0)),
                ("charge", models.BooleanField(default=False)),
                ("manquant", models.BooleanField(default=False)),
                ("quantite_manquante", models.PositiveIntegerField(default=0)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparation_materiel_lignes",
                        to="authentication.company",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiel",
                        to="installations.interventionpreparation",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preparation_lignes",
                        to="stock.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne matériel de préparation",
                "verbose_name_plural": "Lignes matériel de préparation",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="PreparationOutilLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=255)),
                ("coche", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preparation_outil_lignes",
                        to="authentication.company",
                    ),
                ),
                (
                    "outil",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preparation_lignes",
                        to="outillage.outillage",
                    ),
                ),
                (
                    "preparation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outils",
                        to="installations.interventionpreparation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne outil de préparation",
                "verbose_name_plural": "Lignes outil de préparation",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="ShotListSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=120)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("avant", "Avant"),
                            ("pendant", "Pendant"),
                            ("apres", "Après"),
                        ],
                        default="avant",
                        max_length=8,
                    ),
                ),
                ("obligatoire", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("protege", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shotlist_slots",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau de shot list",
                "verbose_name_plural": "Créneaux de shot list",
                "ordering": ["ordre", "libelle"],
                "unique_together": {("company", "cle")},
            },
        ),
    ]
