# Generated by Django 5.1.4 on 2026-06-19 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("installations", "0009_intervention_arrivee_gps_lat_and_more"),
        ("outillage", "0001_initial"),
        ("records", "0003_attachment_phase"),
        ("sav", "0005_contrat_renouvellement"),
        ("stock", "0019_retourfournisseur_ligneretourfournisseur"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentSerial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("slot_cle", models.CharField(blank=True, default="", max_length=40)),
                (
                    "numero_serie",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("serie_ocr", models.BooleanField(default=False)),
                ("pousse_parc", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_serials",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serials",
                        to="installations.intervention",
                    ),
                ),
                (
                    "plaque_attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="records.attachment",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_serials",
                        to="stock.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "N° de série de composant",
                "verbose_name_plural": "N° de série de composants",
                "ordering": ["intervention_id", "id"],
            },
        ),
        migrations.CreateModel(
            name="MaterielConsommation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valide", models.BooleanField(default=False)),
                ("valide_le", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiel_consommations",
                        to="authentication.company",
                    ),
                ),
                (
                    "intervention",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consommation",
                        to="installations.intervention",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réconciliation matériel consommé",
                "verbose_name_plural": "Réconciliations matériel consommé",
                "ordering": ["intervention_id"],
            },
        ),
        migrations.CreateModel(
            name="PhotoAnnotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drawing", models.JSONField(blank=True, default=list)),
                ("caption", models.TextField(blank=True, default="")),
                ("probleme", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation",
                        to="records.attachment",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_annotations",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annotation de photo",
                "verbose_name_plural": "Annotations de photo",
                "ordering": ["-date_modification"],
            },
        ),
        migrations.CreateModel(
            name="SafetySignoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signe", models.BooleanField(default=False)),
                ("signe_le", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_signoffs",
                        to="authentication.company",
                    ),
                ),
                (
                    "intervention",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_signoff",
                        to="installations.intervention",
                    ),
                ),
                (
                    "signe_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sign-off sécurité",
                "verbose_name_plural": "Sign-offs sécurité",
                "ordering": ["intervention_id"],
            },
        ),
        migrations.CreateModel(
            name="VoiceMemo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cible",
                    models.CharField(
                        choices=[
                            ("general", "Note générale"),
                            ("photo", "Note sur photo"),
                            ("variance", "Justification de variance"),
                            ("reserve", "Note sur réserve"),
                        ],
                        default="general",
                        max_length=12,
                    ),
                ),
                ("transcript", models.TextField(blank=True, default="")),
                ("transcrit", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "audio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="records.attachment",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_memos",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_memos",
                        to="installations.intervention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mémo vocal",
                "verbose_name_plural": "Mémos vocaux",
                "ordering": ["-date_creation", "id"],
            },
        ),
        migrations.CreateModel(
            name="Reserve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "statut",
                    models.CharField(
                        choices=[("ouverte", "Ouverte"), ("resolue", "Résolue")],
                        default="ouverte",
                        max_length=10,
                    ),
                ),
                ("resolution", models.TextField(blank=True, default="")),
                ("resolue_le", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserves_assignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserves",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reserves",
                        to="installations.intervention",
                    ),
                ),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="records.attachment",
                    ),
                ),
                (
                    "suivi_intervention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserves_origine",
                        to="installations.intervention",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reserves",
                        to="sav.ticket",
                    ),
                ),
                (
                    "memo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="installations.voicememo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réserve",
                "verbose_name_plural": "Réserves",
                "ordering": ["statut", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ConsommationLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=255)),
                (
                    "quantite_prevue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "quantite_utilisee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("hors_nomenclature", models.BooleanField(default=False)),
                ("justification", models.TextField(blank=True, default="")),
                ("stock_applique", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consommation_lignes",
                        to="authentication.company",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consommation_lignes",
                        to="stock.produit",
                    ),
                ),
                (
                    "consommation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="installations.materielconsommation",
                    ),
                ),
                (
                    "justification_memo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="installations.voicememo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de consommation",
                "verbose_name_plural": "Lignes de consommation",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="SafetyChecklistSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=200)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("protege", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_slots",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consigne de sécurité",
                "verbose_name_plural": "Consignes de sécurité",
                "ordering": ["ordre", "libelle"],
                "unique_together": {("company", "cle")},
            },
        ),
        migrations.CreateModel(
            name="SafetyCheckItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=200)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("coche", models.BooleanField(default=False)),
                ("coche_le", models.DateTimeField(blank=True, null=True)),
                (
                    "coche_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_check_items",
                        to="authentication.company",
                    ),
                ),
                (
                    "signoff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="installations.safetysignoff",
                    ),
                ),
            ],
            options={
                "verbose_name": "Point de consigne (intervention)",
                "verbose_name_plural": "Points de consigne (intervention)",
                "ordering": ["ordre", "id"],
                "unique_together": {("signoff", "cle")},
            },
        ),
        migrations.CreateModel(
            name="ToolReturn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rendu", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("confirme_le", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_returns",
                        to="authentication.company",
                    ),
                ),
                (
                    "confirme_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emplacement_retour",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="stock.emplacementstock",
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_returns",
                        to="installations.intervention",
                    ),
                ),
                (
                    "outil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_returns",
                        to="outillage.outillage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retour d'outil",
                "verbose_name_plural": "Retours d'outils",
                "ordering": ["intervention_id", "id"],
                "unique_together": {("intervention", "outil")},
            },
        ),
    ]
