# Generated by Django 5.1.4 on 2026-06-21 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        (
            "installations",
            "0010_componentserial_materielconsommation_photoannotation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chantierchecklistitem",
            name="photo_obligatoire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="checklistetapemodele",
            name="photo_obligatoire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="installation",
            name="date_pose_fin_prevue",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="duree_pose_jours",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="rdv_confirme",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="intervention",
            name="rdv_confirme_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="rdv_reschedule_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="intervention",
            name="signataire_nom",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="signature_client",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="intervention",
            name="signe_le",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="TypeInterventionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_installation",
                    models.CharField(
                        choices=[
                            ("residentiel", "Résidentiel"),
                            ("industriel", "Industriel / Commercial"),
                            ("agricole", "Agricole (pompage)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("type_intervention_cle", models.CharField(max_length=40)),
                (
                    "libelle_contexte",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_intervention_plans",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan d'intervention standard",
                "verbose_name_plural": "Plans d'intervention standard",
                "ordering": ["type_installation", "ordre"],
                "unique_together": {
                    ("company", "type_installation", "type_intervention_cle")
                },
            },
        ),
    ]
