# Generated by Django 5.1.4 on 2026-06-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "installations",
            "0010_componentserial_materielconsommation_photoannotation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="installation",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
