# Generated by Django 5.1.4 on 2026-06-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0011_fg100_installation_custom_data"),
        ("installations", "0011_fg68_fg69_fg72_fg76_fg78_fg79"),
    ]

    operations = []
