# Generated by Django 5.1.4 on 2026-06-21 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("installations", "0012_merge_20260621_0546"),
        ("stock", "0023_fg54_fg61_fg62_fg63_fg64_stock_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeleProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120)),
                (
                    "type_installation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("residentiel", "Résidentiel"),
                            ("industriel", "Industriel / Commercial"),
                            ("agricole", "Agricole (pompage)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modeles_projet",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de projet",
                "verbose_name_plural": "Modèles de projet",
                "ordering": ["nom"],
                "unique_together": {("company", "nom")},
            },
        ),
        migrations.CreateModel(
            name="ModeleProjetBomLigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quantite",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modele_projet_bom_lignes",
                        to="authentication.company",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lignes",
                        to="installations.modeleprojet",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modele_projet_bom_lignes",
                        to="stock.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de BoM type de modèle de projet",
                "verbose_name_plural": "Lignes de BoM type de modèle de projet",
                "ordering": ["modele_id", "ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="ModeleProjetJalon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("etude", "Étude"),
                            ("appro", "Approvisionnement"),
                            ("pose", "Pose"),
                            ("mes", "Mise en service"),
                            ("reception", "Réception"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=120)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("offset_jours", models.IntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modele_projet_jalons",
                        to="authentication.company",
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jalons",
                        to="installations.modeleprojet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jalon type de modèle de projet",
                "verbose_name_plural": "Jalons type de modèle de projet",
                "ordering": ["modele_id", "ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="JalonProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("etude", "Étude"),
                            ("appro", "Approvisionnement"),
                            ("pose", "Pose"),
                            ("mes", "Mise en service"),
                            ("reception", "Réception"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                ("libelle", models.CharField(max_length=120)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("date_cible", models.DateField(blank=True, null=True)),
                ("date_reelle", models.DateField(blank=True, null=True)),
                ("atteint", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jalons_projet",
                        to="authentication.company",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jalons",
                        to="installations.installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jalon de projet",
                "verbose_name_plural": "Jalons de projet",
                "ordering": ["installation_id", "ordre", "id"],
                "indexes": [
                    models.Index(
                        fields=["company", "installation"],
                        name="installatio_company_2652ae_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReunionChantier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(blank=True, max_length=200, null=True)),
                ("date_reunion", models.DateTimeField(blank=True, null=True)),
                ("ordre_du_jour", models.TextField(blank=True, null=True)),
                ("presents", models.TextField(blank=True, null=True)),
                ("decisions", models.TextField(blank=True, null=True)),
                ("actions", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reunions_chantier",
                        to="authentication.company",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reunions",
                        to="installations.installation",
                    ),
                ),
                (
                    "redige_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reunions_chantier_redigees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte-rendu de réunion de chantier",
                "verbose_name_plural": "Comptes-rendus de réunion de chantier",
                "ordering": ["-date_reunion", "-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["company", "installation"],
                        name="installatio_company_8943a4_idx",
                    )
                ],
            },
        ),
    ]
