# Generated by Django 5.1.4 on 2026-06-30 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0033_fg318_contrat_prix'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Adresse complète du casier, ex. A-03-12.', max_length=40)),
                ('zone', models.CharField(blank=True, max_length=20, null=True)),
                ('allee', models.CharField(blank=True, max_length=20, null=True)),
                ('casier', models.CharField(blank=True, max_length=20, null=True)),
                ('ordre', models.PositiveIntegerField(default=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_bin_locations', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_bin_locations_crees', to=settings.AUTH_USER_MODEL)),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations_bin_locations', to='stock.emplacementstock')),
            ],
            options={
                'verbose_name': 'Casier de rangement',
                'verbose_name_plural': 'Casiers de rangement',
                'ordering': ['emplacement_id', 'ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BinAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_bin_affectations', to='authentication.company')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations_bin_affectations', to='stock.produit')),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='installations.binlocation')),
            ],
            options={
                'verbose_name': 'Affectation produit ↔ casier',
                'verbose_name_plural': 'Affectations produit ↔ casier',
                'ordering': ['bin_id', 'produit_id'],
            },
        ),
        migrations.AddIndex(
            model_name='binlocation',
            index=models.Index(fields=['company', 'emplacement'], name='idx_bin_co_emplacement'),
        ),
        migrations.AddIndex(
            model_name='binlocation',
            index=models.Index(fields=['company', 'archived'], name='idx_bin_co_archived'),
        ),
        migrations.AlterUniqueTogether(
            name='binlocation',
            unique_together={('company', 'emplacement', 'code')},
        ),
        migrations.AddIndex(
            model_name='binaffectation',
            index=models.Index(fields=['company', 'produit'], name='idx_binaff_co_produit'),
        ),
        migrations.AlterUniqueTogether(
            name='binaffectation',
            unique_together={('bin', 'produit')},
        ),
    ]
