# Generated by Django 5.1.4 on 2026-06-30 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0034_binlocation_binaffectation_and_more'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PutAway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('a_ranger', 'À ranger'), ('range', 'Rangé')], default='a_ranger', max_length=20)),
                ('reference_reception', models.CharField(blank=True, max_length=80, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_rangement', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bin_effectif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaways_effectifs', to='installations.binlocation')),
                ('bin_suggere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='putaways_suggeres', to='installations.binlocation')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_putaways', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_putaways_crees', to=settings.AUTH_USER_MODEL)),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_putaways', to='stock.emplacementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations_putaways', to='stock.produit')),
                ('range_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_putaways_ranges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rangement guidé (put-away)',
                'verbose_name_plural': 'Rangements guidés (put-away)',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_putaway_co_statut'), models.Index(fields=['company', 'produit'], name='idx_putaway_co_produit')],
            },
        ),
    ]
