# Generated by Django 5.1.4 on 2026-06-30 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0035_putaway'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('emis', 'Émis'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='emis', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_picklists', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_picklists_crees', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picklists', to='installations.installation')),
            ],
            options={
                'verbose_name': 'Bon de prélèvement',
                'verbose_name_plural': 'Bons de prélèvement',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PickListLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite_demandee', models.PositiveIntegerField(default=0)),
                ('quantite_prelevee', models.PositiveIntegerField(default=0)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('preleve', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='picklist_lignes', to='installations.binlocation')),
                ('pick_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='installations.picklist')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_picklist_lignes', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ligne de prélèvement',
                'verbose_name_plural': 'Lignes de prélèvement',
                'ordering': ['pick_list_id', 'ordre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='picklist',
            index=models.Index(fields=['company', 'statut'], name='idx_pick_co_statut'),
        ),
        migrations.AddIndex(
            model_name='picklist',
            index=models.Index(fields=['company', 'installation'], name='idx_pick_co_install'),
        ),
        migrations.AlterUniqueTogether(
            name='picklist',
            unique_together={('company', 'reference')},
        ),
        migrations.AddIndex(
            model_name='picklistligne',
            index=models.Index(fields=['pick_list'], name='idx_pickl_picklist'),
        ),
        migrations.AddIndex(
            model_name='picklistligne',
            index=models.Index(fields=['produit'], name='idx_pickl_produit'),
        ),
    ]
