# Generated by Django 5.1.4 on 2026-06-30 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0036_picklist_picklistligne_picklist_idx_pick_co_statut_and_more'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('preparation', 'En préparation'), ('controle', 'Contrôlé'), ('expedie', 'Expédié')], default='preparation', max_length=20)),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_controle', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_colis', to='authentication.company')),
                ('controle_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_colis_controles', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_colis_crees', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to='installations.installation')),
            ],
            options={
                'verbose_name': 'Colis de préparation',
                'verbose_name_plural': 'Colis de préparation',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ColisLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('controle_ok', models.BooleanField(default=False)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='installations.colis')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_colis_lignes', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ligne de colis',
                'verbose_name_plural': 'Lignes de colis',
                'ordering': ['colis_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['company', 'statut'], name='idx_colis_co_statut'),
        ),
        migrations.AddIndex(
            model_name='colis',
            index=models.Index(fields=['company', 'installation'], name='idx_colis_co_install'),
        ),
        migrations.AlterUniqueTogether(
            name='colis',
            unique_together={('company', 'reference')},
        ),
        migrations.AddIndex(
            model_name='colisligne',
            index=models.Index(fields=['colis'], name='idx_colisl_colis'),
        ),
        migrations.AddIndex(
            model_name='colisligne',
            index=models.Index(fields=['produit'], name='idx_colisl_produit'),
        ),
    ]
