# Generated by Django 5.1.4 on 2026-06-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0037_colis_colisligne_colis_idx_colis_co_statut_and_more'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieEntrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=120)),
                ('statut', models.CharField(choices=[('en_stock', 'En stock'), ('reserve', 'Réservé'), ('sorti', 'Sorti')], default='en_stock', max_length=20)),
                ('reference_reception', models.CharField(blank=True, max_length=80, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_entrepot', to='installations.binlocation')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_series_entrepot', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_series_entrepot_crees', to=settings.AUTH_USER_MODEL)),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_series_entrepot', to='stock.emplacementstock')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_entrepot', to='installations.installation')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations_series_entrepot', to='stock.produit')),
            ],
            options={
                'verbose_name': 'N° de série en entrepôt',
                'verbose_name_plural': 'N° de série en entrepôt',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_serieent_co_statut'), models.Index(fields=['company', 'produit'], name='idx_serieent_co_produit')],
                'unique_together': {('company', 'produit', 'numero_serie')},
            },
        ),
    ]
