# Generated by Django 5.1.4 on 2026-06-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0038_serieentrepot'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionComptage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('intitule', models.CharField(blank=True, max_length=255, null=True)),
                ('classe_abc', models.CharField(choices=[('A', 'A (forte valeur)'), ('B', 'B (valeur moyenne)'), ('C', 'C (faible valeur)'), ('toutes', 'Toutes')], default='toutes', max_length=10)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planifie', max_length=20)),
                ('date_planifiee', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_sessions_comptage', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_sessions_comptage_crees', to=settings.AUTH_USER_MODEL)),
                ('emplacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_sessions_comptage', to='stock.emplacementstock')),
            ],
            options={
                'verbose_name': 'Session de comptage tournant',
                'verbose_name_plural': 'Sessions de comptage tournant',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ComptageLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite_theorique', models.IntegerField(default=0)),
                ('quantite_comptee', models.IntegerField(blank=True, null=True)),
                ('compte', models.BooleanField(default=False)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_comptage_lignes', to='stock.produit')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='installations.sessioncomptage')),
            ],
            options={
                'verbose_name': 'Ligne de comptage',
                'verbose_name_plural': 'Lignes de comptage',
                'ordering': ['session_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='sessioncomptage',
            index=models.Index(fields=['company', 'statut'], name='idx_cyc_co_statut'),
        ),
        migrations.AddIndex(
            model_name='sessioncomptage',
            index=models.Index(fields=['company', 'classe_abc'], name='idx_cyc_co_classe'),
        ),
        migrations.AlterUniqueTogether(
            name='sessioncomptage',
            unique_together={('company', 'reference')},
        ),
        migrations.AddIndex(
            model_name='comptageligne',
            index=models.Index(fields=['session'], name='idx_cycl_session'),
        ),
        migrations.AddIndex(
            model_name='comptageligne',
            index=models.Index(fields=['produit'], name='idx_cycl_produit'),
        ),
    ]
