# Generated by Django 5.1.4 on 2026-06-30 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0039_sessioncomptage_comptageligne_and_more'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('execute', 'Exécuté')], default='demande', max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_demandes_transfert_approuvees', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_demandes_transfert', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_demandes_transfert_creees', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations_demandes_transfert_entrantes', to='stock.emplacementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations_demandes_transfert', to='stock.produit')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installations_demandes_transfert_sortantes', to='stock.emplacementstock')),
            ],
            options={
                'verbose_name': 'Demande de transfert',
                'verbose_name_plural': 'Demandes de transfert',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_dtr_co_statut'), models.Index(fields=['company', 'produit'], name='idx_dtr_co_produit')],
                'unique_together': {('company', 'reference')},
            },
        ),
    ]
