# Generated by Django 5.1.4 on 2026-06-30 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0040_demandetransfert'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleReappro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_min', models.PositiveIntegerField(default=0)),
                ('seuil_max', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_regles_reappro', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_regles_reappro_creees', to=settings.AUTH_USER_MODEL)),
                ('emplacement_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations_regles_reappro_cibles', to='stock.emplacementstock')),
                ('emplacement_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_regles_reappro_sources', to='stock.emplacementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations_regles_reappro', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Règle de réapprovisionnement',
                'verbose_name_plural': 'Règles de réapprovisionnement',
                'ordering': ['produit_id', 'emplacement_cible_id'],
                'indexes': [models.Index(fields=['company', 'active'], name='idx_reappro_co_active'), models.Index(fields=['company', 'produit'], name='idx_reappro_co_produit')],
                'unique_together': {('company', 'produit', 'emplacement_cible')},
            },
        ),
    ]
