# Generated by Django 5.1.4 on 2026-06-30 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0041_reglereappro'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielConsigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('type_materiel', models.CharField(choices=[('palette', 'Palette'), ('touret', 'Touret de câble'), ('bouteille', 'Bouteille'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('caution_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('detenu', 'Détenu'), ('retourne', 'Retourné')], default='detenu', max_length=20)),
                ('reference_externe', models.CharField(blank=True, max_length=80, null=True)),
                ('date_reception', models.DateField(blank=True, null=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_materiels_consignes', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_materiels_consignes_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_materiels_consignes', to='stock.fournisseur')),
                ('retourne_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_materiels_consignes_retournes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matériel consigné',
                'verbose_name_plural': 'Matériels consignés',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_consig_co_statut'), models.Index(fields=['company', 'fournisseur'], name='idx_consig_co_fourn')],
            },
        ),
    ]
