# Generated by Django 5.1.4 on 2026-06-30 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0042_materielconsigne'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('reference_interne', models.CharField(blank=True, max_length=80, null=True)),
                ('active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_kits', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_kits_crees', to=settings.AUTH_USER_MODEL)),
                ('produit_compose', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_kits_composes', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Kit de pré-assemblage',
                'verbose_name_plural': 'Kits de pré-assemblage',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='KitComposant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='installations.kit')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_kit_composants', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Composant de kit',
                'verbose_name_plural': 'Composants de kit',
                'ordering': ['kit_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrdreAssemblage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='planifie', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_terminaison', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_ordres_assemblage', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_ordres_assemblage_crees', to=settings.AUTH_USER_MODEL)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres', to='installations.kit')),
            ],
            options={
                'verbose_name': "Ordre d'assemblage",
                'verbose_name_plural': "Ordres d'assemblage",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='kit',
            index=models.Index(fields=['company', 'active'], name='idx_kit_co_active'),
        ),
        migrations.AddIndex(
            model_name='kitcomposant',
            index=models.Index(fields=['kit'], name='idx_kitc_kit'),
        ),
        migrations.AddIndex(
            model_name='kitcomposant',
            index=models.Index(fields=['produit'], name='idx_kitc_produit'),
        ),
        migrations.AddIndex(
            model_name='ordreassemblage',
            index=models.Index(fields=['company', 'statut'], name='idx_asm_co_statut'),
        ),
        migrations.AddIndex(
            model_name='ordreassemblage',
            index=models.Index(fields=['company', 'kit'], name='idx_asm_co_kit'),
        ),
        migrations.AlterUniqueTogether(
            name='ordreassemblage',
            unique_together={('company', 'reference')},
        ),
    ]
