# Generated by Django 5.1.4 on 2026-06-30 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0043_kit_kitcomposant_ordreassemblage_and_more'),
        ('stock', '0026_fg67_frais_annexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('transporteur_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_transit', 'En transit'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('adresse_site', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_livraisons', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_livraisons_creees', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_livraisons', to='stock.emplacementstock')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='installations.installation')),
            ],
            options={
                'verbose_name': 'Livraison planifiée',
                'verbose_name_plural': 'Livraisons planifiées',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LivraisonLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('livraison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='installations.livraison')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_livraison_lignes', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Ligne de livraison',
                'verbose_name_plural': 'Lignes de livraison',
                'ordering': ['livraison_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['company', 'statut'], name='idx_liv_co_statut'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['company', 'date_prevue'], name='idx_liv_co_date'),
        ),
        migrations.AlterUniqueTogether(
            name='livraison',
            unique_together={('company', 'reference')},
        ),
        migrations.AddIndex(
            model_name='livraisonligne',
            index=models.Index(fields=['livraison'], name='idx_livl_livraison'),
        ),
        migrations.AddIndex(
            model_name='livraisonligne',
            index=models.Index(fields=['produit'], name='idx_livl_produit'),
        ),
    ]
