# Generated by Django 5.1.4 on 2026-06-30 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0044_livraison_livraisonligne_livraison_idx_liv_co_statut_and_more'),
        ('records', '0006_remove_tag_records_tag_company_nom_uniq_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreuveLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signataire_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_data', models.TextField(blank=True, null=True)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('horodatage', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installations_preuves_livraison', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations_preuves_livraison_creees', to=settings.AUTH_USER_MODEL)),
                ('livraison', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preuve', to='installations.livraison')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='records.attachment')),
            ],
            options={
                'verbose_name': 'Preuve de livraison',
                'verbose_name_plural': 'Preuves de livraison',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['company', 'livraison'], name='idx_pod_co_livraison')],
            },
        ),
    ]
