# Generated by Django 5.1.4 on 2026-06-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0046_livraison_cout_transport_transporteur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livraison',
            name='mode_acheminement',
            field=models.CharField(choices=[('depot', 'Via le dépôt'), ('direct_site', 'Direct site')], default='depot', max_length=20),
        ),
    ]
