# Generated by Django 5.1.4 on 2026-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0089_zfsm5_intervention_devis_upsell_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='astreinte',
            name='idx_astreinte_co_dates',
        ),
        migrations.AlterField(
            model_name='ficheinterventionchamp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ficheinterventionreleve',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ficheinterventiontemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ficheinterventionvaleur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recurrenceintervention',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reglerangement',
            name='categorie_produit',
            field=models.CharField(blank=True, help_text='Catégorie produit (texte libre) — alternative à `produit` pour une règle qui vise toute une famille.', max_length=120, null=True),
        ),
    ]
