# Generated by Django 5.1.4 on 2026-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0091_xfsm23_gps_tracking'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='geofencealert',
            new_name='installatio_company_20074f_idx',
            old_name='inst_geofence_co_iv_crt_idx',
        ),
        migrations.RenameIndex(
            model_name='gpsconsentrecord',
            new_name='installatio_company_b5ad8f_idx',
            old_name='inst_gpsconsent_co_tech_idx',
        ),
        migrations.RenameIndex(
            model_name='positiontechnicien',
            new_name='installatio_company_3d39b6_idx',
            old_name='inst_postech_co_tech_cap_idx',
        ),
        migrations.RenameIndex(
            model_name='positiontechnicien',
            new_name='installatio_interve_c142e8_idx',
            old_name='inst_postech_interv_cap_idx',
        ),
        migrations.AlterField(
            model_name='positiontechnicien',
            name='accuracy_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Précision GPS rapportée par le client (mètres), si fournie.', max_digits=8, null=True),
        ),
    ]
