# Generated by Django 5.1.15 on 2026-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0110_agr608_recette_pompage'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='niveau_tension',
            field=models.CharField(blank=True, choices=[('bt', 'Basse tension (BT)'), ('mt', 'Moyenne tension (MT)')], max_length=2, null=True, verbose_name='Niveau de tension'),
        ),
        migrations.AddField(
            model_name='installation',
            name='niveau_tension_source',
            field=models.CharField(blank=True, choices=[('mesure_visite', 'Mesuré en visite'), ('declare', 'Déclaré')], max_length=14, null=True, verbose_name='Provenance du niveau de tension'),
        ),
        migrations.AddField(
            model_name='installation',
            name='puissance_souscrite_kva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Puissance souscrite (kVA)'),
        ),
    ]
