# Generated by Django 5.1.15 on 2026-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0111_ciq610_niveau_tension'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='niveau_tension',
            field=models.CharField(blank=True, choices=[('bt', 'Basse tension (BT)'), ('mt', 'Moyenne tension (MT)')], max_length=2, null=True),
        ),
    ]
