# Generated by Django 5.1.15 on 2026-10-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0112_ciq611_template_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='regime_8221',
            field=models.CharField(choices=[('non_concerne', 'Non concerné'), ('declaration_bt', 'Déclaration'), ('accord_raccordement', 'Accord de raccordement'), ('autorisation_anre', 'Autorisation (ministère)'), ('declaration_hors_reseau', 'Déclaration hors réseau (loi 82-21, art. 3)'), ('a_qualifier', 'À qualifier')], default='non_concerne', max_length=24),
        ),
    ]
