# Generated by Django 5.1.15 on 2026-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0113_ciq613_regime_a_qualifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagemodele',
            name='exige_hse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentprojet',
            name='type_doc',
            field=models.CharField(choices=[('schema_unifilaire', 'Schéma unifilaire'), ('calepinage', 'Calepinage'), ('note_calcul', 'Note de calcul'), ('autre', 'Autre'), ('plan_prevention', 'Plan de prévention'), ('analyse_risques', 'Analyse de risques'), ('permis_travail_hauteur', 'Permis de travail en hauteur')], default='autre', max_length=30),
        ),
    ]
