# Generated by Django 5.1.15 on 2026-10-06 19:17

from django.db import migrations, models


def _defaut_null_en_faux(apps, schema_editor):
    Reading = apps.get_model('installations', 'CommissioningIVReading')
    Reading.objects.filter(defaut_detecte__isnull=True).update(
        defaut_detecte=False)


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0115_ciq624_consignes_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioningrecord',
            name='decouplage_etat',
            field=models.CharField(choices=[('sans_objet', 'Sans objet'), ('a_faire', 'À faire'), ('ok', 'Conforme'), ('non_ok', 'Non conforme')], default='sans_objet', max_length=10),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='decouplage_piece',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='echantillon_iv_chaines',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='energie_fenetre_debut',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='energie_fenetre_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='energie_mesuree_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='instruments_par_essai',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='irradiance_poa_wm2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='irradiance_source',
            field=models.CharField(blank=True, choices=[('mesuree', 'Mesurée'), ('estimee', 'Estimée')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='irradiation_kwh_m2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='limitation_injection_consigne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='limitation_injection_etat',
            field=models.CharField(choices=[('sans_objet', 'Sans objet'), ('a_faire', 'À faire'), ('ok', 'Conforme'), ('non_ok', 'Non conforme')], default='sans_objet', max_length=10),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='temperature_module_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='terre_installation_ohm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='thermographie_constats',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commissioningrecord',
            name='thermographie_faite',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commissioningivreading',
            name='defaut_detecte',
            field=models.BooleanField(blank=True, null=True),
        ),
        # Retour arrière : un défaut « sans verdict » (null) redevient False
        # avant que la colonne ne redevienne non nulle.
        migrations.RunPython(
            migrations.RunPython.noop, _defaut_null_en_faux),
    ]
