# Generated by Django 5.1.15 on 2026-10-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0116_ciq626_recette_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissioningrecord',
            name='promesse_figee',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
