# Generated by Django 5.1.15 on 2026-10-06 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_solmvp30b_customuser_sans_poste_ref'),
        ('installations', '0117_ciq627_promesse_figee'),
        ('records', '0013_vx210_snooze_trigger_event'),
        ('sav', '0066_ciq640_prestations_contrat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='bloquante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserve',
            name='date_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserves_chantier', to='installations.installation'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='levee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reserve',
            name='origine',
            field=models.CharField(choices=[('intervention', 'Intervention'), ('recette', 'Recette'), ('reception', 'Réception')], default='intervention', max_length=12),
        ),
        migrations.AddField(
            model_name='reserve',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='installations.intervention'),
        ),
        migrations.AddConstraint(
            model_name='reserve',
            constraint=models.CheckConstraint(condition=models.Q(('intervention__isnull', False), ('installation__isnull', False), _connector='OR'), name='reserve_intervention_ou_chantier'),
        ),
    ]
