# Generated by Django 5.1.15 on 2026-10-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0118_ciq628_reserves_chantier'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='date_reception_definitive',
            field=models.DateField(blank=True, null=True, verbose_name='Réception définitive'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='date_reception',
            field=models.DateField(blank=True, null=True, verbose_name='Réception provisoire'),
        ),
    ]
