# Generated by Django 5.1.15 on 2026-10-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0119_ciq629_reception_definitive'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='cosignataire_fonction',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='cosignataire_nom',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='cosignataire_organisme',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='signataire_fonction',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='signataire_societe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
