# Generated by Django 5.1.15 on 2026-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0120_ciq631_pv_signataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprojet',
            name='type_doc',
            field=models.CharField(choices=[('schema_unifilaire', 'Schéma unifilaire'), ('calepinage', 'Calepinage'), ('note_calcul', 'Note de calcul'), ('autre', 'Autre'), ('plan_prevention', 'Plan de prévention'), ('analyse_risques', 'Analyse de risques'), ('permis_travail_hauteur', 'Permis de travail en hauteur'), ('plan_chaines', 'Plan des chaînes'), ('reglages_protections', 'Réglages de protection'), ('manuel_om', "Manuel d'exploitation et maintenance"), ('attestation_formation', 'Attestation de formation'), ('pv_mise_sous_tension', 'PV de mise sous tension'), ('note_structure', 'Note de structure'), ('certificat_organisme_agree', "Certificat d'un organisme agréé"), ('attestation_assurance', "Attestation d'assurance")], default='autre', max_length=30),
        ),
    ]
