# Generated by Django 5.1.15 on 2026-10-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0121_ciq632_pieces_remise_ci'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='series_non_relevees',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
