# Generated by Django 5.1.15 on 2026-10-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0122_ciq633_series_non_relevees'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='garantie_etancheite_mois',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='garantie_etancheite_perimetre',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='installation',
            name='garantie_installation_mois',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='garantie_installation_perimetre',
            field=models.TextField(blank=True, default=''),
        ),
    ]
