# Generated by Django 5.1.15 on 2026-10-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0004_visite_cadence_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteterrain',
            name='gabarit',
            field=models.CharField(choices=[('toiture', 'Toiture'), ('point_eau', "Relevé du point d'eau")], default='toiture', max_length=12, verbose_name='Gabarit de visite'),
        ),
    ]
