# Generated by Django 5.1.4 on 2026-07-17 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('records', '0013_vx210_snooze_trigger_event'),
        ('rh', '0083_yhard1_encrypt_dossieremploye'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=30, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée')], default='active', max_length=10, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('capacite_max', models.PositiveIntegerField(default=30, verbose_name='Capacité maximale')),
                ('salle', models.CharField(blank=True, default='', max_length=50, verbose_name='Salle')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='education.anneescolaire', verbose_name='Année scolaire')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('enseignant_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='rh.dossieremploye', verbose_name='Enseignant principal')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['annee_scolaire', 'niveau__ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de famille')),
                ('parent1_nom', models.CharField(blank=True, default='', max_length=150, verbose_name='Parent 1 — nom')),
                ('parent1_telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Parent 1 — téléphone')),
                ('parent1_whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='Parent 1 — WhatsApp')),
                ('parent1_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Parent 1 — email')),
                ('parent2_nom', models.CharField(blank=True, default='', max_length=150, verbose_name='Parent 2 — nom')),
                ('parent2_telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='Parent 2 — téléphone')),
                ('parent2_whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='Parent 2 — WhatsApp')),
                ('parent2_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Parent 2 — email')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénom')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], default='', max_length=1, verbose_name='Sexe')),
                ('cin', models.CharField(blank=True, default='', max_length=30, verbose_name="CIN / numéro d'identité")),
                ('statut', models.CharField(choices=[('prospect', 'Prospect'), ('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('radie', 'Radié'), ('diplome', 'Diplômé')], default='prospect', max_length=10, verbose_name='Statut')),
                ('numero_dossier', models.CharField(blank=True, db_index=True, default='', max_length=30, verbose_name='Numéro de dossier')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='education.classe', verbose_name='Classe')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves_photo', to='records.attachment', verbose_name='Photo')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to='education.famille', verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Élève',
                'verbose_name_plural': 'Élèves',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('refusee', 'Refusée'), ('liste_attente', "Liste d'attente")], default='en_attente', max_length=15, verbose_name='Statut')),
                ('date_demande', models.DateField(auto_now_add=True, verbose_name='Date de demande')),
                ('date_decision', models.DateField(blank=True, null=True, verbose_name='Date de décision')),
                ('position_liste_attente', models.PositiveIntegerField(blank=True, null=True, verbose_name="Position en liste d'attente")),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='education.anneescolaire', verbose_name='Année scolaire')),
                ('classe_affectee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_affectees', to='education.classe', verbose_name='Classe affectée')),
                ('classe_demandee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscriptions_demandees', to='education.classe', verbose_name='Classe demandée')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('decide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_inscriptions_decidees', to=settings.AUTH_USER_MODEL, verbose_name='Décidé par')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='education.eleve', verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('cycle', models.CharField(choices=[('prescolaire', 'Préscolaire'), ('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('formation', 'Formation')], max_length=15, verbose_name='Cycle')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre de progression')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='education.niveau', verbose_name='Niveau'),
        ),
        migrations.AddConstraint(
            model_name='anneescolaire',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'active')), fields=('company',), name='education_une_annee_active_par_societe'),
        ),
    ]
