# Generated by Django 5.1.4 on 2026-07-17 02:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name="Frais d'inscription")),
                ('scolarite_annuelle', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Scolarité annuelle')),
                ('transport_mensuel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Transport mensuel')),
                ('cantine_mensuelle', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cantine mensuelle')),
                ('activites_annuelles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Activités annuelles')),
                ('devise', models.CharField(default='MAD', max_length=3, verbose_name='Devise')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_tarifaires', to='education.anneescolaire', verbose_name='Année scolaire')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_tarifaires', to='education.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
                'ordering': ['annee_scolaire', 'niveau__ordre'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('annee_scolaire', 'niveau'), name='education_une_grille_active_par_annee_niveau')],
            },
        ),
    ]
