# Generated by Django 5.1.4 on 2026-07-17 02:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('education', '0002_grilletarifaire'),
        ('ged', '0043_zged15_backfill_document_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('fratrie', 'Fratrie'), ('bourse', 'Bourse'), ('autre', 'Autre')], max_length=10, verbose_name='Type')),
                ('mode', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('montant_fixe', 'Montant fixe')], default='pourcentage', max_length=15, verbose_name='Mode')),
                ('valeur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Valeur')),
                ('motif', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_remises_approuvees', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='education.eleve', verbose_name='Élève')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='education.famille', verbose_name='Famille')),
                ('justificatif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_education', to='ged.document', verbose_name='Justificatif (GED)')),
                ('valable_annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='education.anneescolaire', verbose_name='Année scolaire')),
            ],
            options={
                'verbose_name': 'Remise',
                'verbose_name_plural': 'Remises',
                'ordering': ['-id'],
            },
        ),
    ]
