# Generated by Django 5.1.4 on 2026-07-17 02:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('education', '0003_remise'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancierScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Montant total')),
                ('nombre_echeances', models.PositiveIntegerField(default=10, verbose_name="Nombre d'échéances")),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeanciers', to='education.anneescolaire', verbose_name='Année scolaire')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeanciers', to='education.eleve', verbose_name='Élève')),
                ('grille_tarifaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echeanciers', to='education.grilletarifaire', verbose_name='Grille tarifaire')),
                ('remises', models.ManyToManyField(blank=True, related_name='echeanciers', to='education.remise', verbose_name='Remises appliquées')),
            ],
            options={
                'verbose_name': 'Échéancier de scolarité',
                'verbose_name_plural': 'Échéanciers de scolarité',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneEcheance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Montant')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('facturee', 'Facturée'), ('payee', 'Payée'), ('en_retard', 'En retard')], default='a_venir', max_length=10, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('echeancier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='education.echeancierscolarite', verbose_name='Échéancier')),
            ],
            options={
                'verbose_name': "Ligne d'échéance",
                'verbose_name_plural': "Lignes d'échéance",
                'ordering': ['date_echeance'],
            },
        ),
        migrations.AddConstraint(
            model_name='echeancierscolarite',
            constraint=models.UniqueConstraint(fields=('eleve', 'annee_scolaire'), name='education_un_echeancier_par_eleve_annee'),
        ),
    ]
