# Generated by Django 5.1.4 on 2026-07-31 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('education', '0016_famille_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=50, verbose_name='Libellé')),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name="Ordre dans l'année")),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='education.anneescolaire', verbose_name='Année scolaire')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Période scolaire',
                'verbose_name_plural': 'Périodes scolaires',
                'ordering': ['annee_scolaire', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appreciation_generale', models.TextField(blank=True, default='', verbose_name='Appréciation générale')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='education.eleve', verbose_name='Élève')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='education.periodescolaire', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Bulletin',
                'verbose_name_plural': 'Bulletins',
                'ordering': ['-periode__ordre', 'eleve'],
            },
        ),
        migrations.AddConstraint(
            model_name='periodescolaire',
            constraint=models.UniqueConstraint(fields=('company', 'annee_scolaire', 'ordre'), name='education_periode_unique_par_annee_ordre'),
        ),
        migrations.AddConstraint(
            model_name='bulletin',
            constraint=models.UniqueConstraint(fields=('company', 'eleve', 'periode'), name='education_bulletin_unique_par_eleve_periode'),
        ),
    ]
