# Generated by Django 5.1.4 on 2026-07-31 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('education', '0017_ntedu17_periodescolaire_bulletin'),
        ('flotte', '0058_garage_contratvehicule_fournisseur_id_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du circuit')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circuits_transport_education', to='flotte.vehicule', verbose_name='Véhicule (flotte)')),
            ],
            options={
                'verbose_name': 'Circuit de transport',
                'verbose_name_plural': 'Circuits de transport',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ArretTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120, verbose_name="Nom de l'arrêt")),
                ('ordre', models.PositiveSmallIntegerField(default=1, verbose_name='Ordre sur le circuit')),
                ('heure_passage_estimee', models.TimeField(blank=True, null=True, verbose_name='Heure de passage estimée')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='education.circuittransport', verbose_name='Circuit')),
            ],
            options={
                'verbose_name': 'Arrêt de transport',
                'verbose_name_plural': 'Arrêts de transport',
                'ordering': ['circuit', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='AffectationTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_transport', to='education.eleve', verbose_name='Élève')),
                ('arret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations', to='education.arrettransport', verbose_name='Arrêt')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='education.circuittransport', verbose_name='Circuit')),
            ],
            options={
                'verbose_name': 'Affectation transport',
                'verbose_name_plural': 'Affectations transport',
                'ordering': ['-date_debut'],
            },
        ),
    ]
