version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    groups:
      npm-weekly:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/backend/django_core"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    groups:
      pip-weekly:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "chore"
    groups:
      github-actions-weekly:
        patterns:
          - "*"
