# Generated by Django 5.1.4 on 2026-07-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0037_zctr6_ordre_location_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='custom_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Champs personnalisés'),
        ),
    ]
