# Generated by Django 5.1.4 on 2026-07-17 11:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('contrats', '0038_contrat_custom_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prix unitaire')),
                ('facturation', models.CharField(choices=[('recurrente', 'Récurrente'), ('ponctuelle', 'Ponctuelle')], default='recurrente', max_length=15, verbose_name='Facturation')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Add-on d'abonnement",
                'verbose_name_plural': "Add-ons d'abonnement",
                'ordering': ['nom', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('prix_base', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prix de base')),
                ('engagement_mois', models.PositiveIntegerField(blank=True, null=True, verbose_name='Engagement (mois)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('plan_recurrent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans_abonnement', to='contrats.planrecurrent', verbose_name='Plan de facturation récurrente')),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['nom', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PalierUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seuil_min', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Seuil minimum')),
                ('seuil_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Seuil maximum (NULL = infini)')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prix unitaire de la tranche')),
                ('mode', models.CharField(choices=[('volume', 'Volume (dernier palier atteint)'), ('graduated', 'Graduated (par tranche)')], default='volume', max_length=15, verbose_name='Mode')),
                ('seuil_alerte_pct', models.PositiveIntegerField(blank=True, null=True, verbose_name="Seuil d'alerte (%)")),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='contrats.addonabonnement', verbose_name='Add-on')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('plan_abonnement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paliers', to='contrats.planabonnement', verbose_name="Plan d'abonnement")),
            ],
            options={
                'verbose_name': "Palier d'usage",
                'verbose_name_plural': "Paliers d'usage",
                'ordering': ['seuil_min', 'id'],
            },
        ),
        migrations.AddField(
            model_name='addonabonnement',
            name='plan_abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addons', to='contrats.planabonnement', verbose_name="Plan d'abonnement"),
        ),
        migrations.AddField(
            model_name='contrat',
            name='plan_abonnement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='contrats.planabonnement', verbose_name="Plan d'abonnement"),
        ),
        migrations.CreateModel(
            name='AbonnementAddOnLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_cible', models.CharField(choices=[('contrat', 'Contrat'), ('sav_maintenance', 'Maintenance SAV')], max_length=20, verbose_name='Type de cible')),
                ('cible_id', models.PositiveIntegerField(verbose_name='ID de la cible')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('actif_depuis', models.DateField(verbose_name='Actif depuis')),
                ('actif_jusqua', models.DateField(blank=True, null=True, verbose_name="Actif jusqu'à")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='contrats.addonabonnement', verbose_name='Add-on')),
            ],
            options={
                'verbose_name': "Ligne add-on d'abonnement",
                'verbose_name_plural': "Lignes add-on d'abonnement",
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'type_cible', 'cible_id'], name='contrats_addonlig_cible')],
            },
        ),
        migrations.CreateModel(
            name='CompteurUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_cible', models.CharField(choices=[('contrat', 'Contrat'), ('sav_maintenance', 'Maintenance SAV')], max_length=20, verbose_name='Type de cible')),
                ('cible_id', models.PositiveIntegerField(verbose_name='ID de la cible')),
                ('code_compteur', models.CharField(max_length=100, verbose_name='Code du compteur')),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('quantite', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14, verbose_name='Quantité')),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('api', 'API'), ('calcule', 'Calculé')], default='manuel', max_length=10, verbose_name='Source')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Compteur d'usage",
                'verbose_name_plural': "Compteurs d'usage",
                'ordering': ['-periode_debut', '-id'],
                'indexes': [models.Index(fields=['company', 'type_cible', 'cible_id', 'code_compteur'], name='contrats_compteur_co_cible')],
                'constraints': [models.UniqueConstraint(fields=('company', 'type_cible', 'cible_id', 'code_compteur', 'periode_debut', 'periode_fin'), name='contrats_compteur_uniq_periode')],
            },
        ),
        migrations.AddIndex(
            model_name='planabonnement',
            index=models.Index(fields=['company', 'actif'], name='contrats_planabo_co_act'),
        ),
        migrations.AddConstraint(
            model_name='planabonnement',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='contrats_planabo_uniq_code'),
        ),
        migrations.AddIndex(
            model_name='palierusage',
            index=models.Index(fields=['company', 'addon'], name='contrats_palier_co_addon'),
        ),
        migrations.AddIndex(
            model_name='palierusage',
            index=models.Index(fields=['company', 'plan_abonnement'], name='contrats_palier_co_plan'),
        ),
        migrations.AddConstraint(
            model_name='addonabonnement',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='contrats_addon_uniq_code'),
        ),
    ]
