# Generated by Django 5.1.4 on 2026-07-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('contrats', '0039_ntsub1_4_catalogue_addons_paliers_compteurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaiAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_cible', models.CharField(choices=[('contrat', 'Contrat'), ('sav_maintenance', 'Maintenance SAV')], max_length=20, verbose_name='Type de cible')),
                ('cible_id', models.PositiveIntegerField(verbose_name='ID de la cible')),
                ('date_fin_essai', models.DateField(verbose_name="Date de fin d'essai")),
                ('converti', models.BooleanField(default=False, verbose_name='Converti')),
                ('date_conversion', models.DateField(blank=True, null=True, verbose_name='Date de conversion')),
                ('notifie_j3', models.BooleanField(default=False, verbose_name='Notifié J-3')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('plan_apres_essai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essais', to='contrats.planabonnement', verbose_name="Plan d'abonnement après essai")),
            ],
            options={
                'verbose_name': "Essai d'abonnement",
                'verbose_name_plural': "Essais d'abonnement",
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'converti', 'date_fin_essai'], name='contrats_essai_co_fin')],
                'constraints': [models.UniqueConstraint(fields=('company', 'type_cible', 'cible_id'), name='contrats_essai_uniq_cible')],
            },
        ),
    ]
