# Generated by Django 5.1.4 on 2026-07-17 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('contrats', '0040_essaiabonnement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceDunning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Séquence de dunning',
                'verbose_name_plural': 'Séquences de dunning',
                'ordering': ['nom', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EtapeDunning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jour_offset', models.PositiveIntegerField(verbose_name="Jours après l'échéance impayée")),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('notification_interne', 'Notification interne')], default='notification_interne', max_length=25, verbose_name='Canal')),
                ('template_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence de gabarit')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('declenche_suspension', models.BooleanField(default=False, verbose_name='Déclenche la suspension (ZCTR2)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='contrats.sequencedunning', verbose_name='Séquence')),
            ],
            options={
                'verbose_name': 'Étape de dunning',
                'verbose_name_plural': 'Étapes de dunning',
                'ordering': ['sequence_id', 'ordre', 'jour_offset', 'id'],
            },
        ),
        migrations.AddField(
            model_name='contrat',
            name='sequence_dunning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats', to='contrats.sequencedunning', verbose_name='Séquence de dunning'),
        ),
        migrations.CreateModel(
            name='EtapeDunningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_execution', models.DateField(verbose_name="Date d'exécution")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dunning_logs', to='contrats.contrat', verbose_name='Contrat')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='contrats.etapedunning', verbose_name='Étape')),
            ],
            options={
                'verbose_name': 'Trace de dunning',
                'verbose_name_plural': 'Traces de dunning',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'contrat'], name='contrats_dunlog_co_ct')],
                'constraints': [models.UniqueConstraint(fields=('contrat', 'etape'), name='contrats_dunlog_uniq')],
            },
        ),
        migrations.AddIndex(
            model_name='sequencedunning',
            index=models.Index(fields=['company', 'actif'], name='contrats_dunseq_co_act'),
        ),
        migrations.AddIndex(
            model_name='etapedunning',
            index=models.Index(fields=['company', 'sequence'], name='contrats_dunetape_co_seq'),
        ),
    ]
