# Generated by Django 5.1.4 on 2026-07-17 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_attestation', models.CharField(choices=[('fiscale_regularite', 'Attestation de régularité fiscale'), ('sociale_cnss', 'Attestation de régularité CNSS'), ('rc', 'Registre de commerce'), ('patente', 'Patente / taxe professionnelle'), ('agrement', 'Agrément')], max_length=24, verbose_name='Type')),
                ('numero', models.CharField(blank=True, default='', max_length=80, verbose_name='Numéro')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('date_expiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('fichier_key', models.CharField(blank=True, default='', max_length=500, verbose_name='Clé MinIO du fichier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_tenant', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Attestation (tenant)',
                'verbose_name_plural': 'Attestations (tenant)',
                'ordering': ['type_attestation', '-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaireEffectif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('cin_passeport', models.CharField(blank=True, default='', max_length=40, verbose_name='CIN / Passeport')),
                ('nationalite', models.CharField(blank=True, default='', max_length=80, verbose_name='Nationalité')),
                ('pourcentage_detention', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% de détention')),
                ('type_controle', models.CharField(choices=[('direct', 'Contrôle direct'), ('indirect', 'Contrôle indirect')], default='direct', max_length=10, verbose_name='Type de contrôle')),
                ('date_declaration', models.DateField(blank=True, null=True, verbose_name='Date de déclaration')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaires_effectifs', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Bénéficiaire effectif (UBO)',
                'verbose_name_plural': 'Bénéficiaires effectifs (UBO)',
                'ordering': ['-pourcentage_detention', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ObligationFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_obligation', models.CharField(choices=[('tva', 'TVA'), ('is', 'Impôt sur les sociétés'), ('ir', 'Impôt sur le revenu'), ('acompte_is', 'Acompte IS'), ('timbre', 'Droit de timbre'), ('ras', 'Retenue à la source'), ('cnss_ref', 'CNSS'), ('taxe_pro', 'Taxe professionnelle'), ('droit_enregistrement', "Droit d'enregistrement")], max_length=24, verbose_name='Type')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('periodicite', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle'), ('ponctuelle', 'Ponctuelle')], default='mensuelle', max_length=14, verbose_name='Périodicité')),
                ('regle_echeance', models.CharField(blank=True, default='', max_length=120, verbose_name="Règle d'échéance")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations_fiscales_ma', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Obligation fiscale (Maroc)',
                'verbose_name_plural': 'Obligations fiscales (Maroc)',
                'ordering': ['type_obligation'],
            },
        ),
        migrations.CreateModel(
            name='EcheanceFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('periode_debut', models.DateField(verbose_name='Début de période')),
                ('periode_fin', models.DateField(verbose_name='Fin de période')),
                ('date_limite', models.DateField(verbose_name='Date limite')),
                ('statut', models.CharField(choices=[('a_preparer', 'À préparer'), ('deposee', 'Déposée'), ('payee', 'Payée')], default='a_preparer', max_length=12, verbose_name='Statut')),
                ('declaration_type', models.CharField(blank=True, default='', max_length=40, verbose_name='Type de déclaration source')),
                ('declaration_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la déclaration source')),
                ('rappel_envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='Rappel envoyé le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_fiscales_ma', to='authentication.company', verbose_name='Société')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='fiscal.obligationfiscale', verbose_name='Obligation')),
            ],
            options={
                'verbose_name': 'Échéance fiscale',
                'verbose_name_plural': 'Échéances fiscales',
                'ordering': ['date_limite', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VeilleReglementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domaine', models.CharField(choices=[('tva', 'TVA'), ('is', 'IS'), ('ir', 'IR'), ('marches', 'Marchés publics'), ('cnss', 'CNSS'), ('einvoicing', 'E-invoicing'), ('environnement', 'Environnement')], max_length=14, verbose_name='Domaine')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('resume', models.TextField(blank=True, default='', verbose_name='Résumé')),
                ('date_effet', models.DateField(blank=True, null=True, verbose_name="Date d'effet")),
                ('source_url', models.URLField(blank=True, default='', verbose_name='Source')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('traite', 'Traité')], default='nouveau', max_length=10, verbose_name='Statut')),
                ('parametre_cible', models.CharField(blank=True, default='', max_length=120, verbose_name='Paramètre cible')),
                ('impact_traite', models.BooleanField(default=False, verbose_name='Impact traité')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veilles_reglementaires', to='authentication.company', verbose_name='Société (vide = globale)')),
            ],
            options={
                'verbose_name': 'Veille réglementaire',
                'verbose_name_plural': 'Veilles réglementaires',
                'ordering': ['-date_effet', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='obligationfiscale',
            constraint=models.UniqueConstraint(fields=('company', 'type_obligation'), name='uniq_obligation_fiscale_ma_type'),
        ),
        migrations.AddConstraint(
            model_name='echeancefiscale',
            constraint=models.UniqueConstraint(fields=('company', 'obligation', 'periode_debut', 'periode_fin'), name='uniq_echeance_fiscale_ma_periode'),
        ),
    ]
