# Generated by Django 5.1.4 on 2026-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentactionlog',
            name='action_key',
            field=models.CharField(help_text='Clé stable du registre (apps.agent.registry.AgentAction.key).', max_length=100, verbose_name="Clé de l'action"),
        ),
        migrations.AlterField(
            model_name='agentactionlog',
            name='inputs_json',
            field=models.JSONField(blank=True, default=dict, help_text="Paramètres fournis par l'utilisateur au moment de la confirmation.", verbose_name='Paramètres'),
        ),
        migrations.AlterField(
            model_name='agentactionlog',
            name='proposal_hash',
            field=models.CharField(blank=True, default='', help_text='Empreinte HMAC de la proposition confirmée (traçabilité, non secrète).', max_length=128, verbose_name='Empreinte de la proposition'),
        ),
    ]
