# Generated by Django 5.1.4 on 2026-06-18 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("stock", "0019_retourfournisseur_ligneretourfournisseur"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitOutillage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120)),
                (
                    "type_intervention",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kits_outillage",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kit d'outillage",
                "verbose_name_plural": "Kits d'outillage",
                "ordering": ["ordre", "nom"],
                "unique_together": {("company", "nom")},
            },
        ),
        migrations.CreateModel(
            name="Outillage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("categorie", models.CharField(blank=True, default="", max_length=120)),
                ("asset_tag", models.CharField(blank=True, default="", max_length=80)),
                (
                    "numero_serie",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_intervention", "En intervention"),
                            ("en_reparation", "En réparation"),
                            ("perdu", "Perdu"),
                        ],
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("date_achat", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outillages",
                        to="authentication.company",
                    ),
                ),
                (
                    "emplacement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outillages",
                        to="stock.emplacementstock",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outil",
                "verbose_name_plural": "Outillage",
                "ordering": ["nom", "id"],
            },
        ),
        migrations.CreateModel(
            name="KitOutillageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_outillage_items",
                        to="authentication.company",
                    ),
                ),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="outillage.kitoutillage",
                    ),
                ),
                (
                    "outil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_items",
                        to="outillage.outillage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outil du kit",
                "verbose_name_plural": "Outils du kit",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="outillage",
            index=models.Index(
                fields=["company", "statut"], name="outillage_o_company_a17ddd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kitoutillageitem",
            unique_together={("kit", "outil")},
        ),
    ]
