# Generated by Django 5.1.4 on 2026-06-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("outillage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outillage",
            name="date_derniere_calibration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outillage",
            name="date_prochaine_calibration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="outillage",
            name="intervalle_calibration_mois",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="0 = pas de calibration périodique requise."
            ),
        ),
    ]
