# Generated by Django 5.1.4 on 2026-09-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portail', '0006_aud137_uniq_paiement_initie_par_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentclientportail',
            name='fichier_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='documentclientportail',
            name='fichier_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='documentclientportail',
            name='fichier_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='documentclientportail',
            name='fichier_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AlterField(
            model_name='documentclientportail',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='compta/portail_docs/', verbose_name='Fichier (legacy, hors MinIO)'),
        ),
    ]
