# Generated by Django 5.1.4 on 2026-06-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("ged", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentLien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ged_document_liens",
                        to="authentication.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ged_liens_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens",
                        to="ged.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien de document",
                "verbose_name_plural": "Liens de document",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="ged_documen_content_4703d2_idx",
                    ),
                    models.Index(
                        fields=["company", "document"],
                        name="ged_documen_company_bfbdf0_idx",
                    ),
                ],
                "unique_together": {("document", "content_type", "object_id")},
            },
        ),
    ]
