# Generated by Django 5.1.4 on 2026-06-22 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("crm", "0024_lead_bill_kwh_lead_roof_outline_lead_roof_point_and_more"),
        ("ged", "0002_documentlien"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coffre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ged_coffres",
                        to="crm.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ged_coffres",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ged_coffres_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proprietaire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ged_coffres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Coffre-fort",
                "verbose_name_plural": "Coffres-forts",
                "ordering": ["nom", "id"],
            },
        ),
        migrations.AddField(
            model_name="document",
            name="coffre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to="ged.coffre",
            ),
        ),
        migrations.AddIndex(
            model_name="coffre",
            index=models.Index(
                fields=["company", "proprietaire"], name="ged_coffre_company_11941e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coffre",
            index=models.Index(
                fields=["company", "client"], name="ged_coffre_company_2968a7_idx"
            ),
        ),
    ]
