# Generated by Django 5.1.4 on 2026-06-22 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("ged", "0003_coffre_document_coffre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=110)),
                ("couleur", models.CharField(blank=True, default="", max_length=7)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ged_tags",
                        to="authentication.company",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enfants",
                        to="ged.documenttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag documentaire",
                "verbose_name_plural": "Tags documentaires",
                "ordering": ["nom", "id"],
            },
        ),
        migrations.CreateModel(
            name="DocumentTagAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ged_tag_assignments",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ged_tag_assignments_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_assignments",
                        to="ged.document",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="ged.documenttag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affectation de tag",
                "verbose_name_plural": "Affectations de tag",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="documenttag",
            index=models.Index(
                fields=["company", "slug"], name="ged_documen_company_7b1afe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttag",
            index=models.Index(
                fields=["parent"], name="ged_documen_parent__b53e7f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documenttag",
            unique_together={("company", "slug")},
        ),
        migrations.AddIndex(
            model_name="documenttagassignment",
            index=models.Index(
                fields=["company", "document"], name="ged_documen_company_23f838_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttagassignment",
            index=models.Index(fields=["tag"], name="ged_documen_tag_id_9821c8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documenttagassignment",
            unique_together={("document", "tag")},
        ),
    ]
