# Generated by Django 5.1.4 on 2026-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0004_documenttag_documenttagassignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="custom_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
