# Generated by Django 5.1.4 on 2026-06-22 14:39

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("ged", "0006_document_search_vector_document_texte_ocr_and_more"),
    ]

    operations = [
        # GED12 — garantit l'extension pgvector avant d'ajouter la colonne
        # `vector`. Idempotent (CREATE EXTENSION IF NOT EXISTS).
        VectorExtension(),
        migrations.AddField(
            model_name="document",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True
            ),
        ),
    ]
