# Generated by Django 5.1.4 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('ged', '0028_xged7_8_9_13_15_16_18_19_20'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='ged_folder_unique_alias_email',
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('alias_email', ''), _negated=True)), fields=('company', 'alias_email'), name='ged_folder_unique_alias_email'),
        ),
    ]
