# Generated by Django 5.1.4 on 2026-07-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_alias_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cannedresponse',
            new_name='chat_canned_company_83cb34_idx',
            old_name='chat_canned_co_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='messagebookmark',
            new_name='chat_messag_user_id_51b018_idx',
            old_name='chat_bookmark_user_msg_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereminder',
            new_name='chat_messag_status_8c11ce_idx',
            old_name='chat_reminder_status_idx',
        ),
        migrations.RenameIndex(
            model_name='messagereminder',
            new_name='chat_messag_user_id_7ff423_idx',
            old_name='chat_reminder_user_msg_idx',
        ),
        migrations.RenameIndex(
            model_name='pollvote',
            new_name='chat_pollvo_option__79d1a9_idx',
            old_name='chat_pollvote_opt_user_idx',
        ),
        migrations.RenameIndex(
            model_name='retentionsweeprun',
            new_name='chat_retent_company_9a967e_idx',
            old_name='chat_retention_run_co_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledmessage',
            new_name='chat_schedu_status_1cef9a_idx',
            old_name='chat_schedmsg_status_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledmessage',
            new_name='chat_schedu_company_5ea162_idx',
            old_name='chat_schedmsg_co_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='threadfollow',
            new_name='chat_thread_user_id_4484c3_idx',
            old_name='chat_threadfollow_user_idx',
        ),
        migrations.RenameIndex(
            model_name='userchatstatus',
            new_name='chat_userch_company_798a7a_idx',
            old_name='chat_userchatstatus_co_idx',
        ),
    ]
