# Generated by Django 5.1.4 on 2026-07-09 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tiers', models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=20, verbose_name='Type de tiers')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom / Raison sociale')),
                ('prenom', models.CharField(blank=True, default='', max_length=255, verbose_name='Prénom')),
                ('raison_sociale', models.CharField(blank=True, default='', max_length=255, verbose_name='Raison sociale')),
                ('telephone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, default='', max_length=120, verbose_name='Ville')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude GPS')),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude GPS')),
                ('ice', models.CharField(blank=True, default='', help_text="Identifiant Commun de l'Entreprise.", max_length=30, verbose_name='ICE')),
                ('rc', models.CharField(blank=True, default='', help_text='Registre de Commerce.', max_length=30, verbose_name='RC')),
                ('identifiant_fiscal', models.CharField(blank=True, default='', help_text='Identifiant Fiscal.', max_length=30, verbose_name='IF')),
                ('cin', models.CharField(blank=True, default='', help_text="Carte d'Identité Nationale (particulier).", max_length=30, verbose_name='CIN')),
                ('rib', models.CharField(blank=True, default='', max_length=50, verbose_name='RIB')),
                ('is_client', models.BooleanField(default=False, verbose_name='Client')),
                ('is_fournisseur', models.BooleanField(default=False, verbose_name='Fournisseur')),
                ('is_partenaire', models.BooleanField(default=False, verbose_name='Partenaire')),
                ('is_soustraitant', models.BooleanField(default=False, verbose_name='Sous-traitant')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Tiers',
                'verbose_name_plural': 'Tiers',
                'ordering': ['nom', 'prenom'],
                'indexes': [models.Index(fields=['company', 'nom'], name='tiers_tiers_company_51f9b3_idx'), models.Index(fields=['company', 'email'], name='tiers_tiers_company_a2de54_idx')],
            },
        ),
    ]
