# Generated by Django 5.1.4 on 2026-06-21 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NonConformite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Référence",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "gravite",
                    models.CharField(
                        choices=[
                            ("mineure", "Mineure"),
                            ("majeure", "Majeure"),
                            ("critique", "Critique"),
                        ],
                        default="mineure",
                        max_length=10,
                        verbose_name="Gravité",
                    ),
                ),
                (
                    "origine",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Origine"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouverte", "Ouverte"),
                            ("en_traitement", "En traitement"),
                            ("resolue", "Résolue"),
                            ("cloturee", "Clôturée"),
                        ],
                        default="ouverte",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "chantier_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID du chantier"
                    ),
                ),
                (
                    "date_detection",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de détection"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qhse_ncr",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "signale_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qhse_ncr_signalees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Signalé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Non-conformité",
                "verbose_name_plural": "Non-conformités",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ActionCorrectivePreventive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_action",
                    models.CharField(
                        choices=[
                            ("corrective", "Corrective"),
                            ("preventive", "Préventive"),
                        ],
                        default="corrective",
                        max_length=12,
                        verbose_name="Type d'action",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "cause_racine",
                    models.TextField(
                        blank=True, default="", verbose_name="Cause racine"
                    ),
                ),
                (
                    "echeance",
                    models.DateField(
                        blank=True, null=True, verbose_name="Échéance"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("realisee", "Réalisée"),
                            ("verifiee", "Vérifiée"),
                        ],
                        default="a_faire",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qhse_capa",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "non_conformite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="qhse.nonconformite",
                        verbose_name="Non-conformité",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qhse_capa_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action corrective / préventive",
                "verbose_name_plural": "Actions correctives / préventives",
                "ordering": ["-id"],
            },
        ),
    ]
