# Generated by Django 5.1.4 on 2026-06-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qhse", "0003_planinspectionchantier_relevecontrole"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointcontrolemodele",
            name="valeur_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Valeur max attendue",
            ),
        ),
        migrations.AddField(
            model_name="pointcontrolemodele",
            name="valeur_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=14,
                null=True,
                verbose_name="Valeur min attendue",
            ),
        ),
    ]
