# Generated by Django 5.1.4 on 2026-06-22 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("qhse", "0004_pointcontrolemodele_valeur_max_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleveCourbeIV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chantier_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID du chantier"
                    ),
                ),
                (
                    "string_id",
                    models.CharField(
                        max_length=120, verbose_name="Identifiant du string"
                    ),
                ),
                (
                    "voc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Voc — tension circuit ouvert (V)",
                    ),
                ),
                (
                    "isc",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Isc — courant court-circuit (A)",
                    ),
                ),
                (
                    "vmpp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Vmpp — tension au point de puissance max (V)",
                    ),
                ),
                (
                    "impp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Impp — courant au point de puissance max (A)",
                    ),
                ),
                (
                    "pmpp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        verbose_name="Pmpp — puissance au point max (W)",
                    ),
                ),
                (
                    "irradiance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Irradiance (W/m²)",
                    ),
                ),
                (
                    "temperature_module",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Température module (°C)",
                    ),
                ),
                (
                    "courbe_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="Points de la courbe (v, i)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "date_releve",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date du relevé"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qhse_courbes_iv",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "plan_chantier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courbes_iv",
                        to="qhse.planinspectionchantier",
                        verbose_name="Plan d'inspection chantier",
                    ),
                ),
                (
                    "releve_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qhse_courbes_iv_relevees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Relevé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relevé courbe I-V",
                "verbose_name_plural": "Relevés courbe I-V",
                "ordering": ["-id"],
            },
        ),
    ]
