# Generated by Django 5.1.4 on 2026-06-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "installations",
            "0013_modeleprojet_modeleprojetbomligne_modeleprojetjalon_and_more",
        ),
        ("qhse", "0005_relevecourbeiv"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonconformite",
            name="reserve",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qhse_ncr",
                to="installations.reserve",
                verbose_name="Réserve d'origine",
            ),
        ),
    ]
