# Generated by Django 5.1.4 on 2026-06-22 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qhse", "0006_nonconformite_reserve"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actioncorrectivepreventive",
            name="commentaire_verification",
            field=models.TextField(
                blank=True, default="", verbose_name="Commentaire de vérification"
            ),
        ),
        migrations.AddField(
            model_name="actioncorrectivepreventive",
            name="date_verification",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Vérifiée le"
            ),
        ),
        migrations.AddField(
            model_name="actioncorrectivepreventive",
            name="efficace",
            field=models.BooleanField(blank=True, null=True, verbose_name="Efficace"),
        ),
        migrations.AddField(
            model_name="actioncorrectivepreventive",
            name="verifiee_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qhse_capa_verifiees",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vérifiée par",
            ),
        ),
    ]
