# Generated by Django 5.1.4 on 2026-06-22 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("qhse", "0007_actioncorrectivepreventive_commentaire_verification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QhseChatterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cible_type",
                    models.CharField(
                        choices=[
                            ("ncr", "Non-conformité"),
                            ("capa", "Action corrective/préventive"),
                            ("incident", "Incident"),
                            ("audit", "Audit"),
                        ],
                        max_length=10,
                        verbose_name="Type de cible",
                    ),
                ),
                (
                    "cible_id",
                    models.PositiveIntegerField(verbose_name="ID de l'objet ciblé"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("creation", "Création"),
                            ("modification", "Modification"),
                            ("note", "Note"),
                        ],
                        max_length=15,
                        verbose_name="Type d'entrée",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Champ"
                    ),
                ),
                (
                    "field_label",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=150,
                        verbose_name="Libellé du champ",
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True, default="", verbose_name="Ancienne valeur"
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, default="", verbose_name="Nouvelle valeur"
                    ),
                ),
                ("body", models.TextField(blank=True, default="", verbose_name="Note")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qhse_chatter",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qhse_chatter",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée de chatter QHSE",
                "verbose_name_plural": "Entrées de chatter QHSE",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["company", "cible_type", "cible_id"],
                        name="qhse_qhsech_company_b1a842_idx",
                    )
                ],
            },
        ),
    ]
