# Generated by Django 5.1.4 on 2026-06-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("qhse", "0008_qhsechatterentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="GrilleAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Code"
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "type_audit",
                    models.CharField(
                        choices=[
                            ("chantier", "Chantier"),
                            ("securite", "Sécurité"),
                            ("qualite", "Qualité"),
                            ("environnement", "Environnement"),
                        ],
                        default="chantier",
                        max_length=15,
                        verbose_name="Type d'audit",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qhse_grilles_audit",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grille d'audit",
                "verbose_name_plural": "Grilles d'audit",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CritereAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("intitule", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "categorie",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Catégorie"
                    ),
                ),
                ("poids", models.PositiveIntegerField(default=1, verbose_name="Poids")),
                (
                    "note_max",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Note maximale"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qhse_criteres_audit",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "grille",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteres",
                        to="qhse.grilleaudit",
                        verbose_name="Grille d'audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Critère d'audit",
                "verbose_name_plural": "Critères d'audit",
                "ordering": ["grille", "ordre", "id"],
            },
        ),
    ]
