# Generated by Django 5.1.4 on 2026-07-31 19:11
#
# SOL2(a) — RÉÉCRITE le 02/09/2026. À l'origine cette migration ajoutait une
# ForeignKey `NonConformite.cycle_sterilisation` vers `sante.CycleSterilisation`
# et dépendait de ('sante', '0019_ntsan23_sterilisation'). `qhse` est GARDÉ dans
# l'édition solaire alors que `sante` en est PARQUÉ : avec cette dépendance,
# `migrate` sur une base vierge en édition solaire échouait (nœud de migration
# introuvable), et la contrainte de clé étrangère visait une table jamais créée.
#
# La migration crée désormais la MÊME COLONNE (`cycle_sterilisation_id`, entier
# nullable indexé) sans contrainte référentielle et sans dépendance vers
# `sante`. Sur une base DÉJÀ migrée, cette migration est déjà appliquée : la
# colonne et ses données restent en place, inchangées — c'est la migration 0058
# qui y retire l'ancienne contrainte de clé étrangère devenue orpheline.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qhse', '0056_wir128_permis_valideur_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformite',
            name='cycle_sterilisation_id',
            field=models.IntegerField(
                blank=True, null=True, db_index=True,
                verbose_name="Cycle de stérilisation d'origine (sante)"),
        ),
    ]
