# Generated by Django 5.1.4 on 2026-07-31 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qhse', '0056_wir128_permis_valideur_fk'),
        ('sante', '0019_ntsan23_sterilisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonconformite',
            name='cycle_sterilisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qhse_ncr', to='sante.cyclesterilisation', verbose_name="Cycle de stérilisation d'origine"),
        ),
    ]
