# Generated by Django 5.1.4 on 2026-08-14 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('crm', 'CRM'), ('ventes', 'Ventes'), ('stock', 'Stock'), ('installations', 'Chantiers'), ('sav', 'SAV')], db_index=True, max_length=20, verbose_name='Module cible')),
                ('op_type', models.CharField(max_length=60, verbose_name='Type d’opération')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Corps de l’opération')),
                ('client_op_id', models.CharField(db_index=True, max_length=64, verbose_name='Clé client')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('appliquee', 'Appliquée'), ('rejetee', 'Rejetée'), ('conflit', 'En conflit')], db_index=True, default='en_attente', max_length=12, verbose_name='Statut')),
                ('resultat', models.JSONField(blank=True, default=dict, verbose_name='Résultat')),
                ('erreur', models.TextField(blank=True, default='', verbose_name='Motif du refus')),
                ('date_creation', models.DateTimeField(blank=True, null=True, verbose_name='Mise en file (terminal)')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Traitée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auteur (terminal)')),
            ],
            options={
                'verbose_name': 'Opération hors-ligne',
                'verbose_name_plural': 'Opérations hors-ligne',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'statut'], name='offlinesync_co_statut_idx'), models.Index(fields=['company', 'module', 'statut'], name='offlinesync_co_mod_statut_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'client_op_id'), name='offlinesync_op_unique_par_societe')],
            },
        ),
    ]
