# Generated by Django 5.1.4 on 2026-08-14 02:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('fidelite', '0002_ntret10_paliers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='palierfidelite',
            name='chk_palierfidelite_seuil_requis',
        ),
        migrations.AlterField(
            model_name='programmefidelite',
            name='points_par_mad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Points crédités par MAD TTC dépensé.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='programmefidelite',
            name='valeur_mad_par_point',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text="Valeur (MAD) d'un point à la dépense — affichage seul, aucune dépense de points n'est câblée par ce lot (NTRET9).", max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='palierfidelite',
            constraint=models.CheckConstraint(condition=models.Q(('seuil_points__isnull', False), ('seuil_ca_cumule__isnull', False), _connector='OR'), name='chk_palierfidelite_seuil_requis'),
        ),
    ]
