# Generated by Django 5.1.4 on 2026-08-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0002_tenantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='reference_acheteur',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Référence du marché (acheteur)'),
        ),
    ]
