# Generated by Django 5.1.4 on 2026-08-01 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0006_resultat_ao'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        ('records', '0013_vx210_snooze_trigger_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, default='', max_length=40, verbose_name='Référence')),
                ('intitule', models.CharField(default='Dossier de dépôt', max_length=200, verbose_name='Intitulé')),
                ('date_depot', models.DateField(blank=True, null=True, verbose_name='Date de dépôt effectif')),
                ('statut', models.CharField(blank=True, choices=[('montage', 'Montage'), ('en_constitution', 'En constitution'), ('controle', 'Contrôle'), ('pret_a_deposer', 'Prêt à déposer'), ('depose', 'Déposé'), ('clos', 'Clos')], default='montage', max_length=32)),
                ('appel_offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_ao', to='ao.appeloffre', verbose_name="Appel d'offres")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Dossier de dépôt (AO)',
                'verbose_name_plural': 'Dossiers de dépôt (AO)',
                'db_table': 'ao_dossier',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PieceDossierAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('code', models.CharField(max_length=20, verbose_name='Code de la pièce')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_piece', models.CharField(choices=[('generee', 'Générée par la fabrique'), ('fournie', 'Fournie (partenaire / acheteur)')], default='generee', max_length=8, verbose_name='Type de pièce')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('presente', models.BooleanField(default=False, verbose_name='Présente')),
                ('visibilite', models.CharField(choices=[('client', "Client (remise au maître d'ouvrage)"), ('interne', 'Interne'), ('directeur', 'Directeur')], default='client', max_length=10, verbose_name='Visibilité')),
                ('signee', models.BooleanField(default=False, help_text='NON-OBJECTIF v1 ACTÉ : PAS de signature électronique. Le dépôt marocain visé est PAPIER, en 2 exemplaires, avec paraphe manuscrit — ce booléen est donc un POINTAGE HUMAIN, jamais un état cryptographique. Le jour où la signature devient un besoin, elle se branchera sur ged.ChampSignature (déjà en production) et sur AUCUN mécanisme local.', verbose_name='Signée / paraphée (pointage humain)')),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif / commentaire')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_dossier_ao', to='records.attachment', verbose_name='Artefact (MinIO)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='ao.dossierao', verbose_name='Dossier')),
                ('piece_soumission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_dossier_ao', to='ao.piecesoumission', verbose_name='Pièce administrative (legacy)')),
            ],
            options={
                'verbose_name': 'Pièce du dossier de dépôt (AO)',
                'verbose_name_plural': 'Pièces du dossier de dépôt (AO)',
                'db_table': 'ao_piece_dossier',
                'ordering': ['dossier', 'ordre', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='dossierao',
            index=models.Index(fields=['company', 'statut'], name='ao_dossier_company_b93b13_idx'),
        ),
        migrations.AddConstraint(
            model_name='dossierao',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('company', 'reference'), name='uniq_dossier_ao_reference'),
        ),
        migrations.AddIndex(
            model_name='piecedossierao',
            index=models.Index(fields=['company', 'dossier', 'visibilite'], name='ao_piece_do_company_3447a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='piecedossierao',
            constraint=models.UniqueConstraint(fields=('dossier', 'code'), name='uniq_piece_dossier_ao_code'),
        ),
        migrations.AddConstraint(
            model_name='piecedossierao',
            constraint=models.CheckConstraint(condition=models.Q(('attachment__isnull', True), ('piece_soumission__isnull', True), _connector='OR'), name='piece_dossier_ao_source_unique'),
        ),
    ]
