# Generated by Django 5.1.4 on 2026-08-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0007_documents'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, verbose_name='Code du modèle')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Modèle de pack (AO)',
                'verbose_name_plural': 'Modèles de pack (AO)',
                'db_table': 'ao_modele_pack',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PieceModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='Code de la pièce')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('generateur', models.CharField(blank=True, default='', max_length=60, verbose_name='Générateur (nom logique)')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('pdf_a3', 'PDF A3 (planches)'), ('xlsx', 'Classeur XLSX'), ('docx', 'Document DOCX éditable'), ('zip', 'Archive ZIP')], default='pdf', max_length=8, verbose_name='Format')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('visibilite', models.CharField(choices=[('client', "Client (remise au maître d'ouvrage)"), ('interne', 'Interne'), ('directeur', 'Directeur')], default='client', max_length=10, verbose_name='Visibilité')),
                ('gabarit', models.TextField(blank=True, default='', verbose_name='Gabarit (placeholders {{ … }}, aucun chiffre littéral)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='ao.modelepack', verbose_name='Modèle de pack')),
            ],
            options={
                'verbose_name': 'Pièce de gabarit (AO)',
                'verbose_name_plural': 'Pièces de gabarit (AO)',
                'db_table': 'ao_piece_modele',
                'ordering': ['modele', 'ordre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SectionMemoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, verbose_name='Code')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('corps', models.TextField(blank=True, default='', verbose_name='Corps (placeholders {{ … }})')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('conditions_inclusion', models.JSONField(blank=True, default=dict, verbose_name="Conditions d'inclusion")),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Section de mémoire (AO)',
                'verbose_name_plural': 'Sections de mémoire (AO)',
                'db_table': 'ao_section_memoire',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.AddConstraint(
            model_name='modelepack',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_modele_pack_code'),
        ),
        migrations.AddConstraint(
            model_name='piecemodele',
            constraint=models.UniqueConstraint(fields=('modele', 'code'), name='uniq_piece_modele_code'),
        ),
        migrations.AddConstraint(
            model_name='sectionmemoire',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_section_memoire_code'),
        ),
    ]
