# Generated by Django 5.1.4 on 2026-08-01 15:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0008_gabarits'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        ('records', '0013_vx210_snooze_trigger_event'),
        ('stock', '0083_ntprt25_fournisseur_statut_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('module', 'Module photovoltaïque'), ('onduleur', 'Onduleur'), ('batterie', 'Batterie / stockage'), ('coffret_dc', 'Coffret DC'), ('coffret_ac', 'Coffret AC'), ('tgpv', 'TGPV'), ('cable', 'Câble'), ('structure', 'Structure de pose'), ('ems', 'EMS / supervision'), ('station_meteo', 'Station météo'), ('afficheur', 'Afficheur'), ('variateur', 'Variateur')], max_length=14, verbose_name='Rôle')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation (figée)')),
                ('marque', models.CharField(blank=True, default='', max_length=100, verbose_name='Marque (figée)')),
                ('reference_constructeur', models.CharField(blank=True, default='', max_length=120, verbose_name='Référence constructeur (figée)')),
                ('caracteristiques', models.JSONField(blank=True, default=dict, verbose_name='Caractéristiques (figées)')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, default='U', max_length=20, verbose_name='Unité')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('snapshot_le', models.DateTimeField(blank=True, null=True, verbose_name='Snapshot figé le')),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='ao.appeloffre', verbose_name="Appel d'offres")),
                ('batiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='ao.batimentao', verbose_name='Bâtiment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('fiche_technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_ao', to='records.attachment', verbose_name='Fiche technique')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipements_ao', to='stock.produit', verbose_name='Produit du catalogue')),
                ('remplace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remplace_par', to='ao.equipementao', verbose_name='Remplace')),
            ],
            options={
                'verbose_name': 'Équipement engagé (AO)',
                'verbose_name_plural': 'Équipements engagés (AO)',
                'db_table': 'ao_equipement',
                'ordering': ['appel_offre', 'role', 'id'],
                'indexes': [models.Index(fields=['company', 'appel_offre', 'role'], name='ao_equipeme_company_44883e_idx'), models.Index(fields=['company', 'actif'], name='ao_equipeme_company_6e3bcb_idx')],
            },
        ),
    ]
