# Generated by Django 5.1.4 on 2026-08-01 15:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0009_equipements'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        ('stock', '0083_ntprt25_fournisseur_statut_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereauprix',
            name='clause_reserve',
            field=models.TextField(blank=True, default='', verbose_name='Clause de réserve (obligatoire en prix unitaires)'),
        ),
        migrations.AddField(
            model_name='bordereauprix',
            name='indice_revision',
            field=models.CharField(blank=True, default='A', max_length=4, verbose_name='Indice de révision'),
        ),
        migrations.AddField(
            model_name='bordereauprix',
            name='marche_prix_unitaires',
            field=models.BooleanField(default=True, verbose_name='Marché à prix unitaires'),
        ),
        migrations.AddField(
            model_name='bordereauprix',
            name='remise_globale_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise globale (%)'),
        ),
        migrations.AddField(
            model_name='bordereauprix',
            name='taux_tva_defaut',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Taux de TVA par défaut (%)'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='batiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bordereau', to='ao.batimentao', verbose_name='Bâtiment'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bordereau_ao', to='stock.produit', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='quantite_source',
            field=models.CharField(choices=[('calepinage', 'Calepinage (variante)'), ('manuelle', 'Saisie manuelle'), ('catalogue', 'Catalogue'), ('acheteur', "Imposée par l'acheteur")], default='manuelle', max_length=12, verbose_name='Origine de la quantité'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='quantite_verrouillee',
            field=models.BooleanField(default=False, verbose_name='Quantité verrouillée'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='remise_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Remise de ligne (%)'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='taux_tva',
            field=models.DecimalField(blank=True, choices=[('10.00', '10 %'), ('20.00', '20 %')], decimal_places=2, max_digits=5, null=True, verbose_name='Taux de TVA (%) — vide = taux du bordereau'),
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_bordereau', to='ao.variantecalepinage', verbose_name='Variante source'),
        ),
        migrations.CreateModel(
            name='SectionBordereau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=8, verbose_name='Numéro (A, B, C…)')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('batiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections_bordereau', to='ao.batimentao', verbose_name='Bâtiment')),
                ('bordereau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='ao.bordereauprix', verbose_name='Bordereau')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Section de bordereau (AO)',
                'verbose_name_plural': 'Sections de bordereau (AO)',
                'db_table': 'ao_section_bordereau',
                'ordering': ['bordereau', 'ordre', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='lignebordereau',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='ao.sectionbordereau', verbose_name='Section'),
        ),
        migrations.AddConstraint(
            model_name='sectionbordereau',
            constraint=models.UniqueConstraint(fields=('bordereau', 'numero'), name='uniq_section_bordereau_numero'),
        ),
    ]
