# Generated by Django 5.1.4 on 2026-08-01 15:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0010_bordereau_v2'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignebordereau',
            name='est_stockage',
            field=models.BooleanField(default=False, verbose_name='Ligne de stockage (batteries)'),
        ),
        migrations.CreateModel(
            name='SimulationRentabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duree_annees', models.PositiveSmallIntegerField(default=25, verbose_name='Durée de la simulation (ans)')),
                ('productible_kwh_par_kwc_an', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Productible spécifique (kWh/kWc/an)')),
                ('productible_source', models.CharField(blank=True, default='', max_length=200, verbose_name='Source du productible')),
                ('tarif_kwh', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8, verbose_name='Tarif du kWh évité (MAD)')),
                ('inflation_tarif_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Inflation annuelle du tarif (%)')),
                ('degradation_annuelle_pct', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5, verbose_name='Dégradation annuelle des modules (%)')),
                ('taux_actualisation_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name="Taux d'actualisation (%)")),
                ('part_autoconsommee_pct', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Part autoconsommée (%)')),
                ('source_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte des entrées')),
                ('appel_offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_rentabilite', to='ao.appeloffre', verbose_name="Appel d'offres")),
                ('bordereau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulations', to='ao.bordereauprix', verbose_name='Bordereau source du CAPEX')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Simulation de rentabilité (AO)',
                'verbose_name_plural': 'Simulations de rentabilité (AO)',
                'db_table': 'ao_simulation_rentabilite',
                'ordering': ['appel_offre'],
            },
        ),
    ]
