# Generated by Django 5.1.4 on 2026-08-01 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0011_simulation'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneChecklistPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloc', models.CharField(choices=[('cps', 'CPS'), ('acte_engagement', "Acte d'engagement"), ('bordereau', 'Bordereau des prix'), ('lettre_soumission', 'Lettre de soumission'), ('memoire', 'Mémoire technique'), ('administratif', 'Dossier administratif'), ('verifications', 'Vérifications avant dépôt')], max_length=20, verbose_name='Bloc')),
                ('code', models.CharField(max_length=40, verbose_name='Code du point')),
                ('libelle', models.CharField(max_length=255, verbose_name='Point à traiter')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('faite', models.BooleanField(default=False, verbose_name='Fait')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('date_faite', models.DateTimeField(blank=True, null=True, verbose_name='Fait le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_checklist', to='ao.dossierao', verbose_name='Dossier')),
                ('responsable_utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_checklist_ao', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Point de checklist partenaire (AO)',
                'verbose_name_plural': 'Points de checklist partenaire (AO)',
                'db_table': 'ao_ligne_checklist',
                'ordering': ['dossier', 'ordre', 'code'],
                'indexes': [models.Index(fields=['company', 'dossier', 'bloc'], name='ao_ligne_ch_company_226977_idx')],
                'constraints': [models.UniqueConstraint(fields=('dossier', 'code'), name='uniq_ligne_checklist_code')],
            },
        ),
    ]
