# Generated by Django 5.1.4 on 2026-08-01 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0012_checklist'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        ('ged', '0043_zged15_backfill_document_reference'),
        ('records', '0013_vx210_snooze_trigger_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceAdministrative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_piece', models.CharField(choices=[('declaration_honneur', "Déclaration sur l'honneur"), ('pouvoirs', 'Pouvoirs du signataire'), ('attestation_fiscale', 'Attestation fiscale'), ('attestation_cnss', 'Attestation CNSS'), ('registre_commerce', 'Registre de commerce (modèle J)'), ('rib', 'RIB'), ('assurance_rc', 'Assurance responsabilité civile'), ('assurance_decennale', 'Assurance décennale étanchéité'), ('caution_provisoire', 'Caution provisoire'), ('autre', 'Autre pièce administrative')], max_length=24, verbose_name='Type de pièce')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('emetteur', models.CharField(blank=True, default='', max_length=200, verbose_name='Émetteur')),
                ('societe_emettrice', models.CharField(blank=True, default='', max_length=255, verbose_name='Société titulaire de la pièce')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('duree_validite_jours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée de validité (jours)')),
                ('rappel_jours', models.PositiveIntegerField(default=30, verbose_name='Rappel avant expiration (jours)')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_administratives_ao', to='records.attachment', verbose_name='Fichier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('dossiers', models.ManyToManyField(blank=True, related_name='pieces_administratives', to='ao.dossierao', verbose_name='Dossiers rattachés')),
                ('ged_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_administratives_ao', to='ged.document', verbose_name='Document GED')),
            ],
            options={
                'verbose_name': 'Pièce administrative (AO)',
                'verbose_name_plural': 'Pièces administratives (AO)',
                'db_table': 'ao_piece_administrative',
                'ordering': ['type_piece', '-date_emission', 'id'],
                'indexes': [models.Index(fields=['company', 'type_piece'], name='ao_piece_ad_company_67c055_idx'), models.Index(fields=['company', 'actif'], name='ao_piece_ad_company_45aabb_idx')],
            },
        ),
    ]
