# Generated by Django 5.1.4 on 2026-08-01 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0013_administratif'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        ('records', '0013_vx210_snooze_trigger_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationPlanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_document', models.CharField(max_length=20, verbose_name='Code de la planche citée')),
                ('indice_cite', models.CharField(blank=True, default='', max_length=4, verbose_name='Indice cité')),
                ('emplacement', models.CharField(blank=True, default='', max_length=255, verbose_name='Emplacement de la citation')),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations_planches', to='ao.appeloffre', verbose_name="Appel d'offres")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citations_planches', to='ao.sectionmemoire', verbose_name='Section du mémoire')),
            ],
            options={
                'verbose_name': 'Citation de planche (AO)',
                'verbose_name_plural': 'Citations de planche (AO)',
                'db_table': 'ao_citation_planche',
                'ordering': ['appel_offre', 'code_document', 'indice_cite'],
                'indexes': [models.Index(fields=['company', 'appel_offre', 'code_document'], name='ao_citation_company_9cfd42_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlancheAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_document', models.CharField(max_length=20, verbose_name='Code document')),
                ('indice', models.CharField(default='A', max_length=4, verbose_name='Indice')),
                ('empreinte', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte de la source')),
                ('motif_revision', models.TextField(blank=True, default='', verbose_name='Motif de révision')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée')], default='active', max_length=10, verbose_name='Statut')),
                ('cartouche', models.JSONField(blank=True, default=dict, verbose_name='Données du cartouche')),
                ('bandeau_engagement', models.JSONField(blank=True, default=dict, verbose_name="Bandeau d'engagement")),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planches', to='ao.appeloffre', verbose_name="Appel d'offres")),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planches_ao', to='records.attachment', verbose_name='Planche rendue (MinIO)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('toiture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planches', to='ao.toitureao', verbose_name='Toiture')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planches', to='ao.variantecalepinage', verbose_name='Variante représentée')),
            ],
            options={
                'verbose_name': 'Planche (AO)',
                'verbose_name_plural': 'Planches (AO)',
                'db_table': 'ao_planche',
                'ordering': ['appel_offre', 'code_document', 'indice'],
                'indexes': [models.Index(fields=['company', 'appel_offre', 'statut'], name='ao_planche_company_82e5d0_idx')],
                'constraints': [models.UniqueConstraint(fields=('appel_offre', 'code_document', 'indice'), name='uniq_planche_code_indice'), models.UniqueConstraint(condition=models.Q(('statut', 'active')), fields=('appel_offre', 'code_document'), name='uniq_planche_active_par_code')],
            },
        ),
    ]
