# Generated by Django 5.1.4 on 2026-08-01 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0014_planches'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        ('records', '0013_vx210_snooze_trigger_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeloffre',
            name='marque_blanche',
            field=models.BooleanField(default=False, verbose_name='Marque blanche active'),
        ),
        migrations.CreateModel(
            name='IdentiteAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('soumissionnaire', 'Soumissionnaire (déposant)'), ('bureau_execution', "Bureau d'exécution")], max_length=20, verbose_name='Rôle')),
                ('raison_sociale', models.CharField(max_length=255, verbose_name='Raison sociale')),
                ('ice', models.CharField(blank=True, default='', max_length=40, verbose_name='ICE')),
                ('identifiant_fiscal', models.CharField(blank=True, default='', max_length=40, verbose_name='Identifiant fiscal')),
                ('registre_commerce', models.CharField(blank=True, default='', max_length=40, verbose_name='Registre de commerce')),
                ('adresse', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('signataire_nom', models.CharField(blank=True, default='', max_length=200, verbose_name='Signataire')),
                ('signataire_qualite', models.CharField(blank=True, default='', max_length=200, verbose_name='Qualité du signataire')),
                ('rib', models.CharField(blank=True, default='', max_length=60, verbose_name='RIB')),
                ('mentions_legales', models.TextField(blank=True, default='', verbose_name='Mentions légales')),
                ('appel_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identites', to='ao.appeloffre', verbose_name="Appel d'offres")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identites_ao', to='records.attachment', verbose_name='Logo')),
            ],
            options={
                'verbose_name': "Identité d'appel d'offres (AO)",
                'verbose_name_plural': "Identités d'appel d'offres (AO)",
                'db_table': 'ao_identite',
                'ordering': ['appel_offre', 'role'],
                'constraints': [models.UniqueConstraint(fields=('appel_offre', 'role'), name='uniq_identite_ao_role')],
            },
        ),
    ]
