# Generated by Django 5.1.4 on 2026-08-01 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0015_marque_blanche'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecedossierao',
            name='empreinte_source',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte du contexte à la production'),
        ),
        migrations.CreateModel(
            name='ControleCoherence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_regle', models.CharField(max_length=60, verbose_name='Code de règle')),
                ('severite', models.CharField(choices=[('bloquant', 'Bloquant'), ('avertissement', 'Avertissement'), ('info', 'Information')], default='bloquant', max_length=14, verbose_name='Sévérité')),
                ('message', models.TextField(verbose_name='Message (français)')),
                ('objet', models.CharField(blank=True, default='', max_length=255, verbose_name='Objet visé')),
                ('empreinte', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte du contexte contrôlé')),
                ('date_controle', models.DateTimeField(auto_now_add=True, verbose_name='Contrôlé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='ao.dossierao', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Contrôle de cohérence (AO)',
                'verbose_name_plural': 'Contrôles de cohérence (AO)',
                'db_table': 'ao_controle_coherence',
                'ordering': ['dossier', 'severite', 'code_regle', 'id'],
                'indexes': [models.Index(fields=['company', 'dossier', 'severite'], name='ao_controle_company_ba19ec_idx')],
            },
        ),
    ]
