# Generated by Django 5.1.4 on 2026-08-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0016_coherence'),
    ]

    operations = [
        migrations.AddField(
            model_name='piecedossierao',
            name='controlee',
            field=models.CharField(choices=[('fabriquee', 'Fabriquée (contrôlée)'), ('hors_controle', 'Fournie — HORS CONTRÔLE')], default='fabriquee', max_length=14, verbose_name='Régime de contrôle'),
        ),
    ]
