# Generated by Django 5.1.4 on 2026-08-01 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0017_hors_controle'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        ('records', '0013_vx210_snooze_trigger_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtefactAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='Code de la pièce')),
                ('indice', models.CharField(default='A', max_length=4, verbose_name='Indice')),
                ('empreinte', models.CharField(max_length=64, verbose_name='Empreinte du contexte produit')),
                ('cle', models.CharField(max_length=500, verbose_name='Clé objet (MinIO)')),
                ('taille', models.PositiveBigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('mime', models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artefacts_ao', to='records.attachment', verbose_name='Pièce jointe')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artefacts', to='ao.dossierao', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Artefact archivé (AO)',
                'verbose_name_plural': 'Artefacts archivés (AO)',
                'db_table': 'ao_artefact',
                'ordering': ['dossier', 'code', 'indice'],
            },
        ),
        migrations.CreateModel(
            name='ManifestePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empreinte', models.CharField(max_length=64, verbose_name='Empreinte du contexte')),
                ('courant', models.BooleanField(default=True, verbose_name='Manifeste courant')),
                ('artefacts', models.ManyToManyField(blank=True, related_name='manifestes', to='ao.artefactao', verbose_name='Artefacts du pack')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifestes', to='ao.dossierao', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Manifeste de pack (AO)',
                'verbose_name_plural': 'Manifestes de pack (AO)',
                'db_table': 'ao_manifeste_pack',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='artefactao',
            index=models.Index(fields=['company', 'dossier', 'empreinte'], name='ao_artefact_company_1a9c82_idx'),
        ),
        migrations.AddConstraint(
            model_name='artefactao',
            constraint=models.UniqueConstraint(fields=('company', 'cle'), name='uniq_artefact_ao_cle'),
        ),
        migrations.AddConstraint(
            model_name='artefactao',
            constraint=models.UniqueConstraint(fields=('dossier', 'code', 'indice'), name='uniq_artefact_ao_code_indice'),
        ),
        migrations.AddConstraint(
            model_name='manifestepack',
            constraint=models.UniqueConstraint(condition=models.Q(('courant', True)), fields=('dossier',), name='uniq_manifeste_courant_par_dossier'),
        ),
    ]
