# Generated by Django 5.1.4 on 2026-08-01 16:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0018_stockage'),
        ('authentication', '0026_ntmob6_customuser_mobile_home_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomieAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taux_tva_vente', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Taux de TVA de vente (%)')),
                ('taux_tva_achat_reduit', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='TVA sur achats — régime réduit panneaux (%)')),
                ('taux_tva_achat_standard', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='TVA sur achats — régime standard (%)')),
                ('verrouillee', models.BooleanField(default=False, verbose_name='Économie verrouillée')),
                ('note_comptable', models.TextField(blank=True, default='', verbose_name='Point ouvert signalé au comptable')),
                ('appel_offre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economie', to='ao.appeloffre', verbose_name="Appel d'offres")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Économie d'appel d'offres (directeur)",
                'verbose_name_plural': "Économies d'appel d'offres (directeur)",
                'db_table': 'ao_economie',
                'ordering': ['appel_offre'],
            },
        ),
        migrations.CreateModel(
            name='LigneCoutRevient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.CharField(choices=[('panneaux', 'Panneaux'), ('structure', 'Structure'), ('onduleurs', 'Onduleurs et équipements'), ('garantie_onduleurs', 'Extension de garantie onduleurs'), ('cable_solaire', 'Câble solaire'), ('cable_ac', 'Câble AC'), ('main_oeuvre', "Main d'œuvre"), ('aleas', 'Aléas'), ('autre', 'Autre poste')], default='autre', max_length=20, verbose_name='Poste')),
                ('designation', models.CharField(max_length=255, verbose_name='Désignation')),
                ('quantite', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, default='U', max_length=20, verbose_name='Unité')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14, verbose_name='Coût unitaire HT (MAD)')),
                ('regime_tva', models.CharField(choices=[('reduit', 'Réduit (panneaux, 10 %)'), ('standard', 'Standard (20 %)')], default='standard', max_length=10, verbose_name='Régime de TVA sur achat')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('economie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ao.economieao', verbose_name='Économie')),
            ],
            options={
                'verbose_name': 'Ligne de coût de revient (directeur)',
                'verbose_name_plural': 'Lignes de coût de revient (directeur)',
                'db_table': 'ao_ligne_cout_revient',
                'ordering': ['economie', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CibleFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('benefice_net_cible_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Bénéfice net visé HT (MAD)')),
                ('arrondi_psychologique', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name="Pas d'arrondi des prix unitaires (MAD)")),
                ('seuil_psychologique', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='Seuil psychologique TTC (MAD)')),
                ('active', models.BooleanField(default=True, verbose_name='Version active')),
                ('motif', models.TextField(blank=True, default='', verbose_name='Motif de la version')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cibles_financieres_ao', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ligne_ajustement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cibles_financieres', to='ao.lignebordereau', verbose_name="Ligne d'ajustement du résidu")),
                ('economie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cibles', to='ao.economieao', verbose_name='Économie')),
            ],
            options={
                'verbose_name': 'Cible financière (directeur)',
                'verbose_name_plural': 'Cibles financières (directeur)',
                'db_table': 'ao_cible_financiere',
                'ordering': ['economie', '-version'],
                'constraints': [models.UniqueConstraint(fields=('economie', 'version'), name='uniq_cible_financiere_version'), models.UniqueConstraint(condition=models.Q(('active', True)), fields=('economie',), name='uniq_cible_financiere_active')],
            },
        ),
    ]
