# Generated by Django 5.1.4 on 2026-08-01 18:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ao', '0019_economie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignecoutrevient',
            name='prix_unitaire_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Coût unitaire HT (MAD)'),
        ),
    ]
