# Generated by Django 5.1.4 on 2026-06-22 09:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("gestion_projet", "0004_phaseprojet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_wbs",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Code WBS"
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminée"),
                            ("bloque", "Bloquée"),
                        ],
                        default="a_faire",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "avancement_pct",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name="Avancement (%)",
                    ),
                ),
                (
                    "charge_estimee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Charge estimée (j-h)",
                    ),
                ),
                (
                    "date_debut_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début prévue"
                    ),
                ),
                (
                    "date_fin_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin prévue"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet_taches",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sous_taches",
                        to="gestion_projet.tache",
                        verbose_name="Tâche parente",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taches",
                        to="gestion_projet.phaseprojet",
                        verbose_name="Phase",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taches",
                        to="gestion_projet.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tâche de projet",
                "verbose_name_plural": "Tâches de projet",
                "ordering": ["projet", "ordre", "id"],
                "indexes": [
                    models.Index(
                        fields=["projet", "parent"], name="gp_tache_proj_parent_idx"
                    )
                ],
            },
        ),
    ]
