# Generated by Django 5.1.4 on 2026-06-22 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("gestion_projet", "0005_tache"),
    ]

    operations = [
        migrations.CreateModel(
            name="DependanceTache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_dependance",
                    models.CharField(
                        choices=[
                            ("fs", "Fin → Début (FS)"),
                            ("ss", "Début → Début (SS)"),
                            ("ff", "Fin → Fin (FF)"),
                            ("sf", "Début → Fin (SF)"),
                        ],
                        default="fs",
                        max_length=2,
                        verbose_name="Type de dépendance",
                    ),
                ),
                (
                    "lag",
                    models.IntegerField(default=0, verbose_name="Décalage (jours)"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet_dependances",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "predecesseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependances_sortantes",
                        to="gestion_projet.tache",
                        verbose_name="Tâche prédécesseur",
                    ),
                ),
                (
                    "successeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependances_entrantes",
                        to="gestion_projet.tache",
                        verbose_name="Tâche successeur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dépendance de tâche",
                "verbose_name_plural": "Dépendances de tâches",
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["successeur"], name="gp_dep_successeur_idx"),
                    models.Index(
                        fields=["predecesseur"], name="gp_dep_predecesseur_idx"
                    ),
                ],
                "unique_together": {("predecesseur", "successeur")},
            },
        ),
    ]
