# Generated by Django 5.1.4 on 2026-06-22 10:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("gestion_projet", "0006_dependancetache"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jalon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                ("date_prevue", models.DateField(verbose_name="Date prévue")),
                (
                    "date_reelle",
                    models.DateField(blank=True, null=True, verbose_name="Date réelle"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_venir", "À venir"),
                            ("atteint", "Atteint"),
                            ("manque", "Manqué"),
                        ],
                        default="a_venir",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "facturation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Facturation (%)",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet_jalons",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jalons",
                        to="gestion_projet.phaseprojet",
                        verbose_name="Phase",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jalons",
                        to="gestion_projet.projet",
                        verbose_name="Projet",
                    ),
                ),
                (
                    "tache",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jalons",
                        to="gestion_projet.tache",
                        verbose_name="Tâche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jalon de projet",
                "verbose_name_plural": "Jalons de projet",
                "ordering": ["projet", "date_prevue", "id"],
                "indexes": [
                    models.Index(
                        fields=["projet", "date_prevue"], name="gp_jalon_proj_date_idx"
                    )
                ],
            },
        ),
    ]
