# Generated by Django 5.1.4 on 2026-06-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("gestion_projet", "0007_jalon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendrierProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lundi",
                    models.BooleanField(default=True, verbose_name="Lundi ouvré"),
                ),
                (
                    "mardi",
                    models.BooleanField(default=True, verbose_name="Mardi ouvré"),
                ),
                (
                    "mercredi",
                    models.BooleanField(default=True, verbose_name="Mercredi ouvré"),
                ),
                (
                    "jeudi",
                    models.BooleanField(default=True, verbose_name="Jeudi ouvré"),
                ),
                (
                    "vendredi",
                    models.BooleanField(default=True, verbose_name="Vendredi ouvré"),
                ),
                (
                    "samedi",
                    models.BooleanField(default=False, verbose_name="Samedi ouvré"),
                ),
                (
                    "dimanche",
                    models.BooleanField(default=False, verbose_name="Dimanche ouvré"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet_calendriers",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "projet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendrier",
                        to="gestion_projet.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Calendrier de projet",
                "verbose_name_plural": "Calendriers de projet",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="JourFerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Libellé"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "calendrier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jours_feries",
                        to="gestion_projet.calendrierprojet",
                        verbose_name="Calendrier",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet_jours_feries",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jour férié",
                "verbose_name_plural": "Jours fériés",
                "ordering": ["date", "id"],
                "indexes": [
                    models.Index(
                        fields=["calendrier", "date"], name="gp_ferie_cal_date_idx"
                    )
                ],
                "unique_together": {("calendrier", "date")},
            },
        ),
    ]
