# Generated by Django 5.1.4 on 2026-06-22 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("gestion_projet", "0008_calendrierprojet_jourferie"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaselinePlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Libellé"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projet_baselines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet_baselines",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="gestion_projet.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baseline de planning",
                "verbose_name_plural": "Baselines de planning",
                "ordering": ["-date_creation", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BaselineTache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tache_libelle",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Libellé figé",
                    ),
                ),
                (
                    "tache_code_wbs",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Code WBS figé",
                    ),
                ),
                (
                    "date_debut_prevue",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de début prévue (figée)",
                    ),
                ),
                (
                    "date_fin_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de fin prévue (figée)"
                    ),
                ),
                (
                    "charge_estimee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Charge estimée (figée)",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "baseline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="gestion_projet.baselineplanning",
                        verbose_name="Baseline",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projet_baseline_taches",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "tache",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="baseline_lignes",
                        to="gestion_projet.tache",
                        verbose_name="Tâche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de baseline",
                "verbose_name_plural": "Lignes de baseline",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="baselineplanning",
            index=models.Index(
                fields=["projet", "-date_creation"], name="gp_baseline_proj_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baselinetache",
            index=models.Index(fields=["baseline"], name="gp_baseline_tache_idx"),
        ),
    ]
