# Generated by Django 5.1.4 on 2026-07-10 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0041_zprj12_projet_alias_email'),
        ('stock', '0074_revisionkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='soustraitant',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text='Lien optionnel vers le référentiel sous-traitant unifié DC34 (stock.Fournisseur type=service). Posé automatiquement pour tout nouveau sous-traitant créé via le master, ou par le backfill pour les lignes existantes correspondantes.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_projet_sous_traitants_lies', to='stock.fournisseur', verbose_name='Fournisseur (master DC34)'),
        ),
    ]
