# Generated by Django 5.1.4 on 2026-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_seed_activity_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="phase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("avant", "Avant"),
                    ("pendant", "Pendant"),
                    ("apres", "Après"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
