# Generated by Django 5.1.4 on 2026-06-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_seed_activity_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="phase",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
    ]
