# Generated by Django 5.1.4 on 2026-06-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("records", "0005_tag_taggeditem"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tag",
            name="records_tag_company_nom_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="taggeditem",
            name="records_taggeditem_tag_ct_obj_uniq",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="records_com_content_901fe2_idx",
            old_name="records_com_content_2bc5f0_idx",
        ),
        migrations.RenameIndex(
            model_name="comment",
            new_name="records_com_company_33b99b_idx",
            old_name="records_com_company_b0a921_idx",
        ),
        migrations.RenameIndex(
            model_name="tag",
            new_name="records_tag_company_5694bc_idx",
            old_name="records_tag_company_b0a4c2_idx",
        ),
        migrations.RenameIndex(
            model_name="taggeditem",
            new_name="records_tag_content_59c00e_idx",
            old_name="records_tag_content_6d7bd1_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("company", "nom")},
        ),
        migrations.AlterUniqueTogether(
            name="taggeditem",
            unique_together={("tag", "content_type", "object_id")},
        ),
    ]
