# Generated by Django 5.1.4 on 2026-07-09 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='field_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='kind',
            field=models.CharField(blank=True, choices=[('creation', 'Création'), ('modification', 'Modification'), ('note', 'Note')], default='', max_length=15, verbose_name='Type de chatter'),
        ),
        migrations.AddField(
            model_name='activity',
            name='new_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='old_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='records.activitytype'),
        ),
    ]
