# Generated by Django 5.1.4 on 2026-07-16 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('installations', '0096_odx19_repoint_achats_crossapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(blank=True, default='', max_length=100, verbose_name='Lot (gros-œuvre, électricité, plomberie…)')),
                ('localisation_plan', models.JSONField(blank=True, default=dict, verbose_name='Localisation sur le plan')),
                ('description', models.TextField(verbose_name='Description')),
                ('gravite', models.CharField(choices=[('mineure', 'Mineure'), ('majeure', 'Majeure'), ('bloquante', 'Bloquante')], default='mineure', max_length=10, verbose_name='Gravité')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('en_cours', 'En cours'), ('levee', 'Levée'), ('contestee', 'Contestée')], default='ouverte', max_length=10, verbose_name='Statut')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('date_levee', models.DateTimeField(blank=True, null=True, verbose_name='Levée le')),
                ('motif_contestation', models.TextField(blank=True, default='', verbose_name='Motif de contestation')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_reserves', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_reserves_chantier', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_reserves_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('leve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_reserves_levees', to=settings.AUTH_USER_MODEL, verbose_name='Levée par')),
                ('responsable_leve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_reserves_a_lever', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la levée')),
            ],
            options={
                'verbose_name': 'Réserve de chantier',
                'verbose_name_plural': 'Réserves de chantier',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReserveChantierHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, default='', max_length=10)),
                ('nouveau_statut', models.CharField(max_length=10)),
                ('motif', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_reserve_transitions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_reserve_historiques', to='authentication.company', verbose_name='Société')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='btp_chantier.reservechantier', verbose_name='Réserve')),
            ],
            options={
                'verbose_name': 'Historique de réserve',
                'verbose_name_plural': 'Historiques de réserve',
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SignatureBtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('contexte', models.CharField(blank=True, default='', max_length=40, verbose_name='Contexte (levee_reserve, approbation_avenant…)')),
                ('signataire_nom', models.CharField(max_length=255, verbose_name='Nom du signataire')),
                ('methode', models.CharField(choices=[('typed', 'Nom dactylographié'), ('draw', 'Signature dessinée')], default='typed', max_length=20)),
                ('date_signature', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_signatures', to='authentication.company', verbose_name='Société')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('signataire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_signatures', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur signataire')),
            ],
            options={
                'verbose_name': 'Signature BTP',
                'verbose_name_plural': 'Signatures BTP',
                'ordering': ['-date_signature', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='reservechantier',
            index=models.Index(fields=['company', 'chantier', 'statut'], name='btp_chantie_company_6189b7_idx'),
        ),
        migrations.AddIndex(
            model_name='reservechantier',
            index=models.Index(fields=['company', 'lot'], name='btp_chantie_company_b6f794_idx'),
        ),
    ]
