# Generated by Django 5.1.4 on 2026-07-16 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('btp_chantier', '0001_initial'),
        ('installations', '0096_odx19_repoint_achats_crossapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='N° de RFI')),
                ('question', models.TextField(verbose_name='Question')),
                ('destinataire_texte', models.CharField(blank=True, default='', max_length=255, verbose_name='Destinataire (texte libre — MOE/BE)')),
                ('delai_jours', models.PositiveIntegerField(default=5, verbose_name='Délai de réponse (jours ouvrés)')),
                ('date_limite_reponse', models.DateField(blank=True, null=True, verbose_name='Date limite de réponse')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('repondu', 'Répondu'), ('clos', 'Clos')], default='ouvert', max_length=10, verbose_name='Statut')),
                ('impact_cout', models.BooleanField(default=False, verbose_name='Impact coût')),
                ('impact_delai_jours', models.IntegerField(blank=True, null=True, verbose_name='Impact délai (jours)')),
                ('derniere_alerte_retard', models.DateField(blank=True, null=True, verbose_name='Dernière alerte de retard')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_rfis', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_rfis', to='authentication.company', verbose_name='Société')),
                ('destinataire_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_rfis_destinataire', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire (utilisateur)')),
                ('pose_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_rfis_poses', to=settings.AUTH_USER_MODEL, verbose_name='Posé par')),
            ],
            options={
                'verbose_name': 'RFI',
                'verbose_name_plural': 'RFI',
                'ordering': ['date_limite_reponse', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RFIReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Réponse')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_rfi_reponses', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_rfi_reponses', to='authentication.company', verbose_name='Société')),
                ('rfi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='btp_chantier.rfi', verbose_name='RFI')),
            ],
            options={
                'verbose_name': 'Réponse RFI',
                'verbose_name_plural': 'Réponses RFI',
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='rfi',
            index=models.Index(fields=['company', 'chantier', 'statut'], name='btp_chantie_company_4a83bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='rfi',
            constraint=models.UniqueConstraint(fields=('chantier', 'numero'), name='btp_rfi_chantier_numero_uniq'),
        ),
    ]
