# Generated by Django 5.1.4 on 2026-07-16 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('btp_chantier', '0002_rfi_rfireponse_rfi_btp_chantie_company_4a83bc_idx_and_more'),
        ('installations', '0096_odx19_repoint_achats_crossapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_ged_id', models.PositiveIntegerField(verbose_name='ID du document GED')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('type_visa', models.CharField(choices=[('plan_execution', "Plan d'exécution"), ('note_calcul', 'Note de calcul'), ('fiche_technique', 'Fiche technique'), ('methode', 'Méthode'), ('autre', 'Autre')], default='autre', max_length=20, verbose_name='Type de visa')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('en_revue', 'En revue'), ('approuve_sans_reserve', 'Approuvé sans réserve'), ('approuve_avec_observations', 'Approuvé avec observations'), ('refuse', 'Refusé')], default='soumis', max_length=30, verbose_name='Statut')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission')),
                ('date_revue', models.DateTimeField(blank=True, null=True, verbose_name='Date de revue')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observations')),
                ('delai_revue_jours', models.PositiveIntegerField(default=10, verbose_name='Délai de revue (jours ouvrés)')),
                ('date_limite', models.DateField(blank=True, null=True, verbose_name='Date limite de revue')),
                ('nb_resoumissions', models.PositiveIntegerField(default=0, verbose_name='Nombre de resoumissions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_visas', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_visas', to='authentication.company', verbose_name='Société')),
                ('revu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_visas_revus', to=settings.AUTH_USER_MODEL, verbose_name='Revu par')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_visas_soumis', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
            ],
            options={
                'verbose_name': 'Visa de document',
                'verbose_name_plural': 'Visas de document',
                'ordering': ['date_limite', '-id'],
                'indexes': [models.Index(fields=['company', 'chantier', 'statut'], name='btp_chantie_company_646fd3_idx'), models.Index(fields=['company', 'document_ged_id'], name='btp_chantie_company_00c74b_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'reference'), name='btp_visa_company_reference_uniq')],
            },
        ),
    ]
