# Generated by Django 5.1.4 on 2026-07-16 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('btp_chantier', '0003_visadocument'),
        ('installations', '0096_odx19_repoint_achats_crossapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('meteo', models.CharField(blank=True, choices=[('ensoleille', 'Ensoleillé'), ('nuageux', 'Nuageux'), ('pluvieux', 'Pluvieux'), ('venteux', 'Venteux'), ('autre', 'Autre')], default='', max_length=15, verbose_name='Météo')),
                ('effectif_interne', models.JSONField(blank=True, default=dict, verbose_name='Effectif interne')),
                ('effectif_sous_traitant', models.JSONField(blank=True, default=dict, verbose_name='Effectif sous-traitant')),
                ('materiel_present', models.TextField(blank=True, default='', verbose_name='Matériel présent')),
                ('evenements', models.TextField(blank=True, default='', verbose_name='Événements')),
                ('visiteurs', models.JSONField(blank=True, default=list, verbose_name='Visiteurs')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_journaux', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_journaux_chantier', to='authentication.company', verbose_name='Société')),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_journaux_rediges', to=settings.AUTH_USER_MODEL, verbose_name='Rédacteur')),
            ],
            options={
                'verbose_name': 'Journal de chantier',
                'verbose_name_plural': 'Journaux de chantier',
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['company', 'chantier', 'date'], name='btp_chantie_company_0c6a2e_idx')],
                'constraints': [models.UniqueConstraint(fields=('chantier', 'date'), name='btp_journal_chantier_date_uniq')],
            },
        ),
    ]
