# Generated by Django 5.1.4 on 2026-07-17 18:05

import apps.btp_chantier.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('btp_chantier', '0005_journalchantier_updated_at_and_more'),
        ('installations', '0096_odx19_repoint_achats_crossapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvenantChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avenant_contrat_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'avenant contractuel (contrats.Avenant)")),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('description', models.TextField(verbose_name='Description')),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant HT')),
                ('impact_delai_jours', models.IntegerField(blank=True, null=True, verbose_name='Impact délai (jours)')),
                ('impact_budget', models.BooleanField(default=False, verbose_name='Impact budget projet (sinon facture acompte)')),
                ('lignes', models.JSONField(blank=True, default=list, verbose_name='Lignes')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis_client', 'Soumis au client'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='brouillon', max_length=15, verbose_name='Statut')),
                ('token', models.CharField(default=apps.btp_chantier.models._default_btp_token, editable=False, max_length=64, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Lien expire le')),
                ('budget_projet_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du budget projet impacté (gestion_projet.BudgetProjet)')),
                ('facture_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de la facture d'acompte générée (ventes.Facture)")),
                ('motif_refus', models.TextField(blank=True, default='', verbose_name='Motif de refus')),
                ('date_approbation', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_avenants_approuves', to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_avenants', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_avenants_chantier', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_avenants_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Avenant de chantier',
                'verbose_name_plural': 'Avenants de chantier',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'chantier', 'statut'], name='btp_chantie_company_15000b_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'reference'), name='btp_avenant_company_reference_uniq')],
            },
        ),
        migrations.CreateModel(
            name='DecompteGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, verbose_name='Référence')),
                ('montant_marche_initial_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant marché initial HT')),
                ('situations_incluses', models.JSONField(blank=True, default=list, verbose_name='Situations incluses (IDs gestion_projet.SituationTravaux)')),
                ('total_avenants_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total avenants approuvés HT')),
                ('total_situations_facturees_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total situations facturées HT')),
                ('retenue_garantie_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la retenue de garantie (compta.RetenueGarantie)')),
                ('retenue_garantie_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant de retenue de garantie libérée (instantané)')),
                ('solde_du_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Solde dû HT')),
                ('statut', models.CharField(choices=[('projet', 'Projet'), ('notifie', 'Notifié'), ('accepte', 'Accepté'), ('conteste', 'Contesté'), ('definitif', 'Définitif')], default='projet', max_length=10, verbose_name='Statut')),
                ('motif_contestation', models.TextField(blank=True, default='', verbose_name='Motif de contestation')),
                ('montant_conteste', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant contesté')),
                ('date_notification', models.DateTimeField(blank=True, null=True, verbose_name='Notifié le')),
                ('date_finalisation', models.DateTimeField(blank=True, null=True, verbose_name='Finalisé le')),
                ('historique_deverrouillage', models.JSONField(blank=True, default=list, verbose_name='Historique de déverrouillage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_decomptes', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_decomptes_generaux', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_decomptes_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('finalise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_decomptes_finalises', to=settings.AUTH_USER_MODEL, verbose_name='Finalisé par')),
            ],
            options={
                'verbose_name': 'Décompte général et définitif',
                'verbose_name_plural': 'Décomptes généraux et définitifs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'chantier', 'statut'], name='btp_chantie_company_a7b4d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'reference'), name='btp_dgd_company_reference_uniq')],
            },
        ),
        migrations.CreateModel(
            name='DiffusionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_ged_id', models.PositiveIntegerField(verbose_name='ID du document GED')),
                ('version_diffusee', models.PositiveIntegerField(verbose_name='Version diffusée (ged.DocumentVersion.version)')),
                ('destinataires_externes', models.JSONField(blank=True, default=list, verbose_name='Destinataires externes (emails)')),
                ('token', models.CharField(default=apps.btp_chantier.models._default_btp_token, editable=False, max_length=64, unique=True)),
                ('partage_ged_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du partage GED externe (ged.PartageGed)')),
                ('date_diffusion', models.DateTimeField(blank=True, null=True, verbose_name='Diffusé le')),
                ('accuse_reception', models.JSONField(blank=True, default=dict, verbose_name='Accusé de réception')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_diffusions', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btp_diffusions_plan', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='btp_diffusions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('destinataires_internes', models.ManyToManyField(blank=True, related_name='btp_diffusions_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataires internes')),
            ],
            options={
                'verbose_name': 'Diffusion de plan',
                'verbose_name_plural': 'Diffusions de plan',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'chantier', 'document_ged_id'], name='btp_chantie_company_7769eb_idx')],
            },
        ),
    ]
