# Generated by Django 5.2.14 on 2026-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Mon Entreprise', max_length=255)),
                ('adresse', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('siret', models.CharField(blank=True, default='', max_length=20)),
                ('tva_intra', models.CharField(blank=True, default='', max_length=20)),
                ('rib', models.CharField(blank=True, default='', max_length=50)),
                ('banque', models.CharField(blank=True, default='', max_length=100)),
                ('couleur_principale', models.CharField(default='#2563EB', max_length=7)),
                ('logo_key', models.CharField(blank=True, default='', max_length=500)),
                ('signature_key', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Profil entreprise',
            },
        ),
    ]
