# Generated by Django 5.1.4 on 2026-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0002_companyprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='cnss',
            field=models.CharField(blank=True, default='', help_text="Numéro d'affiliation CNSS.", max_length=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='ice',
            field=models.CharField(blank=True, default='', help_text="Identifiant Commun de l'Entreprise (obligatoire sur facture).", max_length=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='identifiant_fiscal',
            field=models.CharField(blank=True, default='', help_text='IF — Identifiant Fiscal.', max_length=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='patente',
            field=models.CharField(blank=True, default='', help_text='Patente / Taxe Professionnelle.', max_length=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rc',
            field=models.CharField(blank=True, default='', help_text='RC — Registre de Commerce.', max_length=30),
        ),
    ]
