# Generated by Django 5.1.4 on 2026-06-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0005_init_default_responsable_meryem'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='agricole_pump_hours',
            field=models.DecimalField(decimal_places=1, default=7, max_digits=4),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='doc_prefixes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='payment_terms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='quote_validity_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tva_panneaux',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tva_standard',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
