# Generated by Django 5.1.4 on 2026-06-15 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_avatar_key_customuser_poste'),
        ('parametres', '0006_companyprofile_agricole_pump_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(choices=[('devis_unique', 'Devis (un seul)'), ('devis_multi_entete', 'Devis (plusieurs) — en-tête'), ('devis_multi_ligne', 'Devis (plusieurs) — ligne'), ('facture', 'Facture'), ('relance', 'Rappel de paiement')], max_length=40)),
                ('corps_fr', models.TextField(blank=True, default='')),
                ('corps_darija', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='authentication.company')),
            ],
            options={
                'ordering': ['cle'],
                'unique_together': {('company', 'cle')},
            },
        ),
    ]
