# Generated by Django 5.1.4 on 2026-06-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0007_messagetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="seuil_remise_approbation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Remise (%) au-delà de laquelle l'envoi d'un devis requiert une approbation. Vide ou 0 = désactivé.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
