# Generated by Django 5.1.4 on 2026-06-16 13:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0007_messagetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="onee_tarif_kwh",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("1.75"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="productible_kwh_kwc",
            field=models.DecimalField(
                decimal_places=1, default=Decimal("1600.0"), max_digits=7
            ),
        ),
    ]
