# Generated by Django 5.1.4 on 2026-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0008_companyprofile_onee_tarif_kwh_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="discount_approval_threshold",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
