# Generated by Django 5.1.4 on 2026-06-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0008_companyprofile_seuil_remise_approbation"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="roi_constants",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
