# Generated by Django 5.1.4 on 2026-06-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0009_companyprofile_roi_constants"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="chantier_checklist_defaut",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
