# Generated by Django 5.1.4 on 2026-06-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0016_companyprofile_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="conditions_generales",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="instructions_paiement",
            field=models.TextField(blank=True, default=""),
        ),
    ]
