# Generated by Django 5.1.4 on 2026-06-18 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("parametres", "0017_companyprofile_conditions_generales_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatutConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domaine",
                    models.CharField(
                        choices=[
                            ("chantier", "Chantier"),
                            ("sav", "SAV"),
                            ("bon_commande", "Bon de commande"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cle", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=120)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statut_configs",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de statut",
                "verbose_name_plural": "Configurations de statut",
                "ordering": ["domaine", "ordre", "id"],
                "unique_together": {("company", "domaine", "cle")},
            },
        ),
    ]
