# Generated by Django 5.1.4 on 2026-06-19 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("parametres", "0019_companyprofile_dgi_export_actif"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "validite_badge_p1",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "validite_onepage",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("cgv_titre", models.CharField(blank=True, default="", max_length=120)),
                ("cgv_bullets", models.JSONField(blank=True, null=True)),
                (
                    "garantie_titre",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("garantie_detail", models.TextField(blank=True, default="")),
                (
                    "garantie_perf_label",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("bpa_titre", models.CharField(blank=True, default="", max_length=120)),
                ("bpa_mention", models.TextField(blank=True, default="")),
                (
                    "acceptance_stamp",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_templates",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de documents",
                "verbose_name_plural": "Modèles de documents",
            },
        ),
    ]
