# Generated by Django 5.1.4 on 2026-06-19 03:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("parametres", "0020_documenttemplates"),
    ]

    operations = [
        migrations.CreateModel(
            name="TariffSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("residential_tiers", models.JSONField(blank=True, null=True)),
                ("tolerance_kwh", models.PositiveIntegerField(default=10)),
                ("selective_threshold_kwh", models.PositiveIntegerField(default=150)),
                (
                    "force_motrice_prix_kwh_ttc",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.9500"), max_digits=6
                    ),
                ),
                ("surplus_injecte_compense", models.BooleanField(default=False)),
                (
                    "surplus_prix_kwh_ttc",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.0000"), max_digits=6
                    ),
                ),
                (
                    "autoconsommation_pct_defaut",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("70.00"), max_digits=5
                    ),
                ),
                (
                    "pertes_systeme_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20.00"), max_digits=5
                    ),
                ),
                ("pvgis_actif", models.BooleanField(default=True)),
                (
                    "productible_manuel_kwh_kwc",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("1500.0"), max_digits=7
                    ),
                ),
                ("inclinaison_defaut_deg", models.PositiveIntegerField(default=30)),
                ("azimut_defaut_deg", models.IntegerField(default=0)),
                ("version", models.PositiveIntegerField(default=1)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariff_settings",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarification & ROI",
                "verbose_name_plural": "Tarifications & ROI",
            },
        ),
    ]
