# Generated by Django 5.1.4 on 2026-06-19 09:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0021_tariffsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="ocr_serie_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur OCR pour l'extraction des n° de série (F9). Vide = saisie manuelle uniquement.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="overage_seuil_pct",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10"),
                help_text="Pourcentage de dépassement de consommation déclenchant la revue (F12).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="photo_qa_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur de contrôle qualité IA des photos (F20). Vide = aucun contrôle.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="transcription_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Fournisseur de transcription des mémos vocaux (F14). Vide = mémos non transcrits.",
                max_length=40,
            ),
        ),
    ]
