# Generated by Django 5.1.4 on 2026-06-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parametres", "0022_companyprofile_ocr_serie_provider_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="lead_sla_hours",
            field=models.PositiveIntegerField(
                default=24,
                help_text="Délai maximum (en heures) avant première prise de contact sur un nouveau lead. 0 = SLA désactivé.",
            ),
        ),
    ]
