# Generated by Django 5.1.4 on 2026-06-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_avatar_key_customuser_poste'),
        ('parametres', '0023_companyprofile_lead_sla_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(choices=[('devis', 'Devis'), ('facture', 'Facture'), ('relance', 'Rappel de paiement'), ('notification', 'Notification')], max_length=40)),
                ('sujet', models.CharField(blank=True, default='', max_length=255)),
                ('corps', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='authentication.company')),
            ],
            options={
                'verbose_name': "Modèle d'e-mail",
                'verbose_name_plural': "Modèles d'e-mail",
                'ordering': ['cle'],
                'unique_together': {('company', 'cle')},
            },
        ),
    ]
