# Generated by Django 5.1.4 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0034_xfac12_escompte_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='cle',
            field=models.CharField(choices=[('devis', 'Devis'), ('facture', 'Facture'), ('relance', 'Rappel de paiement'), ('notification', 'Notification'), ('ticket_recu', 'Ticket SAV reçu'), ('ticket_planifie', 'Ticket SAV planifié'), ('ticket_resolu', 'Ticket SAV résolu'), ('pre_echeance', 'Rappel pré-échéance')], max_length=40),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='cle',
            field=models.CharField(choices=[('devis_unique', 'Devis (un seul)'), ('devis_multi_entete', 'Devis (plusieurs) — en-tête'), ('devis_multi_ligne', 'Devis (plusieurs) — ligne'), ('facture', 'Facture'), ('relance', 'Rappel de paiement'), ('ticket_recu', 'Ticket SAV reçu'), ('ticket_planifie', 'Ticket SAV planifié'), ('ticket_resolu', 'Ticket SAV résolu')], max_length=40),
        ),
    ]
