# Generated by Django 5.1.4 on 2026-07-09 23:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0053_xsal11_round_robin_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='arrondi_caisse',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Plus petit pas d'arrondi (MAD) appliqué au reste à payer d'une facture réglée en espèces (ex. 0,05 / 0,20 / 1,00). 0 = désactivé (comportement actuel).", max_digits=6, verbose_name='Arrondi de caisse (espèces)'),
        ),
    ]
