# Generated by Django 5.1.4 on 2026-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0054_companyprofile_arrondi_caisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='site_web',
            field=models.CharField(blank=True, default='', help_text='Site web de la société (ex. helios.ma), affiché sur le PDF du devis. Vide = défaut historique.', max_length=255),
        ),
    ]
