# Generated by Django 5.1.4 on 2026-07-10 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_company_benchmarking_opt_in'),
        ('parametres', '0055_companyprofile_site_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('libelle', models.CharField(max_length=120)),
                ('taux', models.DecimalField(decimal_places=2, max_digits=5)),
                ('defaut', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taux_tva_referentiel', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Taux de TVA',
                'verbose_name_plural': 'Taux de TVA',
                'ordering': ['-taux', 'code'],
                'indexes': [models.Index(fields=['company', 'actif'], name='param_tauxtva_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
