# Generated by Django 5.1.4 on 2026-07-10 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_company_benchmarking_opt_in'),
        ('parametres', '0056_tauxtva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Libellé FR (ex. « 30 jours fin de mois », « Comptant »).', max_length=120)),
                ('delai_jours', models.PositiveIntegerField(default=0)),
                ('fin_de_mois', models.BooleanField(default=False)),
                ('escompte_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions_paiement_referentiel', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Condition de paiement',
                'verbose_name_plural': 'Conditions de paiement',
                'ordering': ['delai_jours', 'libelle'],
                'indexes': [models.Index(fields=['company', 'actif'], name='param_condpaie_idx')],
                'unique_together': {('company', 'delai_jours', 'fin_de_mois', 'escompte_pct')},
            },
        ),
    ]
