# Generated by Django 5.1.4 on 2026-07-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_company_benchmarking_opt_in'),
        ('parametres', '0057_conditionpaiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteMesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=80)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites_mesure_referentiel', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Unité de mesure',
                'verbose_name_plural': 'Unités de mesure',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['company', 'actif'], name='param_unite_idx')],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
