# Generated by Django 5.1.4 on 2026-08-14 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0070_ntdmo20_companyprofile_essai_expire_le'),
        ('parametres', '0070_ntret8_parametrespos_boutiquepos'),
    ]

    operations = [
    ]
