# Generated by Django 5.1.4 on 2026-08-26 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('parametres', '0077_cj2a_redevance_compteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadenceRelanceEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('delai_jours', models.PositiveIntegerField(help_text='Nombre de jours après le point de départ du plan.')),
                ('canal', models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite')], max_length=20)),
                ('libelle', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cadence_relance_etapes', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Étape de cadence de relance',
                'verbose_name_plural': 'Étapes de cadence de relance',
                'ordering': ['ordre', 'delai_jours'],
                'unique_together': {('company', 'ordre')},
            },
        ),
    ]
