# Generated by Django 5.1.15 on 2026-09-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0096_nti18n51_traduction_manquante'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='lien_video',
            field=models.URLField(blank=True, default='', help_text="Courte vidéo (30 à 60 s) de CETTE installation, si elle existe. Proposée en plus de la page publique, jamais à la place — laisser vide si aucune vidéo n'existe.", max_length=300, verbose_name='Vidéo du chantier'),
        ),
    ]
