# Generated by Django 5.1.15 on 2026-09-21 15:45
#
# CAD38 — la fenêtre d'appel du Ramadan passe de 10 h-14 h à 09 h-15 h :
# l'horaire continu appliqué au Maroc pendant le mois dans les
# administrations, établissements publics et collectivités (Ministère de la
# Transition numérique et de la Réforme de l'administration, annonce du
# 10/02/2026). Deux AlterField de DÉFAUT uniquement : aucune ligne existante
# n'est réécrite, les sociétés qui ont édité leur fenêtre la gardent, et la
# migration est réversible telle quelle.

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0096_nti18n51_traduction_manquante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='ramadan_appel_debut',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Ramadan — début des appels'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='ramadan_appel_fin',
            field=models.TimeField(default=datetime.time(15, 0), verbose_name='Ramadan — fin des appels'),
        ),
    ]
