# Generated by Django 5.1.15 on 2026-09-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0097_cad95_realisation_lien_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='lien_avis_google',
            field=models.URLField(blank=True, default='', help_text='Lien de la fiche Google de la société (pour le message « avis Google » du suivi client). Vide = ce gabarit ne peut pas être assigné à une touche.', max_length=500),
        ),
    ]
