# Generated by Django 5.1.15 on 2026-09-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0098_cad71_lien_avis_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='premier_contact_alerte_min',
            field=models.PositiveIntegerField(blank=True, help_text='À partir de combien de minutes ouvrées faut-il alerter le responsable du lead ? Laisser vide pour utiliser l’objectif de premier contact lui-même.', null=True, verbose_name='Alerter le responsable après (minutes ouvrées)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='premier_contact_escalade_min',
            field=models.PositiveIntegerField(blank=True, help_text='À partir de combien de minutes ouvrées faut-il prévenir le supérieur ? Laisser vide pour qu’il soit prévenu en même temps que le responsable.', null=True, verbose_name='Prévenir le supérieur après (minutes ouvrées)'),
        ),
    ]
