# Generated by Django 5.1.15 on 2026-09-21 16:11
#
# CAD43 — drapeau `samedi_ok` PAR TOUCHE, symétrique exact de `dimanche_ok`.
# AddField booléen avec défaut FALSE : additif, réversible, et rien ne change
# tant que personne ne coche la case (aucune touche du protocole n'arrive
# cochée). Pas d'index, pas de contrainte d'unicité : aucune réécriture de
# table au-delà du défaut.

from django.db import migrations, models


class Migration(migrations.Migration):

    # Renumérotée 0098 -> 0100 au fold (voir 0099_cad38_ramadan_09_15).
    dependencies = [
        ('parametres', '0099_cad38_ramadan_09_15'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadencerelanceetape',
            name='samedi_ok',
            field=models.BooleanField(default=False, help_text="Cette touche peut-elle tomber un samedi ? À réserver aux canaux silencieux (WhatsApp, e-mail) — un appel le samedi n'est pas dans le protocole.", verbose_name='Autorisée le samedi'),
        ),
    ]
