# Generated by Django 5.1.15 on 2026-09-21 17:15
#
# CAD128 — la cadence COURTE « deuxième affaire » (client déjà signé qui
# redemande un devis) rejoint les valeurs acceptées par le gabarit. Un seul
# AlterField de CHOIX : aucune donnée réécrite, aucune ligne existante
# touchée, réversible tel quel. Les barreaux de cette cadence sont seedés à
# la demande par `CadenceRelanceEtape.cadence_pour` (idempotent), pas ici.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0100_cad43_samedi_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadencerelanceetape',
            name='cadence',
            field=models.CharField(choices=[('contact', 'Prise de contact'), ('apres_devis', 'Après devis'), ('reveil', 'Réveil'), ('generique', 'Générique (historique)'), ('deuxieme_affaire', 'Deuxième affaire (client acquis)')], default='contact', max_length=20, verbose_name='Cadence'),
        ),
    ]
