# Generated by Django 5.1.15 on 2026-09-25 01:50
#
# PARAM-CADENCE (décision fondateur du 25/09/2026) — la chaîne après l'appel
# et autour de la visite technique passe dans Paramètres :
#   * deux cadences de plus acceptées par le gabarit (`apres_contact`,
#     `visite`) — AlterField de CHOIX, aucune ligne touchée ;
#   * `cle` : la clé STABLE par laquelle le moteur retrouve un barreau.
#     Colonne ADDITIVE, vide par défaut (les barreaux du protocole n'en ont
#     pas) : aucune donnée réécrite ;
#   * une contrainte d'unicité PARTIELLE (société, cadence, clé) sur les seules
#     clés posées — aucune ligne existante ne la viole (toutes vides).
# Les barreaux des deux cadences sont seedés à la demande
# (`CadenceRelanceEtape.barreau_par_cle` / `cadence_pour`), pas ici.
# Réversible tel quel.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_solmvp30b_customuser_sans_poste_ref'),
        ('parametres', '0108_calx284_amortissement_fiscalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadencerelanceetape',
            name='cle',
            field=models.CharField(blank=True, default='', help_text='Clé stable lue par le moteur (jamais modifiable).', max_length=40, verbose_name='Clé moteur'),
        ),
        migrations.AlterField(
            model_name='cadencerelanceetape',
            name='cadence',
            field=models.CharField(choices=[('contact', 'Prise de contact'), ('apres_devis', 'Après devis'), ('reveil', 'Réveil'), ('generique', 'Générique (historique)'), ('deuxieme_affaire', 'Deuxième affaire (client acquis)'), ('apres_contact', "Après l'appel (avant devis)"), ('visite', 'Visite technique')], default='contact', max_length=20, verbose_name='Cadence'),
        ),
        migrations.AddConstraint(
            model_name='cadencerelanceetape',
            constraint=models.UniqueConstraint(condition=models.Q(('cle__gt', '')), fields=('company', 'cadence', 'cle'), name='param_cad_cle_uniq'),
        ),
    ]
