# Generated by Django 5.1.4 on 2026-06-20 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("definition", models.JSONField(blank=True, default=dict)),
                (
                    "target_kind",
                    models.CharField(
                        choices=[
                            ("sales", "Ventes"),
                            ("stock", "Stock"),
                            ("service", "Service"),
                        ],
                        default="sales",
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[
                            ("none", "Aucune"),
                            ("daily", "Quotidien"),
                            ("weekly", "Hebdomadaire"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("recipients", models.TextField(blank=True, default="")),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to="authentication.company",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport sauvegardé",
                "verbose_name_plural": "Rapports sauvegardés",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["company", "schedule"],
                        name="reporting_s_company_044798_idx",
                    )
                ],
            },
        ),
    ]
