# Generated by Django 5.1.4 on 2026-07-03 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_xplt22_classeur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classeur',
            name='proprietaire',
            field=models.ForeignKey(blank=True, help_text='Vide = classeur de société (non personnel).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_classeurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
