# Generated by Django 5.1.4 on 2026-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_zctr9_approbationslaconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approbationslaconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
