# Generated by Django 5.1.4 on 2026-09-04 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_aud704_identite_employeur'),
        ('reporting', '0016_ntdata40_envoirapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='partage_revoque_le',
            field=models.DateTimeField(blank=True, help_text='Renseigné, tout lien public de ce rapport cesse immédiatement de servir (404), sans attendre son expiration.', null=True, verbose_name='Partage révoqué le'),
        ),
        migrations.CreateModel(
            name='AccesRapportPartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('consulte_le', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acces_rapports_partages', to='authentication.company', verbose_name='Société')),
                ('saved_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_partages', to='reporting.savedreport', verbose_name='Rapport')),
            ],
            options={
                'verbose_name': 'Accès à un rapport partagé',
                'verbose_name_plural': 'Accès aux rapports partagés',
                'ordering': ['-consulte_le', '-id'],
                'indexes': [models.Index(fields=['company', 'saved_report'], name='reporting_acces_co_rap_idx'), models.Index(fields=['saved_report', '-consulte_le'], name='reporting_acces_rap_dt_idx')],
            },
        ),
    ]
