# Generated by Django 5.1.15 on 2026-09-21 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0024_ntobs31_kpi_fiabilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpialerte',
            name='kpi',
            field=models.CharField(blank=True, choices=[('encours_echu_total', 'Encours client échu total (MAD)'), ('valeur_stock_totale', 'Valeur de stock totale (MAD)'), ('couverture_i18n_pct', "i18n — couverture de l'interface (%)"), ('documents_non_fr_pct', 'i18n — documents générés hors FR (%)'), ('uptime_moyen_12_mois', 'Fiabilité — disponibilité moyenne 12 mois (%)'), ('jours_depuis_dernier_drill_reussi', 'Fiabilité — jours depuis le dernier drill de restauration réussi'), ('quota_le_plus_charge_pct', 'Fiabilité — quota le plus chargé (%)')], default='', max_length=40),
        ),
    ]
