# Generated by Django 5.1.4 on 2026-06-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "immatriculation",
                    models.CharField(max_length=30, verbose_name="Immatriculation"),
                ),
                (
                    "marque",
                    models.CharField(blank=True, max_length=80, verbose_name="Marque"),
                ),
                (
                    "modele",
                    models.CharField(blank=True, max_length=80, verbose_name="Modèle"),
                ),
                (
                    "energie",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("essence", "Essence"),
                            ("electrique", "Électrique"),
                            ("hybride", "Hybride"),
                        ],
                        default="diesel",
                        max_length=20,
                        verbose_name="Énergie",
                    ),
                ),
                (
                    "kilometrage",
                    models.PositiveIntegerField(default=0, verbose_name="Kilométrage"),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valeur (MAD)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("maintenance", "En maintenance"),
                            ("reforme", "Réformé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicules",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
                "ordering": ["immatriculation"],
                "unique_together": {("company", "immatriculation")},
            },
        ),
    ]
