# Generated by Django 5.1.4 on 2026-06-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("flotte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnginRoulant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, verbose_name="Désignation")),
                (
                    "type_engin",
                    models.CharField(
                        choices=[
                            ("nacelle", "Nacelle"),
                            ("groupe_electrogene", "Groupe électrogène"),
                            ("chariot", "Chariot"),
                        ],
                        default="nacelle",
                        max_length=30,
                        verbose_name="Type d'engin",
                    ),
                ),
                (
                    "marque",
                    models.CharField(blank=True, max_length=80, verbose_name="Marque"),
                ),
                (
                    "modele",
                    models.CharField(blank=True, max_length=80, verbose_name="Modèle"),
                ),
                (
                    "compteur_heures",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        max_digits=10,
                        verbose_name="Compteur d'heures",
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Valeur (MAD)",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("maintenance", "En maintenance"),
                            ("reforme", "Réformé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engins_roulants",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engin roulant",
                "verbose_name_plural": "Engins roulants",
                "ordering": ["nom"],
            },
        ),
    ]
