# Generated by Django 5.1.4 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('flotte', '0046_activiteflotte'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accusecharte',
            name='flotte_accusecharte_co_cond_ver_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='budgetflotte',
            name='flotte_budgetflotte_co_an_cat_uniq',
        ),
        migrations.RemoveConstraint(
            model_name='chartevehicule',
            name='flotte_chartevehicule_company_version_uniq',
        ),
        migrations.AlterField(
            model_name='ordrereparation',
            name='statut',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('devis_recu', 'Devis reçu'), ('approuve', 'Approuvé'), ('en_cours', 'En cours'), ('cloture', 'Clôturé')], default='ouvert', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_fiscal',
            field=models.CharField(blank=True, choices=[('utilitaire', 'Utilitaire'), ('tourisme', 'Tourisme')], help_text='Utilitaire ou tourisme — sert au calcul TVA et au plafond CGI amortissement.', max_length=15, verbose_name='Type fiscal'),
        ),
        migrations.AlterUniqueTogether(
            name='accusecharte',
            unique_together={('company', 'conducteur', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='budgetflotte',
            unique_together={('company', 'annee', 'categorie')},
        ),
        migrations.AlterUniqueTogether(
            name='chartevehicule',
            unique_together={('company', 'version')},
        ),
    ]
