# Generated by Django 5.1.4 on 2026-07-05 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0053_affectationconducteur_avantage_en_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrereparation',
            name='type_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flotte_ordres_reparation', to='flotte.referentielflotte', verbose_name='Type de service'),
        ),
        migrations.AlterField(
            model_name='referentielflotte',
            name='domaine',
            field=models.CharField(choices=[('type_vehicule', 'Type de véhicule'), ('type_engin', "Type d'engin"), ('energie', 'Énergie'), ('categorie_permis', 'Catégorie de permis'), ('code_dtc', 'Criticité des codes défaut (DTC)'), ('type_service', 'Type de service / entretien')], max_length=30, verbose_name='Domaine'),
        ),
    ]
