# Generated by Django 5.1.4 on 2026-07-05 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('flotte', '0054_ordrereparation_type_service_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conducteur',
            name='employe_id',
            field=models.PositiveIntegerField(blank=True, help_text='Lien optionnel vers le dossier employé RH. Quand renseigné, le permis RH (rh.PermisConduire) prime sur les champs de permis locaux.', null=True, verbose_name='Employé RH (id)'),
        ),
        migrations.AddField(
            model_name='modelevehicule',
            name='pct_charges_non_deductibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0-100 — plafond CGI tourisme. Vide = non renseigné (aucune part non déductible signalée).', max_digits=5, null=True, verbose_name='% charges non déductibles'),
        ),
        migrations.AddField(
            model_name='modelevehicule',
            name='valeur_residuelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur résiduelle (MAD)'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='carte_mobilite',
            field=models.CharField(blank=True, max_length=60, verbose_name='Carte mobilité'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='pct_charges_non_deductibles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0-100 — plafond CGI tourisme. Vide = non renseigné.', max_digits=5, null=True, verbose_name='% charges non déductibles'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='valeur_residuelle',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valeur résiduelle (MAD)'),
        ),
        # NB — l'index composite (company, employe_id) est posé CONCURREMMENT
        # dans 0056 (YOPSB6) pour ne pas verrouiller flotte_conducteur en
        # écriture ; cette migration se limite aux colonnes.
    ]
