# Generated by Django 5.1.4 on 2026-07-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0056_conducteur_employe_id_index_concurrent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='custom_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Champs personnalisés'),
        ),
    ]
