# Generated by Django 5.1.4 on 2026-09-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotte', '0058_garage_contratvehicule_fournisseur_id_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='assurancevehicule',
            name='attestation_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='assurancevehicule',
            name='attestation_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='assurancevehicule',
            name='attestation_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='assurancevehicule',
            name='attestation_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='cartegrisevehicule',
            name='autorisation_fichier_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='cartegrisevehicule',
            name='autorisation_fichier_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='cartegrisevehicule',
            name='autorisation_fichier_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='cartegrisevehicule',
            name='autorisation_fichier_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='cartegrisevehicule',
            name='carte_grise_fichier_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='cartegrisevehicule',
            name='carte_grise_fichier_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='cartegrisevehicule',
            name='carte_grise_fichier_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='cartegrisevehicule',
            name='carte_grise_fichier_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='chartevehicule',
            name='document_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='chartevehicule',
            name='document_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='chartevehicule',
            name='document_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='chartevehicule',
            name='document_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='pv_fichier_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='pv_fichier_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='pv_fichier_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='infraction',
            name='pv_fichier_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='ordrereparation',
            name='devis_fichier_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='ordrereparation',
            name='devis_fichier_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='ordrereparation',
            name='devis_fichier_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='ordrereparation',
            name='devis_fichier_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='signalementvehicule',
            name='photo_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='signalementvehicule',
            name='photo_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='signalementvehicule',
            name='photo_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='signalementvehicule',
            name='photo_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='constat_fichier_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='constat_fichier_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='constat_fichier_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='sinistre',
            name='constat_fichier_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AlterField(
            model_name='assurancevehicule',
            name='attestation',
            field=models.FileField(blank=True, null=True, upload_to='flotte/assurances/attestations/%Y/%m/', verbose_name="Attestation d'assurance (legacy, hors MinIO)"),
        ),
        migrations.AlterField(
            model_name='cartegrisevehicule',
            name='autorisation_fichier',
            field=models.FileField(blank=True, null=True, upload_to='flotte/autorisations_circulation/%Y/%m/', verbose_name='Autorisation de circulation (scan, legacy hors MinIO)'),
        ),
        migrations.AlterField(
            model_name='cartegrisevehicule',
            name='carte_grise_fichier',
            field=models.FileField(blank=True, null=True, upload_to='flotte/cartes_grises/%Y/%m/', verbose_name='Carte grise (scan, legacy hors MinIO)'),
        ),
        migrations.AlterField(
            model_name='chartevehicule',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='flotte/chartes_vehicule/%Y/%m/', verbose_name='Document (charte véhicule, legacy hors MinIO)'),
        ),
        migrations.AlterField(
            model_name='infraction',
            name='pv_fichier',
            field=models.FileField(blank=True, null=True, upload_to='flotte/infractions/pv/%Y/%m/', verbose_name='PV scanné (legacy, hors MinIO)'),
        ),
        migrations.AlterField(
            model_name='ordrereparation',
            name='devis_fichier',
            field=models.FileField(blank=True, null=True, upload_to='flotte/ordres_reparation/devis/%Y/%m/', verbose_name='Devis (scan, legacy hors MinIO)'),
        ),
        migrations.AlterField(
            model_name='signalementvehicule',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='flotte/signalements/photos/%Y/%m/', verbose_name='Photo (legacy, hors MinIO)'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='constat_fichier',
            field=models.FileField(blank=True, null=True, upload_to='flotte/sinistres/constats/%Y/%m/', verbose_name='Constat amiable (legacy, hors MinIO)'),
        ),
    ]
