# Generated by Django 5.1.4 on 2026-08-14 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(blank=True, default='', max_length=30)),
                ('type_flux', models.CharField(choices=[('enlevement_livraison', 'Enlèvement / livraison'), ('inter_site', 'Inter-site'), ('import', 'Import'), ('export', 'Export')], default='enlevement_livraison', max_length=25)),
                ('expediteur_nom', models.CharField(blank=True, default='', max_length=255)),
                ('expediteur_adresse', models.TextField(blank=True, default='')),
                ('destinataire_nom', models.CharField(blank=True, default='', max_length=255)),
                ('destinataire_adresse', models.TextField(blank=True, default='')),
                ('date_enlevement_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifie', 'Planifié'), ('en_cours', 'En cours'), ('livre', 'Livré'), ('annule', 'Annulé')], default='brouillon', max_length=15)),
                ('instructions_speciales', models.TextField(blank=True, default='')),
                ('ventes_boncommande_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bon de commande (ventes.BonCommande)')),
                ('ventes_devis_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Devis (ventes.Devis)')),
                ('installations_installation_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chantier (installations.Installation)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_transport_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordre de transport',
                'verbose_name_plural': 'Ordres de transport',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_ot_co_statut')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('numero', ''), _negated=True), fields=('company', 'numero'), name='uniq_ordretransport_co_numero')],
            },
        ),
    ]
