# Generated by Django 5.1.4 on 2026-08-14 00:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneOrdreTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_produit_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Produit (stock.Produit)')),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('unite', models.CharField(blank=True, default='', max_length=20)),
                ('poids_kg', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('volume_m3', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('valeur_declaree', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='transport.ordretransport')),
            ],
            options={
                'verbose_name': "Ligne d'ordre de transport",
                'verbose_name_plural': "Lignes d'ordre de transport",
                'ordering': ['ordre_id', 'id'],
                'indexes': [models.Index(fields=['ordre'], name='idx_lot_ordre')],
            },
        ),
    ]
