# Generated by Django 5.1.4 on 2026-08-14 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('transport', '0002_ligneordretransport'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('type_etape', models.CharField(choices=[('enlevement', 'Enlèvement'), ('transit', 'Transit'), ('livraison', 'Livraison')], default='transit', max_length=12)),
                ('lieu', models.CharField(blank=True, default='', max_length=255)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_reelle', models.DateField(blank=True, null=True)),
                ('statut_etape', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('incident', 'Incident')], default='a_faire', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ordre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='transport.ordretransport')),
            ],
            options={
                'verbose_name': 'Étape de transport',
                'verbose_name_plural': 'Étapes de transport',
                'ordering': ['ordre_id', 'sequence', 'id'],
                'indexes': [models.Index(fields=['ordre', 'sequence'], name='idx_et_ordre_seq')],
            },
        ),
    ]
