# Generated by Django 5.1.4 on 2026-08-14 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_etapetransport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordretransport',
            name='conducteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_transport_conduits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordretransport',
            name='flotte_actif_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Actif flotte (flotte.ActifFlotte)'),
        ),
        migrations.AddField(
            model_name='ordretransport',
            name='installations_transporteur_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Transporteur (installations.Transporteur)'),
        ),
        migrations.AddField(
            model_name='ordretransport',
            name='mode_transport',
            field=models.CharField(choices=[('flotte_propre', 'Flotte propre'), ('affretement', 'Affrètement')], default='affretement', max_length=15),
        ),
    ]
