# Generated by Django 5.1.4 on 2026-08-14 01:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('transport', '0004_ordretransport_conducteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoutFretReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('devise', models.CharField(default='MAD', max_length=8)),
                ('type_cout', models.CharField(choices=[('transport', 'Transport'), ('assurance', 'Assurance'), ('manutention', 'Manutention'), ('dedouanement', 'Dédouanement')], default='transport', max_length=15)),
                ('stock_boncommandefournisseur_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='BCF (stock.BonCommandeFournisseur)')),
                ('note', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ordre_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couts_fret', to='transport.ordretransport')),
            ],
            options={
                'verbose_name': 'Coût de fret réel',
                'verbose_name_plural': 'Coûts de fret réels',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'stock_boncommandefournisseur_id'], name='idx_cfr_co_bcf')],
            },
        ),
    ]
