# Generated by Django 5.1.4 on 2026-08-14 01:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('transport', '0005_coutfretreel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LitigeTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_litige', models.CharField(choices=[('avarie', 'Avarie'), ('retard', 'Retard'), ('manquant', 'Manquant'), ('erreur_livraison', 'Erreur de livraison')], default='avarie', max_length=20)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_traitement', 'En traitement'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='ouvert', max_length=15)),
                ('montant_conteste', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('description', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_transport_crees', to=settings.AUTH_USER_MODEL)),
                ('ordre_transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to='transport.ordretransport')),
            ],
            options={
                'verbose_name': 'Litige transport',
                'verbose_name_plural': 'Litiges transport',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_lt_co_statut')],
            },
        ),
    ]
