# Generated by Django 5.1.4 on 2026-08-14 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('transport', '0006_litigetransport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nature_reserve', models.TextField(blank=True, default='')),
                ('montant_estime_dommage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='transport.etapetransport')),
                ('litige', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserves', to='transport.litigetransport')),
            ],
            options={
                'verbose_name': 'Réserve à réception',
                'verbose_name_plural': 'Réserves à réception',
                'ordering': ['-created_at'],
            },
        ),
    ]
