# Generated by Django 5.1.4 on 2026-08-14 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_reservereception'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigetransport',
            name='reclamation_destinataire',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='litigetransport',
            name='reclamation_envoyee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
