# Generated by Django 5.1.4 on 2026-08-14 01:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('transport', '0008_litigetransport_reclamation_destinataire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordretransport',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='ordretransport',
            name='mode_acheminement_physique',
            field=models.CharField(choices=[('route', 'Route'), ('mer', 'Mer'), ('air', 'Air')], default='route', max_length=10),
        ),
        migrations.CreateModel(
            name='FacteurEmissionCO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('route', 'Route'), ('mer', 'Mer'), ('air', 'Air')], max_length=10)),
                ('facteur_kg_co2_par_tonne_km', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Facteur d'émission CO2",
                'verbose_name_plural': "Facteurs d'émission CO2",
                'ordering': ['mode'],
                'constraints': [models.UniqueConstraint(fields=('company', 'mode'), name='uniq_facteurco2_co_mode')],
            },
        ),
    ]
