# Generated by Django 5.1.4 on 2026-08-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_ordretransport_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigetransport',
            name='montant_resolu',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
