# Generated by Django 5.1.4 on 2026-08-14 13:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('transport', '0010_litigetransport_montant_resolu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delai_alerte_retard_heures', models.PositiveIntegerField(default=24)),
                ('pod_obligatoire', models.BooleanField(default=True)),
                ('seuil_anomalie_affretement_pct', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport_parametres', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Paramètres transport',
                'verbose_name_plural': 'Paramètres transport',
            },
        ),
    ]
