# Generated by Django 5.1.4 on 2026-08-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_parametrestransport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordretransport',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parametrestransport',
            name='archive_ordres_apres_mois',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
