# Generated by Django 5.1.4 on 2026-07-17 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureElectronique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture_id', models.PositiveIntegerField(verbose_name='ID de la facture (ventes)')),
                ('facture_ref', models.CharField(blank=True, default='', max_length=80, verbose_name='Référence facture (dénormalisée)')),
                ('format', models.CharField(choices=[('ubl', 'UBL 2.1'), ('cii', 'CII')], default='ubl', max_length=6, verbose_name='Format')),
                ('mode', models.CharField(choices=[('dry_run', 'Simulation (dry-run)'), ('reel', 'Réel')], default='dry_run', max_length=8, verbose_name='Mode')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('genere', 'Généré'), ('signe', 'Signé'), ('transmis', 'Transmis'), ('rejete', 'Rejeté')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('xml_key', models.CharField(blank=True, default='', max_length=500, verbose_name='Clé MinIO du XML')),
                ('hash_contenu', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte SHA-256')),
                ('signature_xml', models.TextField(blank=True, default='', verbose_name='XML de signature')),
                ('certificat_ref', models.CharField(blank=True, default='', max_length=120, verbose_name='Référence certificat')),
                ('signe_le', models.DateTimeField(blank=True, null=True, verbose_name='Signé le')),
                ('genere_le', models.DateTimeField(blank=True, null=True, verbose_name='Généré le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_electroniques', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_electroniques_creees', to=settings.AUTH_USER_MODEL, verbose_name='Générée par')),
            ],
            options={
                'verbose_name': 'Facture électronique',
                'verbose_name_plural': 'Factures électroniques',
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransmissionDGI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoye', 'Envoyé'), ('accepte', 'Accepté'), ('rejete', 'Rejeté')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('reponse_json', models.JSONField(blank=True, default=dict, verbose_name='Réponse DGI (brute)')),
                ('tentatives', models.PositiveIntegerField(default=0, verbose_name='Tentatives')),
                ('prochaine_tentative', models.DateTimeField(blank=True, null=True, verbose_name='Prochaine tentative')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions_dgi', to='authentication.company', verbose_name='Société')),
                ('einvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmissions', to='einvoice.factureelectronique', verbose_name='Facture électronique')),
            ],
            options={
                'verbose_name': 'Transmission DGI',
                'verbose_name_plural': 'Transmissions DGI',
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='factureelectronique',
            constraint=models.UniqueConstraint(fields=('company', 'facture_id', 'version'), name='uniq_einvoice_facture_version'),
        ),
        migrations.AddConstraint(
            model_name='transmissiondgi',
            constraint=models.UniqueConstraint(fields=('company', 'einvoice'), name='uniq_transmission_dgi_einvoice'),
        ),
    ]
