# Generated by Django 5.1.4 on 2026-07-31 18:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementSupprime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(verbose_name='Identifiant du document')),
                ('type_libelle', models.CharField(blank=True, default='', max_length=80, verbose_name='Type')),
                ('libelle_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Libellé')),
                ('donnees_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Données (affichage seul)')),
                ('supprime_le', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Supprimé le')),
                ('expire_le', models.DateTimeField(db_index=True, verbose_name='Expire le')),
                ('restaure_le', models.DateTimeField(blank=True, null=True, verbose_name='Restauré le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Type de document')),
                ('supprime_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Élément supprimé',
                'verbose_name_plural': 'Éléments supprimés',
                'ordering': ['-supprime_le', '-id'],
                'indexes': [models.Index(fields=['company', 'restaure_le'], name='trash_co_restaure_idx'), models.Index(fields=['company', 'expire_le'], name='trash_co_expire_idx'), models.Index(fields=['content_type', 'object_id'], name='trash_cible_idx')],
            },
        ),
    ]
