# Generated by Django 5.1.4 on 2026-07-17 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0024_company_est_demo_mode_presentation'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
        ('stock', '0080_odx19_achats_split_repoint'),
        ('ventes', '0087_ntcpq4_listeprix_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreGroupee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('prix_total', models.DecimalField(blank=True, decimal_places=2, help_text='Prix fixe du bundle (mode FIXE) réparti au prorata.', max_digits=12, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_offres_groupees', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Offre groupée',
                'verbose_name_plural': 'Offres groupées',
                'ordering': ['-date_creation', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LigneOffreGroupee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('mode_prix', models.CharField(choices=[('FIXE', 'Prix fixe (bundle)'), ('REMISE_PCT', 'Remise %'), ('PRIX_COMPOSANT', 'Prix composant imposé')], default='FIXE', max_length=20)),
                ('valeur', models.DecimalField(blank=True, decimal_places=2, help_text='% de remise (REMISE_PCT) ou prix imposé (PRIX_COMPOSANT).', max_digits=10, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_lignes_offre', to='stock.produit')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='cpq.offregroupee')),
            ],
            options={
                'verbose_name': 'Ligne offre groupée',
                'verbose_name_plural': 'Lignes offre groupée',
                'ordering': ['offre_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OptionProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groupe_option', models.CharField(help_text="Groupe de l'option (ex. « Onduleur », « Batterie »).", max_length=100)),
                ('obligatoire', models.BooleanField(default=False, help_text='Le groupe doit être renseigné dans la configuration.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_options_produit', to='authentication.company')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_options', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Option produit',
                'verbose_name_plural': 'Options produit',
                'ordering': ['groupe_option', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrixContractuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('motif', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_prix_contractuels', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_prix_contractuels', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpq_prix_contractuels_crees', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_prix_contractuels', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Prix contractuel',
                'verbose_name_plural': 'Prix contractuels',
                'ordering': ['-date_creation', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionConfigurateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('texte', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CHOIX_UNIQUE', 'Choix unique'), ('CHOIX_MULTIPLE', 'Choix multiple'), ('NUMERIQUE', 'Numérique')], default='CHOIX_UNIQUE', max_length=20)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_questions_configurateur', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Question configurateur',
                'verbose_name_plural': 'Questions configurateur',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegleApprobationRemise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(blank=True, default='', max_length=200)),
                ('remise_min_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remise_max_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('niveau_approbation', models.CharField(choices=[('responsable', 'Responsable'), ('administrateur', 'Administrateur'), ('direction', 'Direction')], default='responsable', max_length=20)),
                ('nombre_approbateurs', models.PositiveIntegerField(default=1)),
                ('priorite', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_regles_approbation_remise', to='authentication.company')),
            ],
            options={
                'verbose_name': "Règle d'approbation de remise",
                'verbose_name_plural': "Règles d'approbation de remise",
                'ordering': ['-priorite', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EtapeApprobationDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('niveau', models.PositiveIntegerField(default=1)),
                ('niveau_approbation', models.CharField(choices=[('responsable', 'Responsable'), ('administrateur', 'Administrateur'), ('direction', 'Direction')], default='responsable', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('decision_le', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approbateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpq_etapes_devis_decidees', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_etapes_approbation_devis', to='authentication.company')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_etapes_approbation', to='ventes.devis')),
                ('regle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes', to='cpq.regleapprobationremise')),
            ],
            options={
                'verbose_name': "Étape d'approbation de devis",
                'verbose_name_plural': "Étapes d'approbation de devis",
                'ordering': ['devis_id', 'niveau', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RegleProduitCPQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('condition_group', models.JSONField(blank=True, default=dict, help_text='Arbre de conditions ET/OU/NON (core.rules).')),
                ('actions', models.JSONField(blank=True, default=list, help_text="Liste d'actions déclenchées quand la règle est vraie.")),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_regles_produit', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Règle produit CPQ',
                'verbose_name_plural': 'Règles produit CPQ',
                'ordering': ['-date_creation', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionConfigurateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_sessions_configurateur', to='authentication.company')),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cpq_sessions_configurateur', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Session configurateur',
                'verbose_name_plural': 'Sessions configurateur',
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReponseConfigurateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='cpq.questionconfigurateur')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='cpq.sessionconfigurateur')),
            ],
            options={
                'verbose_name': 'Réponse configurateur',
                'verbose_name_plural': 'Réponses configurateur',
                'ordering': ['session_id', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='SeuilMargeFamille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marge_min_pct', models.DecimalField(decimal_places=2, help_text='Marge minimale attendue (%) pour cette famille.', max_digits=5)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_seuils_marge', to='stock.categorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_seuils_marge', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Seuil de marge par famille',
                'verbose_name_plural': 'Seuils de marge par famille',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContrainteCompatibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INCOMPATIBLE', 'Incompatible'), ('REQUIERT', 'Requiert'), ('RECOMMANDE', 'Recommandé')], max_length=20)),
                ('message_utilisateur', models.CharField(blank=True, default='', help_text="Message affiché à l'utilisateur quand la contrainte joue.", max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_contraintes_compatibilite', to='authentication.company')),
                ('produit_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_contraintes_a', to='stock.produit')),
                ('produit_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_contraintes_b', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Contrainte de compatibilité',
                'verbose_name_plural': 'Contraintes de compatibilité',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['company', 'type'], name='cpq_contr_co_type'), models.Index(fields=['company', 'produit_a'], name='cpq_contr_co_pa')],
            },
        ),
        migrations.AddIndex(
            model_name='offregroupee',
            index=models.Index(fields=['company', 'actif'], name='cpq_offre_co_actif'),
        ),
        migrations.AddIndex(
            model_name='optionproduit',
            index=models.Index(fields=['company', 'groupe_option'], name='cpq_optprod_co_grp'),
        ),
        migrations.AddIndex(
            model_name='prixcontractuel',
            index=models.Index(fields=['company', 'client', 'produit'], name='cpq_prixctr_co_cl_pr'),
        ),
        migrations.AddIndex(
            model_name='questionconfigurateur',
            index=models.Index(fields=['company', 'actif'], name='cpq_question_co_act'),
        ),
        migrations.AddIndex(
            model_name='regleapprobationremise',
            index=models.Index(fields=['company', 'actif'], name='cpq_regleremise_co_act'),
        ),
        migrations.AddIndex(
            model_name='etapeapprobationdevis',
            index=models.Index(fields=['company', 'statut'], name='cpq_etapedev_co_sta'),
        ),
        migrations.AddIndex(
            model_name='etapeapprobationdevis',
            index=models.Index(fields=['devis', 'niveau'], name='cpq_etapedev_dv_niv'),
        ),
        migrations.AddIndex(
            model_name='regleproduitcpq',
            index=models.Index(fields=['company', 'actif'], name='cpq_regle_co_actif'),
        ),
        migrations.AddIndex(
            model_name='sessionconfigurateur',
            index=models.Index(fields=['company', 'updated_at'], name='cpq_session_co_upd'),
        ),
        migrations.AddConstraint(
            model_name='reponseconfigurateur',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='cpq_reponse_unique_sess_q'),
        ),
        migrations.AddConstraint(
            model_name='seuilmargefamille',
            constraint=models.UniqueConstraint(fields=('company', 'categorie'), name='cpq_seuilmarge_unique_co_cat'),
        ),
    ]
