# Generated by Django 5.1.4 on 2026-07-31 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0001_initial'),
        ('stock', '0081_protect_produit_donnees_reelles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneoffregroupee',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpq_lignes_offre', to='stock.produit'),
        ),
        migrations.AlterField(
            model_name='prixcontractuel',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpq_prix_contractuels', to='stock.produit'),
        ),
    ]
