# Generated by Django 5.1.4 on 2026-08-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('cpq', '0002_protect_produit_donnees_reelles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseCGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('corps_texte', models.TextField(blank=True, default='', help_text="Texte de la clause tel qu'il apparaîtra sur le document.")),
                ('type_deal', models.CharField(blank=True, default='', help_text='Référentiel libre (ex. « industriel »). Vide = tous types.', max_length=100)),
                ('applicable_si', models.JSONField(blank=True, default=dict, help_text='Arbre de conditions ET/OU/NON (core.rules). Vide = toujours.')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_clauses_cgv', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Clause / CGV',
                'verbose_name_plural': 'Clauses / CGV',
                'ordering': ['ordre', 'id'],
                'indexes': [models.Index(fields=['company', 'actif'], name='cpq_clause_co_actif')],
            },
        ),
    ]
