# Generated by Django 5.1.4 on 2026-08-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('cpq', '0003_ntcpq11_clause_cgv'),
        ('stock', '0085_ntadm2_produit_entite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitEquivalent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('economique', 'Économique'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_produits_equivalents', to='authentication.company')),
                ('produit_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_equivalents_source', to='stock.produit')),
                ('produit_substitut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_equivalents_substitut', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Produit équivalent',
                'verbose_name_plural': 'Produits équivalents',
                'ordering': ['produit_source_id', 'tier', 'id'],
                'indexes': [models.Index(fields=['company', 'produit_source', 'tier'], name='cpq_equiv_co_src_tier')],
                'constraints': [models.UniqueConstraint(fields=('company', 'produit_source', 'produit_substitut', 'tier'), name='cpq_equiv_unique_co_src_sub_tier')],
            },
        ),
    ]
