# Generated by Django 5.1.4 on 2026-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0004_ntcpq16_variantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='regleproduitcpq',
            name='bloquante',
            field=models.BooleanField(default=False, help_text='Règle bloquante (et non simple avertissement) quand elle se déclenche.'),
        ),
    ]
