# Generated by Django 5.1.4 on 2026-08-14 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('cpq', '0005_ntcpq21_regle_bloquante'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresCPQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marge_min_defaut_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Marge minimale par défaut (%) — repli quand aucun SeuilMargeFamille ne couvre la catégorie.', max_digits=5, null=True)),
                ('approbation_active', models.BooleanField(default=True, help_text='Désactivé : envoyer/generer-pdf ne sont plus bloqués par une approbation de remise en attente (NTCPQ7).')),
                ('variantes_auto_generees', models.BooleanField(default=False, help_text='Générer automatiquement les variantes (NTCPQ16) à la création du devis.')),
                ('duree_validite_prix_contractuel_jours', models.PositiveIntegerField(blank=True, help_text="Durée de validité par défaut d'un PrixContractuel sans date_fin explicite (NULL = pas de limite, comportement historique inchangé).", null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpq_parametres', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Paramètres CPQ',
                'verbose_name_plural': 'Paramètres CPQ',
            },
        ),
    ]
