# Generated by Django 5.1.4 on 2026-08-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0006_ntcpq30_parametres'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescpq',
            name='compatibilite_mode',
            field=models.CharField(choices=[('BLOQUANT', 'Bloquant'), ('AVERTISSEMENT', 'Avertissement')], default='AVERTISSEMENT', help_text='BLOQUANT empêche envoyer/generer-pdf tant qu’une violation de compatibilité bloquante (NTCPQ1) subsiste.', max_length=20),
        ),
    ]
