# Generated by Django 5.1.4 on 2026-08-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0007_ntcpq31_compatibilite_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapeapprobationdevis',
            name='derniere_relance_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parametrescpq',
            name='delai_relance_approbation_jours',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
