# Generated by Django 5.1.4 on 2026-08-14 03:49
#
# SCA4/ARC1 — ParametresCPQ (NTCPQ30) hérite désormais de core.models.TenantModel
# comme le reste de l'app cpq, au lieu de hand-roller sa paire multi-société.
# Purement ADDITIF : les deux horodatages du socle sont ajoutés ; la colonne
# company_id est INCHANGÉE (le OneToOneField est redéclaré à l'identique) et
# date_creation/date_modification restent en place (contrat d'API du serializer).

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpq', '0008_ntcpq33_relance_approbations'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrescpq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrescpq',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
