# Generated by Django 5.1.4 on 2026-07-16 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeReportingESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin', models.DateField(verbose_name='Fin')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('figee', 'Figée'), ('publiee', 'Publiée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('figee_le', models.DateTimeField(blank=True, null=True, verbose_name='Figée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('figee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_esg_figees', to=settings.AUTH_USER_MODEL, verbose_name='Figée par')),
            ],
            options={
                'verbose_name': 'Période de reporting ESG',
                'verbose_name_plural': 'Périodes de reporting ESG',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donnees', models.JSONField(blank=True, default=dict, verbose_name='Données')),
                ('figee_le', models.DateTimeField(auto_now_add=True, verbose_name='Figé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('periode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='esg.periodereportingesg', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Instantané ESG',
                'verbose_name_plural': 'Instantanés ESG',
                'ordering': ['-figee_le', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CatalogueIndicateurESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('pilier', models.CharField(choices=[('environnement', 'Environnement'), ('social', 'Social'), ('gouvernance', 'Gouvernance')], max_length=15, verbose_name='Pilier ESG')),
                ('unite_attendue', models.CharField(blank=True, default='', max_length=30, verbose_name='Unité attendue')),
                ('reference_gri', models.CharField(blank=True, default='', max_length=60, verbose_name='Référence GRI (inspiré de)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Indicateur du catalogue GRI-lite',
                'verbose_name_plural': 'Catalogue GRI-lite',
                'ordering': ['pilier', 'code'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='esg_catalogue_co_code_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ObjectifESGTrajectoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicateur_code', models.CharField(max_length=30, verbose_name='Code indicateur (qhse.IndicateurESG)')),
                ('libelle', models.CharField(blank=True, default='', max_length=255, verbose_name='Libellé')),
                ('valeur_reference', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valeur de référence')),
                ('annee_reference', models.PositiveIntegerField(verbose_name='Année de référence')),
                ('valeur_cible', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Valeur cible')),
                ('annee_cible', models.PositiveIntegerField(verbose_name='Année cible')),
                ('jalons', models.JSONField(blank=True, default=dict, verbose_name='Jalons intermédiaires ({année: valeur})')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Objectif de trajectoire ESG',
                'verbose_name_plural': 'Objectifs de trajectoire ESG',
                'ordering': ['indicateur_code', 'annee_cible'],
                'constraints': [models.UniqueConstraint(fields=('company', 'indicateur_code', 'annee_cible'), name='esg_objectif_co_code_anneecible_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodereportingesg',
            constraint=models.UniqueConstraint(fields=('company', 'libelle'), name='esg_periode_co_libelle_uniq'),
        ),
    ]
