# Generated by Django 5.1.4 on 2026-07-17 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('esg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiePrenanteESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('categorie', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur'), ('collaborateur', 'Collaborateur'), ('collectivite', 'Collectivité'), ('actionnaire', 'Actionnaire')], max_length=15, verbose_name='Catégorie')),
                ('enjeux', models.TextField(blank=True, default='', verbose_name='Enjeux prioritaires')),
                ('influence', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Influence (1-5)')),
                ('interet', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Intérêt (1-5)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Partie prenante ESG',
                'verbose_name_plural': 'Parties prenantes ESG',
                'ordering': ['-influence', '-interet', 'nom'],
            },
        ),
    ]
