# Generated by Django 5.1.4 on 2026-07-17 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('esg', '0002_partieprenanteesg'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPolitiqueESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('type_document', models.CharField(choices=[('charte_ethique', 'Charte éthique'), ('politique_environnementale', 'Politique environnementale'), ('politique_diversite', 'Politique diversité'), ('code_fournisseur', 'Code fournisseur')], max_length=30, verbose_name='Type de document')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée'), ('obsolete', 'Obsolète')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
                ('date_revue', models.DateField(blank=True, null=True, verbose_name='Date de dernière revue')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Document de politique ESG',
                'verbose_name_plural': 'Documents de politique ESG',
                'ordering': ['-date_publication', '-id'],
            },
        ),
    ]
