# Generated by Django 5.1.4 on 2026-07-17 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('esg', '0003_documentpolitiqueesg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacteurEmissionReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(max_length=120, verbose_name='Catégorie')),
                ('unite', models.CharField(max_length=30, verbose_name='Unité')),
                ('valeur', models.DecimalField(decimal_places=6, max_digits=18, verbose_name="Valeur (facteur d'émission)")),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Source')),
                ('date_maj', models.DateField(verbose_name='Date de mise à jour')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('actif', models.BooleanField(default=True, verbose_name='Version active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Facteur d'émission de référence",
                'verbose_name_plural': "Facteurs d'émission de référence",
                'ordering': ['categorie', 'unite', '-version'],
                'constraints': [models.UniqueConstraint(fields=('company', 'categorie', 'unite', 'version'), name='esg_facteur_co_cat_unite_version_uniq')],
            },
        ),
    ]
