# Generated by Django 5.1.4 on 2026-07-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esg', '0004_facteuremissionreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facteuremissionreference',
            name='date_maj',
            field=models.DateTimeField(verbose_name='Date de mise à jour'),
        ),
    ]
