# Generated by Django 5.1.4 on 2026-07-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('esg', '0005_alter_facteuremissionreference_date_maj'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacteurEmissionVersionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(max_length=120)),
                ('unite', models.CharField(max_length=30)),
                ('dernier_version', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Compteur de version de facteur d'émission",
                'verbose_name_plural': "Compteurs de version de facteur d'émission",
                'constraints': [models.UniqueConstraint(fields=('company', 'categorie', 'unite'), name='esg_facteur_version_counter_co_cat_unite_uniq')],
            },
        ),
    ]
