# Generated by Django 5.1.4 on 2026-06-19 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lead_assigned", "Nouveau lead assigné"),
                            ("devis_accepted", "Devis accepté"),
                            ("chantier_due", "Chantier à installer"),
                            ("facture_overdue", "Facture en retard"),
                            ("warranty_expiring", "Garantie bientôt expirée"),
                            ("maintenance_due", "Visite de maintenance due"),
                            ("stock_low", "Stock bas"),
                            ("sav_ticket_opened", "Ticket SAV ouvert"),
                            ("sav_ticket_breaching", "Ticket SAV proche de son délai"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, default="")),
                ("link", models.CharField(blank=True, default="", max_length=512)),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="authentication.company",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["company", "recipient", "read"],
                        name="notificatio_company_8ea43b_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="notificatio_recipie_f39341_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lead_assigned", "Nouveau lead assigné"),
                            ("devis_accepted", "Devis accepté"),
                            ("chantier_due", "Chantier à installer"),
                            ("facture_overdue", "Facture en retard"),
                            ("warranty_expiring", "Garantie bientôt expirée"),
                            ("maintenance_due", "Visite de maintenance due"),
                            ("stock_low", "Stock bas"),
                            ("sav_ticket_opened", "Ticket SAV ouvert"),
                            ("sav_ticket_breaching", "Ticket SAV proche de son délai"),
                        ],
                        max_length=40,
                    ),
                ),
                ("in_app", models.BooleanField(default=True)),
                ("whatsapp", models.BooleanField(default=False)),
                ("email", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to="authentication.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de notification",
                "verbose_name_plural": "Préférences de notification",
                "ordering": ["event_type"],
                "indexes": [
                    models.Index(
                        fields=["company", "user"],
                        name="notificatio_company_123f2b_idx",
                    )
                ],
                "unique_together": {("user", "event_type")},
            },
        ),
    ]
