# Generated by Django 5.1.4 on 2026-06-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lead_assigned", "Nouveau lead assigné"),
                    ("devis_accepted", "Devis accepté"),
                    ("chantier_due", "Chantier à installer"),
                    ("facture_overdue", "Facture en retard"),
                    ("warranty_expiring", "Garantie bientôt expirée"),
                    ("maintenance_due", "Visite de maintenance due"),
                    ("stock_low", "Stock bas"),
                    ("sav_ticket_opened", "Ticket SAV ouvert"),
                    ("sav_ticket_breaching", "Ticket SAV proche de son délai"),
                    ("digest", "Récapitulatif"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lead_assigned", "Nouveau lead assigné"),
                    ("devis_accepted", "Devis accepté"),
                    ("chantier_due", "Chantier à installer"),
                    ("facture_overdue", "Facture en retard"),
                    ("warranty_expiring", "Garantie bientôt expirée"),
                    ("maintenance_due", "Visite de maintenance due"),
                    ("stock_low", "Stock bas"),
                    ("sav_ticket_opened", "Ticket SAV ouvert"),
                    ("sav_ticket_breaching", "Ticket SAV proche de son délai"),
                    ("digest", "Récapitulatif"),
                ],
                max_length=40,
            ),
        ),
    ]
