# Generated by Django 5.1.4 on 2026-06-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_pushsubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="VapidKeyPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_key", models.TextField(default="")),
                ("private_key", models.TextField(default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Paire de clés VAPID",
                "verbose_name_plural": "Paires de clés VAPID",
            },
        ),
    ]
