# Generated by Django 5.1.4 on 2026-06-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_notificationroutingrule"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notificationroutingrule",
            new_name="notificatio_company_eb26f0_idx",
            old_name="notificatio_company_f47d25_idx",
        ),
    ]
