# Generated by Django 5.2.15 on 2026-06-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0006_rename_notificatio_company_f47d25_idx_notificatio_company_eb26f0_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lead_assigned", "Nouveau lead assigné"),
                    ("devis_accepted", "Devis accepté"),
                    ("chantier_due", "Chantier à installer"),
                    ("facture_overdue", "Facture en retard"),
                    ("warranty_expiring", "Garantie bientôt expirée"),
                    ("maintenance_due", "Visite de maintenance due"),
                    ("stock_low", "Stock bas"),
                    ("sav_ticket_opened", "Ticket SAV ouvert"),
                    ("sav_ticket_breaching", "Ticket SAV proche de son délai"),
                    ("chat_message", "Nouveau message"),
                    ("chat_mention", "Vous avez été mentionné"),
                    ("digest", "Récapitulatif"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lead_assigned", "Nouveau lead assigné"),
                    ("devis_accepted", "Devis accepté"),
                    ("chantier_due", "Chantier à installer"),
                    ("facture_overdue", "Facture en retard"),
                    ("warranty_expiring", "Garantie bientôt expirée"),
                    ("maintenance_due", "Visite de maintenance due"),
                    ("stock_low", "Stock bas"),
                    ("sav_ticket_opened", "Ticket SAV ouvert"),
                    ("sav_ticket_breaching", "Ticket SAV proche de son délai"),
                    ("chat_message", "Nouveau message"),
                    ("chat_mention", "Vous avez été mentionné"),
                    ("digest", "Récapitulatif"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="notificationroutingrule",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("lead_assigned", "Nouveau lead assigné"),
                    ("devis_accepted", "Devis accepté"),
                    ("chantier_due", "Chantier à installer"),
                    ("facture_overdue", "Facture en retard"),
                    ("warranty_expiring", "Garantie bientôt expirée"),
                    ("maintenance_due", "Visite de maintenance due"),
                    ("stock_low", "Stock bas"),
                    ("sav_ticket_opened", "Ticket SAV ouvert"),
                    ("sav_ticket_breaching", "Ticket SAV proche de son délai"),
                    ("chat_message", "Nouveau message"),
                    ("chat_mention", "Vous avez été mentionné"),
                    ("digest", "Récapitulatif"),
                ],
                max_length=40,
                verbose_name="Type d'événement",
            ),
        ),
    ]
