# Generated by Django 5.1.4 on 2026-06-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_whatsapp_bsp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('lead_assigned', 'Nouveau lead assigné'), ('lead_new', 'Nouveau lead site web'), ('devis_accepted', 'Devis accepté'), ('devis_opened', 'Proposition ouverte par le client'), ('chantier_due', 'Chantier à installer'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie bientôt expirée'), ('maintenance_due', 'Visite de maintenance due'), ('stock_low', 'Stock bas'), ('sav_ticket_opened', 'Ticket SAV ouvert'), ('sav_ticket_breaching', 'Ticket SAV proche de son délai'), ('chat_message', 'Nouveau message'), ('chat_mention', 'Vous avez été mentionné'), ('digest', 'Récapitulatif')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('lead_assigned', 'Nouveau lead assigné'), ('lead_new', 'Nouveau lead site web'), ('devis_accepted', 'Devis accepté'), ('devis_opened', 'Proposition ouverte par le client'), ('chantier_due', 'Chantier à installer'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie bientôt expirée'), ('maintenance_due', 'Visite de maintenance due'), ('stock_low', 'Stock bas'), ('sav_ticket_opened', 'Ticket SAV ouvert'), ('sav_ticket_breaching', 'Ticket SAV proche de son délai'), ('chat_message', 'Nouveau message'), ('chat_mention', 'Vous avez été mentionné'), ('digest', 'Récapitulatif')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationroutingrule',
            name='event_type',
            field=models.CharField(choices=[('lead_assigned', 'Nouveau lead assigné'), ('lead_new', 'Nouveau lead site web'), ('devis_accepted', 'Devis accepté'), ('devis_opened', 'Proposition ouverte par le client'), ('chantier_due', 'Chantier à installer'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie bientôt expirée'), ('maintenance_due', 'Visite de maintenance due'), ('stock_low', 'Stock bas'), ('sav_ticket_opened', 'Ticket SAV ouvert'), ('sav_ticket_breaching', 'Ticket SAV proche de son délai'), ('chat_message', 'Nouveau message'), ('chat_mention', 'Vous avez été mentionné'), ('digest', 'Récapitulatif')], max_length=40, verbose_name="Type d'événement"),
        ),
    ]
