# Generated by Django 5.1.4 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_xflt18_budget_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='annonce',
            new_name='notificatio_company_453631_idx',
            old_name='notificatio_company_0f3808_idx',
        ),
        migrations.RenameIndex(
            model_name='annonce',
            new_name='notificatio_company_2b1d3d_idx',
            old_name='notificatio_company_e22080_idx',
        ),
        migrations.RenameIndex(
            model_name='annonce',
            new_name='notificatio_company_465a02_idx',
            old_name='notificatio_company_a08c51_idx',
        ),
        migrations.RenameIndex(
            model_name='annoncelecture',
            new_name='notificatio_company_e93e5b_idx',
            old_name='notificatio_company_92a841_idx',
        ),
        migrations.RenameIndex(
            model_name='annoncerelance',
            new_name='notificatio_company_54ffef_idx',
            old_name='notificatio_company_fa7d15_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalreminderstate',
            new_name='notificatio_company_2af78a_idx',
            old_name='notificatio_company_5429ae_idx',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annoncelecture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='annoncerelance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='approvalreminderconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='approvalreminderstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('lead_assigned', 'Nouveau lead assigné'), ('lead_new', 'Nouveau lead site web'), ('devis_accepted', 'Devis accepté'), ('devis_opened', 'Proposition ouverte par le client'), ('client_contact_request', 'Client souhaite être contacté'), ('devis_superior_contact_requested', 'Avis du supérieur demandé sur un devis'), ('chantier_due', 'Chantier à installer'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie bientôt expirée'), ('maintenance_due', 'Visite de maintenance due'), ('stock_low', 'Stock bas'), ('sav_ticket_opened', 'Ticket SAV ouvert'), ('sav_ticket_breaching', 'Ticket SAV proche de son délai'), ('chat_message', 'Nouveau message'), ('chat_mention', 'Vous avez été mentionné'), ('digest', 'Récapitulatif'), ('annonce_published', 'Nouvelle annonce interne'), ('annonce_read_reminder', 'Relance lecture obligatoire'), ('approval_requested', 'Approbation demandée'), ('approval_decided', 'Approbation décidée'), ('approval_reminder', "Relance d'approbation"), ('approval_escalated', 'Approbation escaladée'), ('supplier_doc_expiring', 'Document fournisseur bientôt expiré'), ('bcf_late', 'Bon de commande fournisseur en retard'), ('projet_retard', 'Retard planning projet'), ('flotte_budget_depassement', 'Dépassement budget flotte')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('lead_assigned', 'Nouveau lead assigné'), ('lead_new', 'Nouveau lead site web'), ('devis_accepted', 'Devis accepté'), ('devis_opened', 'Proposition ouverte par le client'), ('client_contact_request', 'Client souhaite être contacté'), ('devis_superior_contact_requested', 'Avis du supérieur demandé sur un devis'), ('chantier_due', 'Chantier à installer'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie bientôt expirée'), ('maintenance_due', 'Visite de maintenance due'), ('stock_low', 'Stock bas'), ('sav_ticket_opened', 'Ticket SAV ouvert'), ('sav_ticket_breaching', 'Ticket SAV proche de son délai'), ('chat_message', 'Nouveau message'), ('chat_mention', 'Vous avez été mentionné'), ('digest', 'Récapitulatif'), ('annonce_published', 'Nouvelle annonce interne'), ('annonce_read_reminder', 'Relance lecture obligatoire'), ('approval_requested', 'Approbation demandée'), ('approval_decided', 'Approbation décidée'), ('approval_reminder', "Relance d'approbation"), ('approval_escalated', 'Approbation escaladée'), ('supplier_doc_expiring', 'Document fournisseur bientôt expiré'), ('bcf_late', 'Bon de commande fournisseur en retard'), ('projet_retard', 'Retard planning projet'), ('flotte_budget_depassement', 'Dépassement budget flotte')], max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationroutingrule',
            name='event_type',
            field=models.CharField(choices=[('lead_assigned', 'Nouveau lead assigné'), ('lead_new', 'Nouveau lead site web'), ('devis_accepted', 'Devis accepté'), ('devis_opened', 'Proposition ouverte par le client'), ('client_contact_request', 'Client souhaite être contacté'), ('devis_superior_contact_requested', 'Avis du supérieur demandé sur un devis'), ('chantier_due', 'Chantier à installer'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie bientôt expirée'), ('maintenance_due', 'Visite de maintenance due'), ('stock_low', 'Stock bas'), ('sav_ticket_opened', 'Ticket SAV ouvert'), ('sav_ticket_breaching', 'Ticket SAV proche de son délai'), ('chat_message', 'Nouveau message'), ('chat_mention', 'Vous avez été mentionné'), ('digest', 'Récapitulatif'), ('annonce_published', 'Nouvelle annonce interne'), ('annonce_read_reminder', 'Relance lecture obligatoire'), ('approval_requested', 'Approbation demandée'), ('approval_decided', 'Approbation décidée'), ('approval_reminder', "Relance d'approbation"), ('approval_escalated', 'Approbation escaladée'), ('supplier_doc_expiring', 'Document fournisseur bientôt expiré'), ('bcf_late', 'Bon de commande fournisseur en retard'), ('projet_retard', 'Retard planning projet'), ('flotte_budget_depassement', 'Dépassement budget flotte')], max_length=40, verbose_name="Type d'événement"),
        ),
    ]
