# Generated by Django 5.1.4 on 2026-07-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('notifications', '0025_alter_notification_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessagelog',
            name='campagne_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Id de la campagne (opaque)'),
        ),
        migrations.AddIndex(
            model_name='whatsappmessagelog',
            index=models.Index(fields=['company', 'campagne_id'], name='nwa_log_company_campagne_idx'),
        ),
    ]
