# Generated by Django 5.1.4 on 2026-09-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0053_cht9_desenchevetrement_chantier_due'),
        ('notifications', '0054_eventtype_visite_assignee'),
    ]

    operations = [
    ]
