# Generated by Django 5.2.14 on 2026-05-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_alter_customuser_groups_and_more'),
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bons_commande', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='devis',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='facture',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='authentication.company'),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devis',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='facture',
            name='reference',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='boncommande',
            unique_together={('company', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='devis',
            unique_together={('company', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='facture',
            unique_together={('company', 'reference')},
        ),
    ]
