# Generated by Django 5.1.4 on 2026-06-12 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_client_lead_ete_differente_lead_facture_ete_and_more'),
        ('ventes', '0002_boncommande_company_devis_company_facture_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='crm.lead'),
        ),
    ]
