# Generated by Django 5.1.4 on 2026-06-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_devis_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='etude_params',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='mode_installation',
            field=models.CharField(blank=True, choices=[('residentiel', 'Résidentiel'), ('industriel', 'Industriel / Commercial'), ('agricole', 'Agricole (pompage)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='devis',
            name='prix_cible_kwc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
