# Generated by Django 5.1.4 on 2026-06-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0004_devis_etude_params_devis_mode_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignedevis',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux TVA de la ligne (%). Vide = taux global du devis.', max_digits=5, null=True),
        ),
    ]
