# Generated by Django 5.1.4 on 2026-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_facture_devis_facture_libelle_facture_montant_ht_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignefacture',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux TVA de la ligne (%). Vide = taux global de la facture.', max_digits=5, null=True),
        ),
    ]
