# Generated by Django 5.1.4 on 2026-06-14 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_avatar_key_customuser_poste'),
        ('crm', '0012_lead_perdu'),
        ('stock', '0013_backfill_garantie_onduleurs'),
        ('ventes', '0007_lignefacture_taux_tva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('emise', 'Émis'), ('annulee', 'Annulé')], default='emise', max_length=20)),
                ('motif', models.TextField(blank=True, default='')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('remise_globale', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('montant_ht', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fichier_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='crm.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avoirs', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avoirs_crees', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs', to='ventes.facture')),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-date_emission', '-id'],
                'unique_together': {('company', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='LigneAvoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avoir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.avoir')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_avoir', to='stock.produit')),
            ],
            options={
                'verbose_name': "Ligne d'avoir",
                'verbose_name_plural': "Lignes d'avoir",
            },
        ),
    ]
