# Generated by Django 5.1.4 on 2026-06-14 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_avatar_key_customuser_poste'),
        ('ventes', '0008_avoir_ligneavoir'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='exclu_relances',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='prochaine_relance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FollowupLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('nom', models.CharField(max_length=120)),
                ('delai_jours', models.PositiveIntegerField(default=7)),
                ('message', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followup_levels', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Niveau de relance',
                'ordering': ['delai_jours', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='RelanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.PositiveIntegerField(blank=True, null=True)),
                ('niveau_nom', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relance_logs', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_effectuees', to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='ventes.facture')),
            ],
            options={
                'verbose_name': 'Relance',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
