# Generated by Django 5.1.4 on 2026-06-16 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0011_sharelink"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remplace",
                to="ventes.devis",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="devis",
            name="version_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions_enfants",
                to="ventes.devis",
            ),
        ),
    ]
