# Generated by Django 5.1.4 on 2026-06-16 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ventes",
            "0012_devis_remise_approuvee_le_devis_remise_approuvee_par_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="accepte_par_nom",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="devis",
            name="accepte_par_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devis_acceptes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="bon_pour_accord",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_acceptation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facture",
            name="conditions_paiement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="facture",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
    ]
