# Generated by Django 5.1.4 on 2026-06-16 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0012_devis_is_active_devis_superseded_by_devis_version_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="remise_approuvee",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="devis",
            name="remise_approuvee_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remises_approuvees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
