# Generated by Django 5.1.4 on 2026-06-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0013_devis_remise_approuvee_devis_remise_approuvee_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="conditions_paiement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="facture",
            name="date_livraison",
            field=models.DateField(blank=True, null=True),
        ),
    ]
