# Generated by Django 5.1.4 on 2026-06-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0014_facture_conformite_article145"),
    ]

    operations = [
        migrations.AddField(
            model_name="facture",
            name="statut_teledeclaration",
            field=models.CharField(
                choices=[
                    ("non_soumise", "Non soumise"),
                    ("soumise", "Soumise"),
                    ("validee", "Validée"),
                ],
                default="non_soumise",
                max_length=15,
            ),
        ),
    ]
