# Generated by Django 5.1.4 on 2026-06-19 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("crm", "0017_parrainage"),
        ("ventes", "0018_devis_option_acceptee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("sortant", "Sortant"), ("entrant", "Entrant")],
                        default="sortant",
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("envoye", "Envoyé"),
                            ("echec", "Échec"),
                            ("recu", "Reçu"),
                        ],
                        default="envoye",
                        max_length=10,
                    ),
                ),
                ("to_email", models.CharField(blank=True, default="", max_length=254)),
                (
                    "from_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("sujet", models.CharField(blank=True, default="", max_length=300)),
                ("corps", models.TextField(blank=True, default="")),
                ("reference", models.CharField(blank=True, default="", max_length=80)),
                (
                    "piece_jointe",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("erreur", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="crm.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="ventes.devis",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_logs",
                        to="ventes.facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["client", "-created_at"], name="ventes_emaillog_cli_idx"
                    ),
                    models.Index(
                        fields=["facture", "-created_at"],
                        name="ventes_emaillog_fac_idx",
                    ),
                ],
            },
        ),
    ]
