# Generated by Django 5.1.4 on 2026-06-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0020_factureactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="date_refus",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="motif_refus",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
