# Generated by Django 5.1.4 on 2026-06-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0021_fg44_devis_refus_motif"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="acompte_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant TTC de la première tranche. Calculé ou saisi.",
                max_digits=12,
                null=True,
                verbose_name="Acompte (MAD TTC)",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="acompte_pct",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pourcentage de la première tranche. Persiste la valeur choisie.",
                max_digits=5,
                null=True,
                verbose_name="Acompte (%)",
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="echeancier",
            field=models.JSONField(
                blank=True,
                help_text="Liste ordonnée de tranches [{libelle, type, pct_or_montant}]. Vide = 3 tranches par défaut.",
                null=True,
                verbose_name="Échéancier personnalisé",
            ),
        ),
    ]
