# Generated by Django 5.1.4 on 2026-06-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0021_fg100_devis_custom_data"),
        ("ventes", "0022_fg46_devis_echeancier_acompte"),
    ]

    operations = []
