# Generated by Django 5.2.15 on 2026-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0023_merge_20260621_0546"),
    ]

    operations = [
        migrations.AddField(
            model_name="devis",
            name="roof_image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="devis",
            name="roof_layout",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
