# Generated by Django 5.1.4 on 2026-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventes", "0024_devis_roof_image_devis_roof_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="boncommande",
            name="date_livraison_reelle",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="boncommande",
            name="pv_livraison",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
