# Generated by Django 5.1.4 on 2026-06-22 14:32

import apps.ventes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("ventes", "0025_boncommande_date_livraison_reelle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.ventes.models._default_payment_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("provider", models.CharField(default="noop", max_length=40)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("paye", "Payé"),
                            ("expire", "Expiré"),
                            ("annule", "Annulé"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "provider_ref",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=apps.ventes.models._default_payment_expiry
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_links",
                        to="authentication.company",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_links",
                        to="ventes.facture",
                    ),
                ),
                (
                    "paiement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_links",
                        to="ventes.paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien de paiement",
                "verbose_name_plural": "Liens de paiement",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["token"], name="ventes_paym_token_d35b85_idx")
                ],
            },
        ),
    ]
