# Generated by Django 5.1.4 on 2026-06-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0035_qj4_devisnudgelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devisnudgelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devispreset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
