# Generated by Django 5.1.4 on 2026-06-30 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0033_fg318_contrat_prix'),
        ('ventes', '0044_fg275_iv_curve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsBuiltPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=160, null=True, verbose_name='Titre du dossier')),
                ('pieces', models.JSONField(blank=True, default=list, verbose_name='Pièces assemblées (plans/schéma/datasheets/séries/photos/PV)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asbuilt_packs', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asbuilt_packs', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asbuilt_packs_crees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asbuilt_packs', to='ventes.devis', verbose_name='Devis')),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asbuilt_packs', to='ventes.commissioningtest', verbose_name='Fiche de recette')),
            ],
            options={
                'verbose_name': 'Pack as-built',
                'verbose_name_plural': 'Packs as-built',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'chantier'], name='ix_asbuilt_comp_chant')],
            },
        ),
        migrations.CreateModel(
            name='AttestationConformite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40, null=True, verbose_name='Référence attestation')),
                ('referentiel', models.CharField(blank=True, max_length=160, null=True, verbose_name='Référentiel (NF C 15-100 / IEC 62446 …)')),
                ('mesures', models.JSONField(blank=True, default=list, verbose_name='Mesures relevées')),
                ('signataire_nom', models.CharField(blank=True, max_length=120, null=True, verbose_name='Signataire')),
                ('signataire_qualite', models.CharField(blank=True, max_length=120, null=True, verbose_name='Qualité du signataire')),
                ('signataire_habilitation', models.CharField(blank=True, max_length=80, null=True, verbose_name="N° d'habilitation")),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('annulee', 'Annulée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_conformite', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_conformite', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_conformite_crees', to=settings.AUTH_USER_MODEL)),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_conformite', to='ventes.commissioningtest', verbose_name='Fiche de recette')),
            ],
            options={
                'verbose_name': 'Attestation de conformité',
                'verbose_name_plural': 'Attestations de conformité',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='ix_attconf_comp_statut')],
            },
        ),
        migrations.CreateModel(
            name='AttestationRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=40, null=True, verbose_name='Référence attestation')),
                ('periode_debut', models.DateField(blank=True, null=True, verbose_name='Période début')),
                ('periode_fin', models.DateField(blank=True, null=True, verbose_name='Période fin')),
                ('energie_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Énergie renouvelable produite (kWh)')),
                ('facteur_co2_kg_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Facteur réseau (kg CO₂/kWh)')),
                ('co2_evite_t', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='CO₂ évité (t)')),
                ('signataire_nom', models.CharField(blank=True, max_length=120, null=True, verbose_name='Signataire')),
                ('date_emission', models.DateField(blank=True, null=True, verbose_name="Date d'émission")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('annulee', 'Annulée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_re', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_re', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_re_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Attestation d'énergie renouvelable",
                'verbose_name_plural': "Attestations d'énergie renouvelable",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='ix_attre_comp_statut')],
            },
        ),
        migrations.CreateModel(
            name='TestPerformanceReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_mesure', models.DateField(blank=True, null=True, verbose_name='Date de mesure')),
                ('energie_mesuree_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Énergie mesurée (kWh)')),
                ('energie_attendue_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Énergie attendue (kWh)')),
                ('pr_mesure', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='PR mesuré')),
                ('pr_attendu', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='PR attendu')),
                ('pr_seuil_acceptation', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name="PR seuil d'acceptation")),
                ('ecart_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Écart PR (%)')),
                ('verdict', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé (sous le seuil)')], default='en_attente', max_length=12, verbose_name='Verdict')),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_pr_reception', to='installations.installation', verbose_name='Chantier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_pr_reception', to='authentication.company', verbose_name='Société')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_pr_reception_crees', to=settings.AUTH_USER_MODEL)),
                ('recette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests_pr_reception', to='ventes.commissioningtest', verbose_name='Fiche de recette')),
            ],
            options={
                'verbose_name': 'Test de performance de réception (PR)',
                'verbose_name_plural': 'Tests de performance de réception (PR)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'verdict'], name='ix_prrec_comp_verdict')],
            },
        ),
    ]
