# Generated by Django 5.1.4 on 2026-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0067_zfac8_parametrage_relance_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandatpaiement',
            name='expiration_mois',
            field=models.CharField(blank=True, default='', help_text='MM/AAAA, affichage seulement.', max_length=7),
        ),
        migrations.AlterField(
            model_name='remiseencaissement',
            name='montant_declare',
            field=models.DecimalField(decimal_places=2, help_text='Montant total déclaré par le technicien pour cette collecte (avant rapprochement des lignes).', max_digits=12),
        ),
    ]
