# Generated by Django 5.1.4 on 2026-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0073_xsal16_sharelink_engagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='abandon_motif',
            field=models.CharField(blank=True, choices=[('irrecouvrable', 'Irrécouvrable'), ('geste_commercial', 'Geste commercial'), ('ecart_reglement', 'Écart de règlement'), ('liquidation', 'Liquidation'), ('arrondi_caisse', 'Arrondi espèces')], default='', max_length=20),
        ),
    ]
