# Generated by Django 5.1.4 on 2026-07-10 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_company_benchmarking_opt_in'),
        ('crm', '0049_qw10_lead_dedup_indexes_concurrent'),
        ('ventes', '0075_sca39_index_devis_facture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text="Clé d'idempotence (déduplication webhook PSP) — unique par société quand renseignée.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='provider_ref',
            field=models.CharField(blank=True, help_text="Référence du prestataire de paiement (PSP) — vide tant qu'aucune intégration ne renseigne ce paiement.", max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='paiement',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False), models.Q(('idempotency_key', ''), _negated=True)), fields=('company', 'idempotency_key'), name='uniq_paiement_idempotency_par_societe'),
        ),
    ]
