# Generated by Django 5.1.4 on 2026-07-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0076_sca45_paiement_provider_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='prix_par_kwc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prix TTC au kWc, dérivé et gelé à la création (interne générateur/BI — jamais sur un PDF/sortie client).', max_digits=10, null=True),
        ),
    ]
