# Generated by Django 5.1.4 on 2026-07-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0057_conditionpaiement'),
        ('ventes', '0077_sca47_devis_prix_par_kwc'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='condition_paiement_ref',
            field=models.ForeignKey(blank=True, help_text='Condition du référentiel Paramètres — source du libellé par défaut. Le texte libre reste surchargeable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='parametres.conditionpaiement', verbose_name='Condition de paiement (référentiel)'),
        ),
    ]
