# Generated by Django 5.1.4 on 2026-07-17 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0088_ntcpq4_listeprix_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooflayout',
            name='devis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventes_roof_layouts', to='ventes.devis', verbose_name='Devis'),
        ),
    ]
