# Generated by Django 5.1.4 on 2026-07-31 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0081_protect_produit_donnees_reelles'),
        ('ventes', '0089_alter_rooflayout_devis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetechnique',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiches_techniques', to='stock.produit', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='ligneprixliste',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_liste_prix', to='stock.produit'),
        ),
        migrations.AlterField(
            model_name='reglelisteprix',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='regles_liste_prix', to='stock.produit'),
        ),
    ]
