# Generated by Django 5.1.4 on 2026-08-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0092_ntadm2_devis_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='clauses_appliquees',
            field=models.JSONField(blank=True, help_text="Snapshot [{clause_id, nom, corps_texte, type_deal, ordre}] figé au moment de l'envoi. Jamais recalculé ensuite.", null=True, verbose_name="Clauses/CGV appliquées (figées à l'envoi)"),
        ),
    ]
