# Generated by Django 5.1.4 on 2026-08-13 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0093_ntcpq11_clause_cgv'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='devis_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renouvellements', to='ventes.devis', verbose_name="Devis d'origine (renouvellement)"),
        ),
        migrations.AddField(
            model_name='devis',
            name='numero_renouvellement',
            field=models.PositiveIntegerField(default=0, help_text="0 = devis d'origine ; 1, 2… = renouvellements successifs.", verbose_name='N° de renouvellement'),
        ),
    ]
