# Generated by Django 5.1.4 on 2026-08-13 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('ventes', '0094_ntcpq13_renouvellement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='variante_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes_cpq', to='ventes.devis', verbose_name='Variante de (devis de base)'),
        ),
        migrations.AddField(
            model_name='devis',
            name='variante_tier',
            field=models.CharField(blank=True, default='', help_text='economique / standard / premium. Vide = devis normal.', max_length=20, verbose_name='Tier de la variante'),
        ),
        migrations.CreateModel(
            name='LotDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom_lot', models.CharField(max_length=150)),
                ('adresse_site', models.CharField(blank=True, default='', max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_lots', to='authentication.company')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Lot de devis',
                'verbose_name_plural': 'Lots de devis',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='ventes.lotdevis', verbose_name='Lot (site/bâtiment)'),
        ),
        migrations.CreateModel(
            name='PalierRemiseVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie_nom', models.CharField(blank=True, default='', help_text='Catégorie visée (nom). Vide = tout le catalogue.', max_length=150)),
                ('quantite_min', models.DecimalField(decimal_places=2, default=1, help_text='Quantité minimale pour que le palier se déclenche.', max_digits=10)),
                ('remise_pct', models.DecimalField(decimal_places=2, default=0, help_text='Remise accordée par ce palier (%).', max_digits=5)),
                ('priorite', models.PositiveIntegerField(default=0, help_text='Ordre de la cascade (plus haut = appliqué en premier).')),
                ('cumulable', models.BooleanField(default=False, help_text="Le palier s'ajoute à la remise de ligne (cascade globale) quand plusieurs catégories atteignent leur seuil.")),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_remise_volume', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Palier de remise volume',
                'verbose_name_plural': 'Paliers de remise volume',
                'ordering': ['-priorite', '-quantite_min', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AvenantDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lignes_ajoutees', models.JSONField(blank=True, default=list)),
                ('lignes_retirees', models.JSONField(blank=True, default=list)),
                ('motif', models.TextField(blank=True, default='')),
                ('taux_remise_global', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de remise global du devis APRÈS avenant (%).', max_digits=6, null=True)),
                ('approbation_requise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_avenants', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_avenants', to='authentication.company')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avenants', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Avenant de devis',
                'verbose_name_plural': 'Avenants de devis',
                'ordering': ['-date_creation', '-id'],
                'indexes': [models.Index(fields=['company', 'devis'], name='ventes_avenant_co_dv')],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationDevisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenu', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_config_snapshots', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_config_snapshots', to='authentication.company')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshots', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Instantané de configuration de devis',
                'verbose_name_plural': 'Instantanés de configuration de devis',
                'ordering': ['date_creation', 'id'],
                'indexes': [models.Index(fields=['devis', 'date_creation'], name='ventes_cfgsnap_dv_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='lotdevis',
            constraint=models.UniqueConstraint(fields=('devis', 'nom_lot'), name='ventes_lotdevis_unique_devis_nom'),
        ),
        migrations.AddIndex(
            model_name='palierremisevolume',
            index=models.Index(fields=['company', 'actif'], name='ventes_palvol_co_actif'),
        ),
    ]
