# Generated by Django 5.1.4 on 2026-08-13 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('ventes', '0094_ntcpq13_renouvellement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvenantDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lignes_ajoutees', models.JSONField(blank=True, default=list)),
                ('lignes_retirees', models.JSONField(blank=True, default=list)),
                ('motif', models.TextField(blank=True, default='')),
                ('taux_remise_global', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de remise global du devis APRÈS avenant (%).', max_digits=6, null=True)),
                ('approbation_requise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_avenants', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_avenants', to='authentication.company')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avenants', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Avenant de devis',
                'verbose_name_plural': 'Avenants de devis',
                'ordering': ['-date_creation', '-id'],
                'indexes': [models.Index(fields=['company', 'devis'], name='ventes_avenant_co_dv')],
            },
        ),
    ]
