# Generated by Django 5.1.4 on 2026-08-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0095_ntcpq14_avenant_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='variante_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variantes_cpq', to='ventes.devis', verbose_name='Variante de (devis de base)'),
        ),
        migrations.AddField(
            model_name='devis',
            name='variante_tier',
            field=models.CharField(blank=True, default='', help_text='economique / standard / premium. Vide = devis normal.', max_length=20, verbose_name='Tier de la variante'),
        ),
    ]
