# Generated by Django 5.1.4 on 2026-08-13 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('ventes', '0096_ntcpq16_variantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalierRemiseVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_nom', models.CharField(blank=True, default='', help_text='Catégorie visée (nom). Vide = tout le catalogue.', max_length=150)),
                ('quantite_min', models.DecimalField(decimal_places=2, default=1, help_text='Quantité minimale pour que le palier se déclenche.', max_digits=10)),
                ('remise_pct', models.DecimalField(decimal_places=2, default=0, help_text='Remise accordée par ce palier (%).', max_digits=5)),
                ('priorite', models.PositiveIntegerField(default=0, help_text='Ordre de la cascade (plus haut = appliqué en premier).')),
                ('cumulable', models.BooleanField(default=False, help_text="Le palier s'ajoute à la remise de ligne (cascade globale) quand plusieurs catégories atteignent leur seuil.")),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paliers_remise_volume', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Palier de remise volume',
                'verbose_name_plural': 'Paliers de remise volume',
                'ordering': ['-priorite', '-quantite_min', 'id'],
                'indexes': [models.Index(fields=['company', 'actif'], name='ventes_palvol_co_actif')],
            },
        ),
    ]
