# Generated by Django 5.1.4 on 2026-08-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('ventes', '0097_ntcpq17_palier_remise_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_lot', models.CharField(max_length=150)),
                ('adresse_site', models.CharField(blank=True, default='', max_length=255)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_lots', to='authentication.company')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Lot de devis',
                'verbose_name_plural': 'Lots de devis',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lignedevis',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes', to='ventes.lotdevis', verbose_name='Lot (site/bâtiment)'),
        ),
        migrations.AddConstraint(
            model_name='lotdevis',
            constraint=models.UniqueConstraint(fields=('devis', 'nom_lot'), name='ventes_lotdevis_unique_devis_nom'),
        ),
    ]
