# Generated by Django 5.1.4 on 2026-08-13 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('ventes', '0098_ntcpq18_lot_devis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDevisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.JSONField(blank=True, default=dict)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_config_snapshots', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devis_config_snapshots', to='authentication.company')),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshots', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Instantané de configuration de devis',
                'verbose_name_plural': 'Instantanés de configuration de devis',
                'ordering': ['date_creation', 'id'],
                'indexes': [models.Index(fields=['devis', 'date_creation'], name='ventes_cfgsnap_dv_date')],
            },
        ),
    ]
