# Generated by Django 5.1.15 on 2026-09-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0117_stkcat23_lignedevis_role_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='date_signature_domicile',
            field=models.DateField(blank=True, help_text='Quelle date le client a-t-il écrite de sa main à côté de sa signature (loi 31-08 art. 47 al. 2) ?', null=True, verbose_name='Date écrite par le client'),
        ),
        migrations.AddField(
            model_name='boncommande',
            name='signe_au_domicile',
            field=models.BooleanField(default=False, help_text='Ce bon de commande a-t-il été signé chez le client (démarchage, loi 31-08 art. 45) ?', verbose_name='Signé au domicile du client'),
        ),
    ]
