# Generated by Django 5.1.15 on 2026-10-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0119_qacoh_violation_coherence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoofLayout',
        ),
    ]
