# Generated by Django 5.1.15 on 2026-10-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0127_ciq216_reference_commande_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='devissignature',
            name='ice_declare',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name="ICE déclaré à l'acceptation"),
        ),
        migrations.AddField(
            model_name='devissignature',
            name='raison_sociale',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name="Raison sociale de l'entreprise signataire"),
        ),
        migrations.AddField(
            model_name='devissignature',
            name='signataire_qualite',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Qualité du signataire'),
        ),
    ]
