# Generated by Django 5.1.15 on 2026-10-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0129_ciq616_dossier_etape_exploitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatorydossier',
            name='accord_exploitation_le',
            field=models.DateField(blank=True, null=True, verbose_name="Accord d'exploitation reçu le"),
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='capacite_date',
            field=models.DateField(blank=True, null=True, verbose_name='Capacité réservée le'),
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='capacite_etat',
            field=models.CharField(blank=True, choices=[('provisoire', 'Réservée provisoirement'), ('definitive', 'Réservée définitivement')], max_length=12, null=True, verbose_name='Capacité réservée (art. 13)'),
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='convention_signee_le',
            field=models.DateField(blank=True, null=True, verbose_name='Convention de raccordement signée le (art. 14)'),
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='demande_exploitation_le',
            field=models.DateField(blank=True, null=True, verbose_name="Demande d'exploitation déposée le (art. 15-16)"),
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='etude_conclusion',
            field=models.CharField(blank=True, choices=[('favorable', 'Favorable'), ('alternative', 'Solution alternative proposée'), ('refus', 'Refus')], max_length=12, null=True, verbose_name="Conclusion de l'étude (art. 27)"),
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='etude_frais_notifies_le',
            field=models.DateField(blank=True, null=True, verbose_name="Frais d'étude notifiés le (art. 13)"),
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='etude_payee_le',
            field=models.DateField(blank=True, null=True, verbose_name='Étude payée le (art. 13)'),
        ),
        migrations.AddField(
            model_name='regulatorydossier',
            name='etude_reglages_imposes',
            field=models.BooleanField(blank=True, null=True, verbose_name="Réglages imposés par l'étude (art. 27)"),
        ),
    ]
