# Generated by Django 5.1.15 on 2026-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0130_ciq619_dossier_delais_decret'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatorydossier',
            name='equipements_figes',
            field=models.JSONField(blank=True, default=list, verbose_name='Équipements figés au dépôt'),
        ),
    ]
