# Generated by Django 5.1.4 on 2026-07-31 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0001_odx19_achats_split'),
        ('stock', '0081_protect_produit_donnees_reelles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prixfournisseur',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prix_fournisseurs', to='stock.produit'),
        ),
    ]
