# Generated by Django 5.1.4 on 2026-09-19 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0032_customuser_calendrier_hegirien'),
        ('crm', '0103_stkcat9_lead_structure_produit'),
        ('ventes', '0117_stkcat23_lignedevis_role_devis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calepinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Lead (identifiant)')),
                ('appel_offre_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name="Appel d'offres (identifiant)")),
                ('titre', models.CharField(blank=True, default='', max_length=200, verbose_name='Titre')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('perime', 'Périmé')], db_index=True, default='brouillon', max_length=12, verbose_name='Statut')),
                ('roof_layout', models.JSONField(blank=True, null=True, verbose_name='Conception (roof_layout)')),
                ('layout_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Empreinte du layout')),
                ('roof_image', models.CharField(blank=True, default='', max_length=500, verbose_name='Rendu (clé de stockage)')),
                ('version_moteur', models.CharField(blank=True, default='', max_length=40, verbose_name='Version du moteur')),
                ('resultat', models.JSONField(blank=True, null=True, verbose_name='Résultat du moteur')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calepinages', to='crm.client', verbose_name='Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calepinages_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calepinages', to='ventes.devis', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Calepinage',
                'verbose_name_plural': 'Calepinages',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CalepinageVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=160, verbose_name='Nom')),
                ('roof_layout', models.JSONField(blank=True, null=True, verbose_name='Conception')),
                ('layout_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte du layout')),
                ('resultat', models.JSONField(blank=True, null=True, verbose_name='Résultat du moteur')),
                ('retenue', models.BooleanField(default=False, verbose_name='Retenue')),
                ('calepinage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='calepinage.calepinage', verbose_name='Calepinage')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calepinage_variantes_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Variante de calepinage',
                'verbose_name_plural': 'Variantes de calepinage',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CalepinageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('roof_layout', models.JSONField(blank=True, null=True, verbose_name='Conception (gelée)')),
                ('layout_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='Empreinte du layout')),
                ('resultat', models.JSONField(blank=True, null=True, verbose_name='Résultat (gelé)')),
                ('calepinage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='calepinage.calepinage', verbose_name='Calepinage')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calepinage_versions_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
            ],
            options={
                'verbose_name': 'Version de calepinage',
                'verbose_name_plural': 'Versions de calepinage',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ParametresCalepinage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imagerie', models.JSONField(blank=True, default=dict, verbose_name='Imagerie et pays')),
                ('degagements', models.JSONField(blank=True, default=dict, verbose_name='Dégagements')),
                ('zones_types', models.JSONField(blank=True, default=dict, verbose_name='Zones types')),
                ('gabarits_disposition', models.JSONField(blank=True, default=dict, verbose_name='Gabarits de disposition')),
                ('presets', models.JSONField(blank=True, default=dict, verbose_name='Presets')),
                ('favoris_materiel', models.JSONField(blank=True, default=dict, verbose_name='Favoris matériel')),
                ('gabarits_dossier', models.JSONField(blank=True, default=dict, verbose_name='Gabarits de dossier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Réglages de calepinage',
                'verbose_name_plural': 'Réglages de calepinage',
            },
        ),
        migrations.AddIndex(
            model_name='calepinage',
            index=models.Index(fields=['company', 'statut'], name='cal_cal_co_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='calepinage',
            index=models.Index(fields=['company', 'lead_id'], name='cal_cal_co_lead_idx'),
        ),
        migrations.AddIndex(
            model_name='calepinage',
            index=models.Index(fields=['company', 'appel_offre_id'], name='cal_cal_co_ao_idx'),
        ),
        migrations.AddIndex(
            model_name='calepinage',
            index=models.Index(fields=['company', '-created_at'], name='cal_cal_co_cree_idx'),
        ),
        migrations.AddConstraint(
            model_name='calepinage',
            constraint=models.CheckConstraint(condition=models.Q(('lead_id__isnull', False), ('client__isnull', False), _connector='OR'), name='calepinage_lead_ou_client'),
        ),
        migrations.AddIndex(
            model_name='calepinagevariante',
            index=models.Index(fields=['calepinage', 'retenue'], name='cal_var_cal_ret_idx'),
        ),
        migrations.AddConstraint(
            model_name='calepinagevariante',
            constraint=models.UniqueConstraint(condition=models.Q(('retenue', True)), fields=('calepinage',), name='uniq_variante_retenue_par_calepinage'),
        ),
        migrations.AddIndex(
            model_name='calepinageversion',
            index=models.Index(fields=['calepinage', '-created_at'], name='cal_ver_cal_cree_idx'),
        ),
        migrations.AddConstraint(
            model_name='parametrescalepinage',
            constraint=models.UniqueConstraint(fields=('company',), name='uniq_parametres_calepinage_societe'),
        ),
    ]
