# Generated by Django 5.1.4 (hand-written, matches Django's deterministic
# CreateModel/AddIndex/AlterUniqueTogether shape) — XPLT5.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("publicapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("response_status", models.IntegerField()),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idempotency_records",
                        to="publicapi.apikey",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicapi_idempotency_records",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enregistrement d'idempotence (API publique)",
                "verbose_name_plural": "Enregistrements d'idempotence (API publique)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="idempotencyrecord",
            index=models.Index(
                fields=["company", "created_at"],
                name="publicapi_i_company_53dd3b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="idempotencyrecord",
            unique_together={("api_key", "endpoint", "idempotency_key")},
        ),
    ]
