# Generated by Django 5.1.4 on 2026-07-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapi', '0002_idempotencyrecord'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencyrecord',
            new_name='publicapi_i_company_033314_idx',
            old_name='publicapi_i_company_53dd3b_idx',
        ),
    ]
