# Generated by Django 5.1.4 on 2026-07-31 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('publicapi', '0012_ntapi23_apikey_expire_le'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('export', 'Export'), ('import', 'Import')], max_length=10)),
                ('entite', models.CharField(max_length=30)),
                ('statut', models.CharField(choices=[('en_file', 'En file'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('echec', 'Échec')], default='en_file', max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('resultat_file_key', models.CharField(blank=True, default='', max_length=512)),
                ('erreurs_file_key', models.CharField(blank=True, default='', max_length=512)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('traites', models.PositiveIntegerField(default=0)),
                ('succes', models.PositiveIntegerField(default=0)),
                ('erreurs', models.PositiveIntegerField(default=0)),
                ('cursor', models.PositiveIntegerField(default=0)),
                ('message_erreur', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_jobs', to='publicapi.apikey')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_jobs', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Job bulk (API publique)',
                'verbose_name_plural': 'Jobs bulk (API publique)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='publicapi_bulkjob_co_st_idx')],
            },
        ),
    ]
