# Generated by Django 5.1.4 on 2026-08-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceVeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Identifiant stable de la source (ex. « pmmp »).', max_length=40, verbose_name='Code')),
                ('libelle', models.CharField(max_length=160, verbose_name='Libellé')),
                ('type_source', models.CharField(choices=[('portail_officiel', 'Portail officiel (PMMP)'), ('saisie_manuelle', 'Saisie manuelle'), ('import_csv', 'Import de fichier'), ('portail_sectoriel', 'Portail sectoriel (EEP)'), ('agregateur', 'Agrégateur commercial'), ('tuyau_partenaire', 'Tuyau partenaire')], default='saisie_manuelle', max_length=32, verbose_name='Type de source')),
                ('url_base', models.URLField(blank=True, default='', help_text="Racine de la source, quand elle en a une. C'est le SEUL endroit où une URL de portail est écrite — jamais dans le collecteur.", max_length=300, verbose_name='URL de base')),
                ('actif', models.BooleanField(default=False, help_text="Interrupteur d'arrêt : une source inactive n'est jamais interrogée ni collectée.", verbose_name='Active')),
                ('cadence_heures', models.PositiveIntegerField(default=24, help_text='Délai minimal entre deux collectes de cette source.', verbose_name='Cadence (heures)')),
                ('derniere_collecte_reussie', models.DateTimeField(blank=True, null=True, verbose_name='Dernière collecte réussie')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Source de veille',
                'verbose_name_plural': 'Sources de veille',
                'ordering': ['libelle', 'id'],
                'indexes': [models.Index(fields=['company', 'actif'], name='veille_ao_src_co_actif_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='veille_ao_source_co_code_uniq')],
            },
        ),
    ]
