# Generated by Django 5.1.4 on 2026-08-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('veille_ao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_consultation', models.CharField(blank=True, default='', max_length=60, verbose_name='Référence de consultation')),
                ('org_acronyme', models.CharField(blank=True, default='', max_length=60, verbose_name="Acronyme de l'organisme")),
                ('reference_avis', models.CharField(blank=True, default='', max_length=120, verbose_name="Référence de l'avis")),
                ('objet', models.TextField(verbose_name='Objet')),
                ('acheteur', models.CharField(blank=True, default='', max_length=255, verbose_name='Acheteur public')),
                ('lieu', models.CharField(blank=True, default='', max_length=255, verbose_name="Lieu d'exécution")),
                ('region', models.CharField(blank=True, default='', max_length=120, verbose_name='Région')),
                ('procedure', models.CharField(blank=True, default='', max_length=160, verbose_name='Procédure')),
                ('categorie', models.CharField(choices=[('travaux', 'Travaux'), ('fournitures', 'Fournitures'), ('services', 'Services'), ('autre', 'Autre / non précisée')], default='autre', max_length=20, verbose_name='Catégorie')),
                ('lot', models.CharField(blank=True, default='', max_length=160, verbose_name='Lot')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Publié le')),
                ('date_limite_remise', models.DateTimeField(blank=True, null=True, verbose_name='Date limite de remise')),
                ('date_ouverture', models.DateTimeField(blank=True, null=True, verbose_name="Date d'ouverture des plis")),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant estimé (MAD)')),
                ('caution_provisoire', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Caution provisoire (MAD)')),
                ('url_detail', models.URLField(blank=True, default='', max_length=500, verbose_name='URL de la page de détail')),
                ('mots_cles_declenches', models.JSONField(blank=True, default=list, help_text="La liste des mots qui ont fait remonter l'avis : l'utilisateur doit voir POURQUOI il le voit.", verbose_name='Mots-clés déclenchés')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('retenu', 'Retenu'), ('ignore', 'Ignoré'), ('converti', "Converti en appel d'offres"), ('expire', 'Expiré')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('appel_offre_id', models.PositiveIntegerField(blank=True, help_text='Entier OPAQUE vers apps.ao — jamais une clé étrangère : les deux apps restent découplées.', null=True, verbose_name="Appel d'offres créé")),
                ('donnees_brutes', models.JSONField(blank=True, default=dict, help_text='Ce qui a été lu tel quel, pour pouvoir rejouer une analyse sans retourner sur la source.', verbose_name='Données brutes')),
                # VAO11 — empreinte de dédoublonnage de niveau 2. Posée DANS
                # le CreateModel (et non par un AddIndex ultérieur) : l'app
                # est neuve et jamais déployée, la table naît donc avec son
                # index — aucun verrou d'écriture sur une table vivante.
                ('empreinte', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Empreinte')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avis', to='veille_ao.sourceveille', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Avis de marché',
                'verbose_name_plural': 'Avis de marché',
                'ordering': ['-date_publication', '-id'],
                'indexes': [models.Index(fields=['company', 'statut'], name='veille_ao_avis_co_statut_idx'), models.Index(fields=['company', 'date_limite_remise'], name='veille_ao_avis_co_limite_idx'), models.Index(fields=['company', '-score'], name='veille_ao_avis_co_score_idx'), models.Index(fields=['company', 'empreinte'], name='veille_ao_avis_co_empr_idx')],
                # VAO11 — dédoublonnage de NIVEAU 1 : l'identité propre du
                # portail. PARTIELLE : une saisie manuelle ou un import n'a
                # aucun identifiant de portail et entrerait sinon en
                # collision sur la chaîne vide.
                'constraints': [models.UniqueConstraint(condition=models.Q(('ref_consultation', ''), _negated=True), fields=('company', 'source', 'ref_consultation', 'org_acronyme'), name='veille_ao_avis_identite_portail_uniq')],
            },
        ),
    ]
