# Generated by Django 5.1.4 on 2026-08-07 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('veille_ao', '0002_vao8_avismarche'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotCleVeille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=120, verbose_name='Mot-clé')),
                ('niveau', models.CharField(choices=[('noyau', 'Noyau (précision haute)'), ('large', 'Large (bruit accepté)')], default='large', max_length=10, verbose_name='Niveau')),
                ('poids', models.PositiveIntegerField(default=3, help_text="Contribution du mot-clé au score de l'avis.", verbose_name='Poids')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Mot-clé de veille',
                'verbose_name_plural': 'Mots-clés de veille',
                'ordering': ['niveau', 'libelle', 'id'],
                'indexes': [models.Index(fields=['company', 'actif'], name='veille_ao_mc_co_actif_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'libelle'), name='veille_ao_motcle_co_libelle_uniq')],
            },
        ),
    ]
