# Generated by Django 5.1.4 on 2026-08-07 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('veille_ao', '0003_vao9_motcleveille'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portee', models.CharField(choices=[('acheteur', 'Acheteur'), ('libelle', "Mot de l'objet"), ('categorie', 'Catégorie'), ('region', 'Région')], max_length=20, verbose_name='Portée')),
                ('valeur', models.CharField(help_text="Ce qui est comparé : acheteur, mot de l'objet, catégorie ou région.", max_length=200, verbose_name='Valeur')),
                ('motif', models.CharField(help_text='Pourquoi cet arbitrage — en français, obligatoire.', max_length=255, verbose_name='Motif')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('compteur_application', models.PositiveIntegerField(default=0, help_text="Combien d'avis cette règle a filtrés — une règle qui ne sert jamais est une règle à supprimer.", verbose_name="Nombre d'applications")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Règle d'exclusion",
                'verbose_name_plural': "Règles d'exclusion",
                'ordering': ['portee', 'valeur', 'id'],
            },
        ),
        migrations.AddField(
            model_name='avismarche',
            name='regle_exclusion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis_ignores', to='veille_ao.regleexclusion', verbose_name="Règle d'exclusion appliquée"),
        ),
        migrations.AddIndex(
            model_name='regleexclusion',
            index=models.Index(fields=['company', 'actif'], name='veille_ao_regle_co_actif_idx'),
        ),
        migrations.AddConstraint(
            model_name='regleexclusion',
            constraint=models.UniqueConstraint(fields=('company', 'portee', 'valeur'), name='veille_ao_regle_co_portee_valeur_uniq'),
        ),
    ]
