# Generated by Django 5.1.4 on 2026-08-07 14:48

"""VAO29 — ``AcheteurCible`` : le carnet des acheteurs à DÉMARCHER.

Additive et revertable : un seul ``CreateModel``, index et contrainte nés
AVEC la table (aucun index posé sur une table vivante). Le lien vers le CRM
est un ENTIER opaque (``lead_id``), jamais une clé étrangère : c'est ce qui
garde ``veille_ao`` et ``crm`` découplés et le contrat import-linter vert.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('veille_ao', '0006_vao27_informateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcheteurCible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name="Nom de l'organisme")),
                ('type', models.CharField(choices=[('fondation', 'Fondation'), ('universite_privee', 'Université privée'), ('clinique', 'Clinique'), ('groupe_hotelier', 'Groupe hôtelier'), ('industriel', 'Industriel'), ('cooperative_agricole', 'Coopérative agricole'), ('promoteur', 'Promoteur'), ('collectivite', 'Collectivité')], default='fondation', max_length=32, verbose_name='Type')),
                ('contact', models.CharField(blank=True, default='', help_text='Nom, téléphone ou e-mail de la personne à joindre.', max_length=255, verbose_name='Contact')),
                ('dernier_contact', models.DateField(blank=True, null=True, verbose_name='Dernier contact')),
                ('prochaine_relance', models.DateField(blank=True, null=True, verbose_name='Prochaine relance')),
                ('statut_relation', models.CharField(choices=[('a_contacter', 'À contacter'), ('contacte', 'Contacté'), ('en_discussion', 'En discussion'), ('reference', 'Référencé (reçoit les consultations)'), ('client', 'Client'), ('sans_suite', 'Sans suite')], default='a_contacter', max_length=20, verbose_name='Statut de la relation')),
                ('lead_id', models.PositiveIntegerField(blank=True, help_text='Entier OPAQUE vers apps.crm — jamais une clé étrangère : les deux apps restent découplées.', null=True, verbose_name='Lead CRM')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Acheteur cible',
                'verbose_name_plural': 'Acheteurs cibles',
                'ordering': ['nom', 'id'],
                'indexes': [models.Index(fields=['company', 'prochaine_relance'], name='veille_ao_ach_co_relance_idx'), models.Index(fields=['company', 'statut_relation'], name='veille_ao_ach_co_statut_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'nom'), name='veille_ao_acheteur_co_nom_uniq')],
            },
        ),
    ]
