# Generated by Django 5.1.4 on 2026-07-17 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0024_company_est_demo_mode_presentation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Territoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120)),
                ('type_territoire', models.CharField(choices=[('geo', 'Géographique'), ('segment', 'Segment'), ('secteur', 'Secteur')], default='geo', max_length=10, verbose_name='Type')),
                ('criteres', models.JSONField(blank=True, help_text='Description libre des critères (région/ville/CP, type_installation, tranche CA) — informative.', null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territoires', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Territoire',
                'verbose_name_plural': 'Territoires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TerritoireRegle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre de priorité')),
                ('condition', models.JSONField(help_text='Arbre de conditions (core.rules FG367) évalué contre les attributs du lead entrant.')),
                ('actif', models.BooleanField(default=True)),
                ('territoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles', to='territoires.territoire')),
            ],
            options={
                'verbose_name': 'Règle de territoire',
                'verbose_name_plural': 'Règles de territoire',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TerritoireMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Vide = pas de quota, rotation équitable simple.', max_digits=5, null=True, verbose_name='Quota de rotation (%)')),
                ('nb_assignations', models.PositiveIntegerField(default=0)),
                ('dernier_assigne_at', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('territoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='territoires.territoire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territoires_membre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre de territoire',
                'verbose_name_plural': 'Membres de territoire',
                'ordering': ['id'],
                'unique_together': {('territoire', 'utilisateur')},
            },
        ),
    ]
