# Generated by Django 5.1.4 on 2026-07-17 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('exercice_comptable_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Exercice comptable (référence)')),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin', models.DateField(verbose_name='Fin')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert_saisie', 'Ouvert à la saisie'), ('en_validation', 'En validation'), ('clos', 'Clos')], default='brouillon', max_length=15, verbose_name='Statut')),
                ('type_cycle', models.CharField(choices=[('annuel', 'Annuel'), ('trimestriel', 'Trimestriel')], default='annuel', max_length=15, verbose_name='Type de cycle')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Cycle budgétaire',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_departements', to='fpa.departement', verbose_name='Département parent')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpa_departements_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Département',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='CommentaireVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois (1-12)')),
                ('texte', models.TextField(verbose_name='Explication')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpa_commentaires_variance', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_variance', to='fpa.cyclebudgetaire', verbose_name='Cycle budgétaire')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_variance', to='fpa.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Commentaire de variance',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneBudgetDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois (1-12)')),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant prévu')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budget', to='fpa.cyclebudgetaire', verbose_name='Cycle budgétaire')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budget', to='fpa.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Ligne de budget département',
                'ordering': ['departement', 'categorie', 'mois'],
            },
        ),
        migrations.CreateModel(
            name='MappingCategorieCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie FP&A')),
                ('compte_cgnc_prefixe', models.CharField(max_length=10, verbose_name='Préfixe de compte CGNC')),
                ('compte_cgnc_libelle', models.CharField(blank=True, default='', max_length=150, verbose_name='Libellé du compte')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Mapping catégorie ↔ compte CGNC',
                'ordering': ['categorie', 'compte_cgnc_prefixe'],
            },
        ),
        migrations.CreateModel(
            name='PrevisionGlissante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_reference', models.DateField(verbose_name='Mois de départ')),
                ('horizon_mois', models.PositiveSmallIntegerField(choices=[(12, '12 mois'), (18, '18 mois')], default=12, verbose_name='Horizon (mois)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsions_glissantes', to='fpa.departement', verbose_name='Département (vide = vue globale)')),
            ],
            options={
                'verbose_name': 'Prévision glissante',
                'ordering': ['-date_reference'],
            },
        ),
        migrations.CreateModel(
            name='LignePrevisionGlissante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mois_relatif', models.PositiveSmallIntegerField(verbose_name='Mois relatif (1..horizon)')),
                ('categorie', models.CharField(choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant prévu')),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('driver', 'Driver'), ('statistique', 'Statistique')], default='statistique', max_length=15, verbose_name='Source')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fpa.previsionglissante', verbose_name='Prévision glissante')),
            ],
            options={
                'verbose_name': 'Ligne de prévision glissante',
                'ordering': ['mois_relatif', 'categorie'],
            },
        ),
        migrations.CreateModel(
            name='HypotheseRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poste', models.CharField(max_length=150, verbose_name='Poste')),
                ('date_effet', models.DateField(verbose_name="Date d'effet")),
                ('salaire_brut_estime', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salaire brut estimé')),
                ('type_mouvement', models.CharField(choices=[('embauche', 'Embauche'), ('depart', 'Départ')], default='embauche', max_length=10, verbose_name='Type de mouvement')),
                ('statut', models.CharField(choices=[('hypothese', 'Hypothèse'), ('confirme', 'Confirmé')], default='hypothese', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses_recrutement', to='fpa.departement', verbose_name='Département')),
                ('prevision_glissante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypotheses_recrutement', to='fpa.previsionglissante', verbose_name='Prévision glissante liée')),
            ],
            options={
                'verbose_name': 'Hypothèse de recrutement',
                'ordering': ['date_effet'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('archive', 'Archivé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('est_scenario_base', models.BooleanField(default=False, verbose_name='Scénario de base')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='fpa.cyclebudgetaire', verbose_name='Cycle budgétaire')),
            ],
            options={
                'verbose_name': 'Scénario budgétaire',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(blank=True, choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Catégorie ciblée (si pas une ligne précise)')),
                ('delta_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Delta %% (ex. -10)')),
                ('delta_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Delta montant absolu')),
                ('raison', models.CharField(blank=True, default='', max_length=255, verbose_name='Raison')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ligne_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deltas_scenario', to='fpa.lignebudgetdepartement', verbose_name='Ligne budget de référence (optionnel)')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fpa.scenariobudgetaire', verbose_name='Scénario')),
            ],
            options={
                'verbose_name': 'Ligne de scénario',
            },
        ),
        migrations.CreateModel(
            name='SoumissionBudgetDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_saisie', 'En saisie'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_saisie', max_length=10, verbose_name='Statut')),
                ('motif_rejet', models.TextField(blank=True, default='', verbose_name='Motif de rejet')),
                ('soumis_le', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='fpa.cyclebudgetaire', verbose_name='Cycle budgétaire')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_budget', to='fpa.departement', verbose_name='Département')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpa_budgets_soumis', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpa_budgets_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Soumission de budget département',
            },
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='fpa_departement_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='lignebudgetdepartement',
            constraint=models.UniqueConstraint(fields=('cycle', 'departement', 'categorie', 'mois'), name='fpa_ligne_budget_unique'),
        ),
        migrations.AddConstraint(
            model_name='lignebudgetdepartement',
            constraint=models.CheckConstraint(condition=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='fpa_ligne_budget_mois_valide'),
        ),
        migrations.AddConstraint(
            model_name='ligneprevisionglissante',
            constraint=models.UniqueConstraint(fields=('prevision', 'mois_relatif', 'categorie'), name='fpa_ligne_prevision_glissante_unique'),
        ),
        migrations.AddConstraint(
            model_name='scenariobudgetaire',
            constraint=models.UniqueConstraint(condition=models.Q(('est_scenario_base', True)), fields=('cycle',), name='fpa_un_seul_scenario_base_par_cycle'),
        ),
        migrations.AddConstraint(
            model_name='soumissionbudgetdepartement',
            constraint=models.UniqueConstraint(fields=('cycle', 'departement'), name='fpa_soumission_cycle_departement_unique'),
        ),
    ]
