# Generated by Django 5.1.4 on 2026-07-16 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('fpa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('exercice_comptable_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Exercice comptable (référence)')),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin', models.DateField(verbose_name='Fin')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('ouvert_saisie', 'Ouvert à la saisie'), ('en_validation', 'En validation'), ('clos', 'Clos')], default='brouillon', max_length=15, verbose_name='Statut')),
                ('type_cycle', models.CharField(choices=[('annuel', 'Annuel'), ('trimestriel', 'Trimestriel')], default='annuel', max_length=15, verbose_name='Type de cycle')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_cycles_budgetaires', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Cycle budgétaire',
                'ordering': ['-date_debut'],
            },
        ),
    ]
