# Generated by Django 5.1.4 on 2026-07-16 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('fpa', '0002_cyclebudgetaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneBudgetDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois (1-12)')),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant prévu')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_lignes_budget', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budget', to='fpa.cyclebudgetaire', verbose_name='Cycle budgétaire')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_budget', to='fpa.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Ligne de budget département',
                'ordering': ['departement', 'categorie', 'mois'],
                'constraints': [models.UniqueConstraint(fields=('cycle', 'departement', 'categorie', 'mois'), name='fpa_ligne_budget_unique'), models.CheckConstraint(condition=models.Q(('mois__gte', 1), ('mois__lte', 12)), name='fpa_ligne_budget_mois_valide')],
            },
        ),
    ]
