# Generated by Django 5.1.4 on 2026-07-16 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('fpa', '0003_lignebudgetdepartement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoumissionBudgetDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_saisie', 'En saisie'), ('soumis', 'Soumis'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_saisie', max_length=10, verbose_name='Statut')),
                ('motif_rejet', models.TextField(blank=True, default='', verbose_name='Motif de rejet')),
                ('soumis_le', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('valide_le', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_soumissions_budget', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='fpa.cyclebudgetaire', verbose_name='Cycle budgétaire')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_budget', to='fpa.departement', verbose_name='Département')),
                ('soumis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpa_budgets_soumis', to=settings.AUTH_USER_MODEL, verbose_name='Soumis par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpa_budgets_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Soumission de budget département',
                'constraints': [models.UniqueConstraint(fields=('cycle', 'departement'), name='fpa_soumission_cycle_departement_unique')],
            },
        ),
    ]
