# Generated by Django 5.1.4 on 2026-07-17 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('fpa', '0004_soumissionbudgetdepartement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingCategorieCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie FP&A')),
                ('compte_cgnc_prefixe', models.CharField(max_length=10, verbose_name='Préfixe de compte CGNC')),
                ('compte_cgnc_libelle', models.CharField(blank=True, default='', max_length=150, verbose_name='Libellé du compte')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_mappings_categorie_compte', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Mapping catégorie ↔ compte CGNC',
                'ordering': ['categorie', 'compte_cgnc_prefixe'],
            },
        ),
        migrations.CreateModel(
            name='PrevisionGlissante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reference', models.DateField(verbose_name='Mois de départ')),
                ('horizon_mois', models.PositiveSmallIntegerField(choices=[(12, '12 mois'), (18, '18 mois')], default=12, verbose_name='Horizon (mois)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_previsions_glissantes', to='authentication.company', verbose_name='Société')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsions_glissantes', to='fpa.departement', verbose_name='Département (vide = vue globale)')),
            ],
            options={
                'verbose_name': 'Prévision glissante',
                'ordering': ['-date_reference'],
            },
        ),
        migrations.CreateModel(
            name='LignePrevisionGlissante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois_relatif', models.PositiveSmallIntegerField(verbose_name='Mois relatif (1..horizon)')),
                ('categorie', models.CharField(choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant prévu')),
                ('source', models.CharField(choices=[('manuel', 'Manuel'), ('driver', 'Driver'), ('statistique', 'Statistique')], default='statistique', max_length=15, verbose_name='Source')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_lignes_prevision_glissante', to='authentication.company', verbose_name='Société')),
                ('prevision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fpa.previsionglissante', verbose_name='Prévision glissante')),
            ],
            options={
                'verbose_name': 'Ligne de prévision glissante',
                'ordering': ['mois_relatif', 'categorie'],
                'constraints': [models.UniqueConstraint(fields=('prevision', 'mois_relatif', 'categorie'), name='fpa_ligne_prevision_glissante_unique')],
            },
        ),
    ]
