# Generated by Django 5.1.4 on 2026-07-17 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('fpa', '0005_mappingcategoriecompte_previsionglissante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HypotheseRecrutement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=150, verbose_name='Poste')),
                ('date_effet', models.DateField(verbose_name="Date d'effet")),
                ('salaire_brut_estime', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Salaire brut estimé')),
                ('type_mouvement', models.CharField(choices=[('embauche', 'Embauche'), ('depart', 'Départ')], default='embauche', max_length=10, verbose_name='Type de mouvement')),
                ('statut', models.CharField(choices=[('hypothese', 'Hypothèse'), ('confirme', 'Confirmé')], default='hypothese', max_length=10, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_hypotheses_recrutement', to='authentication.company', verbose_name='Société')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hypotheses_recrutement', to='fpa.departement', verbose_name='Département')),
                ('prevision_glissante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hypotheses_recrutement', to='fpa.previsionglissante', verbose_name='Prévision glissante liée')),
            ],
            options={
                'verbose_name': 'Hypothèse de recrutement',
                'ordering': ['date_effet'],
            },
        ),
    ]
