# Generated by Django 5.1.4 on 2026-07-17 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('fpa', '0006_hypotheserecrutement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('archive', 'Archivé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('est_scenario_base', models.BooleanField(default=False, verbose_name='Scénario de base')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_scenarios', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='fpa.cyclebudgetaire', verbose_name='Cycle budgétaire')),
            ],
            options={
                'verbose_name': 'Scénario budgétaire',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='LigneScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(blank=True, choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], default='', max_length=20, verbose_name='Catégorie ciblée (si pas une ligne précise)')),
                ('delta_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Delta %% (ex. -10)')),
                ('delta_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Delta montant absolu')),
                ('raison', models.CharField(blank=True, default='', max_length=255, verbose_name='Raison')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_lignes_scenario', to='authentication.company', verbose_name='Société')),
                ('ligne_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deltas_scenario', to='fpa.lignebudgetdepartement', verbose_name='Ligne budget de référence (optionnel)')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fpa.scenariobudgetaire', verbose_name='Scénario')),
            ],
            options={
                'verbose_name': 'Ligne de scénario',
            },
        ),
        migrations.AddConstraint(
            model_name='scenariobudgetaire',
            constraint=models.UniqueConstraint(condition=models.Q(('est_scenario_base', True)), fields=('cycle',), name='fpa_un_seul_scenario_base_par_cycle'),
        ),
    ]
