# Generated by Django 5.1.4 on 2026-07-17 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('fpa', '0007_scenariobudgetaire_lignescenario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaireVariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('masse_salariale', 'Masse salariale'), ('marketing', 'Marketing'), ('it', 'IT'), ('frais_generaux', 'Frais généraux'), ('investissement', 'Investissement'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('mois', models.PositiveSmallIntegerField(verbose_name='Mois (1-12)')),
                ('texte', models.TextField(verbose_name='Explication')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpa_commentaires_variance', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpa_commentaires_variance', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_variance', to='fpa.cyclebudgetaire', verbose_name='Cycle budgétaire')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires_variance', to='fpa.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Commentaire de variance',
                'ordering': ['-cree_le'],
            },
        ),
    ]
