# Generated by Django 5.1.4 on 2026-06-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("client", "Client"),
                            ("produit", "Produit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.SlugField()),
                ("libelle", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("number", "Nombre"),
                            ("date", "Date"),
                            ("choice", "Choix"),
                            ("boolean", "Oui/Non"),
                        ],
                        default="text",
                        max_length=12,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                ("obligatoire", models.BooleanField(default=False)),
                ("visible_liste", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_fields",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ personnalisé",
                "verbose_name_plural": "Champs personnalisés",
                "ordering": ["module", "ordre", "libelle"],
                "unique_together": {("company", "module", "code")},
            },
        ),
    ]
