# Generated by Django 5.1.4 on 2026-06-16 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("client", "Client"),
                            ("produit", "Produit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_key", models.SlugField(max_length=60)),
                ("label", models.CharField(max_length=120)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texte"),
                            ("number", "Nombre"),
                            ("date", "Date"),
                            ("choice", "Liste de choix"),
                            ("boolean", "Oui / Non"),
                        ],
                        max_length=20,
                    ),
                ),
                ("choices", models.JSONField(blank=True, default=list)),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("show_in_list", models.BooleanField(default=False)),
                ("show_in_filter", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_definitions",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ personnalisé",
                "verbose_name_plural": "Champs personnalisés",
                "ordering": ["module", "order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "module", "field_key"),
                        name="uniq_customfield_company_module_key",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HiddenStandardField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("client", "Client"),
                            ("produit", "Produit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("field_key", models.CharField(max_length=60)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hidden_standard_fields",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Champ standard masqué",
                "verbose_name_plural": "Champs standard masqués",
                "ordering": ["module", "field_key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "module", "field_key"),
                        name="uniq_hiddenfield_company_module_key",
                    )
                ],
            },
        ),
    ]
