# Generated by Django 5.1.4 on 2026-06-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customfields", "0002_fg100_new_modules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customfielddef",
            name="module",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("client", "Client"),
                    ("produit", "Produit"),
                    ("devis", "Devis"),
                    ("installation", "Chantier"),
                    ("ticket", "Ticket SAV"),
                    ("document", "Document GED"),
                ],
                max_length=20,
            ),
        ),
    ]
