# Generated by Django 5.1.4 on 2026-06-19 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("lead_stage_change", "Changement d'étape d'un lead"),
                            ("devis_accepted", "Devis accepté"),
                            ("chantier_status", "Chantier atteint un statut"),
                            ("facture_overdue", "Facture en retard"),
                            ("warranty_expiring", "Garantie proche expiration"),
                            ("maintenance_due", "Visite de maintenance due"),
                            ("stock_below_threshold", "Stock sous le seuil"),
                        ],
                        max_length=40,
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_whatsapp", "Envoyer un WhatsApp"),
                            ("send_email", "Envoyer un email"),
                            ("send_sms", "Envoyer un SMS"),
                            ("create_activity", "Créer une activité / tâche"),
                            ("assign_record", "Assigner un enregistrement"),
                            ("set_field", "Mettre à jour un champ"),
                            ("create_sav_ticket", "Créer un ticket SAV"),
                        ],
                        max_length=40,
                    ),
                ),
                ("action_config", models.JSONField(blank=True, default=dict)),
                ("requires_approval", models.BooleanField(default=False)),
                (
                    "approval_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règle d'automatisation",
                "verbose_name_plural": "Règles d'automatisation",
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="AutomationApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_approvals",
                        to="authentication.company",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_approvals_decided",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="automation_approvals_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals",
                        to="automation.automationrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approbation d'automatisation",
                "verbose_name_plural": "Approbations d'automatisation",
                "ordering": ["-date_creation", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("target_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Réussi"),
                            ("skipped", "Ignoré"),
                            ("failed", "Échec"),
                            ("pending_approval", "En attente d'approbation"),
                            ("noop", "Sans effet"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_runs",
                        to="authentication.company",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="automation.automationrule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exécution d'automatisation",
                "verbose_name_plural": "Exécutions d'automatisation",
                "ordering": ["-timestamp", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["company", "enabled", "trigger_type"],
                name="automation__company_971e4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationapproval",
            index=models.Index(
                fields=["company", "status"], name="automation__company_91168d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrun",
            index=models.Index(
                fields=["company", "-timestamp"], name="automation__company_ca55a8_idx"
            ),
        ),
    ]
