# Generated by Django 5.1.4 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_xprj23_projet_triggers'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvaldecision',
            new_name='automation__request_f93647_idx',
            old_name='automation_decision_idx',
        ),
        migrations.RenameIndex(
            model_name='approvaldelegation',
            new_name='automation__company_da51d1_idx',
            old_name='automation_deleg_delegant_idx',
        ),
        migrations.RenameIndex(
            model_name='approvaldelegation',
            new_name='automation__company_165862_idx',
            old_name='automation_deleg_suppleant_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrequest',
            new_name='automation__company_14fccf_idx',
            old_name='automation_arequest_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalrequesttype',
            new_name='automation__company_9b39d5_idx',
            old_name='automation_artype_idx',
        ),
        migrations.RenameIndex(
            model_name='incomingwebhooktrigger',
            new_name='automation__token_ca18c2_idx',
            old_name='automation_hook_token_idx',
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('lead_stage_change', "Changement d'étape d'un lead"), ('devis_accepted', 'Devis accepté'), ('chantier_status', 'Chantier atteint un statut'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie proche expiration'), ('maintenance_due', 'Visite de maintenance due'), ('stock_below_threshold', 'Stock sous le seuil'), ('date_echeance_champ', 'Échéance de champ (± N jours)'), ('webhook_inbound', 'Webhook entrant'), ('projet_status_change', 'Changement de statut de projet'), ('projet_phase_change', 'Changement de phase de projet')], max_length=40),
        ),
    ]
