# Generated by Django 5.1.4 on 2026-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_rename_automation_decision_idx_automation__request_f93647_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('lead_stage_change', "Changement d'étape d'un lead"), ('devis_accepted', 'Devis accepté'), ('chantier_status', 'Chantier atteint un statut'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie proche expiration'), ('maintenance_due', 'Visite de maintenance due'), ('stock_below_threshold', 'Stock sous le seuil'), ('date_echeance_champ', 'Échéance de champ (± N jours)'), ('webhook_inbound', 'Webhook entrant'), ('projet_status_change', 'Changement de statut de projet'), ('projet_phase_change', 'Changement de phase de projet'), ('record_state_change', "Changement d'état d'un enregistrement")], max_length=40),
        ),
    ]
