# Generated by Django 5.1.4 on 2026-07-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_alter_automationrule_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationstep',
            name='action_type',
            field=models.CharField(choices=[('send_whatsapp', 'Envoyer un WhatsApp'), ('send_email', 'Envoyer un email'), ('send_sms', 'Envoyer un SMS'), ('create_activity', 'Créer une activité / tâche'), ('assign_record', 'Assigner un enregistrement'), ('set_field', 'Mettre à jour un champ'), ('create_sav_ticket', 'Créer un ticket SAV'), ('create_custom_record', 'Créer un enregistrement personnalisé')], max_length=40),
        ),
    ]
