# Generated by Django 5.1.15 on 2026-09-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0021_ntext30_automationruleversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(choices=[('lead_stage_change', "Changement d'étape d'un lead"), ('devis_accepted', 'Devis accepté'), ('chantier_status', 'Chantier atteint un statut'), ('facture_overdue', 'Facture en retard'), ('warranty_expiring', 'Garantie proche expiration'), ('maintenance_due', 'Visite de maintenance due'), ('stock_below_threshold', 'Stock sous le seuil'), ('date_echeance_champ', 'Échéance de champ (± N jours)'), ('webhook_inbound', 'Webhook entrant'), ('projet_status_change', 'Changement de statut de projet'), ('projet_phase_change', 'Changement de phase de projet'), ('record_state_change', "Changement d'état d'un enregistrement"), ('custom_record_saved', "Enregistrement d'objet personnalisé créé/modifié"), ('demande_achat_approuvee', "Demande d'achat approuvée"), ('rfq_attribuee', 'RFQ attribuée à un fournisseur'), ('langue_changed', 'Langue de document changée'), ('dossier_echeance_depassee', 'Dossier en retard (échéance dépassée)')], max_length=40),
        ),
    ]
