# Generated by Django 5.1.4 on 2026-06-18 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_username",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("status", "Changement de statut"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("login_failed", "Échec de connexion"),
                            ("pdf", "PDF généré"),
                            ("email", "Email envoyé"),
                            ("whatsapp", "WhatsApp envoyé"),
                            ("export", "Export"),
                            ("accept", "Devis accepté"),
                            ("refuse", "Devis refusé"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("object_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("detail", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="authentication.company",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrée du journal d'activité",
                "verbose_name_plural": "Journal d'activité",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["company", "-timestamp"],
                        name="audit_audit_company_853041_idx",
                    ),
                    models.Index(
                        fields=["company", "action", "-timestamp"],
                        name="audit_audit_company_f21475_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="audit_audit_content_4c2ead_idx",
                    ),
                ],
            },
        ),
    ]
