# Generated by Django 5.1.4 on 2026-07-09 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auditlog_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('status', 'Changement de statut'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('login_failed', 'Échec de connexion'), ('security_alert', 'Alerte de sécurité'), ('pdf', 'PDF généré'), ('email', 'Email envoyé'), ('whatsapp', 'WhatsApp envoyé'), ('export', 'Export'), ('accept', 'Devis accepté'), ('refuse', 'Devis refusé'), ('notify', 'Notification envoyée'), ('switch_company', 'Changement de société active')], db_index=True, max_length=20),
        ),
    ]
