# Generated by Django 5.1.4 on 2026-06-21 04:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reclamation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Référence"
                    ),
                ),
                (
                    "type_reclamation",
                    models.CharField(
                        choices=[
                            ("financier", "Financier"),
                            ("qualite", "Qualité"),
                            ("delai", "Délai"),
                            ("commercial", "Commercial"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                        verbose_name="Type de réclamation",
                    ),
                ),
                (
                    "gravite",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("moyenne", "Moyenne"),
                            ("elevee", "Élevée"),
                        ],
                        default="moyenne",
                        max_length=10,
                        verbose_name="Gravité",
                    ),
                ),
                ("objet", models.CharField(max_length=255, verbose_name="Objet")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Type de document source",
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID du document source"
                    ),
                ),
                (
                    "montant_conteste",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant contesté",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouverte", "Ouverte"),
                            ("en_traitement", "En traitement"),
                            ("resolue", "Résolue"),
                            ("rejetee", "Rejetée"),
                        ],
                        default="ouverte",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="litiges_reclamations",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reclamations_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réclamation",
                "verbose_name_plural": "Réclamations",
                "ordering": ["-id"],
            },
        ),
    ]
