# Generated by Django 5.1.4 on 2026-07-16 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_limite', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Limite de crédit')),
                ('devise', models.CharField(default='MAD', max_length=3)),
                ('mode_hold', models.CharField(choices=[('aucun', 'Aucun'), ('avertissement', 'Avertissement'), ('blocage', 'Blocage')], default='avertissement', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('motif_null', models.TextField(blank=True, default='', help_text='Motif si la limite est volontairement non définie.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_credit', to='authentication.company')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limites_credit_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limite de crédit',
                'verbose_name_plural': 'Limites de crédit',
                'ordering': ['-date_modification'],
                'unique_together': {('company', 'client')},
            },
        ),
    ]
