# Generated by Django 5.1.4 on 2026-07-17 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
        ('ventes', '0087_qx43_mode_commercial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DerogationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motif', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('valide_jusqu_au', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approuvee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derogations_credit_decidees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derogations_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derogations_credit_demandees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derogations_credit', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Dérogation crédit',
                'verbose_name_plural': 'Dérogations crédit',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EncoursCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encours', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('calcule_le', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encours_cache_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Cache d'encours crédit",
                'verbose_name_plural': "Caches d'encours crédit",
            },
        ),
        migrations.CreateModel(
            name='PoliceAssuranceCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assureur', models.CharField(max_length=150)),
                ('numero_police', models.CharField(blank=True, default='', max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('franchise', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('taux_couverture_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de couverture assureur (ex. 90 %).', max_digits=5, null=True)),
                ('plafond_global', models.DecimalField(blank=True, decimal_places=2, help_text='Encours max garanti, tous clients confondus.', max_digits=16, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_alerte_le', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Police d'assurance-crédit",
                'verbose_name_plural': "Polices d'assurance-crédit",
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReglageCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode_hold_defaut', models.CharField(choices=[('aucun', 'Aucun'), ('avertissement', 'Avertissement'), ('blocage', 'Blocage')], default='avertissement', help_text='Mode de hold hérité par une LimiteCredit qui ne le surcharge pas explicitement. Jamais "blocage" par défaut.', max_length=20)),
                ('inclure_bc_non_factures', models.BooleanField(default=True)),
                ('inclure_devis_en_cours', models.BooleanField(default=False)),
                ('seuil_alerte_pct', models.DecimalField(decimal_places=2, default=80, help_text='Seuil (% de la limite) déclenchant une alerte avant blocage.', max_digits=5)),
                ('seuil_alerte_exposition_globale', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('derniere_alerte_exposition_le', models.DateField(blank=True, null=True)),
                ('devise_consolidation', models.CharField(default='MAD', max_length=3)),
                ('seuil_tolerance_depassement', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('roles_bypass_hold', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglage_credit', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Réglage crédit (société)',
                'verbose_name_plural': 'Réglages crédit (société)',
            },
        ),
        migrations.CreateModel(
            name='SegmentClientCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.CharField(max_length=100)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segment_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Segment crédit du client',
                'verbose_name_plural': 'Segments crédit des clients',
            },
        ),
        migrations.CreateModel(
            name='ConditionPaiementSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.CharField(max_length=100)),
                ('delai_paiement_jours', models.PositiveIntegerField(default=0)),
                ('pct_acompte_defaut', models.DecimalField(blank=True, decimal_places=2, help_text="% d'acompte par défaut pour ce segment (vide = défaut société).", max_digits=5, null=True)),
                ('mode_hold_override', models.CharField(blank=True, choices=[('aucun', 'Aucun'), ('avertissement', 'Avertissement'), ('blocage', 'Blocage')], default='', help_text='Surcharge le mode de hold pour ce segment (vide = défaut société).', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Condition de paiement par segment',
                'verbose_name_plural': 'Conditions de paiement par segment',
                'ordering': ['segment'],
                'unique_together': {('company', 'segment')},
            },
        ),
        migrations.CreateModel(
            name='LimiteCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_limite', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Limite de crédit')),
                ('devise', models.CharField(default='MAD', max_length=3)),
                ('mode_hold', models.CharField(choices=[('aucun', 'Aucun'), ('avertissement', 'Avertissement'), ('blocage', 'Blocage')], default='avertissement', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('motif_null', models.TextField(blank=True, default='', help_text='Motif si la limite est volontairement non définie.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limites_credit_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limite de crédit',
                'verbose_name_plural': 'Limites de crédit',
                'ordering': ['-date_modification'],
                'unique_together': {('company', 'client')},
            },
        ),
        migrations.CreateModel(
            name='EncoursGarantiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_garanti', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_agrement', models.DateField(blank=True, null=True)),
                ('statut_agrement', models.CharField(choices=[('accorde', 'Accordé'), ('refuse', 'Refusé'), ('en_attente', 'En attente'), ('reduit', 'Réduit')], default='en_attente', max_length=20)),
                ('reference_assureur', models.CharField(blank=True, default='', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encours_garantis_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encours_garantis', to='credit.policeassurancecredit')),
            ],
            options={
                'verbose_name': 'Encours garanti client',
                'verbose_name_plural': 'Encours garantis client',
                'ordering': ['-date_agrement', '-id'],
                'unique_together': {('police', 'client')},
            },
        ),
    ]
