# Generated by Django 5.1.4 on 2026-07-16 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglageCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_hold_defaut', models.CharField(choices=[('aucun', 'Aucun'), ('avertissement', 'Avertissement'), ('blocage', 'Blocage')], default='avertissement', help_text='Mode de hold hérité par une LimiteCredit qui ne le surcharge pas explicitement. Jamais "blocage" par défaut.', max_length=20)),
                ('inclure_bc_non_factures', models.BooleanField(default=True)),
                ('inclure_devis_en_cours', models.BooleanField(default=False)),
                ('seuil_alerte_pct', models.DecimalField(decimal_places=2, default=80, help_text='Seuil (% de la limite) déclenchant une alerte avant blocage.', max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reglage_credit', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Réglage crédit (société)',
                'verbose_name_plural': 'Réglages crédit (société)',
            },
        ),
    ]
