# Generated by Django 5.1.4 on 2026-07-17 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('credit', '0002_reglagecredit'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
        ('ventes', '0086_xsal14_ligne_section_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DerogationCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motif', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('expiree', 'Expirée')], default='en_attente', max_length=20)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('valide_jusqu_au', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('approuvee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derogations_credit_decidees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derogations_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derogations_credit', to='authentication.company')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derogations_credit_demandees', to=settings.AUTH_USER_MODEL)),
                ('devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derogations_credit', to='ventes.devis')),
            ],
            options={
                'verbose_name': 'Dérogation crédit',
                'verbose_name_plural': 'Dérogations crédit',
                'ordering': ['-date_creation'],
            },
        ),
    ]
