# Generated by Django 5.1.4 on 2026-07-17 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('credit', '0003_derogationcredit'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentClientCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segment_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_client_credit', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Segment crédit du client',
                'verbose_name_plural': 'Segments crédit des clients',
            },
        ),
        migrations.CreateModel(
            name='ConditionPaiementSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('delai_paiement_jours', models.PositiveIntegerField(default=0)),
                ('pct_acompte_defaut', models.DecimalField(blank=True, decimal_places=2, help_text="% d'acompte par défaut pour ce segment (vide = défaut société).", max_digits=5, null=True)),
                ('mode_hold_override', models.CharField(blank=True, choices=[('aucun', 'Aucun'), ('avertissement', 'Avertissement'), ('blocage', 'Blocage')], default='', help_text='Surcharge le mode de hold pour ce segment (vide = défaut société).', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions_paiement_segment', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Condition de paiement par segment',
                'verbose_name_plural': 'Conditions de paiement par segment',
                'ordering': ['segment'],
                'unique_together': {('company', 'segment')},
            },
        ),
    ]
