# Generated by Django 5.1.4 on 2026-07-17 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('credit', '0004_segmentclientcredit_conditionpaiementsegment'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceAssuranceCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assureur', models.CharField(max_length=150)),
                ('numero_police', models.CharField(blank=True, default='', max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('franchise', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('taux_couverture_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Taux de couverture assureur (ex. 90 %).', max_digits=5, null=True)),
                ('plafond_global', models.DecimalField(blank=True, decimal_places=2, help_text='Encours max garanti, tous clients confondus.', max_digits=16, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polices_assurance_credit', to='authentication.company')),
            ],
            options={
                'verbose_name': "Police d'assurance-crédit",
                'verbose_name_plural': "Polices d'assurance-crédit",
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EncoursGarantiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_garanti', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_agrement', models.DateField(blank=True, null=True)),
                ('statut_agrement', models.CharField(choices=[('accorde', 'Accordé'), ('refuse', 'Refusé'), ('en_attente', 'En attente'), ('reduit', 'Réduit')], default='en_attente', max_length=20)),
                ('reference_assureur', models.CharField(blank=True, default='', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encours_garantis_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encours_garantis_client', to='authentication.company')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encours_garantis', to='credit.policeassurancecredit')),
            ],
            options={
                'verbose_name': 'Encours garanti client',
                'verbose_name_plural': 'Encours garantis client',
                'ordering': ['-date_agrement', '-id'],
                'unique_together': {('police', 'client')},
            },
        ),
    ]
