# Generated by Django 5.1.4 on 2026-07-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_policeassurancecredit_encoursgaranticlient'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglagecredit',
            name='derniere_alerte_exposition_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reglagecredit',
            name='seuil_alerte_exposition_globale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
