# Generated by Django 5.1.4 on 2026-07-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_reglagecredit_derniere_alerte_exposition_le_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglagecredit',
            name='devise_consolidation',
            field=models.CharField(default='MAD', max_length=3),
        ),
    ]
