# Generated by Django 5.1.4 on 2026-07-17 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        ('credit', '0008_reglagecredit_roles_bypass_hold_and_more'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncoursCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encours', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('calcule_le', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encours_cache_credit', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encours_cache_credit', to='authentication.company')),
            ],
            options={
                'verbose_name': "Cache d'encours crédit",
                'verbose_name_plural': "Caches d'encours crédit",
            },
        ),
    ]
