# Generated by Django 5.1.4 on 2026-07-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_encourscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeassurancecredit',
            name='derniere_alerte_le',
            field=models.DateField(blank=True, null=True),
        ),
    ]
