# Generated by Django 5.1.4 on 2026-07-17 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('ice', models.CharField(blank=True, default='', max_length=30, verbose_name='ICE')),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('adresse', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assureurs', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Assureur',
                'verbose_name_plural': 'Assureurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Courtier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('numero_agrement', models.CharField(blank=True, default='', max_length=60, verbose_name="Numéro d'agrément")),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtiers', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Courtier',
                'verbose_name_plural': 'Courtiers',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='DeclarationSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, default='', max_length=40)),
                ('date_survenance', models.DateField(verbose_name='Date de survenance')),
                ('date_declaration', models.DateField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('nature_sinistre', models.TextField(blank=True, default='')),
                ('type_sinistre', models.CharField(choices=[('dommage_materiel', 'Dommage matériel'), ('responsabilite_civile', 'Responsabilité civile'), ('decennale', 'Décennale'), ('cyber', 'Cyber'), ('vol', 'Vol'), ('incendie', 'Incendie'), ('autre', 'Autre')], default='autre', max_length=25)),
                ('montant_estime_degats', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant estimé des dégâts')),
                ('statut', models.CharField(choices=[('declare', 'Déclaré'), ('en_expertise', 'En expertise'), ('indemnise', 'Indemnisé'), ('refuse', 'Refusé'), ('clos', 'Clos')], default='declare', max_length=15)),
                ('description', models.TextField(blank=True, default='')),
                ('flotte_sinistre_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sinistre véhicule lié (flotte)')),
                ('risque_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name='Risque ERM lié (string-FK NTGRC)')),
                ('dossier_contentieux_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name='Dossier contentieux lié (string-FK NTJUR)')),
                ('conteste', models.BooleanField(default=False, verbose_name='Contesté')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_sinistre', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Déclaration de sinistre',
                'verbose_name_plural': 'Déclarations de sinistre',
                'ordering': ['-date_survenance'],
            },
        ),
        migrations.CreateModel(
            name='IndemnisationSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_reclame', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('franchise_appliquee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Franchise appliquée (snapshot)')),
                ('montant_indemnise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_versement', models.DateField(blank=True, null=True)),
                ('ecriture_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name='Référence écriture comptable')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indemnisations_sinistre', to='authentication.company', verbose_name='Société')),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indemnisation', to='assurances.declarationsinistre')),
            ],
            options={
                'verbose_name': 'Indemnisation de sinistre',
                'verbose_name_plural': 'Indemnisations de sinistre',
            },
        ),
        migrations.CreateModel(
            name='PoliceAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_police', models.CharField(max_length=80, verbose_name='Numéro de police')),
                ('type_police', models.CharField(choices=[('rc_pro', 'RC professionnelle'), ('decennale', 'Décennale'), ('multirisque', 'Multirisque'), ('cyber', 'Cyber'), ('homme_cle', 'Homme-clé'), ('transport_marchandises', 'Transport de marchandises'), ('bris_machine', 'Bris de machine'), ('perte_exploitation', "Perte d'exploitation"), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Type de police')),
                ('libelle', models.CharField(blank=True, default='', max_length=200)),
                ('date_effet', models.DateField(verbose_name="Date d'effet")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('tacite_reconduction', models.BooleanField(default=False, verbose_name='Tacite reconduction')),
                ('prime_annuelle_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prime annuelle HT')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('resiliee', 'Résiliée'), ('expiree', 'Expirée')], default='active', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('employe_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name='Employé couvert (homme-clé, string-FK rh)')),
                ('cyber_clauses', models.JSONField(blank=True, default=dict, verbose_name='Clauses cyber (JSON)')),
                ('assureur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polices', to='assurances.assureur', verbose_name='Assureur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polices_assurance', to='authentication.company', verbose_name='Société')),
                ('courtier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polices', to='assurances.courtier', verbose_name='Courtier')),
                ('police_precedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polices_suivantes', to='assurances.policeassurance', verbose_name='Police précédente')),
            ],
            options={
                'verbose_name': "Police d'assurance",
                'verbose_name_plural': "Polices d'assurance",
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='GarantiePolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle_garantie', models.CharField(max_length=200, verbose_name='Libellé de la garantie')),
                ('plafond_indemnisation', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Plafond d'indemnisation")),
                ('franchise_montant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Franchise (montant)')),
                ('franchise_pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Franchise (%)')),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garanties_police', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garanties', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': 'Garantie de police',
                'verbose_name_plural': 'Garanties de police',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EcheancePrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_echeance_paiement', models.DateField(verbose_name="Date d'échéance")),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('periodicite', models.CharField(choices=[('annuelle', 'Annuelle'), ('semestrielle', 'Semestrielle'), ('trimestrielle', 'Trimestrielle'), ('mensuelle', 'Mensuelle')], default='annuelle', max_length=15)),
                ('statut', models.CharField(choices=[('a_payer', 'À payer'), ('proposee_compta', 'Proposée en compta'), ('payee', 'Payée'), ('en_retard', 'En retard')], default='a_payer', max_length=20)),
                ('ecriture_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name='Référence écriture comptable')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_prime', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_prime', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': 'Échéance de prime',
                'verbose_name_plural': 'Échéances de prime',
                'ordering': ['date_echeance_paiement'],
            },
        ),
        migrations.AddField(
            model_name='declarationsinistre',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations_sinistre', to='assurances.policeassurance'),
        ),
        migrations.CreateModel(
            name='AttestationAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_validite', models.DateField(verbose_name='Date de validité')),
                ('emise_pour', models.CharField(blank=True, default='', max_length=255, verbose_name='Émise pour (client / marché)')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('expiree', 'Expirée')], default='valide', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_assurance', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': "Attestation d'assurance",
                'verbose_name_plural': "Attestations d'assurance",
                'ordering': ['-date_validite'],
            },
        ),
        migrations.CreateModel(
            name='ActifCouvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_actif', models.CharField(choices=[('site', 'Site'), ('vehicule', 'Véhicule'), ('equipement', 'Équipement'), ('autre', 'Autre')], default='autre', max_length=15)),
                ('actif_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name="Référence de l'actif (string-FK)")),
                ('actif_libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé (snapshot)')),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actifs_couverts', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actifs_couverts', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': 'Actif couvert',
                'verbose_name_plural': 'Actifs couverts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExigenceAssuranceMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marche_ref', models.PositiveIntegerField(verbose_name='Référence du marché (string-FK)')),
                ('type_police_requis', models.CharField(choices=[('rc_pro', 'RC professionnelle'), ('decennale', 'Décennale'), ('multirisque', 'Multirisque'), ('cyber', 'Cyber'), ('homme_cle', 'Homme-clé'), ('transport_marchandises', 'Transport de marchandises'), ('bris_machine', 'Bris de machine'), ('perte_exploitation', "Perte d'exploitation"), ('autre', 'Autre')], max_length=30, verbose_name='Type de police requis')),
                ('montant_couverture_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Couverture minimum exigée')),
                ('statut_verification', models.CharField(choices=[('a_verifier', 'À vérifier'), ('conforme', 'Conforme'), ('non_conforme', 'Non conforme')], default='a_verifier', max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exigences_assurance_marche', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Exigence d'assurance de marché",
                'verbose_name_plural': "Exigences d'assurance de marché",
                'ordering': ['id'],
                'indexes': [models.Index(fields=['company', 'marche_ref'], name='assurances__company_47a186_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='policeassurance',
            index=models.Index(fields=['company', 'statut'], name='assurances__company_bc76dc_idx'),
        ),
        migrations.AddIndex(
            model_name='policeassurance',
            index=models.Index(fields=['company', 'type_police'], name='assurances__company_9492e5_idx'),
        ),
        migrations.AddIndex(
            model_name='policeassurance',
            index=models.Index(fields=['company', 'date_echeance'], name='assurances__company_eeed19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='policeassurance',
            unique_together={('company', 'numero_police')},
        ),
        migrations.AddIndex(
            model_name='garantiepolice',
            index=models.Index(fields=['police'], name='assurances__police__0f7abd_idx'),
        ),
        migrations.AddIndex(
            model_name='echeanceprime',
            index=models.Index(fields=['police', 'date_echeance_paiement'], name='assurances__police__f57da0_idx'),
        ),
        migrations.AddIndex(
            model_name='echeanceprime',
            index=models.Index(fields=['company', 'statut'], name='assurances__company_9c91d1_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationsinistre',
            index=models.Index(fields=['company', 'statut'], name='assurances__company_ea2675_idx'),
        ),
        migrations.AddIndex(
            model_name='declarationsinistre',
            index=models.Index(fields=['company', 'type_sinistre'], name='assurances__company_c7755e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='declarationsinistre',
            unique_together={('company', 'reference')},
        ),
        migrations.AddIndex(
            model_name='attestationassurance',
            index=models.Index(fields=['company', 'statut'], name='assurances__company_353d79_idx'),
        ),
        migrations.AddIndex(
            model_name='attestationassurance',
            index=models.Index(fields=['police', '-date_validite'], name='assurances__police__c8985f_idx'),
        ),
        migrations.AddIndex(
            model_name='actifcouvert',
            index=models.Index(fields=['police', 'type_actif'], name='assurances__police__55f0c5_idx'),
        ),
    ]
