# Generated by Django 5.1.4 on 2026-07-16 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assureur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('ice', models.CharField(blank=True, default='', max_length=30, verbose_name='ICE')),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('adresse', models.TextField(blank=True, default='')),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assureurs', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Assureur',
                'verbose_name_plural': 'Assureurs',
                'ordering': ['raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='Courtier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(max_length=200, verbose_name='Raison sociale')),
                ('numero_agrement', models.CharField(blank=True, default='', max_length=60, verbose_name="Numéro d'agrément")),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courtiers', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Courtier',
                'verbose_name_plural': 'Courtiers',
                'ordering': ['raison_sociale'],
            },
        ),
    ]
