# Generated by Django 5.1.4 on 2026-07-16 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0001_initial'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_police', models.CharField(max_length=80, verbose_name='Numéro de police')),
                ('type_police', models.CharField(choices=[('rc_pro', 'RC professionnelle'), ('decennale', 'Décennale'), ('multirisque', 'Multirisque'), ('cyber', 'Cyber'), ('homme_cle', 'Homme-clé'), ('transport_marchandises', 'Transport de marchandises'), ('bris_machine', 'Bris de machine'), ('perte_exploitation', "Perte d'exploitation"), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Type de police')),
                ('libelle', models.CharField(blank=True, default='', max_length=200)),
                ('date_effet', models.DateField(verbose_name="Date d'effet")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('tacite_reconduction', models.BooleanField(default=False, verbose_name='Tacite reconduction')),
                ('prime_annuelle_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Prime annuelle HT')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('suspendue', 'Suspendue'), ('resiliee', 'Résiliée'), ('expiree', 'Expirée')], default='active', max_length=15)),
                ('document_police', models.FileField(blank=True, null=True, upload_to='assurances/polices/%Y/%m/', verbose_name='Contrat scanné')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assureur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polices', to='assurances.assureur', verbose_name='Assureur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polices_assurance', to='authentication.company', verbose_name='Société')),
                ('courtier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polices', to='assurances.courtier', verbose_name='Courtier')),
                ('police_precedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polices_suivantes', to='assurances.policeassurance', verbose_name='Police précédente')),
            ],
            options={
                'verbose_name': "Police d'assurance",
                'verbose_name_plural': "Polices d'assurance",
                'ordering': ['date_echeance'],
                'indexes': [models.Index(fields=['company', 'statut'], name='assurances__company_bc76dc_idx'), models.Index(fields=['company', 'type_police'], name='assurances__company_9492e5_idx'), models.Index(fields=['company', 'date_echeance'], name='assurances__company_eeed19_idx')],
                'unique_together': {('company', 'numero_police')},
            },
        ),
    ]
