# Generated by Django 5.1.4 on 2026-07-16 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0002_policeassurance'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('note', 'Note')], max_length=15)),
                ('champ', models.CharField(blank=True, max_length=100, null=True)),
                ('champ_label', models.CharField(blank=True, max_length=150, null=True)),
                ('ancienne_valeur', models.TextField(blank=True, null=True)),
                ('nouvelle_valeur', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police_activities', to='authentication.company')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='assurances.policeassurance')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité police',
                'verbose_name_plural': 'Activités police',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['police', '-created_at'], name='assurances__police__1fdd4a_idx')],
            },
        ),
    ]
