# Generated by Django 5.1.4 on 2026-07-16 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0003_policeactivity'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarantiePolice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_garantie', models.CharField(max_length=200, verbose_name='Libellé de la garantie')),
                ('plafond_indemnisation', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Plafond d'indemnisation")),
                ('franchise_montant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Franchise (montant)')),
                ('franchise_pourcentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Franchise (%)')),
                ('notes', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garanties_police', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garanties', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': 'Garantie de police',
                'verbose_name_plural': 'Garanties de police',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['police'], name='assurances__police__0f7abd_idx')],
            },
        ),
    ]
