# Generated by Django 5.1.4 on 2026-07-16 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0004_garantiepolice'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcheancePrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_echeance_paiement', models.DateField(verbose_name="Date d'échéance")),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('periodicite', models.CharField(choices=[('annuelle', 'Annuelle'), ('semestrielle', 'Semestrielle'), ('trimestrielle', 'Trimestrielle'), ('mensuelle', 'Mensuelle')], default='annuelle', max_length=15)),
                ('statut', models.CharField(choices=[('a_payer', 'À payer'), ('proposee_compta', 'Proposée en compta'), ('payee', 'Payée'), ('en_retard', 'En retard')], default='a_payer', max_length=20)),
                ('ecriture_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name='Référence écriture comptable')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_prime', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances_prime', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': 'Échéance de prime',
                'verbose_name_plural': 'Échéances de prime',
                'ordering': ['date_echeance_paiement'],
                'indexes': [models.Index(fields=['police', 'date_echeance_paiement'], name='assurances__police__f57da0_idx'), models.Index(fields=['company', 'statut'], name='assurances__company_9c91d1_idx')],
            },
        ),
    ]
