# Generated by Django 5.1.4 on 2026-07-16 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0005_echeanceprime'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActifCouvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_actif', models.CharField(choices=[('site', 'Site'), ('vehicule', 'Véhicule'), ('equipement', 'Équipement'), ('autre', 'Autre')], default='autre', max_length=15)),
                ('actif_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name="Référence de l'actif (string-FK)")),
                ('actif_libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé (snapshot)')),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actifs_couverts', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actifs_couverts', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': 'Actif couvert',
                'verbose_name_plural': 'Actifs couverts',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['police', 'type_actif'], name='assurances__police__55f0c5_idx')],
            },
        ),
    ]
