# Generated by Django 5.1.4 on 2026-07-16 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0006_actifcouvert'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, default='', max_length=40)),
                ('date_survenance', models.DateField(verbose_name='Date de survenance')),
                ('date_declaration', models.DateField(auto_now_add=True, verbose_name='Date de déclaration')),
                ('nature_sinistre', models.TextField(blank=True, default='')),
                ('type_sinistre', models.CharField(choices=[('dommage_materiel', 'Dommage matériel'), ('responsabilite_civile', 'Responsabilité civile'), ('decennale', 'Décennale'), ('cyber', 'Cyber'), ('vol', 'Vol'), ('incendie', 'Incendie'), ('autre', 'Autre')], default='autre', max_length=25)),
                ('montant_estime_degats', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant estimé des dégâts')),
                ('statut', models.CharField(choices=[('declare', 'Déclaré'), ('en_expertise', 'En expertise'), ('indemnise', 'Indemnisé'), ('refuse', 'Refusé'), ('clos', 'Clos')], default='declare', max_length=15)),
                ('description', models.TextField(blank=True, default='')),
                ('flotte_sinistre_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sinistre véhicule lié (flotte)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_sinistre', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declarations_sinistre', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': 'Déclaration de sinistre',
                'verbose_name_plural': 'Déclarations de sinistre',
                'ordering': ['-date_survenance'],
                'indexes': [models.Index(fields=['company', 'statut'], name='assurances__company_ea2675_idx'), models.Index(fields=['company', 'type_sinistre'], name='assurances__company_c7755e_idx')],
                'unique_together': {('company', 'reference')},
            },
        ),
    ]
