# Generated by Django 5.1.4 on 2026-07-17 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0008_sinistreactivity'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndemnisationSinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_reclame', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('franchise_appliquee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Franchise appliquée (snapshot)')),
                ('montant_indemnise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_versement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indemnisations_sinistre', to='authentication.company', verbose_name='Société')),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indemnisation', to='assurances.declarationsinistre')),
            ],
            options={
                'verbose_name': 'Indemnisation de sinistre',
                'verbose_name_plural': 'Indemnisations de sinistre',
            },
        ),
    ]
