# Generated by Django 5.1.4 on 2026-07-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0009_indemnisationsinistre'),
    ]

    operations = [
        migrations.AddField(
            model_name='indemnisationsinistre',
            name='ecriture_ref',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Référence écriture comptable'),
        ),
    ]
