# Generated by Django 5.1.4 on 2026-07-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0010_indemnisationsinistre_ecriture_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationsinistre',
            name='risque_ref',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Risque ERM lié (string-FK NTGRC)'),
        ),
    ]
