# Generated by Django 5.1.4 on 2026-07-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0011_declarationsinistre_risque_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationsinistre',
            name='conteste',
            field=models.BooleanField(default=False, verbose_name='Contesté'),
        ),
        migrations.AddField(
            model_name='declarationsinistre',
            name='dossier_contentieux_ref',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Dossier contentieux lié (string-FK NTJUR)'),
        ),
    ]
