# Generated by Django 5.1.4 on 2026-07-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0012_declarationsinistre_conteste_and_more'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, null=True, upload_to='assurances/attestations/%Y/%m/', verbose_name='Attestation scannée')),
                ('date_emission', models.DateField(verbose_name="Date d'émission")),
                ('date_validite', models.DateField(verbose_name='Date de validité')),
                ('emise_pour', models.CharField(blank=True, default='', max_length=255, verbose_name='Émise pour (client / marché)')),
                ('statut', models.CharField(choices=[('valide', 'Valide'), ('expiree', 'Expirée')], default='valide', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_assurance', to='authentication.company', verbose_name='Société')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='assurances.policeassurance')),
            ],
            options={
                'verbose_name': "Attestation d'assurance",
                'verbose_name_plural': "Attestations d'assurance",
                'ordering': ['-date_validite'],
                'indexes': [models.Index(fields=['company', 'statut'], name='assurances__company_353d79_idx'), models.Index(fields=['police', '-date_validite'], name='assurances__police__c8985f_idx')],
            },
        ),
    ]
