# Generated by Django 5.1.4 on 2026-07-17 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0013_attestationassurance'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExigenceAssuranceMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marche_ref', models.PositiveIntegerField(verbose_name='Référence du marché (string-FK)')),
                ('type_police_requis', models.CharField(choices=[('rc_pro', 'RC professionnelle'), ('decennale', 'Décennale'), ('multirisque', 'Multirisque'), ('cyber', 'Cyber'), ('homme_cle', 'Homme-clé'), ('transport_marchandises', 'Transport de marchandises'), ('bris_machine', 'Bris de machine'), ('perte_exploitation', "Perte d'exploitation"), ('autre', 'Autre')], max_length=30, verbose_name='Type de police requis')),
                ('montant_couverture_minimum', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Couverture minimum exigée')),
                ('statut_verification', models.CharField(choices=[('a_verifier', 'À vérifier'), ('conforme', 'Conforme'), ('non_conforme', 'Non conforme')], default='a_verifier', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exigences_assurance_marche', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Exigence d'assurance de marché",
                'verbose_name_plural': "Exigences d'assurance de marché",
                'ordering': ['id'],
                'indexes': [models.Index(fields=['company', 'marche_ref'], name='assurances__company_47a186_idx')],
            },
        ),
    ]
