# Generated by Django 5.1.4 on 2026-07-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0014_exigenceassurancemarche'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeassurance',
            name='employe_ref',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Employé couvert (homme-clé, string-FK rh)'),
        ),
    ]
