# Generated by Django 5.1.4 on 2026-07-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurances', '0015_policeassurance_employe_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeassurance',
            name='cyber_clauses',
            field=models.JSONField(blank=True, default=dict, verbose_name='Clauses cyber (JSON)'),
        ),
    ]
