# Generated by Django 5.1.4 on 2026-06-19 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("installations", "0009_intervention_arrivee_gps_lat_and_more"),
        ("sav", "0005_contrat_renouvellement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "underperf_threshold_pct",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                ("auto_create_ticket", models.BooleanField(default=False)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_settings",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réglage supervision",
                "verbose_name_plural": "Réglages supervision",
            },
        ),
        migrations.CreateModel(
            name="MonitoringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="noop", max_length=40)),
                ("enabled", models.BooleanField(default=False)),
                ("credentials", models.JSONField(blank=True, default=dict)),
                (
                    "expected_annual_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_configs",
                        to="authentication.company",
                    ),
                ),
                (
                    "installation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_config",
                        to="installations.installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration de supervision",
                "verbose_name_plural": "Configurations de supervision",
                "ordering": ["-date_modification"],
                "indexes": [
                    models.Index(
                        fields=["company", "provider"],
                        name="monitoring__company_51916e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductionReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("period_days", models.PositiveIntegerField(default=1)),
                ("energy_kwh", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Saisie manuelle"),
                            ("auto", "Automatique"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_readings",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_readings",
                        to="installations.installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relevé de production",
                "verbose_name_plural": "Relevés de production",
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["company", "installation", "-date"],
                        name="monitoring__company_5e8363_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("source", "auto"),
                            models.Q(("external_id", ""), _negated=True),
                        ),
                        fields=("installation", "external_id"),
                        name="uniq_auto_reading_external_id",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UnderperformanceFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ratio_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_cloture", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="underperformance_flags",
                        to="authentication.company",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="underperformance_flags",
                        to="installations.installation",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="underperformance_flags",
                        to="sav.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Drapeau de sous-performance",
                "verbose_name_plural": "Drapeaux de sous-performance",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["company", "installation", "is_open"],
                        name="monitoring__company_cf467e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_open", True)),
                        fields=("installation",),
                        name="uniq_open_underperf_flag",
                    )
                ],
            },
        ),
    ]
