# Generated by Django 5.1.4 on 2026-06-30 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0033_fg318_contrat_prix'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guaranteed_year1_kwh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('degradation_pct_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_year', models.PositiveIntegerField()),
                ('compensation_mad_per_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('tolerance_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('note', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_warranties', to='authentication.company')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_warranty', to='installations.installation')),
            ],
            options={
                'verbose_name': 'Garantie de production',
                'verbose_name_plural': 'Garanties de production',
                'ordering': ['-date_modification'],
                'indexes': [models.Index(fields=['company', 'installation'], name='monitoring__company_3b5c5f_idx')],
            },
        ),
    ]
