# Generated by Django 5.1.4 on 2026-06-21 04:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120, verbose_name="Nom")),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Code"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_departements",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="DossierEmploye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricule",
                    models.CharField(max_length=30, verbose_name="Matricule"),
                ),
                ("nom", models.CharField(max_length=120, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=120, verbose_name="Prénom")),
                (
                    "cin",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="CIN"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Poste"
                    ),
                ),
                (
                    "date_embauche",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("anapec", "ANAPEC"),
                            ("stage", "Stage"),
                            ("interim", "Intérim"),
                        ],
                        default="cdi",
                        max_length=10,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("suspendu", "Suspendu"),
                            ("sorti", "Sorti"),
                        ],
                        default="actif",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "cout_horaire",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Coût horaire",
                    ),
                ),
                (
                    "rib",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="RIB"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_dossiers",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employes",
                        to="rh.departement",
                        verbose_name="Département",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossier_employe",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier employé",
                "verbose_name_plural": "Dossiers employés",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="departement",
            unique_together={("company", "nom")},
        ),
        migrations.AlterUniqueTogether(
            name="dossieremploye",
            unique_together={("company", "matricule")},
        ),
    ]
