# Generated by Django 5.1.4 on 2026-06-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("rh", "0003_dossieremploye_identite_legale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remuneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "periodicite",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("horaire", "Horaire"),
                            ("journalier", "Journalier"),
                            ("annuel", "Annuel"),
                        ],
                        default="mensuel",
                        max_length=12,
                        verbose_name="Périodicité",
                    ),
                ),
                ("date_effet", models.DateField(verbose_name="Date d'effet")),
                (
                    "motif",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Motif"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_remunerations",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remunerations",
                        to="rh.dossieremploye",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rémunération",
                "verbose_name_plural": "Rémunérations",
                "ordering": ["-date_effet", "-date_creation"],
            },
        ),
    ]
