# Generated by Django 5.1.4 on 2026-06-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("records", "0006_remove_tag_records_tag_company_nom_uniq_and_more"),
        ("rh", "0005_dossieremploye_contact_urgence"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEmploye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[
                            ("contrat", "Contrat"),
                            ("cin", "CIN"),
                            ("rib", "RIB"),
                            ("diplome", "Diplôme"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=10,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "date_expiration",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expiration"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Note"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "attachment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_employe",
                        to="records.attachment",
                        verbose_name="Pièce jointe",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_documents",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="rh.dossieremploye",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document employé",
                "verbose_name_plural": "Documents employés",
                "ordering": ["type_document", "-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["company", "employe"],
                        name="rh_document_company_2d5b71_idx",
                    ),
                    models.Index(
                        fields=["company", "date_expiration"],
                        name="rh_document_company_ac76db_idx",
                    ),
                ],
            },
        ),
    ]
