# Generated by Django 5.1.4 on 2026-06-22 14:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("rh", "0006_documentemploye"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dossieremploye",
            name="date_sortie",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de sortie"
            ),
        ),
        migrations.AddField(
            model_name="dossieremploye",
            name="motif_sortie",
            field=models.CharField(
                blank=True,
                choices=[
                    ("demission", "Démission"),
                    ("licenciement", "Licenciement"),
                    ("fin_contrat", "Fin de contrat"),
                    ("retraite", "Retraite"),
                    ("rupture_essai", "Rupture période d'essai"),
                    ("autre", "Autre"),
                ],
                default="",
                max_length=20,
                verbose_name="Motif de sortie",
            ),
        ),
        migrations.AlterField(
            model_name="dossieremploye",
            name="poste",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Poste (libre)"
            ),
        ),
        migrations.AlterField(
            model_name="dossieremploye",
            name="statut",
            field=models.CharField(
                choices=[
                    ("embauche", "Embauché"),
                    ("actif", "Actif"),
                    ("suspendu", "Suspendu"),
                    ("sorti", "Sorti"),
                ],
                default="actif",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intitule", models.CharField(max_length=120, verbose_name="Intitulé")),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Code"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_postes",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="postes",
                        to="rh.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste",
                "verbose_name_plural": "Postes",
                "ordering": ["intitule"],
                "unique_together": {("company", "intitule")},
            },
        ),
        migrations.AddField(
            model_name="dossieremploye",
            name="poste_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employes",
                to="rh.poste",
                verbose_name="Poste",
            ),
        ),
        migrations.CreateModel(
            name="TypeAbsence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, verbose_name="Code")),
                ("libelle", models.CharField(max_length=120, verbose_name="Libellé")),
                (
                    "decompte_jours_ouvres",
                    models.BooleanField(
                        default=True, verbose_name="Décompte en jours ouvrés"
                    ),
                ),
                (
                    "deduit_solde",
                    models.BooleanField(
                        default=True, verbose_name="Déduit du solde de congés"
                    ),
                ),
                (
                    "remunere",
                    models.BooleanField(default=True, verbose_name="Rémunéré"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_types_absence",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Type d'absence",
                "verbose_name_plural": "Types d'absence",
                "ordering": ["libelle"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="ElementSortie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=160, verbose_name="Libellé")),
                (
                    "type_element",
                    models.CharField(
                        choices=[
                            ("epi", "EPI"),
                            ("outil", "Outil"),
                            ("badge", "Badge"),
                            ("cles", "Clés"),
                            ("vehicule", "Véhicule"),
                            ("telephone", "Téléphone"),
                            ("ordinateur", "Ordinateur"),
                            ("acces_si", "Accès informatiques"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=12,
                        verbose_name="Type",
                    ),
                ),
                (
                    "recupere",
                    models.BooleanField(default=False, verbose_name="Récupéré"),
                ),
                (
                    "date_recuperation",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de récupération"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Note"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_elements_sortie",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements_sortie",
                        to="rh.dossieremploye",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément de sortie",
                "verbose_name_plural": "Éléments de sortie",
                "ordering": ["type_element", "libelle"],
                "indexes": [
                    models.Index(
                        fields=["company", "employe"],
                        name="rh_elements_company_670d9f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SoldeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField(verbose_name="Année")),
                (
                    "acquis",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Jours acquis",
                    ),
                ),
                (
                    "report",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Report année précédente",
                    ),
                ),
                (
                    "pris",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Jours pris",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_soldes_conge",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soldes_conge",
                        to="rh.dossieremploye",
                        verbose_name="Employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solde de congés",
                "verbose_name_plural": "Soldes de congés",
                "ordering": ["-annee", "employe"],
                "unique_together": {("company", "employe", "annee")},
            },
        ),
        migrations.CreateModel(
            name="DemandeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Du")),
                ("date_fin", models.DateField(verbose_name="Au")),
                (
                    "jours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Jours décomptés",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Motif"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("soumise", "Soumise"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                        ],
                        default="soumise",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_decision",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de décision"
                    ),
                ),
                (
                    "motif_refus",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Motif de refus",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rh_demandes_conge",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "decide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rh_demandes_decidees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Décidé par",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_conge",
                        to="rh.dossieremploye",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "type_absence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes",
                        to="rh.typeabsence",
                        verbose_name="Type d'absence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de congés",
                "verbose_name_plural": "Demandes de congés",
                "ordering": ["-date_debut", "-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["company", "employe"],
                        name="rh_demandec_company_53724f_idx",
                    ),
                    models.Index(
                        fields=["company", "statut"],
                        name="rh_demandec_company_892ec3_idx",
                    ),
                    models.Index(
                        fields=["company", "date_debut", "date_fin"],
                        name="rh_demandec_company_2a4df7_idx",
                    ),
                ],
            },
        ),
    ]
