# Generated by Django 5.1.4 on 2026-07-03 08:12

import apps.rh.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('records', '0007_comment_resolved'),
        ('rh', '0058_vivier_candidats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dossieremploye',
            name='rh_dossier_code_pointage_uniq',
        ),
        migrations.RenameIndex(
            model_name='elementintegration',
            new_name='rh_elementi_company_b191bf_idx',
            old_name='rh_el_int_comp_mod_idx',
        ),
        migrations.RenameIndex(
            model_name='elementintegrationemploye',
            new_name='rh_elementi_company_e61723_idx',
            old_name='rh_el_int_emp_comp_idx',
        ),
        migrations.AlterField(
            model_name='candidature',
            name='emails_auto',
            field=models.BooleanField(default=True, verbose_name='Emails automatiques'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='tags_vivier',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Tags vivier (séparés par virgule)'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='vivier',
            field=models.BooleanField(default=False, verbose_name='Au vivier'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='vivier_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rattachements', to='rh.candidature', verbose_name='Origine (vivier)'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_candidature_activites', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='rh.candidature', verbose_name='Candidature'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_candidature_activites', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='field',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Champ'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='new_value',
            field=models.TextField(blank=True, default='', verbose_name='Nouvelle valeur'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='old_value',
            field=models.TextField(blank=True, default='', verbose_name='Ancienne valeur'),
        ),
        migrations.AlterField(
            model_name='candidatureactivity',
            name='type',
            field=models.CharField(choices=[('log', 'Transition'), ('note', 'Note')], max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='competencerequise',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_competences_requises', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='competencerequise',
            name='competence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requise_pour_postes', to='rh.competence', verbose_name='Compétence'),
        ),
        migrations.AlterField(
            model_name='competencerequise',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='competencerequise',
            name='niveau_requis',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Non acquis'), (1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Confirmé'), (4, 'Expert')], default=2, verbose_name='Niveau requis'),
        ),
        migrations.AlterField(
            model_name='competencerequise',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_requises', to='rh.poste', verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='correctionpointage',
            name='ancienne_valeur',
            field=models.TextField(blank=True, default='', verbose_name='Ancienne valeur'),
        ),
        migrations.AlterField(
            model_name='correctionpointage',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_corrections_pointage', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='correctionpointage',
            name='champ',
            field=models.CharField(max_length=60, verbose_name='Champ modifié'),
        ),
        migrations.AlterField(
            model_name='correctionpointage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_corrections_pointage', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='correctionpointage',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='correctionpointage',
            name='motif',
            field=models.CharField(max_length=255, verbose_name='Motif'),
        ),
        migrations.AlterField(
            model_name='correctionpointage',
            name='nouvelle_valeur',
            field=models.TextField(blank=True, default='', verbose_name='Nouvelle valeur'),
        ),
        migrations.AlterField(
            model_name='correctionpointage',
            name='pointage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='rh.pointage', verbose_name='Pointage'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_demandes', to='records.attachment', verbose_name='Pièce jointe (PDF)'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_demandes', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_rh', to='rh.dossieremploye', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='Message (précision « autre »)'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='motif_refus',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motif de refus'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='statut',
            field=models.CharField(choices=[('soumise', 'Soumise'), ('traitee', 'Traitée'), ('refusee', 'Refusée')], default='soumise', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='traite_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Traité le'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rh_demandes_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AlterField(
            model_name='demanderh',
            name='type',
            field=models.CharField(choices=[('attestation_travail', 'Attestation de travail'), ('attestation_salaire', 'Attestation de salaire'), ('attestation_domiciliation', 'Attestation de domiciliation'), ('autre', 'Autre')], default='attestation_travail', max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='devicekiosque',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='devicekiosque',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_devices_kiosque', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='devicekiosque',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='devicekiosque',
            name='derniere_utilisation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière utilisation'),
        ),
        migrations.AlterField(
            model_name='devicekiosque',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='devicekiosque',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Empreinte'),
        ),
        migrations.AlterField(
            model_name='dossieremploye',
            name='code_pointage',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Code pointage (PIN)'),
        ),
        migrations.AlterField(
            model_name='employedevicemap',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_device_maps', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='employedevicemap',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='employedevicemap',
            name='device_user_id',
            field=models.CharField(max_length=60, verbose_name='ID employé (pointeuse)'),
        ),
        migrations.AlterField(
            model_name='employedevicemap',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_maps', to='rh.dossieremploye', verbose_name='Employé'),
        ),
        migrations.AlterField(
            model_name='entretienrecrutement',
            name='candidature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='rh.candidature', verbose_name='Candidature'),
        ),
        migrations.AlterField(
            model_name='entretienrecrutement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_entretiens_recrutement', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='entretienrecrutement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='entretienrecrutement',
            name='date_heure',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date et heure'),
        ),
        migrations.AlterField(
            model_name='entretienrecrutement',
            name='evaluateurs',
            field=models.ManyToManyField(blank=True, related_name='rh_entretiens_a_evaluer', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateurs'),
        ),
        migrations.AlterField(
            model_name='entretienrecrutement',
            name='statut',
            field=models.CharField(choices=[('planifie', 'Planifié'), ('realise', 'Réalisé'), ('annule', 'Annulé')], default='planifie', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='entretienrecrutement',
            name='type',
            field=models.CharField(choices=[('telephonique', 'Téléphonique'), ('technique', 'Technique'), ('rh', 'RH'), ('final', 'Final')], default='rh', max_length=15, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='gabaritemailrecrutement',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='gabaritemailrecrutement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_gabarits_email_recrutement', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='gabaritemailrecrutement',
            name='corps',
            field=models.TextField(verbose_name='Corps'),
        ),
        migrations.AlterField(
            model_name='gabaritemailrecrutement',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='gabaritemailrecrutement',
            name='etape',
            field=models.CharField(choices=[('recu', 'Reçu'), ('preselection', 'Présélection'), ('entretien', 'Entretien'), ('offre', 'Offre'), ('embauche', 'Embauché'), ('rejete', 'Rejeté')], max_length=20, verbose_name='Étape'),
        ),
        migrations.AlterField(
            model_name='gabaritemailrecrutement',
            name='objet',
            field=models.CharField(max_length=255, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='grillesalariale',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_grilles_salariales', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='grillesalariale',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='grillesalariale',
            name='date_effet',
            field=models.DateField(verbose_name="Date d'effet"),
        ),
        migrations.AlterField(
            model_name='grillesalariale',
            name='echelon',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Échelon'),
        ),
        migrations.AlterField(
            model_name='grillesalariale',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_salariales', to='rh.poste', verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='grillesalariale',
            name='salaire_max',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Salaire maximum (MAD)'),
        ),
        migrations.AlterField(
            model_name='grillesalariale',
            name='salaire_min',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Salaire minimum (MAD)'),
        ),
        migrations.AlterField(
            model_name='noteentretien',
            name='avis',
            field=models.CharField(choices=[('favorable', 'Favorable'), ('reserve', 'Réservé'), ('defavorable', 'Défavorable')], default='reserve', max_length=15, verbose_name='Avis'),
        ),
        migrations.AlterField(
            model_name='noteentretien',
            name='commentaire',
            field=models.TextField(blank=True, default='', verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='noteentretien',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_notes_entretien', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='noteentretien',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='noteentretien',
            name='entretien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='rh.entretienrecrutement', verbose_name='Entretien'),
        ),
        migrations.AlterField(
            model_name='noteentretien',
            name='evaluateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_notes_entretien', to=settings.AUTH_USER_MODEL, verbose_name='Évaluateur'),
        ),
        migrations.AlterField(
            model_name='noteentretien',
            name='notes_criteres',
            field=models.JSONField(blank=True, default=dict, verbose_name='Notes par critère'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='appliquee',
            field=models.BooleanField(default=False, verbose_name='Appliquée'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='appliquee_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appliquée le'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_periodes_fermeture', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='date_debut',
            field=models.DateField(verbose_name='Du'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='date_fin',
            field=models.DateField(verbose_name='Au'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='departements',
            field=models.ManyToManyField(blank=True, related_name='periodes_fermeture', to='rh.departement', verbose_name='Départements'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='libelle',
            field=models.CharField(max_length=200, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='periodefermeture',
            name='type_absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodes_fermeture', to='rh.typeabsence', verbose_name="Type d'absence"),
        ),
        migrations.AlterField(
            model_name='presencechantier',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS — latitude'),
        ),
        migrations.AlterField(
            model_name='presencechantier',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS — longitude'),
        ),
        migrations.AlterField(
            model_name='presencechantier',
            name='hors_zone',
            field=models.BooleanField(default=False, verbose_name='Hors zone (géofence)'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='candidature',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promesse_embauche', to='rh.candidature', verbose_name='Candidature'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_promesses_embauche', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='date_debut_proposee',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début proposée'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='date_signature',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signé le'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='expires_at',
            field=models.DateTimeField(default=apps.rh.models._default_promesse_expiry, verbose_name='Expire le'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='ip_adresse',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='poste_propose',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Poste proposé'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='salaire_propose',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Salaire proposé (MAD)'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='signataire_nom',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du signataire'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='statut',
            field=models.CharField(choices=[('envoyee', 'Envoyée'), ('signee', 'Signée'), ('expiree', 'Expirée')], default='envoyee', max_length=10, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='token',
            field=models.CharField(default=apps.rh.models._default_promesse_token, editable=False, max_length=64, unique=True, verbose_name='Jeton'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='type_contrat',
            field=models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('anapec', 'ANAPEC'), ('stage', 'Stage'), ('interim', 'Intérim')], default='cdi', max_length=10, verbose_name='Type de contrat'),
        ),
        migrations.AlterField(
            model_name='promesseembauche',
            name='user_agent',
            field=models.TextField(blank=True, default='', verbose_name='User agent'),
        ),
        migrations.AlterField(
            model_name='reglagerh',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rh_reglage', to='authentication.company', verbose_name='Société'),
        ),
        migrations.AlterField(
            model_name='reglagerh',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Modifié le'),
        ),
        migrations.AlterField(
            model_name='reglagerh',
            name='geofence_metres',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Géofence (mètres)'),
        ),
        migrations.AddConstraint(
            model_name='dossieremploye',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('code_pointage', ''), _negated=True)), fields=('company', 'code_pointage'), name='rh_dossier_code_pointage_uniq'),
        ),
    ]
