# Generated by Django 5.1.4 on 2026-07-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('rh', '0080_zrh9_retour_feedback360'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAppreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, verbose_name='Libellé')),
                ('mois_apres_embauche', models.JSONField(blank=True, default=list, help_text='Liste de nombres de mois, ex. [3, 12, 24].', verbose_name='Jalons (mois après embauche)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('campagne_cible', models.ForeignKey(blank=True, help_text="Vide = une campagne annuelle par défaut est créée/réutilisée à l'exécution.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_appreciation', to='rh.campagneevaluation', verbose_name='Campagne cible')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rh_plans_appreciation', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Plan d'appréciation",
                'verbose_name_plural': "Plans d'appréciation",
                'ordering': ['libelle'],
                'indexes': [models.Index(fields=['company', 'actif'], name='rh_planappr_comp_actif_idx')],
            },
        ),
    ]
