"""SOLMVP — coquille de migrations de l'app « rh ».

Migration d'ÉTAT SEUL générée par ``manage.py parquer_app rh`` :
``database_operations=[]`` — AUCUNE table supprimée, AUCUNE ligne de
``django_migrations`` touchée. Les modèles sortent seulement de l'état
Django ; les données restent intégralement en base.

Retour du module : ``manage.py migrate rh 0104_nthcm9_checkin_okr`` (renverse cet état),
puis suppression de ce fichier — docs/parked-modules.md §5.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0104_nthcm9_checkin_okr'),
        ('authentication', '0033_solmvp30b_customuser_sans_poste_ref'),
        ('education', '0021_solmvp_coquille'),
        ('paie', '0055_solmvp_coquille'),
        ('qhse', '0059_solmvp_coquille'),
        ('sav', '0064_solmvp14_detacher_apps_parquees'),
        ('stock', '0159_solmvp12_detacher_flotte_qhse_rh'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='AccidentTravail'),
                migrations.DeleteModel(name='AffectationRoster'),
                migrations.DeleteModel(name='AffectationVehicule'),
                migrations.DeleteModel(name='AttributionBadge'),
                migrations.DeleteModel(name='AvanceSalaire'),
                migrations.DeleteModel(name='AvantageSocial'),
                migrations.DeleteModel(name='AyantDroit'),
                migrations.DeleteModel(name='BesoinFormation'),
                migrations.DeleteModel(name='BulletinPaie'),
                migrations.DeleteModel(name='CandidatureActivity'),
                migrations.DeleteModel(name='CauserieParticipant'),
                migrations.DeleteModel(name='Certification'),
                migrations.DeleteModel(name='CheckInOkr'),
                migrations.DeleteModel(name='CompetenceEmploye'),
                migrations.DeleteModel(name='CompetenceRequise'),
                migrations.DeleteModel(name='CorrectionPointage'),
                migrations.DeleteModel(name='DemandeAllocation'),
                migrations.DeleteModel(name='DemandeConge'),
                migrations.DeleteModel(name='DemandeRH'),
                migrations.DeleteModel(name='DeviceKiosque'),
                migrations.DeleteModel(name='DocumentEmploye'),
                migrations.DeleteModel(name='DossierActivity'),
                migrations.DeleteModel(name='ElementIntegration'),
                migrations.DeleteModel(name='ElementIntegrationEmploye'),
                migrations.DeleteModel(name='ElementSortie'),
                migrations.DeleteModel(name='ElementsVariablesPaie'),
                migrations.DeleteModel(name='EmargementEpi'),
                migrations.DeleteModel(name='EmployeDeviceMap'),
                migrations.DeleteModel(name='EntretienSortie'),
                migrations.DeleteModel(name='EnveloppeManager'),
                migrations.DeleteModel(name='EvaluationNeufBox'),
                migrations.DeleteModel(name='FeedbackContinu'),
                migrations.DeleteModel(name='FeuilleTemps'),
                migrations.DeleteModel(name='GabaritEmailRecrutement'),
                migrations.DeleteModel(name='GrilleSalariale'),
                migrations.DeleteModel(name='Habilitation'),
                migrations.DeleteModel(name='HeuresSupp'),
                migrations.DeleteModel(name='HistoriqueCompetence'),
                migrations.DeleteModel(name='IncidentPresence'),
                migrations.DeleteModel(name='InscriptionFormation'),
                migrations.DeleteModel(name='JourBloqueConge'),
                migrations.DeleteModel(name='KeyResult'),
                migrations.DeleteModel(name='KeyResultIndividuel'),
                migrations.DeleteModel(name='LigneParcours'),
                migrations.DeleteModel(name='LigneRisqueChantier'),
                migrations.DeleteModel(name='NoteDeFrais'),
                migrations.DeleteModel(name='NoteEntretien'),
                migrations.DeleteModel(name='ObjectifIndividuel'),
                migrations.DeleteModel(name='OrdreMission'),
                migrations.DeleteModel(name='ParticipationEnquete'),
                migrations.DeleteModel(name='ParticipationPulse'),
                migrations.DeleteModel(name='PeriodeFermeture'),
                migrations.DeleteModel(name='PermisConduire'),
                migrations.DeleteModel(name='PlanActionEngagement'),
                migrations.DeleteModel(name='PlanAppreciation'),
                migrations.DeleteModel(name='PlanSuccession'),
                migrations.DeleteModel(name='PresenceChantier'),
                migrations.DeleteModel(name='PresquAccident'),
                migrations.DeleteModel(name='PrimeAttribuee'),
                migrations.DeleteModel(name='ProgressionParcours'),
                migrations.DeleteModel(name='PromesseEmbauche'),
                migrations.DeleteModel(name='PropositionRevision'),
                migrations.DeleteModel(name='RattachementFonctionnel'),
                migrations.DeleteModel(name='ReglageRH'),
                migrations.DeleteModel(name='Remuneration'),
                migrations.DeleteModel(name='ReponseEnquete'),
                migrations.DeleteModel(name='ReponsePulse'),
                migrations.DeleteModel(name='RetourFeedback360'),
                migrations.DeleteModel(name='Sanction'),
                migrations.DeleteModel(name='SoldeConge'),
                migrations.DeleteModel(name='TentativeQuiz'),
                migrations.DeleteModel(name='VisiteMedicale'),
                migrations.DeleteModel(name='AnalyseRisquesChantier'),
                migrations.DeleteModel(name='BadgeReconnaissance'),
                migrations.DeleteModel(name='CampagnePulse'),
                migrations.DeleteModel(name='CauserieSecurite'),
                migrations.DeleteModel(name='CycleRevisionSalariale'),
                migrations.DeleteModel(name='DotationEpi'),
                migrations.DeleteModel(name='EnqueteEngagement'),
                migrations.DeleteModel(name='EntretienRecrutement'),
                migrations.DeleteModel(name='EtapeParcours'),
                migrations.DeleteModel(name='EvaluationEmploye'),
                migrations.DeleteModel(name='ModeleIntegration'),
                migrations.DeleteModel(name='OkrIndividuel'),
                migrations.DeleteModel(name='Pointage'),
                migrations.DeleteModel(name='PosteCle'),
                migrations.DeleteModel(name='TypeAbsence'),
                migrations.DeleteModel(name='TypeLigneParcours'),
                migrations.DeleteModel(name='TypePrime'),
                migrations.DeleteModel(name='CampagneEvaluation'),
                migrations.DeleteModel(name='Candidature'),
                migrations.DeleteModel(name='EpiCatalogue'),
                migrations.DeleteModel(name='ObjectifEntreprise'),
                migrations.DeleteModel(name='ParcoursFormation'),
                migrations.DeleteModel(name='QuizFormation'),
                migrations.DeleteModel(name='SessionFormation'),
                migrations.DeleteModel(name='Competence'),
                migrations.DeleteModel(name='DossierEmploye'),
                migrations.DeleteModel(name='ModeleEvaluation'),
                migrations.DeleteModel(name='OuverturePoste'),
                migrations.DeleteModel(name='HoraireTravail'),
                migrations.DeleteModel(name='Poste'),
                migrations.DeleteModel(name='Departement'),
            ],
            database_operations=[],
        ),
    ]
