# Generated by Django 5.1.4 on 2026-06-21 04:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompteComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=20, verbose_name="Numéro de compte"),
                ),
                ("intitule", models.CharField(max_length=200, verbose_name="Intitulé")),
                (
                    "classe",
                    models.IntegerField(
                        choices=[
                            (1, "1 — Financement permanent"),
                            (2, "2 — Actif immobilisé"),
                            (3, "3 — Actif circulant (hors trésorerie)"),
                            (4, "4 — Passif circulant (hors trésorerie)"),
                            (5, "5 — Trésorerie"),
                            (6, "6 — Charges"),
                            (7, "7 — Produits"),
                            (8, "8 — Résultats"),
                        ],
                        verbose_name="Classe",
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("actif", "Actif"),
                            ("passif", "Passif"),
                            ("charge", "Charge"),
                            ("produit", "Produit"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="Sens",
                    ),
                ),
                (
                    "est_tiers",
                    models.BooleanField(default=False, verbose_name="Compte de tiers"),
                ),
                (
                    "lettrable",
                    models.BooleanField(default=False, verbose_name="Lettrable"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comptes_comptables",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte comptable",
                "verbose_name_plural": "Comptes comptables",
                "ordering": ["numero"],
            },
        ),
        migrations.CreateModel(
            name="CompteTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_compte",
                    models.CharField(
                        choices=[("banque", "Banque"), ("caisse", "Caisse")],
                        default="banque",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("libelle", models.CharField(max_length=120, verbose_name="Libellé")),
                (
                    "banque",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Banque"
                    ),
                ),
                (
                    "rib",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="RIB"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="IBAN"
                    ),
                ),
                (
                    "swift",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="SWIFT/BIC"
                    ),
                ),
                (
                    "devise",
                    models.CharField(
                        default="MAD", max_length=3, verbose_name="Devise"
                    ),
                ),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Solde initial",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comptes_tresorerie",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "compte_comptable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comptes_tresorerie",
                        to="compta.comptecomptable",
                        verbose_name="Compte comptable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte de trésorerie",
                "verbose_name_plural": "Comptes de trésorerie",
                "ordering": ["type_compte", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                ("libelle", models.CharField(max_length=120, verbose_name="Libellé")),
                (
                    "type_journal",
                    models.CharField(
                        choices=[
                            ("VTE", "Ventes"),
                            ("ACH", "Achats"),
                            ("BNK", "Banque"),
                            ("CSH", "Caisse"),
                            ("OD", "Opérations diverses"),
                            ("AN", "À-nouveaux"),
                        ],
                        max_length=5,
                        verbose_name="Type de journal",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journaux",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "compte_contrepartie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journaux_contrepartie",
                        to="compta.comptecomptable",
                        verbose_name="Compte de contrepartie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journaux",
                "ordering": ["code"],
                "unique_together": {("company", "code")},
            },
        ),
        migrations.CreateModel(
            name="EcritureComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Référence de pièce",
                    ),
                ),
                ("date_ecriture", models.DateField(verbose_name="Date d'écriture")),
                ("libelle", models.CharField(max_length=255, verbose_name="Libellé")),
                (
                    "statut",
                    models.CharField(
                        choices=[("brouillon", "Brouillon"), ("validee", "Validée")],
                        default="brouillon",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Type de document source",
                    ),
                ),
                (
                    "source_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID du document source"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créée le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ecritures",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_creees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créée par",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecritures",
                        to="compta.journal",
                        verbose_name="Journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture comptable",
                "verbose_name_plural": "Écritures comptables",
                "ordering": ["-date_ecriture", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LigneEcriture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Libellé"
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Débit",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Crédit",
                    ),
                ),
                (
                    "lettrage",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="Lettrage"
                    ),
                ),
                (
                    "tiers_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Type de tiers",
                    ),
                ),
                (
                    "tiers_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID du tiers"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_ecriture",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_ecriture",
                        to="compta.comptecomptable",
                        verbose_name="Compte",
                    ),
                ),
                (
                    "ecriture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="compta.ecriturecomptable",
                        verbose_name="Écriture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'écriture",
                "verbose_name_plural": "Lignes d'écriture",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PlanComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default="CGNC", max_length=20, verbose_name="Code du plan"
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        default="Plan comptable CGNC",
                        max_length=120,
                        verbose_name="Libellé",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans_comptables",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan comptable",
                "verbose_name_plural": "Plans comptables",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="comptecomptable",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comptes",
                to="compta.plancomptable",
                verbose_name="Plan comptable",
            ),
        ),
        migrations.AddConstraint(
            model_name="ecriturecomptable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_id__isnull", False)),
                fields=("company", "source_type", "source_id"),
                name="uniq_ecriture_par_source",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plancomptable",
            unique_together={("company", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="comptecomptable",
            unique_together={("company", "numero")},
        ),
    ]
