# Generated by Django 5.1.4 on 2026-06-21 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("compta", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciceComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Libellé"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Début")),
                ("date_fin", models.DateField(verbose_name="Fin")),
                (
                    "statut",
                    models.CharField(
                        choices=[("ouvert", "Ouvert"), ("cloture", "Clôturé")],
                        default="ouvert",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "an_reporte",
                    models.BooleanField(
                        default=False, verbose_name="À-nouveaux reportés"
                    ),
                ),
                (
                    "date_cloture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Clôturé le"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercices_comptables",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercice comptable",
                "verbose_name_plural": "Exercices comptables",
                "ordering": ["-date_debut"],
                "unique_together": {("company", "date_debut", "date_fin")},
            },
        ),
        migrations.CreateModel(
            name="PeriodeComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_periode",
                    models.CharField(
                        choices=[("mois", "Mois"), ("exercice", "Exercice")],
                        default="mois",
                        max_length=10,
                        verbose_name="Type de période",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Libellé"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Début")),
                ("date_fin", models.DateField(verbose_name="Fin")),
                (
                    "verrouillee",
                    models.BooleanField(default=False, verbose_name="Verrouillée"),
                ),
                (
                    "date_verrouillage",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verrouillée le"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodes_comptables",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "exercice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodes",
                        to="compta.exercicecomptable",
                        verbose_name="Exercice",
                    ),
                ),
                (
                    "verrouillee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodes_verrouillees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Verrouillée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Période comptable",
                "verbose_name_plural": "Périodes comptables",
                "ordering": ["-date_debut"],
                "unique_together": {("company", "date_debut", "date_fin")},
            },
        ),
    ]
