# Generated by Django 5.1.4 on 2026-06-22 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("compta", "0002_exercicecomptable_periodecomptable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Immobilisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Référence interne",
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("vehicule", "Véhicule"),
                            ("outillage", "Outillage"),
                            ("materiel", "Matériel"),
                            ("mobilier", "Mobilier"),
                            ("informatique", "Matériel informatique"),
                            ("autre", "Autre"),
                        ],
                        default="materiel",
                        max_length=15,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "cout",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Coût d'acquisition (HT)",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        max_digits=5,
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "date_acquisition",
                    models.DateField(verbose_name="Date d'acquisition"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immobilisations",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Immobilisation",
                "verbose_name_plural": "Immobilisations",
                "ordering": ["-date_acquisition", "-id"],
            },
        ),
    ]
