# Generated by Django 5.1.4 on 2026-06-22 10:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("compta", "0005_cessionimmobilisation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LigneReleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_operation", models.DateField(verbose_name="Date d'opération")),
                ("libelle", models.CharField(max_length=255, verbose_name="Libellé")),
                (
                    "reference",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Référence"
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("non_pointee", "Non pointée"),
                            ("rapprochee", "Rapprochée"),
                        ],
                        default="non_pointee",
                        max_length=12,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_releve",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de relevé",
                "verbose_name_plural": "Lignes de relevé",
                "ordering": ["date_operation", "id"],
            },
        ),
        migrations.CreateModel(
            name="PointageReleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages_releve",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "ligne_gl",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages_releve",
                        to="compta.ligneecriture",
                        verbose_name="Ligne du grand livre",
                    ),
                ),
                (
                    "ligne_releve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="compta.lignereleve",
                        verbose_name="Ligne de relevé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage de relevé",
                "verbose_name_plural": "Pointages de relevé",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="lignereleve",
            name="lignes_gl",
            field=models.ManyToManyField(
                related_name="lignes_releve",
                through="compta.PointageReleve",
                to="compta.ligneecriture",
                verbose_name="Lignes du grand livre",
            ),
        ),
        migrations.CreateModel(
            name="RapprochementBancaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Libellé"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Début de période")),
                ("date_fin", models.DateField(verbose_name="Fin de période")),
                (
                    "date_releve",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date du relevé"
                    ),
                ),
                (
                    "solde_releve",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Solde du relevé",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("en_cours", "En cours"), ("rapproche", "Rapproché")],
                        default="en_cours",
                        max_length=12,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_rapprochement",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Rapproché le"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapprochements_bancaires",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "compte_tresorerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rapprochements",
                        to="compta.comptetresorerie",
                        verbose_name="Compte de trésorerie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rapprochements_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapprochement bancaire",
                "verbose_name_plural": "Rapprochements bancaires",
                "ordering": ["-date_fin", "-id"],
            },
        ),
        migrations.AddField(
            model_name="lignereleve",
            name="rapprochement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lignes_releve",
                to="compta.rapprochementbancaire",
                verbose_name="Rapprochement",
            ),
        ),
        migrations.AddConstraint(
            model_name="pointagereleve",
            constraint=models.UniqueConstraint(
                fields=("ligne_releve", "ligne_gl"), name="uniq_pointage_releve_gl"
            ),
        ),
    ]
