# Generated by Django 5.1.4 on 2026-06-22 11:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("compta", "0006_lignereleve_pointagereleve_lignereleve_lignes_gl_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=120, verbose_name="Libellé")),
                (
                    "solde_initial",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Solde initial",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caisses",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "compte_tresorerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="caisses",
                        to="compta.comptetresorerie",
                        verbose_name="Compte de trésorerie (caisse)",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisses_responsable",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caisse",
                "verbose_name_plural": "Caisses",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="MouvementCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=10,
                        verbose_name="Sens",
                    ),
                ),
                ("date_mouvement", models.DateField(verbose_name="Date du mouvement")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant",
                    ),
                ),
                ("motif", models.CharField(max_length=255, verbose_name="Motif")),
                (
                    "justificatif",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Référence du justificatif",
                    ),
                ),
                (
                    "piece",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Pièce (document)",
                    ),
                ),
                (
                    "posted",
                    models.BooleanField(
                        default=False, verbose_name="Postée au grand livre"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements",
                        to="compta.caisse",
                        verbose_name="Caisse",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mouvements_caisse",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "compte_contrepartie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements_caisse",
                        to="compta.comptecomptable",
                        verbose_name="Compte de contrepartie",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_caisse_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Saisi par",
                    ),
                ),
                (
                    "ecriture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mouvements_caisse",
                        to="compta.ecriturecomptable",
                        verbose_name="Écriture comptable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de caisse",
                "verbose_name_plural": "Mouvements de caisse",
                "ordering": ["date_mouvement", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClotureCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_cloture", models.DateField(verbose_name="Date de clôture")),
                (
                    "solde_theorique",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Solde théorique",
                    ),
                ),
                (
                    "solde_compte",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Solde compté",
                    ),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Écart",
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clotures",
                        to="compta.caisse",
                        verbose_name="Caisse",
                    ),
                ),
                (
                    "cloturee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clotures_caisse",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Clôturée par",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clotures_caisse",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clôture de caisse",
                "verbose_name_plural": "Clôtures de caisse",
                "ordering": ["-date_cloture", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("caisse", "date_cloture"),
                        name="uniq_cloture_caisse_date",
                    )
                ],
            },
        ),
    ]
