# Generated by Django 5.1.4 on 2026-06-22 14:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("compta", "0007_caisse_mouvementcaisse_cloturecaisse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BordereauRemise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Référence"
                    ),
                ),
                ("date_remise", models.DateField(verbose_name="Date de remise")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("remis", "Remis en banque"),
                        ],
                        default="brouillon",
                        max_length=12,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Total remis",
                    ),
                ),
                (
                    "posted",
                    models.BooleanField(
                        default=False, verbose_name="Postée au grand livre"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bordereaux_remise",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "compte_tresorerie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bordereaux_remise",
                        to="compta.comptetresorerie",
                        verbose_name="Compte de trésorerie (banque)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bordereaux_remise_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "ecriture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bordereaux_remise",
                        to="compta.ecriturecomptable",
                        verbose_name="Écriture comptable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bordereau de remise",
                "verbose_name_plural": "Bordereaux de remise",
                "ordering": ["-date_remise", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Effet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[
                            ("recevoir", "À recevoir (client)"),
                            ("payer", "À payer (fournisseur)"),
                        ],
                        max_length=10,
                        verbose_name="Sens",
                    ),
                ),
                (
                    "type_effet",
                    models.CharField(
                        choices=[
                            ("cheque", "Chèque"),
                            ("traite", "Traite / LCN"),
                            ("billet", "Billet à ordre"),
                        ],
                        default="cheque",
                        max_length=10,
                        verbose_name="Type d'effet",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=60,
                        verbose_name="Numéro (chèque/traite)",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant",
                    ),
                ),
                ("date_emission", models.DateField(verbose_name="Date d'émission")),
                ("date_echeance", models.DateField(verbose_name="Date d'échéance")),
                (
                    "banque",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Banque (tirée/domiciliation)",
                    ),
                ),
                (
                    "tireur",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=160,
                        verbose_name="Tireur / bénéficiaire",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("portefeuille", "En portefeuille"),
                            ("remis", "Remis à l'encaissement"),
                            ("encaisse", "Encaissé"),
                            ("paye", "Payé"),
                            ("impaye", "Impayé / rejeté"),
                        ],
                        default="portefeuille",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "tiers_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Type de tiers",
                    ),
                ),
                (
                    "tiers_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID du tiers"
                    ),
                ),
                (
                    "frais_rejet",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Frais de rejet",
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "bordereau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="effets",
                        to="compta.bordereauremise",
                        verbose_name="Bordereau de remise",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="effets",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="effets_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Saisi par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Effet (chèque / traite)",
                "verbose_name_plural": "Effets (chèques / traites)",
                "ordering": ["date_echeance", "id"],
            },
        ),
        migrations.CreateModel(
            name="LignePrevisionnelTresorerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=255, verbose_name="Libellé")),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("credit", "Crédit / financement"),
                            ("leasing", "Leasing"),
                            ("salaire", "Salaires"),
                            ("impot", "Impôts / acomptes IS"),
                            ("loyer", "Loyer"),
                            ("encaissement", "Encaissement prévu"),
                            ("decaissement", "Décaissement prévu"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=15,
                        verbose_name="Catégorie",
                    ),
                ),
                ("date_prevue", models.DateField(verbose_name="Date prévue")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[
                            ("aucune", "Ponctuelle"),
                            ("hebdomadaire", "Hebdomadaire"),
                            ("mensuelle", "Mensuelle"),
                        ],
                        default="aucune",
                        max_length=15,
                        verbose_name="Récurrence",
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Commentaire",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes_previsionnel_tresorerie",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de prévisionnel de trésorerie",
                "verbose_name_plural": "Lignes de prévisionnel de trésorerie",
                "ordering": ["date_prevue", "id"],
            },
        ),
        migrations.CreateModel(
            name="VirementInterne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_virement", models.DateField(verbose_name="Date du virement")),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Libellé"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Référence"
                    ),
                ),
                (
                    "posted",
                    models.BooleanField(
                        default=False, verbose_name="Postée au grand livre"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virements_internes",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "compte_destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virements_recus",
                        to="compta.comptetresorerie",
                        verbose_name="Compte destination",
                    ),
                ),
                (
                    "compte_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="virements_emis",
                        to="compta.comptetresorerie",
                        verbose_name="Compte source",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="virements_internes_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Saisi par",
                    ),
                ),
                (
                    "ecriture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="virements_internes",
                        to="compta.ecriturecomptable",
                        verbose_name="Écriture comptable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Virement interne",
                "verbose_name_plural": "Virements internes",
                "ordering": ["-date_virement", "-id"],
            },
        ),
    ]
