# Generated by Django 5.1.4 on 2026-06-30 19:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0023_entiteconsolidation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppelTelephonique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead (id crm)')),
                ('numero', models.CharField(max_length=32, verbose_name='Numéro')),
                ('direction', models.CharField(choices=[('sortant', 'Sortant'), ('entrant', 'Entrant')], default='sortant', max_length=8, verbose_name='Direction')),
                ('issue', models.CharField(choices=[('repondu', 'Répondu'), ('sans_reponse', 'Sans réponse'), ('rappel', 'À rappeler'), ('faux_numero', 'Faux numéro')], default='repondu', max_length=14, verbose_name='Issue')),
                ('duree_secondes', models.PositiveIntegerField(default=0, verbose_name='Durée (s)')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('a_rappeler_le', models.DateField(blank=True, null=True, verbose_name='À rappeler le')),
                ('date_appel', models.DateTimeField(auto_now_add=True, verbose_name='Appelé le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_passes', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels_telephoniques', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Journal d'appel",
                'verbose_name_plural': "Journal d'appels",
                'ordering': ['-date_appel'],
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la campagne')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], default='email', max_length=8, verbose_name='Canal')),
                ('objet', models.CharField(blank=True, default='', max_length=255, verbose_name='Objet (email)')),
                ('corps', models.TextField(blank=True, default='', verbose_name='Message')),
                ('segment', models.JSONField(blank=True, default=dict, verbose_name='Critères de segment (JSON)')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoyee', 'Envoyée'), ('annulee', 'Annulée')], default='brouillon', max_length=12, verbose_name='Statut')),
                ('nb_destinataires', models.PositiveIntegerField(default=0, verbose_name='Destinataires')),
                ('nb_envois', models.PositiveIntegerField(default=0, verbose_name='Envoyés')),
                ('nb_ouvertures', models.PositiveIntegerField(default=0, verbose_name='Ouvertures')),
                ('nb_clics', models.PositiveIntegerField(default=0, verbose_name='Clics')),
                ('envoyee_le', models.DateTimeField(blank=True, null=True, verbose_name='Envoyée le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagnes_marketing', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Campagne email/SMS',
                'verbose_name_plural': 'Campagnes email/SMS',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeApprobationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Devis (id ventes)')),
                ('devis_reference', models.CharField(blank=True, default='', max_length=50, verbose_name='Référence devis')),
                ('motif', models.TextField(verbose_name='Motif de la non-conformité')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('commentaire_decision', models.TextField(blank=True, default='', verbose_name='Commentaire de décision')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Décidée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approbations_config', to='authentication.company', verbose_name='Société')),
                ('decideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approbations_decidees', to=settings.AUTH_USER_MODEL, verbose_name='Décideur')),
                ('demandeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approbations_demandees', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
            ],
            options={
                'verbose_name': "Demande d'approbation de configuration",
                'verbose_name_plural': "Demandes d'approbation de configuration",
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ECatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Catalogue', max_length=200, verbose_name='Titre')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token public')),
                ('produit_ids', models.JSONField(blank=True, default=list, verbose_name='Produits exposés (ids stock)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('expire_le', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecatalogues', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'E-catalogue public',
                'verbose_name_plural': 'E-catalogues publics',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ModeleDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('marche', models.CharField(choices=[('residentiel', 'Résidentiel'), ('industriel', 'Industriel/Commercial'), ('agricole', 'Agricole (pompage)')], default='residentiel', max_length=12, verbose_name='Marché')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('lignes_type', models.JSONField(blank=True, default=list, verbose_name='Lignes-types (JSON)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles_devis', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Modèle de devis',
                'verbose_name_plural': 'Modèles de devis',
                'ordering': ['marche', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='RelanceDevisAbandonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis_id', models.PositiveIntegerField(verbose_name='Devis (id ventes)')),
                ('devis_reference', models.CharField(blank=True, default='', max_length=50, verbose_name='Référence devis')),
                ('jours_sans_reponse', models.PositiveIntegerField(default=0, verbose_name='Jours sans réponse à la relance')),
                ('canal', models.CharField(blank=True, default='', max_length=20, verbose_name='Canal de relance')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('date_relance', models.DateTimeField(auto_now_add=True, verbose_name='Relancé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances_devis_abandonnes', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Relance devis abandonné',
                'verbose_name_plural': 'Relances devis abandonnés',
                'ordering': ['-date_relance'],
            },
        ),
        migrations.CreateModel(
            name='SequenceRelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la séquence')),
                ('stage_declencheur', models.CharField(blank=True, default='', max_length=40, verbose_name="Clé d'étape déclencheuse")),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences_relance', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Séquence de relance',
                'verbose_name_plural': 'Séquences de relance',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SessionGuidedSelling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marche', models.CharField(default='residentiel', max_length=12, verbose_name='Marché')),
                ('reponses', models.JSONField(blank=True, default=dict, verbose_name='Réponses (JSON)')),
                ('composition', models.JSONField(blank=True, default=dict, verbose_name='Composition proposée (JSON)')),
                ('complet', models.BooleanField(default=False, verbose_name='Complète')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_guided_selling', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_guided_selling', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Session de configuration guidée',
                'verbose_name_plural': 'Sessions de configuration guidée',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='CodePromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='Code')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('taux_remise', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux de remise (%)')),
                ('date_debut', models.DateField(verbose_name='Valable du')),
                ('date_fin', models.DateField(verbose_name='Valable au')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('nb_utilisations', models.PositiveIntegerField(default=0, verbose_name="Nombre d'utilisations")),
                ('ca_genere', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='CA généré (TTC)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_promotion', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Code de promotion',
                'verbose_name_plural': 'Codes de promotion',
                'ordering': ['-date_creation'],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='uniq_code_promotion')],
            },
        ),
        migrations.CreateModel(
            name='FormulaireIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du formulaire')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug public')),
                ('tag_prefill', models.CharField(blank=True, default='', max_length=80, verbose_name='Tag pré-rempli sur le lead')),
                ('type_installation', models.CharField(blank=True, default='', max_length=40, verbose_name="Type d'installation par défaut")),
                ('champs', models.JSONField(blank=True, default=list, verbose_name='Définition des champs (JSON)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires_intake', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Formulaire d'intake",
                'verbose_name_plural': "Formulaires d'intake",
                'ordering': ['nom'],
                'constraints': [models.UniqueConstraint(fields=('company', 'slug'), name='uniq_formulaire_intake_slug')],
            },
        ),
        migrations.CreateModel(
            name='MessageWhatsAppEntrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_message_id', models.CharField(max_length=128, verbose_name='ID message WhatsApp')),
                ('expediteur', models.CharField(max_length=32, verbose_name='Numéro expéditeur')),
                ('nom_profil', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom du profil')),
                ('texte', models.TextField(blank=True, default='', verbose_name='Texte')),
                ('lead_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead créé (id crm)')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('date_reception', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_whatsapp_entrants', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Message WhatsApp entrant',
                'verbose_name_plural': 'Messages WhatsApp entrants',
                'ordering': ['-date_reception'],
                'constraints': [models.UniqueConstraint(fields=('company', 'wa_message_id'), name='uniq_wa_message_entrant')],
            },
        ),
        migrations.CreateModel(
            name='OuverturePartage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, verbose_name='Token du lien de partage')),
                ('cible', models.CharField(choices=[('devis', 'Devis'), ('facture', 'Facture')], default='devis', max_length=8, verbose_name='Cible')),
                ('cible_reference', models.CharField(blank=True, default='', max_length=50, verbose_name='Référence document')),
                ('nb_ouvertures', models.PositiveIntegerField(default=0, verbose_name="Nombre d'ouvertures")),
                ('premier_vu_le', models.DateTimeField(blank=True, null=True, verbose_name='Premier vu le')),
                ('dernier_vu_le', models.DateTimeField(blank=True, null=True, verbose_name='Dernier vu le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouvertures_partage', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Ouverture de lien de partage',
                'verbose_name_plural': 'Ouvertures de liens de partage',
                'ordering': ['-dernier_vu_le'],
                'constraints': [models.UniqueConstraint(fields=('company', 'token'), name='uniq_ouverture_partage_token')],
            },
        ),
        migrations.CreateModel(
            name='EtapeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('delai_jours', models.PositiveIntegerField(default=0, verbose_name='Délai (jours depuis le déclenchement)')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('appel', 'Appel')], default='email', max_length=10, verbose_name='Canal')),
                ('modele_message', models.TextField(blank=True, default='', verbose_name='Modèle de message')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_sequence', to='authentication.company', verbose_name='Société')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='compta.sequencerelance', verbose_name='Séquence')),
            ],
            options={
                'verbose_name': 'Étape de séquence',
                'verbose_name_plural': 'Étapes de séquence',
                'ordering': ['sequence', 'ordre'],
                'constraints': [models.UniqueConstraint(fields=('sequence', 'ordre'), name='uniq_etape_sequence_ordre')],
            },
        ),
    ]
