# Generated by Django 5.1.4 on 2026-06-30 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0025_appeloffre_bordereauprix_cautionsoumission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptationDevisPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis_id', models.PositiveIntegerField(verbose_name='Id du devis')),
                ('option_choisie', models.CharField(blank=True, default='', max_length=120, verbose_name='Option choisie')),
                ('nom_signataire', models.CharField(max_length=200, verbose_name='Nom du signataire')),
                ('signature_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de signature')),
                ('accepte', models.BooleanField(default=False, verbose_name='Accepté')),
                ('signe_le', models.DateTimeField(blank=True, null=True, verbose_name='Signé le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptations_devis_portail', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Acceptation de devis (portail)',
                'verbose_name_plural': 'Acceptations de devis (portail)',
                'ordering': ['-date_creation'],
            },
        ),
    ]
