# Generated by Django 5.1.4 on 2026-06-30 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0026_acceptationdevisportail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementFacturePortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facture_id', models.PositiveIntegerField(verbose_name='Id de la facture')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant (MAD)')),
                ('methode', models.CharField(choices=[('carte', 'Carte (CMI)'), ('virement', 'Virement')], default='carte', max_length=8, verbose_name='Méthode')),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('paye', 'Payé'), ('echoue', 'Échoué')], default='initie', max_length=8, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, default='', max_length=64, verbose_name='Référence de transaction')),
                ('paye_le', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_facture_portail', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Paiement de facture (portail)',
                'verbose_name_plural': 'Paiements de facture (portail)',
                'ordering': ['-date_creation'],
            },
        ),
    ]
