# Generated by Django 5.1.4 on 2026-07-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0027_paiementfactureportail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClientPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='Id du client')),
                ('lead_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id du lead')),
                ('type_document', models.CharField(choices=[('facture_onee', 'Facture ONEE'), ('plan', 'Plan / schéma'), ('autre', 'Autre')], default='facture_onee', max_length=14, verbose_name='Type de document')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='compta/portail_docs/', verbose_name='Fichier')),
                ('traite', models.BooleanField(default=False, verbose_name="Traité (intégré à l'étude)")),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Déposé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_client_portail', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Document client (portail)',
                'verbose_name_plural': 'Documents client (portail)',
                'ordering': ['-date_depot'],
            },
        ),
    ]
