# Generated by Django 5.1.4 on 2026-07-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0028_documentclientportail'),
    ]

    operations = [
        migrations.CreateModel(
            name='JalonChantierPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chantier_id', models.PositiveIntegerField(verbose_name='Id du chantier')),
                ('libelle', models.CharField(max_length=120, verbose_name='Jalon')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('atteint', models.BooleanField(default=False, verbose_name='Atteint')),
                ('date_jalon', models.DateField(blank=True, null=True, verbose_name='Date du jalon')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jalons_chantier_portail', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Jalon de chantier (portail)',
                'verbose_name_plural': 'Jalons de chantier (portail)',
                'ordering': ['chantier_id', 'ordre', 'id'],
            },
        ),
    ]
