# Generated by Django 5.1.4 on 2026-07-01 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0029_jalonchantierportail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeTicketPortail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='Id du client')),
                ('chantier_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id du chantier')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('statut', models.CharField(choices=[('soumise', 'Soumise'), ('prise_en_charge', 'Prise en charge'), ('resolue', 'Résolue'), ('refusee', 'Refusée')], default='soumise', max_length=16, verbose_name='Statut')),
                ('ticket_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id du ticket SAV créé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_ticket_portail', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Demande de ticket SAV (portail)',
                'verbose_name_plural': 'Demandes de ticket SAV (portail)',
                'ordering': ['-date_creation'],
            },
        ),
    ]
