# Generated by Django 5.1.4 on 2026-07-01 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0030_demandeticketportail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom / raison sociale')),
                ('type_partenaire', models.CharField(choices=[('apporteur', "Apporteur d'affaires"), ('sous_revendeur', 'Sous-revendeur'), ('installateur', 'Installateur')], default='apporteur', max_length=16, verbose_name='Type de partenaire')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone')),
                ('taux_commission', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('token_acces', models.CharField(db_index=True, max_length=64, unique=True, verbose_name="Token d'accès")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partenaires', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Partenaire commercial',
                'verbose_name_plural': 'Partenaires commerciaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SoumissionLeadPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prospect', models.CharField(max_length=200, verbose_name='Nom du prospect')),
                ('telephone_prospect', models.CharField(blank=True, default='', max_length=30, verbose_name='Téléphone du prospect')),
                ('email_prospect', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email du prospect')),
                ('ville', models.CharField(blank=True, default='', max_length=120, verbose_name='Ville')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('statut', models.CharField(choices=[('soumis', 'Soumis'), ('qualifie', 'Qualifié'), ('converti', 'Converti'), ('rejete', 'Rejeté')], default='soumis', max_length=10, verbose_name='Statut')),
                ('lead_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id du lead créé')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Soumis le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions_lead_partenaire', to='authentication.company', verbose_name='Société')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='compta.partenaire', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Soumission de lead (partenaire)',
                'verbose_name_plural': 'Soumissions de lead (partenaire)',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
