# Generated by Django 5.1.4 on 2026-07-01 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0031_partenaire_soumissionleadpartenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionPartenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devis_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id du devis signé')),
                ('lead_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id du lead')),
                ('base_ht', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Base HT (MAD)')),
                ('taux', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant de commission (MAD)')),
                ('statut', models.CharField(choices=[('due', 'Due'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='due', max_length=8, verbose_name='Statut')),
                ('paye_le', models.DateField(blank=True, null=True, verbose_name='Payée le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_partenaire', to='authentication.company', verbose_name='Société')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='compta.partenaire', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Commission partenaire',
                'verbose_name_plural': 'Commissions partenaire',
                'ordering': ['-date_creation'],
            },
        ),
    ]
