# Generated by Django 5.1.4 on 2026-07-01 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0032_commissionpartenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoireCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom du territoire')),
                ('villes', models.JSONField(blank=True, default=list, verbose_name='Villes / régions (liste)')),
                ('owner_user_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Commercial responsable (id)')),
                ('priorite', models.IntegerField(default=0, verbose_name='Priorité (haute = prioritaire)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territoires_commerciaux', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Territoire commercial',
                'verbose_name_plural': 'Territoires commerciaux',
                'ordering': ['-priorite', 'nom'],
            },
        ),
    ]
