# Generated by Django 5.1.4 on 2026-07-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0033_territoirecommercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='date_activation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'activation"),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='numero_agrement',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name="Numéro d'agrément"),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='statut_onboarding',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('en_cours', "En cours d'agrément"), ('agree', 'Agréé (activé)'), ('suspendu', 'Suspendu')], default='prospect', max_length=12, verbose_name="Statut d'onboarding"),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Zone géographique'),
        ),
    ]
