# Generated by Django 5.1.4 on 2026-07-01 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0034_partenaire_date_activation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueteNPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='Id du client')),
                ('chantier_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Id du chantier')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Note (0–10)')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('repondue', 'Répondue')], default='envoyee', max_length=8, verbose_name='Statut')),
                ('envoi_reel', models.BooleanField(default=False, verbose_name='Envoi réel effectué (Brevo)')),
                ('envoyee_le', models.DateTimeField(auto_now_add=True, verbose_name='Envoyée le')),
                ('repondue_le', models.DateTimeField(blank=True, null=True, verbose_name='Répondue le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_nps', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Enquête NPS',
                'verbose_name_plural': 'Enquêtes NPS',
                'ordering': ['-envoyee_le'],
            },
        ),
    ]
