# Generated by Django 5.1.4 on 2026-07-01 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0035_enquetenps'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='Id du client')),
                ('note', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Note (1–5)')),
                ('temoignage', models.TextField(blank=True, default='', verbose_name='Témoignage')),
                ('statut', models.CharField(choices=[('sollicite', 'Sollicité'), ('recu', 'Reçu'), ('publie_google', 'Routé vers Google')], default='sollicite', max_length=14, verbose_name='Statut')),
                ('google_review_url', models.URLField(blank=True, default='', verbose_name='Lien Google Reviews')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_clients', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-date_creation'],
            },
        ),
    ]
