# Generated by Django 5.1.4 on 2026-07-01 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0036_avisclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='Id du client')),
                ('points', models.IntegerField(default=0, verbose_name='Solde de points')),
                ('palier', models.CharField(choices=[('bronze', 'Bronze'), ('argent', 'Argent'), ('or', 'Or'), ('platine', 'Platine')], default='bronze', max_length=10, verbose_name='Palier')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_fidelite', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Compte de fidélité',
                'verbose_name_plural': 'Comptes de fidélité',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='MouvementFidelite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='Points (+ gain / − dépense)')),
                ('motif', models.CharField(blank=True, default='', max_length=200, verbose_name='Motif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_fidelite', to='authentication.company', verbose_name='Société')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='compta.comptefidelite', verbose_name='Compte de fidélité')),
            ],
            options={
                'verbose_name': 'Mouvement de fidélité',
                'verbose_name_plural': 'Mouvements de fidélité',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='comptefidelite',
            constraint=models.UniqueConstraint(fields=('company', 'client_id'), name='uniq_compte_fidelite_client'),
        ),
    ]
