# Generated by Django 5.1.4 on 2026-07-01 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0037_comptefidelite_mouvementfidelite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegleUpsell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declencheur', models.CharField(choices=[('sans_batterie', 'Client sans batterie'), ('site_unique', 'Un seul site équipé'), ('sans_contrat_om', 'Sans contrat O&M'), ('installation_ancienne', 'Installation ancienne')], max_length=24, verbose_name='Déclencheur de contexte')),
                ('produit_suggere', models.CharField(max_length=200, verbose_name='Produit / service suggéré')),
                ('message', models.CharField(blank=True, default='', max_length=255, verbose_name='Message commercial')),
                ('priorite', models.IntegerField(default=0, verbose_name='Priorité (haute = affichée en premier)')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regles_upsell', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Règle d'upsell / cross-sell",
                'verbose_name_plural': "Règles d'upsell / cross-sell",
                'ordering': ['-priorite', 'id'],
            },
        ),
    ]
