# Generated by Django 5.1.4 on 2026-07-01 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0038_regleupsell'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonnementMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='Id du client')),
                ('installation_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="Id de l'installation")),
                ('periodicite', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], default='mensuel', max_length=8, verbose_name='Périodicité')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant par période (MAD)')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='actif', max_length=8, verbose_name='Statut')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('prochaine_echeance', models.DateField(blank=True, null=True, verbose_name='Prochaine échéance')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements_monitoring', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Abonnement de monitoring',
                'verbose_name_plural': 'Abonnements de monitoring',
                'ordering': ['prochaine_echeance', 'id'],
            },
        ),
    ]
