# Generated by Django 5.1.4 on 2026-07-01 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0039_abonnementmonitoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('fichier', models.FileField(upload_to='compta/pieces/%Y/%m/', verbose_name='Fichier justificatif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces_justificatives_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='authentication.company', verbose_name='Société')),
                ('ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='compta.ecriturecomptable', verbose_name='Écriture')),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'verbose_name_plural': 'Pièces justificatives',
                'ordering': ['-date_creation', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CompteAuxiliaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_tiers', models.CharField(choices=[('client', 'Client'), ('fournisseur', 'Fournisseur')], max_length=12, verbose_name='Type de tiers')),
                ('tiers_id', models.PositiveIntegerField(verbose_name='ID du tiers')),
                ('code', models.CharField(max_length=20, verbose_name='Code auxiliaire')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes_auxiliaires', to='authentication.company', verbose_name='Société')),
                ('compte_collectif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auxiliaires', to='compta.comptecomptable', verbose_name='Compte collectif')),
            ],
            options={
                'verbose_name': 'Compte auxiliaire',
                'verbose_name_plural': 'Comptes auxiliaires',
                'ordering': ['type_tiers', 'code'],
                'unique_together': {('company', 'code'), ('company', 'type_tiers', 'tiers_id')},
            },
        ),
        migrations.CreateModel(
            name='MappingCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_clef', models.CharField(choices=[('famille', 'Famille de produit'), ('tva', 'Taux de TVA'), ('paiement', 'Mode de paiement')], max_length=10, verbose_name='Type de clef')),
                ('clef', models.CharField(max_length=60, verbose_name='Clef (famille / taux / mode)')),
                ('libelle', models.CharField(blank=True, default='', max_length=120, verbose_name='Libellé')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings_compte', to='authentication.company', verbose_name='Société')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings', to='compta.comptecomptable', verbose_name='Compte comptable')),
            ],
            options={
                'verbose_name': 'Mapping document → compte',
                'verbose_name_plural': 'Mappings document → compte',
                'ordering': ['type_clef', 'clef'],
                'unique_together': {('company', 'type_clef', 'clef')},
            },
        ),
    ]
