# Generated by Django 5.1.4 on 2026-07-01 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0040_piecejustificative_compteauxiliaire_mappingcompte'),
    ]

    operations = [
        migrations.CreateModel(
            name='PisteAuditComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='Rang dans la chaîne')),
                ('empreinte_contenu', models.CharField(max_length=64, verbose_name='Empreinte du contenu')),
                ('hash_precedent', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash précédent')),
                ('hash', models.CharField(max_length=64, verbose_name='Hash du maillon')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Scellé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pistes_audit_compta', to='authentication.company', verbose_name='Société')),
                ('ecriture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='piste_audit', to='compta.ecriturecomptable', verbose_name='Écriture')),
            ],
            options={
                'verbose_name': "Maillon de piste d'audit comptable",
                'verbose_name_plural': "Piste d'audit comptable",
                'ordering': ['company', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('company', 'sequence'), name='uniq_piste_seq_par_soc')],
            },
        ),
    ]
