# Generated by Django 5.1.4 on 2026-07-05 14:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0077_rapportnotefrais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeconstateeavance',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant total à étaler'),
        ),
        migrations.AlterField(
            model_name='dotationderogatoire',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Différence (dérogatoire)'),
        ),
        migrations.AlterField(
            model_name='dotationderogatoire',
            name='dotation_comptable',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Dotation comptable'),
        ),
        migrations.AlterField(
            model_name='dotationderogatoire',
            name='dotation_fiscale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Dotation fiscale'),
        ),
        migrations.AlterField(
            model_name='dotationetalement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Dotation'),
        ),
        migrations.AlterField(
            model_name='ecartchange',
            name='difference',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Écart (signé, MAD)'),
        ),
        migrations.AlterField(
            model_name='echeanceemprunt',
            name='capital_restant_du',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Capital restant dû après échéance'),
        ),
        migrations.AlterField(
            model_name='echeanceemprunt',
            name='interets',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name="Part d'intérêts"),
        ),
        migrations.AlterField(
            model_name='echeanceemprunt',
            name='mensualite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Mensualité'),
        ),
        migrations.AlterField(
            model_name='echeanceemprunt',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Part de principal'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='capital',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Capital emprunté (MAD)'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='taux_annuel',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, verbose_name='Taux annuel (%)'),
        ),
        migrations.AlterField(
            model_name='lignereevaluation',
            name='ecart',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Écart latent (signé, MAD)'),
        ),
        migrations.AlterField(
            model_name='ligneregleimputation',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Pourcentage (%)'),
        ),
        migrations.AlterField(
            model_name='ligneventilation',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Pourcentage (%)'),
        ),
        migrations.AlterField(
            model_name='reevaluationcloture',
            name='total_ecart',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total des écarts latents (signé, MAD)'),
        ),
        migrations.AlterField(
            model_name='tauxdevise',
            name='taux_vers_mad',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=14, verbose_name='Taux vers MAD (1 devise = X MAD)'),
        ),
    ]
