# Generated by Django 5.1.4 on 2026-07-17 07:21

import apps.compta.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0111_odx19_repoint_achats_crossapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comptetresorerie',
            name='seuil_alerte_bas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Notifie quand le solde passe sous ce seuil (vide = aucune).', max_digits=14, null=True, verbose_name="Seuil d'alerte bas"),
        ),
        migrations.AddField(
            model_name='comptetresorerie',
            name='seuil_alerte_decouvert',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Notifie quand le solde passe sous ce seuil (vide = aucune).', max_digits=14, null=True, verbose_name='Seuil de découvert'),
        ),
        migrations.AddField(
            model_name='effet',
            name='date_protet',
            field=models.DateField(blank=True, null=True, verbose_name='Date du protêt'),
        ),
        migrations.AddField(
            model_name='effet',
            name='frais_protet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Frais de protêt'),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='approbateur_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compta_payment_runs_approuves_1', to=settings.AUTH_USER_MODEL, verbose_name='Premier approbateur'),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='approbateur_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compta_payment_runs_approuves_2', to=settings.AUTH_USER_MODEL, verbose_name='Second approbateur'),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='date_approbation_1',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Première approbation le'),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='date_approbation_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Seconde approbation le'),
        ),
        migrations.AlterField(
            model_name='paymentrun',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('proposee', 'Proposition figée'), ('en_attente_approbation', "En attente d'approbation"), ('postee', 'Postée au grand livre')], default='brouillon', max_length=24, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='PouvoirBancaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulaire_nom', models.CharField(max_length=160, verbose_name='Titulaire (nom)')),
                ('titulaire_cin', models.CharField(blank=True, default='', max_length=40, verbose_name='CIN du titulaire')),
                ('plafond_signature_seul', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant max engageable seul (0 = aucune signature seule).', max_digits=14, verbose_name='Plafond signature seul')),
                ('plafond_signature_conjointe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Plafond signature conjointe')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Début de validité')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin de validité')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('revoque', 'Révoqué')], default='actif', max_length=10, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('compte_tresorerie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pouvoirs_bancaires', to='compta.comptetresorerie', verbose_name='Compte de trésorerie')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pouvoirs_bancaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ERP')),
            ],
            options={
                'verbose_name': 'Pouvoir bancaire',
                'verbose_name_plural': 'Pouvoirs bancaires',
                'ordering': ['titulaire_nom', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ParametresTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('double_validation_paiement_actif', models.BooleanField(default=False, help_text='NTTRE5 — exige deux approbateurs distincts avant de poster une campagne de règlement.', verbose_name='Double validation des paiements')),
                ('delai_alerte_rupture_jours', models.PositiveIntegerField(default=14, verbose_name='Délai alerte rupture (jours)')),
                ('format_export_virement_defaut', models.CharField(choices=[('csv', 'CSV générique'), ('bancaire', 'Format banque marocaine (largeur fixe)')], default='csv', max_length=10, verbose_name='Format export virement')),
                ('scenario_previsionnel_defaut', models.CharField(choices=[('realiste', 'Réaliste'), ('optimiste', 'Optimiste'), ('pessimiste', 'Pessimiste')], default='realiste', max_length=12, verbose_name='Scénario prévisionnel')),
                ('comptes_frais_bancaires', models.JSONField(blank=True, default=apps.compta.models._comptes_frais_defaut, help_text="Numéros de compte suivis par l'analyse des frais (NTTRE9).", verbose_name='Comptes de frais bancaires (CGNC)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Paramètres trésorerie',
                'verbose_name_plural': 'Paramètres trésorerie',
                'constraints': [models.UniqueConstraint(fields=('company',), name='uniq_parametres_tresorerie_company')],
            },
        ),
    ]
