# Generated by Django 5.1.4 on 2026-07-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0112_nttre5_8_paymentrun_pouvoirs_seuils_effet_protet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligneprevisionneltresorerie',
            name='scenario',
            field=models.CharField(choices=[('realiste', 'Réaliste'), ('optimiste', 'Optimiste'), ('pessimiste', 'Pessimiste')], default='realiste', max_length=12, verbose_name='Scénario'),
        ),
        migrations.AddField(
            model_name='lignereleve',
            name='devise',
            field=models.CharField(default='MAD', max_length=3, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='lignereleve',
            name='taux_change',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Taux du jour de l'opération ; vide pour une ligne en MAD.", max_digits=12, null=True, verbose_name='Taux de change (vers MAD)'),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='format_export',
            field=models.CharField(choices=[('csv', 'CSV générique'), ('bancaire', 'Format banque marocaine (largeur fixe)')], default='csv', max_length=10, verbose_name="Format d'export virement"),
        ),
        migrations.CreateModel(
            name='PlanRelanceTresorerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=160, verbose_name='Nom du plan')),
                ('segment_client', models.CharField(blank=True, default='', help_text='Vide = plan par défaut (tous segments).', max_length=60, verbose_name='Segment client')),
                ('paliers', models.JSONField(blank=True, default=list, help_text='Liste de {jours, canal, libelle} — ex. J+7 email doux…', verbose_name='Paliers')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Plan de relance trésorerie',
                'verbose_name_plural': 'Plans de relance trésorerie',
                'ordering': ['nom', 'id'],
            },
        ),
    ]
