# Generated by Django 5.1.4 on 2026-07-17 10:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0113_nttre11_13_14_16_relance_devise_format_scenario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Début de période')),
                ('date_fin', models.DateField(verbose_name='Fin de période')),
                ('devise_presentation', models.CharField(default='MAD', max_length=3, verbose_name='Devise de présentation (ISO 4217)')),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('collecte', 'Collecte'), ('eliminations', 'Éliminations'), ('valide', 'Validé'), ('publie', 'Publié')], default='ouvert', max_length=14, verbose_name='Statut')),
                ('verrouille', models.BooleanField(default=False, verbose_name='Verrouillé')),
                ('tolerance_interco', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Écart absolu toléré pour apparier deux soldes réciproques.', max_digits=14, verbose_name='Tolérance de matching interco')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles_consolidation', to='compta.exercicecomptable', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Cycle de consolidation',
                'verbose_name_plural': 'Cycles de consolidation',
                'ordering': ['-date_debut', '-id'],
            },
        ),
        migrations.AddField(
            model_name='entiteconsolidation',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entites', to='compta.cycleconsolidation', verbose_name='Cycle de consolidation'),
        ),
        migrations.CreateModel(
            name='EcritureElimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_elimination', models.CharField(choices=[('reciproque', 'Créances/dettes réciproques'), ('marge_interne', 'Marge interne sur stock'), ('dividende', 'Dividendes internes'), ('titres', 'Titres de participation'), ('minoritaires', 'Intérêts minoritaires')], default='reciproque', max_length=14, verbose_name="Type d'élimination")),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('lignes', models.JSONField(blank=True, default=list, verbose_name="Lignes d'élimination")),
                ('automatique', models.BooleanField(default=False, verbose_name='Générée automatiquement')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminations', to='compta.cycleconsolidation', verbose_name='Cycle de consolidation')),
            ],
            options={
                'verbose_name': "Écriture d'élimination",
                'verbose_name_plural': "Écritures d'élimination",
                'ordering': ['cycle', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EliminationTitres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valeur_titres', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valeur des titres')),
                ('quote_part_capitaux_propres', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Quote-part de capitaux propres')),
                ('ecart_acquisition', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name="Écart d'acquisition (goodwill)")),
                ('methode', models.CharField(choices=[('acquisition', "Méthode de l'acquisition"), ('equivalence', 'Mise en équivalence')], default='acquisition', max_length=12, verbose_name='Méthode')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminations_titres', to='compta.cycleconsolidation', verbose_name='Cycle de consolidation')),
                ('elimination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminations_titres', to='compta.ecritureelimination', verbose_name="Écriture d'élimination générée")),
                ('entite_fille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eliminations_titres', to='authentication.company', verbose_name='Entité fille')),
            ],
            options={
                'verbose_name': 'Élimination de titres',
                'verbose_name_plural': 'Éliminations de titres',
                'ordering': ['cycle', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LiasseRemontee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('a_collecter', 'À collecter'), ('collecte', 'Collectée'), ('valide', 'Validée')], default='a_collecter', max_length=12, verbose_name='Statut')),
                ('date_collecte', models.DateTimeField(blank=True, null=True, verbose_name='Collectée le')),
                ('devise_locale', models.CharField(default='MAD', max_length=3, verbose_name='Devise locale (ISO 4217)')),
                ('snapshot_balance', models.JSONField(blank=True, default=list, verbose_name='Snapshot de balance')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liasses', to='compta.cycleconsolidation', verbose_name='Cycle de consolidation')),
                ('entite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liasses_remontee', to='authentication.company', verbose_name='Entité')),
            ],
            options={
                'verbose_name': 'Liasse de remontée',
                'verbose_name_plural': 'Liasses de remontée',
                'ordering': ['cycle', 'entite'],
            },
        ),
        migrations.CreateModel(
            name='MappingConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_local_prefixe', models.CharField(max_length=20, verbose_name='Préfixe de compte local')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('compte_groupe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mappings_consolidation', to='compta.comptecomptable', verbose_name='Compte de groupe')),
            ],
            options={
                'verbose_name': 'Mapping de consolidation',
                'verbose_name_plural': 'Mappings de consolidation',
                'ordering': ['plan_local_prefixe'],
            },
        ),
        migrations.CreateModel(
            name='MargeInterneStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('montant_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant du stock détenu')),
                ('taux_marge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taux de marge (%)')),
                ('taux_impot', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=5, verbose_name="Taux d'impôt différé (%)")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marges_internes', to='compta.cycleconsolidation', verbose_name='Cycle de consolidation')),
                ('elimination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marges_internes', to='compta.ecritureelimination', verbose_name="Écriture d'élimination générée")),
                ('entite_acheteuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marges_internes_acheteuse', to='authentication.company', verbose_name='Entité acheteuse')),
                ('entite_vendeuse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marges_internes_vendeuse', to='authentication.company', verbose_name='Entité vendeuse')),
            ],
            options={
                'verbose_name': 'Marge interne sur stock',
                'verbose_name_plural': 'Marges internes sur stock',
                'ordering': ['cycle', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperationInterco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_reciproque', models.CharField(max_length=20, verbose_name='Compte réciproque (CGNC)')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('montant_declare_a', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant déclaré (débit)')),
                ('montant_declare_b', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant déclaré (crédit)')),
                ('ecart', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Écart')),
                ('statut', models.CharField(choices=[('non_apparie', 'Non apparié'), ('apparie', 'Apparié'), ('ecart', 'Écart')], default='non_apparie', max_length=12, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercos', to='compta.cycleconsolidation', verbose_name='Cycle de consolidation')),
                ('entite_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercos_credit', to='authentication.company', verbose_name='Entité créditrice')),
                ('entite_debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intercos_debit', to='authentication.company', verbose_name='Entité débitrice')),
            ],
            options={
                'verbose_name': 'Opération inter-sociétés',
                'verbose_name_plural': 'Opérations inter-sociétés',
                'ordering': ['cycle', 'id'],
            },
        ),
        migrations.AddField(
            model_name='ecritureelimination',
            name='source_interco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminations', to='compta.operationinterco', verbose_name='Opération interco source'),
        ),
        migrations.AddConstraint(
            model_name='cycleconsolidation',
            constraint=models.UniqueConstraint(fields=('company', 'exercice', 'libelle'), name='uniq_cycle_consol_par_exercice'),
        ),
        migrations.AddConstraint(
            model_name='liasseremontee',
            constraint=models.UniqueConstraint(fields=('cycle', 'entite'), name='uniq_liasse_cycle_entite'),
        ),
        migrations.AddConstraint(
            model_name='mappingconsolidation',
            constraint=models.UniqueConstraint(fields=('company', 'plan_local_prefixe'), name='uniq_mapping_consol_prefixe'),
        ),
    ]
