# Generated by Django 5.1.4 on 2026-07-17 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0114_ntfin_consolidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxeAnalytique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('libelle', models.CharField(max_length=120, verbose_name='Libellé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Axe analytique',
                'verbose_name_plural': 'Axes analytiques',
                'ordering': ['ordre', 'code'],
            },
        ),
        migrations.AddField(
            model_name='centrecout',
            name='axe_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centres_cout', to='compta.axeanalytique', verbose_name='Axe analytique (configurable)'),
        ),
        migrations.CreateModel(
            name='ImputationAxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('axe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputations', to='compta.axeanalytique', verbose_name='Axe analytique')),
                ('centre_cout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputations_axes', to='compta.centrecout', verbose_name="Centre de coût (valeur de l'axe)")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ligne_ecriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations_axes', to='compta.ligneecriture', verbose_name="Ligne d'écriture")),
            ],
            options={
                'verbose_name': 'Imputation analytique multi-axes',
                'verbose_name_plural': 'Imputations analytiques multi-axes',
                'ordering': ['ligne_ecriture', 'axe'],
            },
        ),
        migrations.CreateModel(
            name='ReferentielComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('CGNC', 'CGNC (Maroc)'), ('IFRS', 'IFRS'), ('GROUPE', 'Référentiel de groupe'), ('FISCAL', 'Référentiel fiscal')], default='CGNC', max_length=10, verbose_name='Code du référentiel')),
                ('libelle', models.CharField(max_length=120, verbose_name='Libellé')),
                ('devise_fonctionnelle', models.CharField(default='MAD', max_length=3, verbose_name='Devise fonctionnelle')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('est_principal', models.BooleanField(default=False, verbose_name='Référentiel principal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Référentiel comptable',
                'verbose_name_plural': 'Référentiels comptables',
                'ordering': ['company', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AjustementGaap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_ajustement', models.CharField(blank=True, default='', max_length=60, verbose_name="Type d'ajustement")),
                ('motif', models.CharField(max_length=255, verbose_name='Motif')),
                ('reversible', models.BooleanField(default=True, verbose_name='Réversible')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustements_gaap', to='compta.ecriturecomptable', verbose_name='Écriture générée')),
                ('referentiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustements_gaap', to='compta.referentielcomptable', verbose_name='Référentiel cible')),
            ],
            options={
                'verbose_name': 'Ajustement GAAP',
                'verbose_name_plural': 'Ajustements GAAP',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='ligneecriture',
            name='referentiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_ecriture', to='compta.referentielcomptable', verbose_name='Référentiel comptable'),
        ),
        migrations.AddConstraint(
            model_name='axeanalytique',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_axe_analytique_code'),
        ),
        migrations.AddConstraint(
            model_name='imputationaxe',
            constraint=models.UniqueConstraint(fields=('ligne_ecriture', 'axe'), name='uniq_imputation_ligne_axe'),
        ),
        migrations.AddConstraint(
            model_name='referentielcomptable',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_referentiel_par_code'),
        ),
        migrations.AddConstraint(
            model_name='referentielcomptable',
            constraint=models.UniqueConstraint(condition=models.Q(('est_principal', True)), fields=('company',), name='uniq_referentiel_principal_par_societe'),
        ),
    ]
