# Generated by Django 5.1.4 on 2026-07-17 13:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0115_ntfin_referentiel_axes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleRepartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('type_cle', models.CharField(choices=[('manuel', 'Manuel (coefficients saisis)'), ('statistique', 'Statistique'), ('proportionnel', 'Proportionnel')], default='manuel', max_length=14, verbose_name='Type de clé')),
                ('base', models.CharField(choices=[('m2', 'Surface (m²)'), ('effectif', 'Effectifs'), ('ca', "Chiffre d'affaires"), ('personnalisee', 'Base personnalisée')], default='personnalisee', max_length=14, verbose_name='Base de répartition')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Clé de répartition',
                'verbose_name_plural': 'Clés de répartition',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AllocationRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('compte_source', models.CharField(max_length=20, verbose_name='Compte source')),
                ('periodicite', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle')], default='mensuelle', max_length=14, verbose_name='Périodicité')),
                ('prochaine_echeance', models.DateField(verbose_name='Prochaine échéance')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('derniere_generation', models.DateField(blank=True, null=True, verbose_name='Dernière génération')),
                ('centre_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_recurrentes_source', to='compta.centrecout', verbose_name='Centre source')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('referentiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations_recurrentes', to='compta.referentielcomptable', verbose_name='Référentiel')),
                ('cle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations_recurrentes', to='compta.clerepartition', verbose_name='Clé de répartition')),
            ],
            options={
                'verbose_name': 'Allocation récurrente',
                'verbose_name_plural': 'Allocations récurrentes',
                'ordering': ['prochaine_echeance'],
            },
        ),
        migrations.CreateModel(
            name='EngagementComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_engagement', models.CharField(choices=[('bon_commande', 'Bon de commande'), ('note_frais', 'Note de frais'), ('marche', 'Marché')], default='bon_commande', max_length=14, verbose_name="Type d'engagement")),
                ('source_type', models.CharField(blank=True, default='', max_length=40, verbose_name='Type de pièce source (string-ref)')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la pièce source (string-ref)')),
                ('reference', models.CharField(blank=True, default='', max_length=50, verbose_name='Référence')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('montant_engage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant engagé')),
                ('montant_liquide', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant liquidé')),
                ('date_engagement', models.DateField(verbose_name="Date d'engagement")),
                ('statut', models.CharField(choices=[('engage', 'Engagé'), ('partiellement_liquide', 'Partiellement liquidé'), ('solde', 'Soldé')], default='engage', max_length=22, verbose_name='Statut')),
                ('centre_cout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='compta.centrecout', verbose_name='Centre de coût')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='compta.comptecomptable', verbose_name='Compte')),
                ('referentiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='compta.referentielcomptable', verbose_name='Référentiel')),
            ],
            options={
                'verbose_name': 'Engagement comptable',
                'verbose_name_plural': 'Engagements comptables',
                'ordering': ['-date_engagement', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneCleRepartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coefficient', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7, verbose_name='Coefficient (%)')),
                ('centre_cout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_cle_repartition', to='compta.centrecout', verbose_name='Centre/axe cible')),
                ('cle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='compta.clerepartition', verbose_name='Clé de répartition')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Ligne de clé de répartition',
                'verbose_name_plural': 'Lignes de clé de répartition',
                'ordering': ['cle', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RunAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte_source', models.CharField(max_length=20, verbose_name='Compte source')),
                ('periode', models.DateField(verbose_name='Période (mois de référence)')),
                ('montant_reparti', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant réparti')),
                ('statut', models.CharField(choices=[('executee', 'Exécutée'), ('reversee', 'Réversée')], default='executee', max_length=10, verbose_name='Statut')),
                ('centre_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_allocation_source', to='compta.centrecout', verbose_name='Centre source')),
                ('cle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='compta.clerepartition', verbose_name='Clé de répartition')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_allocation', to='compta.ecriturecomptable', verbose_name="Écriture d'allocation générée")),
                ('referentiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs_allocation', to='compta.referentielcomptable', verbose_name='Référentiel')),
            ],
            options={
                'verbose_name': "Run d'allocation",
                'verbose_name_plural': "Runs d'allocation",
                'ordering': ['-periode', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clerepartition',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_cle_repartition_code'),
        ),
        migrations.AddConstraint(
            model_name='ligneclerepartition',
            constraint=models.UniqueConstraint(fields=('cle', 'centre_cout'), name='uniq_ligne_cle_centre'),
        ),
    ]
