# Generated by Django 5.1.4 on 2026-07-17 13:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0116_ntfin_allocations_engagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modeleecriture',
            name='categorie_cloture',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='Catégorie de clôture'),
        ),
        migrations.AddField(
            model_name='modeleecriture',
            name='cloture',
            field=models.BooleanField(default=False, verbose_name='Modèle de clôture'),
        ),
        migrations.CreateModel(
            name='AccrualCloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_accrual', models.CharField(choices=[('charge_a_payer', 'Charge à payer'), ('produit_a_recevoir', 'Produit à recevoir'), ('fnp', 'Facture non parvenue')], default='charge_a_payer', max_length=20, verbose_name="Type d'accrual")),
                ('compte_charge_produit', models.CharField(max_length=20, verbose_name='Compte de charge/produit')),
                ('compte_contrepartie', models.CharField(max_length=20, verbose_name='Compte de contrepartie')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('source_type', models.CharField(blank=True, default='', max_length=40, verbose_name='Type de pièce source (string-ref)')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la pièce source (string-ref)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accruals_cloture', to='compta.ecriturecomptable', verbose_name="Écriture d'accrual")),
                ('ecriture_extourne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accruals_cloture_extourne', to='compta.ecriturecomptable', verbose_name="Écriture d'extourne")),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals_cloture', to='compta.periodecomptable', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Accrual de clôture',
                'verbose_name_plural': 'Accruals de clôture',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ModeleCloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('periodicite', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('annuelle', 'Annuelle')], default='mensuelle', max_length=14, verbose_name='Périodicité')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Modèle de clôture',
                'verbose_name_plural': 'Modèles de clôture',
                'ordering': ['periodicite', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='InstanceCloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('valide', 'Validé')], default='ouvert', max_length=10, verbose_name='Statut')),
                ('date_cible', models.DateField(blank=True, null=True, verbose_name='Date cible de clôture')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_cloture', to='compta.periodecomptable', verbose_name='Période')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='compta.modelecloture', verbose_name='Modèle de clôture')),
            ],
            options={
                'verbose_name': 'Instance de clôture',
                'verbose_name_plural': 'Instances de clôture',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TacheCloture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('categorie', models.CharField(choices=[('rapprochement', 'Rapprochement'), ('accrual', 'Accrual / régularisation'), ('analyse', 'Analyse'), ('reporting', 'Reporting')], default='analyse', max_length=14, verbose_name='Catégorie')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('fait', 'Fait'), ('na', 'Non applicable')], default='a_faire', max_length=10, verbose_name='Statut')),
                ('fait_le', models.DateTimeField(blank=True, null=True, verbose_name='Fait le')),
                ('piece_jointe_key', models.CharField(blank=True, default='', max_length=255, verbose_name='Pièce jointe (clé de stockage)')),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_cloture_assignees', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('fait_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_cloture_faites', to=settings.AUTH_USER_MODEL, verbose_name='Fait par')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='compta.instancecloture', verbose_name='Instance de clôture')),
            ],
            options={
                'verbose_name': 'Tâche de clôture',
                'verbose_name_plural': 'Tâches de clôture',
                'ordering': ['instance', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TacheClotureModele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('role_responsable', models.CharField(blank=True, default='', max_length=60, verbose_name='Rôle responsable')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('categorie', models.CharField(choices=[('rapprochement', 'Rapprochement'), ('accrual', 'Accrual / régularisation'), ('analyse', 'Analyse'), ('reporting', 'Reporting')], default='analyse', max_length=14, verbose_name='Catégorie')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='compta.modelecloture', verbose_name='Modèle de clôture')),
            ],
            options={
                'verbose_name': 'Tâche-modèle de clôture',
                'verbose_name_plural': 'Tâches-modèle de clôture',
                'ordering': ['modele', 'ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JustificationVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compte', models.CharField(max_length=20, verbose_name='Compte')),
                ('montant_variation', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant de la variation')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('statut', models.CharField(choices=[('expliquee', 'Expliquée'), ('non_expliquee', 'Non expliquée')], default='expliquee', max_length=14, verbose_name='Statut')),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justifications_variation', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications_variation', to='compta.periodecomptable', verbose_name='Période')),
            ],
            options={
                'verbose_name': 'Justification de variation',
                'verbose_name_plural': 'Justifications de variation',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'periode', 'compte'), name='uniq_justif_variation_periode_compte')],
            },
        ),
        migrations.AddConstraint(
            model_name='modelecloture',
            constraint=models.UniqueConstraint(fields=('company', 'libelle', 'periodicite'), name='uniq_modele_cloture'),
        ),
        migrations.AddConstraint(
            model_name='instancecloture',
            constraint=models.UniqueConstraint(fields=('company', 'periode'), name='uniq_instance_cloture_periode'),
        ),
    ]
