# Generated by Django 5.1.4 on 2026-07-17 14:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0117_ntfin_close_management'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RapprochementCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solde_gl', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Solde grand livre')),
                ('solde_justifie', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Solde justifié')),
                ('ecart', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Écart')),
                ('statut', models.CharField(choices=[('a_rapprocher', 'À rapprocher'), ('en_cours', 'En cours'), ('soumis', 'Soumis à revue'), ('rapproche', 'Rapproché'), ('valide', 'Validé')], default='a_rapprocher', max_length=14, verbose_name='Statut')),
                ('date_soumission', models.DateTimeField(blank=True, null=True, verbose_name='Soumis le')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Validé le')),
                ('commentaire', models.TextField(blank=True, default='', verbose_name='Commentaire')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rapprochements_compte', to='compta.comptecomptable', verbose_name='Compte')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapprochements_compte', to='compta.periodecomptable', verbose_name='Période')),
                ('preparateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapprochements_compte_prepares', to=settings.AUTH_USER_MODEL, verbose_name='Préparateur')),
                ('reviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapprochements_compte_revises', to=settings.AUTH_USER_MODEL, verbose_name='Réviseur')),
            ],
            options={
                'verbose_name': 'Rapprochement de compte',
                'verbose_name_plural': 'Rapprochements de compte',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneJustificationCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant')),
                ('type_element', models.CharField(choices=[('ecriture', 'Écriture'), ('document', 'Document'), ('reconciliant', 'Élément réconciliant')], default='ecriture', max_length=14, verbose_name="Type d'élément")),
                ('source_type', models.CharField(blank=True, default='', max_length=40, verbose_name='Type de source (string-ref)')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la source (string-ref)')),
                ('permanente', models.BooleanField(default=False, help_text='NTFIN39 — reportée automatiquement à la période suivante.', verbose_name='Ligne permanente (reportée N+1)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('rapprochement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='compta.rapprochementcompte', verbose_name='Rapprochement')),
            ],
            options={
                'verbose_name': 'Ligne justificative de compte',
                'verbose_name_plural': 'Lignes justificatives de compte',
                'ordering': ['rapprochement', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='rapprochementcompte',
            constraint=models.UniqueConstraint(fields=('company', 'compte', 'periode'), name='uniq_rapprochement_compte_periode'),
        ),
    ]
