# Generated by Django 5.1.4 on 2026-07-17 14:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0118_ntfin_rapprochement_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposantImmobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('valeur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valeur du composant')),
                ('duree_amortissement', models.PositiveIntegerField(verbose_name="Durée d'amortissement (années)")),
                ('methode', models.CharField(choices=[('lineaire', 'Linéaire'), ('degressif', 'Dégressif')], default='lineaire', max_length=10, verbose_name="Méthode d'amortissement")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composants', to='compta.immobilisation', verbose_name='Immobilisation')),
            ],
            options={
                'verbose_name': "Composant d'immobilisation",
                'verbose_name_plural': "Composants d'immobilisation",
                'ordering': ['immobilisation', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DepreciationImmobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_test', models.DateField(verbose_name='Date du test')),
                ('valeur_recuperable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valeur recouvrable')),
                ('valeur_comptable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valeur comptable (VNC)')),
                ('perte_valeur', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Perte de valeur')),
                ('reversible', models.BooleanField(default=True, verbose_name='Réversible')),
                ('reprise', models.BooleanField(default=False, verbose_name='Reprise de dépréciation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciations_immo', to='compta.ecriturecomptable', verbose_name='Écriture générée')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciations', to='compta.immobilisation', verbose_name='Immobilisation')),
            ],
            options={
                'verbose_name': "Dépréciation d'immobilisation",
                'verbose_name_plural': "Dépréciations d'immobilisation",
                'ordering': ['-date_test', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImmobilisationEnCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('compte_encours', models.CharField(default='231', max_length=20, verbose_name='Compte immobilisation en cours (classe 23)')),
                ('montant_cumule', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant cumulé engagé')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('mis_en_service', 'Mis en service')], default='en_cours', max_length=16, verbose_name='Statut')),
                ('date_mise_en_service', models.DateField(blank=True, null=True, verbose_name='Date de mise en service')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('immobilisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origine_encours', to='compta.immobilisation', verbose_name='Immobilisation mise en service')),
            ],
            options={
                'verbose_name': 'Immobilisation en cours (CIP)',
                'verbose_name_plural': 'Immobilisations en cours (CIP)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LigneImmobilisationEnCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('source_type', models.CharField(blank=True, default='', max_length=40, verbose_name='Type de source (string-ref)')),
                ('source_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la source (string-ref)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('encours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='compta.immobilisationencours', verbose_name='Immobilisation en cours')),
            ],
            options={
                'verbose_name': "Ligne d'immobilisation en cours",
                'verbose_name_plural': "Lignes d'immobilisation en cours",
                'ordering': ['encours', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MutationImmobilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date de mutation')),
                ('motif', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif')),
                ('ancien_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_immo_depuis', to='compta.centrecout', verbose_name='Ancien centre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('entite_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_immo_cible', to='authentication.company', verbose_name='Entité cible')),
                ('entite_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_immo_source', to='authentication.company', verbose_name='Entité source')),
                ('immobilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutations', to='compta.immobilisation', verbose_name='Immobilisation')),
                ('nouveau_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_immo_vers', to='compta.centrecout', verbose_name='Nouveau centre')),
            ],
            options={
                'verbose_name': "Mutation d'immobilisation",
                'verbose_name_plural': "Mutations d'immobilisation",
                'ordering': ['-date', '-id'],
            },
        ),
    ]
