# Generated by Django 5.1.4 on 2026-07-17 14:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0119_ntfin_immobilisations_avancees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratRevenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, default='', max_length=50, verbose_name='Référence')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('client_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID du client (string-ref)')),
                ('client_nom', models.CharField(blank=True, default='', max_length=200, verbose_name='Client')),
                ('source_devis_ref', models.CharField(blank=True, default='', max_length=50, verbose_name="Devis d'origine (string-ref)")),
                ('montant_transaction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant du prix de transaction')),
                ('devise', models.CharField(default='MAD', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('cloture', 'Clôturé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Contrat de revenu (IFRS 15)',
                'verbose_name_plural': 'Contrats de revenu (IFRS 15)',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EtapeAuditConsolidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etape', models.CharField(max_length=40, verbose_name='Étape')),
                ('sequence', models.PositiveIntegerField(verbose_name='Rang dans la chaîne')),
                ('hash_snapshot', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash du snapshot de balance')),
                ('hash_precedent', models.CharField(blank=True, default='', max_length=64, verbose_name='Hash précédent')),
                ('hash', models.CharField(max_length=64, verbose_name='Hash du maillon')),
                ('detail', models.CharField(blank=True, default='', max_length=255, verbose_name='Détail')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapes_audit_consolidation', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_audit', to='compta.cycleconsolidation', verbose_name='Cycle de consolidation')),
            ],
            options={
                'verbose_name': "Maillon d'audit de consolidation",
                'verbose_name_plural': "Piste d'audit de consolidation",
                'ordering': ['cycle', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ObligationPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('prix_vente_specifique', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prix de vente spécifique (standalone)')),
                ('prix_alloue', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Prix alloué')),
                ('methode_reconnaissance', models.CharField(choices=[('a_une_date', 'À une date (transfert du contrôle)'), ('dans_le_temps', 'Dans le temps (linéaire)')], default='a_une_date', max_length=14, verbose_name='Méthode de reconnaissance')),
                ('duree_mois', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (mois, pour reconnaissance dans le temps)')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('remplie', 'Remplie')], default='en_attente', max_length=12, verbose_name='Statut')),
                ('montant_facture', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant facturé (à ce jour)')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='compta.contratrevenu', verbose_name='Contrat de revenu')),
            ],
            options={
                'verbose_name': 'Obligation de performance',
                'verbose_name_plural': 'Obligations de performance',
                'ordering': ['contrat', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EcheancierReconnaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='Date de reconnaissance')),
                ('montant_a_reconnaitre', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant à reconnaître')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('reconnu', 'Reconnu')], default='planifie', max_length=10, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ecriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeances_reconnaissance', to='compta.ecriturecomptable', verbose_name='Écriture de reconnaissance')),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='compta.obligationperformance', verbose_name='Obligation de performance')),
            ],
            options={
                'verbose_name': 'Échéance de reconnaissance',
                'verbose_name_plural': 'Échéances de reconnaissance',
                'ordering': ['obligation', 'date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='contratrevenu',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__gt', '')), fields=('company', 'reference'), name='uniq_contrat_revenu_ref'),
        ),
        migrations.AddConstraint(
            model_name='etapeauditconsolidation',
            constraint=models.UniqueConstraint(fields=('cycle', 'sequence'), name='uniq_etape_audit_conso_seq'),
        ),
    ]
