# Generated by Django 5.1.4 on 2026-07-17 17:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_ntprt1_customuser_portee'),
        ('compta', '0120_ntfin_ifrs15_conso_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='retenuesource',
            name='convention_appliquee',
            field=models.BooleanField(default=False, verbose_name='Taux conventionnel appliqué'),
        ),
        migrations.AddField(
            model_name='retenuesource',
            name='pays_beneficiaire',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Pays du bénéficiaire'),
        ),
        migrations.AddField(
            model_name='timbrefiscal',
            name='mode_acquittement',
            field=models.CharField(choices=[('papier', 'Timbre papier'), ('electronique', 'Timbre électronique')], default='papier', max_length=12, verbose_name="Mode d'acquittement"),
        ),
        migrations.AlterField(
            model_name='retenuesource',
            name='type_prestation',
            field=models.CharField(choices=[('honoraires', 'Honoraires'), ('redevances', 'Redevances'), ('loyers', 'Loyers'), ('prestations', 'Prestations de services'), ('prestation_etrangere', 'Prestation étrangère'), ('autre', 'Autre')], default='honoraires', max_length=12, verbose_name='Type de prestation'),
        ),
        migrations.CreateModel(
            name='AcompteIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rang', models.PositiveSmallIntegerField(verbose_name='Rang (1-4)')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant')),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('a_payer', 'À payer'), ('paye', 'Payé')], default='a_payer', max_length=8, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acomptes_is', to='authentication.company', verbose_name='Société')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acomptes_is', to='compta.exercicecomptable', verbose_name='Exercice')),
            ],
            options={
                'verbose_name': 'Acompte IS',
                'verbose_name_plural': 'Acomptes IS',
                'ordering': ['exercice', 'rang'],
                'constraints': [models.UniqueConstraint(fields=('company', 'exercice', 'rang'), name='uniq_acompte_is_rang')],
            },
        ),
        migrations.CreateModel(
            name='ConventionFiscale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pays', models.CharField(max_length=80, verbose_name='Pays bénéficiaire')),
                ('code_pays', models.CharField(blank=True, default='', max_length=3, verbose_name='Code pays (ISO)')),
                ('taux_conventionnel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Taux conventionnel (%)')),
                ('libelle', models.CharField(blank=True, default='', max_length=200, verbose_name='Libellé')),
                ('actif', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conventions_fiscales', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Convention fiscale',
                'verbose_name_plural': 'Conventions fiscales',
                'ordering': ['pays'],
                'constraints': [models.UniqueConstraint(fields=('company', 'pays'), name='uniq_convention_fiscale_pays')],
            },
        ),
    ]
