"""SOLMVP — coquille de migrations de l'app « compta ».

Migration d'ÉTAT SEUL générée par ``manage.py parquer_app compta`` :
``database_operations=[]`` — AUCUNE table supprimée, AUCUNE ligne de
``django_migrations`` touchée. Les modèles sortent seulement de l'état
Django ; les données restent intégralement en base.

Retour du module : ``manage.py migrate compta 0128_nti18n18_plan_comptable_ohada`` (renverse cet état),
puis suppression de ce fichier — docs/parked-modules.md §5.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0128_nti18n18_plan_comptable_ohada'),
        ('flotte', '0060_solmvp_coquille'),
        ('frais', '0006_solmvp_coquille'),
        ('paie', '0055_solmvp_coquille'),
        ('pos', '0012_solmvp_coquille'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='AbonnementEcriture'),
                migrations.DeleteModel(name='AccrualCloture'),
                migrations.DeleteModel(name='AcompteIS'),
                migrations.DeleteModel(name='AjustementGaap'),
                migrations.DeleteModel(name='AllocationRecurrente'),
                migrations.DeleteModel(name='AvancementRevenu'),
                migrations.DeleteModel(name='BudgetLigne'),
                migrations.DeleteModel(name='CautionBancaire'),
                migrations.DeleteModel(name='CessionImmobilisation'),
                migrations.DeleteModel(name='ClotureCaisse'),
                migrations.DeleteModel(name='CodePromotion'),
                migrations.DeleteModel(name='ColonneEtatPersonnalise'),
                migrations.DeleteModel(name='CommissionPayoutLine'),
                migrations.DeleteModel(name='ComposantImmobilisation'),
                migrations.DeleteModel(name='CompteAuxiliaire'),
                migrations.DeleteModel(name='ConventionFiscale'),
                migrations.DeleteModel(name='DeclarationTVA'),
                migrations.DeleteModel(name='DemandeApprobationConfig'),
                migrations.DeleteModel(name='DemandeApprobationRib'),
                migrations.DeleteModel(name='DepreciationImmobilisation'),
                migrations.DeleteModel(name='DocumentProposition'),
                migrations.DeleteModel(name='DotationAmortissement'),
                migrations.DeleteModel(name='DotationDerogatoire'),
                migrations.DeleteModel(name='DotationEtalement'),
                migrations.DeleteModel(name='ECatalogue'),
                migrations.DeleteModel(name='EcartChange'),
                migrations.DeleteModel(name='EcheanceEmprunt'),
                migrations.DeleteModel(name='EcheancierReconnaissance'),
                migrations.DeleteModel(name='EcritureLiaisonInterSociete'),
                migrations.DeleteModel(name='Effet'),
                migrations.DeleteModel(name='EliminationTitres'),
                migrations.DeleteModel(name='EngagementComptable'),
                migrations.DeleteModel(name='EntiteConsolidation'),
                migrations.DeleteModel(name='EtapeAuditConsolidation'),
                migrations.DeleteModel(name='FamilleTvaNonDeductible'),
                migrations.DeleteModel(name='ImputationAxe'),
                migrations.DeleteModel(name='JustificationVariation'),
                migrations.DeleteModel(name='LiasseRemontee'),
                migrations.DeleteModel(name='LigneCleRepartition'),
                migrations.DeleteModel(name='LigneCompensation'),
                migrations.DeleteModel(name='LigneEtatPersonnalise'),
                migrations.DeleteModel(name='LigneImmobilisationEnCours'),
                migrations.DeleteModel(name='LigneIncitation'),
                migrations.DeleteModel(name='LigneJustificationCompte'),
                migrations.DeleteModel(name='LigneModeleEcriture'),
                migrations.DeleteModel(name='LignePrevisionnelTresorerie'),
                migrations.DeleteModel(name='LigneReevaluation'),
                migrations.DeleteModel(name='LigneRegleImputation'),
                migrations.DeleteModel(name='LigneVentilation'),
                migrations.DeleteModel(name='MappingCompte'),
                migrations.DeleteModel(name='MappingConsolidation'),
                migrations.DeleteModel(name='MargeInterneStock'),
                migrations.DeleteModel(name='ModeleDevis'),
                migrations.DeleteModel(name='ModeleRapprochement'),
                migrations.DeleteModel(name='MouvementCaisse'),
                migrations.DeleteModel(name='MutationImmobilisation'),
                migrations.DeleteModel(name='ObligationFiscale'),
                migrations.DeleteModel(name='OffreFinancement'),
                migrations.DeleteModel(name='ParametresTresorerie'),
                migrations.DeleteModel(name='PaymentRunLine'),
                migrations.DeleteModel(name='PieceJustificative'),
                migrations.DeleteModel(name='PisteAuditComptable'),
                migrations.DeleteModel(name='PlanComptableOHADA'),
                migrations.DeleteModel(name='PlanRelanceTresorerie'),
                migrations.DeleteModel(name='PointageReleve'),
                migrations.DeleteModel(name='PouvoirBancaire'),
                migrations.DeleteModel(name='Provision'),
                migrations.DeleteModel(name='ProvisionCreance'),
                migrations.DeleteModel(name='Rapprochement'),
                migrations.DeleteModel(name='RetenueGarantie'),
                migrations.DeleteModel(name='RetenueSource'),
                migrations.DeleteModel(name='RunAllocation'),
                migrations.DeleteModel(name='SessionGuidedSelling'),
                migrations.DeleteModel(name='SimulationFinancement'),
                migrations.DeleteModel(name='SimulationPublique'),
                migrations.DeleteModel(name='TacheCloture'),
                migrations.DeleteModel(name='TacheClotureModele'),
                migrations.DeleteModel(name='TauxDevise'),
                migrations.DeleteModel(name='TimbreFiscal'),
                migrations.DeleteModel(name='TranchePaiement'),
                migrations.DeleteModel(name='TravauxEnCours'),
                migrations.DeleteModel(name='VirementInterne'),
                migrations.DeleteModel(name='BordereauRemise'),
                migrations.DeleteModel(name='Budget'),
                migrations.DeleteModel(name='Caisse'),
                migrations.DeleteModel(name='ChargeConstateeAvance'),
                migrations.DeleteModel(name='CleRepartition'),
                migrations.DeleteModel(name='CommissionPayoutRun'),
                migrations.DeleteModel(name='Compensation'),
                migrations.DeleteModel(name='ContratAvancement'),
                migrations.DeleteModel(name='EcheancierPaiement'),
                migrations.DeleteModel(name='EcritureElimination'),
                migrations.DeleteModel(name='Emprunt'),
                migrations.DeleteModel(name='EtatPersonnalise'),
                migrations.DeleteModel(name='ImmobilisationEnCours'),
                migrations.DeleteModel(name='InstanceCloture'),
                migrations.DeleteModel(name='ItemOuvertDevise'),
                migrations.DeleteModel(name='LigneReleve'),
                migrations.DeleteModel(name='ModeleEcriture'),
                migrations.DeleteModel(name='ObligationPerformance'),
                migrations.DeleteModel(name='PaymentRun'),
                migrations.DeleteModel(name='PlanAmortissementFiscal'),
                migrations.DeleteModel(name='RapprochementCompte'),
                migrations.DeleteModel(name='ReevaluationCloture'),
                migrations.DeleteModel(name='RegleImputation'),
                migrations.DeleteModel(name='RegleInterSociete'),
                migrations.DeleteModel(name='VentilationAnalytique'),
                migrations.DeleteModel(name='ContratRevenu'),
                migrations.DeleteModel(name='LigneEcriture'),
                migrations.DeleteModel(name='ModeleCloture'),
                migrations.DeleteModel(name='OperationInterco'),
                migrations.DeleteModel(name='PeriodeComptable'),
                migrations.DeleteModel(name='PlanAmortissement'),
                migrations.DeleteModel(name='RapprochementBancaire'),
                migrations.DeleteModel(name='CentreCout'),
                migrations.DeleteModel(name='CompteTresorerie'),
                migrations.DeleteModel(name='CycleConsolidation'),
                migrations.DeleteModel(name='EcritureComptable'),
                migrations.DeleteModel(name='Immobilisation'),
                migrations.DeleteModel(name='ReferentielComptable'),
                migrations.DeleteModel(name='AxeAnalytique'),
                migrations.DeleteModel(name='ExerciceComptable'),
                migrations.DeleteModel(name='Journal'),
                migrations.DeleteModel(name='CompteComptable'),
                migrations.DeleteModel(name='PlanComptable'),
            ],
            database_operations=[],
        ),
    ]
