# Generated by Django 5.1.4 on 2026-06-11 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_role'),
        ('crm', '0002_client_company_alter_client_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255, null=True)),
                ('societe', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=120, null=True)),
                ('stage', models.CharField(choices=[('NEW', 'Nouveau'), ('CONTACTED', 'Contacté'), ('QUOTE_SENT', 'Devis envoyé'), ('FOLLOW_UP', 'Relance'), ('SIGNED', 'Signé'), ('COLD', 'Froid')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('os_native', 'Créé dans TAQINOR'), ('odoo_import_test', 'Import test Odoo')], default='os_native', max_length=32)),
                ('external_system', models.CharField(blank=True, max_length=50, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['company', 'source'], name='crm_lead_company_822dc2_idx'), models.Index(fields=['company', 'stage'], name='crm_lead_company_93881e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('company', 'external_system', 'external_id'), name='uniq_lead_external_ref')],
            },
        ),
    ]
