# Generated by Django 5.1.4 on 2026-06-12 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.client'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ete_differente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='facture_ete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='facture_hiver',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
