# Generated by Django 5.1.4 on 2026-06-12 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_role'),
        ('crm', '0004_lead_client_lead_ete_differente_lead_facture_ete_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='batterie_souhaitee',
            field=models.CharField(blank=True, choices=[('sans', 'Sans batterie'), ('avec', 'Avec batterie'), ('les_deux', 'Les deux options')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='canal',
            field=models.CharField(blank=True, choices=[('meta_ads', 'Publicité Meta'), ('whatsapp_ctwa', 'WhatsApp/CTWA'), ('site_web', 'Site web'), ('reference', 'Référence'), ('telephone', 'Téléphone'), ('walk_in', 'Visite/Walk-in'), ('autre', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='conso_mensuelle_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gps_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='gps_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='inclinaison_deg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='motif_perte',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='nb_etages',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ombrage',
            field=models.CharField(blank=True, choices=[('aucun', 'Aucun'), ('partiel', 'Partiel'), ('important', 'Important')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ombrage_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='orientation',
            field=models.CharField(blank=True, choices=[('sud', 'Sud'), ('sud_est', 'Sud-Est'), ('sud_ouest', 'Sud-Ouest'), ('est', 'Est'), ('ouest', 'Ouest'), ('autre', 'Autre')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assignes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute')], default='normale', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='raccordement',
            field=models.CharField(blank=True, choices=[('monophase', 'Monophasé'), ('triphase', 'Triphasé')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='regularisation_8221',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='relance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='structure_pref',
            field=models.CharField(blank=True, choices=[('acier', 'Acier'), ('aluminium', 'Aluminium')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='surface_toiture_m2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='taille_souhaitee_kwc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='tranche_onee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='type_installation',
            field=models.CharField(blank=True, choices=[('residentiel', 'Résidentiel'), ('commercial', 'Commercial'), ('industriel', 'Industriel'), ('agricole', 'Agricole')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='type_toiture',
            field=models.CharField(blank=True, choices=[('terrasse_beton', 'Terrasse béton'), ('tole_metal', 'Tôle/Métal'), ('tuiles', 'Tuiles'), ('bac_acier', 'Bac acier'), ('fibrociment', 'Fibrociment'), ('autre', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='visite_effectuee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='visite_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='visite_prevue_le',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('note', 'Note')], max_length=15)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('field_label', models.CharField(blank=True, max_length=150, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_activities', to='authentication.company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='crm.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité lead',
                'verbose_name_plural': 'Activités lead',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='crm_leadact_lead_id_639066_idx')],
            },
        ),
    ]
