# Generated by Django 5.1.4 on 2026-06-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_role'),
        ('crm', '0005_lead_batterie_souhaitee_lead_canal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bill_range_bucket',
            field=models.CharField(blank=True, choices=[('lt800', 'Moins de 800 MAD'), ('800-1000', '800 – 1 000 MAD'), ('1000-1500', '1 000 – 1 500 MAD'), ('1500-3000', '1 500 – 3 000 MAD'), ('3000-5000', '3 000 – 5 000 MAD'), ('5000-10000', '5 000 – 10 000 MAD'), ('gt10000', 'Plus de 10 000 MAD')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fbclid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='roi_band',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='roof_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp_opt_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('os_native', 'Créé dans TAQINOR'), ('odoo_import_test', 'Import test Odoo'), ('site_web', 'Site web')], default='os_native', max_length=32),
        ),
        migrations.CreateModel(
            name='WebsiteLeadPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField()),
                ('remote_addr', models.CharField(blank=True, max_length=64, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website_lead_payloads', to='authentication.company')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_payloads', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Payload lead site web',
                'verbose_name_plural': 'Payloads leads site web',
                'ordering': ['-received_at'],
            },
        ),
    ]
