# Generated by Django 5.1.4 on 2026-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_lead_bill_range_bucket_lead_consent_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ice',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
