# Generated by Django 5.1.4 on 2026-06-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_client_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='pompe_cv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='pompe_debit_m3h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='pompe_hmt_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
