# Generated by Django 5.1.4 on 2026-06-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_lead_archived_at_lead_archived_by_lead_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='if_fiscal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='rc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='type_client',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise')], default='particulier', max_length=12),
        ),
    ]
