# Generated by Django 5.1.4 on 2026-06-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_client_type_from_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='perdu',
            field=models.BooleanField(default=False),
        ),
    ]
