# Generated by Django 5.1.4 on 2026-06-14 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_avatar_key_customuser_poste'),
        ('crm', '0012_lead_perdu'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('couleur', models.CharField(blank=True, default='', max_length=7)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_tags', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Étiquette de lead',
                'ordering': ['nom'],
                'unique_together': {('company', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='MotifPerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motifs_perte', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Motif de perte',
                'ordering': ['nom'],
                'unique_together': {('company', 'nom')},
            },
        ),
    ]
