# Generated by Django 5.1.4 on 2026-06-16 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("crm", "0013_leadtag_motifperte"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanalSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=40)),
                ("label", models.CharField(max_length=120)),
                ("ordre", models.PositiveIntegerField(default=100)),
                ("archived", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canaux_sources",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal / source de lead",
                "verbose_name_plural": "Canaux / sources de lead",
                "ordering": ["ordre", "label"],
                "unique_together": {("company", "key")},
            },
        ),
    ]
