# Generated by Django 5.1.4 on 2026-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0013_leadtag_motifperte"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadactivity",
            name="bulk",
            field=models.BooleanField(default=False),
        ),
    ]
