# Generated by Django 5.1.4 on 2026-06-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("crm", "0014_leadactivity_bulk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Canal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=40)),
                ("libelle", models.CharField(max_length=80)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("protege", models.BooleanField(default=False)),
                ("archived", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canaux",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Canal de lead",
                "verbose_name_plural": "Canaux de lead",
                "ordering": ["ordre", "libelle"],
                "unique_together": {("company", "cle")},
            },
        ),
    ]
