# Generated by Django 5.1.4 on 2026-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_canal"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
