# Generated by Django 5.1.4 on 2026-06-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0015_backfill_canalsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
