# Generated by Django 5.1.4 on 2026-06-16 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0016_client_custom_fields_lead_custom_fields"),
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="imports.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="imports.importbatch",
            ),
        ),
    ]
