# Generated by Django 5.1.4 on 2026-06-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_client_created_by_date_modification"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="langue_preferee",
            field=models.CharField(
                blank=True,
                choices=[("fr", "Français"), ("darija", "Darija")],
                max_length=10,
                null=True,
            ),
        ),
    ]
