# Generated by Django 5.1.4 on 2026-06-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0020_alter_lead_gps_lat_alter_lead_gps_lng"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="plafond_credit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Seuil d'encours client. Vide = pas de limite.",
                max_digits=12,
                null=True,
                verbose_name="Plafond de crédit (MAD TTC)",
            ),
        ),
    ]
