# Generated by Django 5.1.4 on 2026-06-21 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("crm", "0020_alter_lead_gps_lat_alter_lead_gps_lng"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="first_contacted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Premier contact à"
            ),
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=150, verbose_name="Nom du modèle")),
                (
                    "langue",
                    models.CharField(
                        choices=[("fr", "Français"), ("darija", "Darija")],
                        default="fr",
                        max_length=10,
                        verbose_name="Langue",
                    ),
                ),
                ("corps", models.TextField(verbose_name="Corps du message")),
                (
                    "archived",
                    models.BooleanField(default=False, verbose_name="Archivé"),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_message_templates",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de message",
                "verbose_name_plural": "Modèles de messages",
                "ordering": ["nom"],
                "unique_together": {("company", "nom")},
            },
        ),
    ]
