# Generated by Django 5.1.4 on 2026-06-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_lead_first_contacted_at_messagetemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="leadactivity",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("joint", "Joint"),
                    ("non_joint", "Non joint"),
                    ("rappel", "À rappeler"),
                    ("refuse", "Refus"),
                    ("interesse", "Intéressé"),
                ],
                default="",
                max_length=20,
                verbose_name="Résultat de l'interaction",
            ),
        ),
        migrations.AlterField(
            model_name="leadactivity",
            name="kind",
            field=models.CharField(
                choices=[
                    ("creation", "Création"),
                    ("modification", "Modification"),
                    ("note", "Note"),
                    ("appel", "Appel"),
                    ("email", "E-mail"),
                ],
                max_length=15,
            ),
        ),
    ]
