# Generated by Django 5.1.4 on 2026-06-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_fg41_client_plafond_credit"),
        ("crm", "0022_leadactivity_appel_email_outcome"),
    ]

    operations = []
