# Generated by Django 5.1.4 on 2026-07-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_qw10_lead_dedup_indexes_concurrent'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tiers',
            field=models.ForeignKey(blank=True, help_text='Fiche du répertoire unifié des parties prenantes reflétant ce client. Renseignée automatiquement (miroir).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='tiers.tiers', verbose_name='Tiers (répertoire unifié)'),
        ),
    ]
