# Generated by Django 5.1.4 on 2026-07-10 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_client_tiers'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='tiers',
            field=models.ForeignKey(blank=True, help_text='Fiche du répertoire unifié reflétant ce prospect (stade amont). Renseignée automatiquement (miroir).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='tiers.tiers', verbose_name='Tiers (répertoire unifié)'),
        ),
    ]
