# Generated by Django 5.1.4 on 2026-07-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_vx96_lead_soft_delete'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='lead',
            managers=[
            ],
        ),
    ]
