# Generated by Django 5.1.4 on 2026-07-17 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_company_est_demo_mode_presentation'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(choices=[('commit', 'Commit'), ('best_case', 'Best case'), ('pipeline', 'Pipeline'), ('omis', 'Omis')], default='pipeline', max_length=12)),
                ('montant_prevu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant prévu (MAD)')),
                ('commentaire', models.TextField(blank=True, default='')),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_entries', to='authentication.company')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_entry', to='crm.lead')),
                ('mis_a_jour_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_entries_maj', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée de forecast',
                'verbose_name_plural': 'Entrées de forecast',
                'ordering': ['-mis_a_jour_le'],
            },
        ),
        migrations.CreateModel(
            name='PlanCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('objectifs_strategiques', models.TextField(blank=True, default='')),
                ('potentiel_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Potentiel estimé (MAD)')),
                ('concurrents_presents', models.TextField(blank=True, default='')),
                ('swot_forces', models.JSONField(blank=True, null=True)),
                ('swot_faiblesses', models.JSONField(blank=True, null=True)),
                ('swot_opportunites', models.JSONField(blank=True, null=True)),
                ('swot_menaces', models.JSONField(blank=True, null=True)),
                ('prochaine_revue', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('actif', 'Actif'), ('archive', 'Archivé')], default='brouillon', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_compte', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_compte', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_compte_crees', to=settings.AUTH_USER_MODEL)),
                ('mis_a_jour_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_compte_maj', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de compte',
                'verbose_name_plural': 'Plans de compte',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150)),
                ('actif', models.BooleanField(default=True)),
                ('bloquant', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Playbook',
                'verbose_name_plural': 'Playbooks',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PlaybookEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('NEW', 'Nouveau'), ('CONTACTED', 'Contacté'), ('QUOTE_SENT', 'Devis envoyé'), ('FOLLOW_UP', 'Relance'), ('SIGNED', 'Signé'), ('COLD', 'Froid')], max_length=20)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('playbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='crm.playbook')),
            ],
            options={
                'verbose_name': 'Étape de playbook',
                'verbose_name_plural': 'Étapes de playbook',
                'ordering': ['ordre', 'id'],
                'unique_together': {('playbook', 'stage')},
            },
        ),
        migrations.CreateModel(
            name='PlaybookTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='crm.playbooketape')),
            ],
            options={
                'verbose_name': 'Tâche de playbook',
                'verbose_name_plural': 'Tâches de playbook',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RevueCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_revue', models.DateField()),
                ('participants', models.TextField(blank=True, default='')),
                ('decisions', models.TextField(blank=True, default='')),
                ('prochaine_action', models.CharField(blank=True, default='', max_length=255)),
                ('prochaine_action_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revues_compte_creees', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revues', to='crm.plancompte')),
            ],
            options={
                'verbose_name': 'Revue de compte',
                'verbose_name_plural': 'Revues de compte',
                'ordering': ['-date_revue'],
            },
        ),
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semaine_iso', models.CharField(max_length=8, verbose_name='Semaine ISO (ex. 2026-W29)')),
                ('categorie', models.CharField(choices=[('commit', 'Commit'), ('best_case', 'Best case'), ('pipeline', 'Pipeline'), ('omis', 'Omis')], max_length=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nb_leads', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_snapshots', to='authentication.company')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot de forecast',
                'verbose_name_plural': 'Snapshots de forecast',
                'ordering': ['-semaine_iso'],
                'constraints': [models.UniqueConstraint(fields=('company', 'semaine_iso', 'categorie', 'owner'), name='crm_forecast_snapshot_uniq_semaine_owner')],
            },
        ),
        migrations.CreateModel(
            name='LeadPlaybookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fait', models.BooleanField(default=False)),
                ('fait_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fait_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playbook_taches_faites', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbook_progress', to='crm.lead')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='crm.playbooktache')),
            ],
            options={
                'verbose_name': 'Progression playbook du lead',
                'verbose_name_plural': 'Progressions playbook des leads',
                'ordering': ['tache__ordre', 'id'],
                'unique_together': {('lead', 'tache')},
            },
        ),
    ]
