"""LB48 — SavedView (vues enregistrées de compte, additif).

Nouvelle table uniquement — aucune colonne existante modifiée. Vue
PERSONNELLE (TenantModel : company+timestamps du socle SCA4) : filtres +
disposition (payload) par utilisateur et par page ; UniqueConstraint
(user, page, name) ; rank 0 = vue par défaut de connexion.
"""
# Generated by Django 5.1.4 on 2026-07-20 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('crm', '0066_appointment_statut_no_show'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(help_text="Clé applicative de la page (ex. 'crm.leads').", max_length=64)),
                ('name', models.CharField(max_length=80, verbose_name='Nom')),
                ('rank', models.PositiveIntegerField(default=0, help_text='0 = première/vue par défaut.', verbose_name='Rang')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Contenu de la vue : {filters, view}.')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_vues_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vue enregistrée',
                'verbose_name_plural': 'Vues enregistrées',
                'ordering': ['rank', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'page', 'name'), name='crm_sv_uniq_user_page_name')],
            },
        ),
    ]
