# Generated by Django 5.1.4 on 2026-08-25 01:18

import apps.crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('crm', '0080_l_back2_clim_piscine_creneau'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireLien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.crm.models._default_questionnaire_token, editable=False, max_length=64, unique=True)),
                ('token_interne', models.CharField(default=apps.crm.models._default_questionnaire_token, editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.crm.models._default_questionnaire_expiry)),
                ('questions', models.JSONField(blank=True, default=dict, verbose_name='Sections demandées')),
                ('sections_repondues', models.JSONField(blank=True, default=dict, verbose_name='Sections déjà répondues')),
                ('derniere_reponse_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière réponse du client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_liens', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaire_liens_crees', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_liens', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Lien questionnaire client',
                'verbose_name_plural': 'Liens questionnaire client',
                'ordering': ['-created_at'],
            },
        ),
    ]
