# Generated by Django 5.1.4 on 2026-08-26 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('crm', '0083_t_trace_lead_appareil_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelanceEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateField()),
                ('canal', models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite')], max_length=20)),
                ('libelle', models.CharField(blank=True, default='', max_length=150)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('fait', 'Fait'), ('sautee', 'Sautée')], default='a_faire', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relance_etapes', to='authentication.company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relance_etapes', to='crm.lead')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relance_etapes_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étape de relance',
                'verbose_name_plural': 'Étapes de relance',
                'ordering': ['ordre', 'due_date'],
                'indexes': [models.Index(fields=['company', 'statut', 'due_date'], name='crm_relanceetape_due_idx')],
            },
        ),
    ]
