# Generated by Django 5.1.15 on 2026-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0103_stkcat9_lead_structure_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='carburant_litres_mois',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Combien de litres de carburant la pompe consomme-t-elle par mois ? » (litres/mois, vide = pas encore posée). C’est l’unité qui manquait à côté de la dépense en dirhams : l’économie de carburant se calcule sur ce que le client DÉCLARE, aucun prix de gasoil de référence n’est écrit nulle part.", max_digits=9, null=True, verbose_name='Carburant consommé (litres/mois)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='decideur',
            field=models.CharField(blank=True, choices=[('seul', 'Décide seul'), ('conjoint_famille', 'Avec le conjoint / la famille'), ('associe_direction', 'Avec un associé / la direction'), ('proprietaire_tiers', 'Le propriétaire (un tiers) décide')], help_text="Question à l'appel : « Qui décide avec vous de ce projet ? » (vide = pas encore posée). Renseigné à « avec le conjoint / la famille » ou « avec un associé / la direction », il pose l’étiquette « Décision à plusieurs » qui pilote la touche du dimanche en famille. Question ORALE uniquement : jamais dans le questionnaire envoyé au client.", max_length=20, null=True, verbose_name='Qui décide'),
        ),
        migrations.AddField(
            model_name='lead',
            name='devis_concurrents',
            field=models.CharField(blank=True, choices=[('non', 'Non, aucun autre devis'), ('en_attente', 'En attente d’un autre devis'), ('recu', 'A déjà reçu un autre devis')], help_text="Question à l'appel : « Avez-vous déjà reçu ou demandé un autre devis ? » (vide = pas encore posée). État de la comparaison EN COURS — le post-mortem d’une affaire perdue reste, lui, dans la fiche « concurrent ». Question ORALE uniquement.", max_length=10, null=True, verbose_name='Autres devis en cours'),
        ),
        migrations.AddField(
            model_name='lead',
            name='equip_ve_statut',
            field=models.CharField(blank=True, choices=[('possede', 'Véhicule déjà là'), ('prevu', 'Véhicule seulement prévu')], help_text="Question à l'appel : « Ce véhicule électrique, vous l'avez déjà, ou c'est un projet ? » (vide = pas encore posée). Précise le « avez-vous OU prévoyez-vous » du champ véhicule électrique : une voiture seulement PRÉVUE reste comptée, et le devis comme la proposition portent alors l’étiquette « avec votre future voiture » — sans elle, le chiffre mentirait.", max_length=10, null=True, verbose_name='Véhicule électrique — déjà là ou prévu ?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='objectif_projet',
            field=models.CharField(blank=True, choices=[('facture', 'Baisser la facture'), ('secours_coupures', 'Tenir pendant les coupures'), ('autonomie', 'Gagner en autonomie'), ('injection_8221', 'Injecter le surplus (loi 82-21)'), ('autre', 'Autre')], help_text="Question à l'appel : « Qu'est-ce qui compte le plus pour vous — baisser la facture, tenir pendant les coupures, gagner en autonomie, injecter le surplus ? » (vide = pas encore posée). « Tenir pendant les coupures » est un ARGUMENT : aucun dimensionnement de secours n’en découle.", max_length=16, null=True, verbose_name='Objectif du projet'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pompage_heures_jour',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Question à l'appel : « Combien d'heures par jour la pompe tourne-t-elle ? » (h/jour, vide = pas encore posée). Colonne dédiée de la réponse que le site envoie déjà sous « heures de pompage ».", max_digits=4, null=True, verbose_name='Pompage — heures par jour'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pompe_alim_actuelle',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune pompe'), ('diesel', 'Diesel'), ('butane', 'Butane'), ('electrique', 'Électrique (réseau)')], help_text="Question à l'appel : « Votre pompe actuelle marche à quoi — diesel, butane, électricité, ou vous n’en avez pas ? » (vide = pas encore posée). Colonne dédiée de la réponse déjà émise par le site, butane compris.", max_length=12, null=True, verbose_name='Pompe actuelle — alimentation'),
        ),
        migrations.AddField(
            model_name='lead',
            name='type_bien',
            field=models.CharField(blank=True, choices=[('villa', 'Villa'), ('appartement', 'Appartement'), ('immeuble', 'Immeuble'), ('riad', 'Riad'), ('ferme', 'Ferme'), ('autre', 'Autre')], help_text="Question à l'appel : « De quel type de bien s'agit-il — villa, appartement, immeuble, riad, ferme ? » (vide = pas encore posée). Remplace l'idée de faire saisir le type de toit au téléphone : ce chemin-là est fermé depuis la décision du 18/08/2026.", max_length=12, null=True, verbose_name='Type de bien'),
        ),
    ]
