# Generated by Django 5.1.15 on 2026-09-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0104_cad118_issue_de_touche'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_creation_origine',
            field=models.DateTimeField(blank=True, help_text="Quand ce dossier est-il né chez le système qui nous l'a transmis (Odoo, import) ? Vide si créé ici.", null=True, verbose_name="Date de création dans le système d'origine"),
        ),
    ]
