# Generated by Django 5.1.15 on 2026-09-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0104_cad149_vague1_champs'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='budget_client_mad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel, APRÈS l'envoi du devis seulement (décision fondateur du 21/09/2026) : « Quel budget aviez-vous en tête ? » (vide = pas encore posée). DISTINCT du montant estimé, qui est l'estimation du COMMERCIAL et nourrit le forecast pondéré. Question ORALE : jamais dans le questionnaire envoyé au client.", max_digits=12, null=True, verbose_name='Budget annoncé par le client (MAD)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='chauffage_electrique_hiver',
            field=models.BooleanField(blank=True, help_text="Question à l'appel : « Vous chauffez-vous à l'électricité en hiver ? » (Oui/Non — vide = pas encore posée). Champ INFORMATIF : décision fondateur du 21/09/2026 — aucune couche de chauffage d'hiver n'est composée, donc il n’ajuste AUCUNE courbe.", null=True, verbose_name='Chauffage électrique en hiver'),
        ),
        migrations.AddField(
            model_name='lead',
            name='compteur_puissance_kva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel, EN DERNIER RECOURS seulement : « Quelle puissance est inscrite sur votre compteur (kVA) ? » (vide = pas encore posée). La voie NORMALE est la photo du compteur, que le questionnaire demande déjà — on ne fait lire une plaque au téléphone que si la photo est impossible.", max_digits=7, null=True, verbose_name='Puissance souscrite du compteur (kVA)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='declencheur',
            field=models.CharField(blank=True, choices=[('economies', 'Les économies'), ('coupures', 'Les coupures / l’autonomie'), ('ecologie', 'L’écologie'), ('technologie', 'La technologie')], help_text="Question à l'appel : « Qu'est-ce qui vous a donné envie de vous renseigner ? » (vide = pas encore posée). Même vocabulaire que la qualification de visite. Question ORALE.", max_length=12, null=True, verbose_name='Ce qui a accroché'),
        ),
        migrations.AddField(
            model_name='lead',
            name='frein_principal',
            field=models.CharField(blank=True, choices=[('aucun', 'Aucun frein'), ('prix', 'Prix'), ('compare', 'Compare d’autres devis'), ('timing', 'Timing'), ('technique', 'Technique'), ('confiance', 'Confiance')], help_text="Question à l'appel : « Qu'est-ce qui vous retient aujourd’hui ? » (vide = pas encore posée). Même vocabulaire que la qualification de visite, pour que le terrain et le téléphone se relisent. Question ORALE.", max_length=12, null=True, verbose_name='Frein principal'),
        ),
        migrations.AddField(
            model_name='lead',
            name='nb_personnes_foyer',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Question à l'appel : « Combien de personnes vivent dans ce logement ? » (vide = pas encore posée). Le moteur dit lui-même que son absence l'empêche de chiffrer le chauffe-eau par ordre de grandeur : sans ce nombre, la couche est OMISE plutôt qu’inventée.", null=True, verbose_name='Nombre de personnes au foyer'),
        ),
    ]
