# Generated by Django 5.1.15 on 2026-09-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0105_cad154_vague2_champs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='distributeur',
            field=models.CharField(blank=True, choices=[('srm_tanger', 'SRM Tanger-Tétouan-Al Hoceïma'), ('srm_oriental', 'SRM de l’Oriental'), ('srm_fes', 'SRM Fès-Meknès'), ('srm_rabat', 'SRM Rabat-Salé-Kénitra'), ('srm_beni_mellal', 'SRM Béni Mellal-Khénifra'), ('srm_casablanca', 'SRM Casablanca-Settat'), ('srm_marrakech', 'SRM Marrakech-Safi'), ('srm_draa', 'SRM Drâa-Tafilalet'), ('srm_souss', 'SRM Souss-Massa'), ('srm_guelmim', 'SRM Guelmim-Oued Noun'), ('srm_laayoune', 'SRM Laâyoune-Sakia El Hamra'), ('srm_dakhla', 'SRM Dakhla-Oued Ed-Dahab'), ('onee', 'ONEE (historique)'), ('lydec', 'Lydec (historique)'), ('redal', 'Redal (historique)'), ('amendis', 'Amendis (historique)'), ('autre', 'Autre (historique)')], help_text="Question à l'appel : AUCUNE — la SRM se DÉDUIT de la ville du lead (règle CAD167). Le champ reste saisissable pour corriger une déduction, et les libellés historiques (ONEE, Lydec, Redal, Amendis) restent lisibles sur les fiches déjà remplies. La valeur ne change AUCUN prix : le barème est national et unique.", max_length=20, null=True, verbose_name="Distributeur d'électricité"),
        ),
    ]
