# Generated by Django 5.1.15 on 2026-09-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Rebasée au fold du 21/09 : la chaîne crm a avancé (CAD149/154/167)
        # pendant que cette lane construisait. Une seule feuille, jamais un
        # `--merge` : la migration est purement additive.
        ('crm', '0106_cad167_distributeur_srm'),
    ]

    operations = [
        migrations.AddField(
            model_name='relanceetape',
            name='outcome',
            field=models.CharField(blank=True, choices=[('', '—'), ('joint', 'Joint'), ('non_joint', 'Non joint'), ('rappel', 'À rappeler'), ('refuse', 'Refus'), ('interesse', 'Intéressé'), ('visite_acceptee', 'Visite acceptée')], default='', help_text='Ce que la touche a donné : le client a-t-il été joint ?', max_length=20, verbose_name='Issue de la touche'),
        ),
    ]
