# Generated by Django 5.1.15 on 2026-09-21 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_solmvp30b_customuser_sans_poste_ref'),
        ('crm', '0108_cad119_date_creation_origine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_debut', models.DateField(help_text='À partir de quel jour, ce jour-là compris ?', verbose_name='Premier jour')),
                ('date_fin', models.DateField(help_text='Jusqu’à quel jour, ce jour-là compris ?', verbose_name='Dernier jour')),
                ('motif', models.CharField(choices=[('conge', 'Congé'), ('arret', 'Arrêt maladie'), ('formation', 'Formation'), ('autre', 'Autre')], default='conge', help_text='Congé, arrêt maladie, formation, ou autre ?', max_length=10, verbose_name='Motif')),
                ('note', models.TextField(blank=True, default='', help_text='Quelque chose à savoir pour la reprise ?', verbose_name='Note')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('remplacant', models.ForeignKey(blank=True, help_text='Qui reprend les dossiers pendant cette absence ?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_absences_couvertes', to=settings.AUTH_USER_MODEL, verbose_name='Reprise des dossiers')),
                ('utilisateur', models.ForeignKey(blank=True, help_text='Qui est absent ? Laisser vide pour une fermeture qui concerne toute la société.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_absences', to=settings.AUTH_USER_MODEL, verbose_name='Personne absente')),
            ],
            options={
                'verbose_name': 'Période d’absence',
                'verbose_name_plural': 'Périodes d’absence',
                'ordering': ['-date_debut', 'utilisateur_id'],
                'indexes': [models.Index(fields=['company', 'date_debut', 'date_fin'], name='crm_absence_periode_idx')],
            },
        ),
    ]
