# Generated by Django 5.1.15 on 2026-09-25 01:55
#
# PARAM-CADENCE (décision fondateur du 25/09/2026) — `RelanceEtape.cle` : la
# clé stable du barreau paramétré (Paramètres → CRM, cadences « Après l'appel
# (avant devis) » et « Visite technique ») dont le moteur a tiré l'étape.
# Colonne ADDITIVE, vide par défaut, SANS migration de données : les étapes
# posées avant la clé restent reconnues par leur libellé par défaut
# (`apps/crm/cadence_config.est_etape`). Réversible tel quel.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0113_cad65_lead_civilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='relanceetape',
            name='cle',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Clé moteur'),
        ),
    ]
