# Generated by Django 5.1.15 on 2026-09-28 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_solmvp30b_customuser_sans_poste_ref'),
        ('crm', '0114_param_cadence_relance_etape_cle'),
    ]

    operations = [
        migrations.CreateModel(
            name='GesteRelanceAppareil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geste', models.CharField(choices=[('fait', 'Fait'), ('reporter', 'Reporter'), ('appeler', 'Appeler'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('famille_appareil', models.CharField(choices=[('mobile', 'Mobile'), ('tablette', 'Tablette'), ('ordinateur', 'Ordinateur'), ('inconnu', 'Inconnu')], max_length=20)),
                ('jour', models.DateField(verbose_name='Jour (Casablanca)')),
                ('total', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Geste de relance par appareil',
                'verbose_name_plural': 'Gestes de relance par appareil',
                'ordering': ['-jour', 'geste', 'famille_appareil'],
                'indexes': [models.Index(fields=['company', 'jour'], name='crm_geste_appareil_jour_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'geste', 'famille_appareil', 'jour'), name='crm_geste_appareil_unique')],
            },
        ),
    ]
