# Generated by Django 5.1.15 on 2026-10-03 03:00

import apps.crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0117_qjr595_bag_pro_vers_colonnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='autorisation_debit_l_s',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Quel débit l'autorisation vous accorde-t-elle, en litres par seconde ? » (vide = pas encore posée).", max_digits=8, null=True, verbose_name='Débit autorisé (L/s)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='autorisation_numero',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Quel est le numéro de cette autorisation ? » (vide = pas encore posée).", max_length=60, null=True, verbose_name="Numéro de l'autorisation"),
        ),
        migrations.AddField(
            model_name='lead',
            name='autorisation_prelevement',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('en_cours', 'En cours'), ('ne_sait_pas', 'Ne sait pas')], help_text="Question à l'appel : « Avez-vous l'autorisation de l'Agence de bassin (ABH) pour ce point d'eau ? » (vide = pas encore posée).", max_length=12, null=True, verbose_name='Autorisation de prélèvement (ABH)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='autorisation_volume_m3_an',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Quel volume par an l'autorisation vous accorde-t-elle ? » (vide = pas encore posée).", max_digits=12, null=True, verbose_name='Volume autorisé (m³/an)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='besoin_eau_m3j',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Combien de m³ d'eau par jour en pleine saison ? » (vide = pas encore posée).", max_digits=9, null=True, verbose_name='Besoin en eau (m³/jour)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='besoin_eau_source',
            field=models.CharField(blank=True, choices=[('client', 'Déclaré par le client'), ('site_web', 'Saisi sur le site'), ('pompe_actuelle', 'Calculé depuis la pompe actuelle')], max_length=14, null=True, verbose_name='Provenance du besoin en eau'),
        ),
        migrations.AddField(
            model_name='lead',
            name='butane_bouteilles_jour',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Question à l'appel : « Combien de bouteilles de butane par jour en saison ? » (bouteilles de 12 kg par jour d'irrigation, vide = pas encore posée).", max_digits=5, null=True, verbose_name='Butane — bouteilles par jour'),
        ),
        migrations.AddField(
            model_name='lead',
            name='carburant_prix_declare_le',
            field=models.DateField(blank=True, null=True, verbose_name='Prix du carburant déclaré le'),
        ),
        migrations.AddField(
            model_name='lead',
            name='carburant_prix_unitaire_mad',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Vous la payez combien, la bouteille (ou le litre de gasoil) ? » (MAD, vide = pas encore posée). Prix PAYÉ déclaré, jamais pré-rempli.", max_digits=8, null=True, verbose_name='Prix payé (bouteille ou litre, MAD)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='compteur_eau',
            field=models.BooleanField(blank=True, help_text="Question à l'appel : « Avez-vous un compteur d'eau ? » (vide = pas encore posée).", null=True, verbose_name="Compteur d'eau"),
        ),
        migrations.AddField(
            model_name='lead',
            name='culture',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Qu'est-ce que vous cultivez ? » (vide = pas encore posée).", max_length=120, null=True, verbose_name='Culture'),
        ),
        migrations.AddField(
            model_name='lead',
            name='debit_forage_m3h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Le débit de votre forage est-il connu (essai, foreur) ? Combien d'eau peut-il donner par heure ? » (m³/h, vide = pas encore posée).", max_digits=8, null=True, verbose_name='Débit du forage (m³/h)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='debit_forage_source',
            field=models.CharField(blank=True, choices=[('essai', 'Essai de pompage'), ('foreur', 'Donné par le foreur'), ('client', 'Estimation du client'), ('mesure_visite', 'Mesuré en visite')], max_length=14, null=True, verbose_name='Provenance du débit du forage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='deja_beneficiaire_fda',
            field=models.BooleanField(blank=True, help_text="Question à l'appel : « Avez-vous déjà reçu une aide FDA pour un pompage solaire sur cette exploitation ? » (vide = pas encore posée). Information interne : jamais un verdict client.", null=True, verbose_name='Déjà bénéficiaire FDA'),
        ),
        migrations.AddField(
            model_name='lead',
            name='depense_carburant_mad_mois',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Combien dépensez-vous en carburant par mois ? » (MAD/mois, vide = pas encore posée). Information : jamais convertie en consommation.", max_digits=10, null=True, verbose_name='Dépense carburant (MAD/mois)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='distance_forage_champ_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « À quelle distance du forage peut-on poser les panneaux ? » (mètres, vide = pas encore posée).", max_digits=8, null=True, verbose_name='Distance forage — panneaux (m)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='electricite_sur_place',
            field=models.CharField(blank=True, choices=[('aucune', 'Aucune'), ('monophase', 'Monophasé'), ('triphase', 'Triphasé'), ('ne_sait_pas', 'Ne sait pas')], help_text="Question à l'appel : « Y a-t-il l'électricité au forage : monophasé, triphasé ou rien ? » (vide = pas encore posée).", max_length=12, null=True, verbose_name='Électricité au forage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='irrigation_methode',
            field=models.CharField(blank=True, choices=[('goutte', 'Goutte-à-goutte'), ('aspersion', 'Aspersion'), ('gravitaire', 'Gravitaire (à la raie)')], help_text="Question à l'appel : « Vous arrosez comment : goutte-à-goutte, aspersion ou à la raie ? » (vide = pas encore posée).", max_length=12, null=True, verbose_name="Méthode d'irrigation"),
        ),
        migrations.AddField(
            model_name='lead',
            name='mois_irrigation',
            field=models.JSONField(blank=True, help_text="Question à l'appel : « Vous irriguez quels mois ? » (liste de mois 1 à 12, vide = pas encore posée).", null=True, validators=[apps.crm.models.valider_mois_irrigation], verbose_name="Mois d'irrigation"),
        ),
        migrations.AddField(
            model_name='lead',
            name='niveau_statique_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « À quelle profondeur est l'eau quand la pompe est arrêtée ? » (mètres, vide = pas encore posée).", max_digits=7, null=True, verbose_name="Niveau de l'eau, pompe arrêtée (m)"),
        ),
        migrations.AddField(
            model_name='lead',
            name='niveau_statique_source',
            field=models.CharField(blank=True, choices=[('declare', 'Déclaré par le client'), ('site_web', 'Saisi sur le site'), ('mesure_visite', 'Mesuré en visite')], max_length=14, null=True, verbose_name='Provenance du niveau statique'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pompe_actuelle_debit_m3h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Combien d'eau votre pompe actuelle sort-elle par heure ? » (m³/h, vide = pas encore posée). Avec les heures de la pompe actuelle, donne le volume déclaré.", max_digits=8, null=True, verbose_name='Pompe actuelle — débit (m³/h)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pompe_actuelle_type',
            field=models.CharField(blank=True, choices=[('immergee', 'Immergée'), ('surface', 'De surface'), ('ne_sait_pas', 'Ne sait pas')], help_text="Question à l'appel : « Votre pompe actuelle est-elle immergée dans le forage, ou en surface ? » (vide = pas encore posée).", max_length=12, null=True, verbose_name='Pompe actuelle — type'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pompe_hmt_source',
            field=models.CharField(blank=True, choices=[('declaree', 'Déclarée'), ('site_web', 'Saisie sur le site')], max_length=10, null=True, verbose_name='Provenance de la HMT'),
        ),
        migrations.AddField(
            model_name='lead',
            name='profondeur_forage_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Quelle est la profondeur totale du forage ? » (mètres, vide = pas encore posée).", max_digits=7, null=True, verbose_name='Profondeur du forage (m)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='projet_pompage',
            field=models.CharField(blank=True, choices=[('existant', 'Remplacer une pompe existante'), ('nouveau_forage', 'Nouveau forage')], help_text="Question à l'appel : « C'est un puits/forage qui existe, ou un forage à creuser ? » (vide = pas encore posée).", max_length=16, null=True, verbose_name='Projet de pompage'),
        ),
        migrations.AddField(
            model_name='lead',
            name='region_agricole',
            field=models.CharField(blank=True, choices=[('souss-massa', 'Souss-Massa'), ('doukkala', 'Doukkala'), ('tadla', 'Tadla'), ('saiss', 'Saïss'), ('oriental', 'Oriental'), ('draa-tafilalet', 'Drâa-Tafilalet'), ('gharb-loukkos', 'Gharb-Loukkos'), ('haouz', 'Haouz')], help_text="Question à l'appel : « Dans quelle région se trouve l'exploitation ? » (vide = pas encore posée).", max_length=16, null=True, verbose_name='Région agricole'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_eau',
            field=models.CharField(blank=True, choices=[('puits', 'Puits'), ('forage', 'Forage'), ('bassin', 'Bassin'), ('riviere', 'Rivière')], help_text="Question à l'appel : « L'eau vient d'où : un puits, un forage, un bassin ou une rivière ? » (vide = pas encore posée).", max_length=10, null=True, verbose_name="Source d'eau"),
        ),
        migrations.AddField(
            model_name='lead',
            name='surface_irriguee_ha',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Combien d'hectares irriguez-vous ? » (vide = pas encore posée).", max_digits=9, null=True, verbose_name='Surface irriguée (ha)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pompage_heures_jour',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="Question à l'appel : « Combien d'heures par jour la pompe ACTUELLE tourne-t-elle ? » (h/jour, vide = pas encore posée). Heures de la pompe ACTUELLE : elles servent seulement à estimer un volume déclaré (débit actuel × heures), jamais des heures de pompage solaire. Colonne dédiée de la réponse que le site envoie déjà sous « heures de pompage ».", max_digits=4, null=True, verbose_name='Pompage — heures par jour'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pompe_debit_m3h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Quel débit voulez-vous, en m³ par heure ? » (débit SOUHAITÉ, vide = pas encore posée). Servi à côté du débit livré, il ne fixe jamais seul le besoin.", max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='pompe_hmt_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Connaissez-vous la hauteur totale de pompage, en mètres ? » (HMT, vide = pas encore posée).", max_digits=8, null=True),
        ),
    ]
