# Generated by Django 5.1.15 on 2026-10-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0120_agr402_sac_pompage_vers_colonnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='dossier_subvention',
            field=models.CharField(blank=True, choices=[('non_concerne', 'Non concerné'), ('a_deposer', 'À déposer'), ('depose', 'Déposé'), ('accorde', 'Accordé (approbation préalable)'), ('refuse', 'Refusé')], max_length=14, null=True, verbose_name='Dossier de subvention (FDA)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='dossier_subvention_le',
            field=models.DateField(blank=True, null=True, verbose_name='Date de l’état du dossier de subvention'),
        ),
    ]
