# Generated by Django 5.1.15 on 2026-10-05 10:00
# CIQ401 — colonnes PRO du Lead (contrat CIQ1 lead_pro.json), chacune avec sa
# question d'appel. ADDITIVE : toutes nullables (vide = pas encore posée) ; les
# AlterField ne changent que help_text / verbose_name / choix (credit_bail
# interne) — aucune opération en base.

import apps.crm.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0122_agr525_seed_playbooks_segment_existants'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='adresse_siege',
            field=models.TextField(blank=True, help_text="Question à l'appel : « Quelle est l'adresse du siège, si elle diffère de celle du site ? » (vide = pas encore posée).", null=True, verbose_name='Adresse du siège'),
        ),
        migrations.AddField(
            model_name='lead',
            name='categorie_commerciale',
            field=models.CharField(blank=True, choices=[('hotel', 'Hôtel / riad'), ('restaurant', 'Restaurant / café'), ('commerce', 'Commerce / supermarché'), ('bureau', 'Bureaux'), ('sante', 'Santé (clinique, cabinet)'), ('ecole', 'École'), ('hammam', 'Hammam / spa / salle de sport'), ('boulangerie', 'Boulangerie'), ('froid', 'Froid / entrepôt frigorifique'), ('autre', 'Autre')], help_text="Question à l'appel : « Quelle est votre activité : hôtel, restaurant ou café, commerce, bureaux, santé, école, hammam, boulangerie, froid, ou autre chose ? » (vide = pas encore posée).", max_length=12, null=True, verbose_name='Activité (catégorie commerciale)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_secondaire_email',
            field=models.EmailField(blank=True, help_text="Question à l'appel : « Pouvons-nous lui envoyer le devis par e-mail ? À quelle adresse ? » (jamais utilisé par la cadence ; vide = pas encore posée).", max_length=254, null=True, verbose_name='Contact secondaire (e-mail)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_secondaire_fonction',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Qui d'autre décide avec vous ? Quelle est sa fonction ? » (CAD144 : sans automatisation ; vide = pas encore posée).", max_length=120, null=True, verbose_name='Contact secondaire (fonction)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='cos_phi',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Question à l'appel : « Votre facture indique-t-elle un cosinus phi ou une pénalité d'énergie réactive ? Quelle valeur ? » (jamais supposé ; vide = pas encore posée).", max_digits=4, null=True, validators=[apps.crm.models.valider_cos_phi], verbose_name='Cos φ'),
        ),
        migrations.AddField(
            model_name='lead',
            name='cos_phi_source',
            field=models.CharField(blank=True, choices=[('facture', 'Lu sur la facture'), ('site_web', 'Saisi sur le site'), ('mesure_visite', 'Mesuré en visite')], max_length=14, null=True, verbose_name='Provenance du cos φ'),
        ),
        migrations.AddField(
            model_name='lead',
            name='export_ue_declare',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], help_text="Question à l'appel : « Exportez-vous une partie de votre production vers l'Union européenne ? » (vide = pas encore posée).", max_length=3, null=True, verbose_name="Exporte vers l'Union européenne"),
        ),
        migrations.AddField(
            model_name='lead',
            name='facture_tranche_declaree',
            field=models.JSONField(blank=True, help_text="Question à l'appel : « Votre facture mensuelle se situe dans quelle tranche ? » — D-CIQ-19 : une tranche OUVERTE (« plus de 4 000 DH ») n'est JAMAIS stockée comme un montant.", null=True, validators=[apps.crm.models.valider_facture_tranche_declaree], verbose_name='Tranche de facture déclarée'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fermeture_mois',
            field=models.JSONField(blank=True, help_text="Question à l'appel : « Fermez-vous certains mois de l'année, pour des congés ou une saison creuse ? Lesquels ? » (entiers 1-12 ; vide = pas encore posée).", null=True, validators=[apps.crm.models.valider_fermeture_mois], verbose_name='Mois de fermeture'),
        ),
        migrations.AddField(
            model_name='lead',
            name='fonction_contact',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Quelle est votre fonction dans l'entreprise ? » (vide = pas encore posée).", max_length=120, null=True, verbose_name='Fonction du contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='groupe_depense_mad_mois',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Combien dépensez-vous en gasoil pour le groupe chaque mois ? » (DÉCLARÉ seulement, jamais un prix pré-rempli — Q17 ; vide = pas encore posée).", max_digits=10, null=True, verbose_name='Groupe électrogène — dépense (MAD/mois)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='groupe_electrogene',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non')], help_text="Question à l'appel : « Avez-vous un groupe électrogène sur le site ? » (vide = pas encore posée).", max_length=3, null=True, verbose_name='Groupe électrogène'),
        ),
        migrations.AddField(
            model_name='lead',
            name='groupe_kva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Quelle est sa puissance, en kVA ? » (vide = pas encore posée).", max_digits=8, null=True, verbose_name='Groupe électrogène — puissance (kVA)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='groupe_litres_mois',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Combien de litres de gasoil consomme-t-il par mois ? » (vide = pas encore posée).", max_digits=9, null=True, verbose_name='Groupe électrogène — gasoil (L/mois)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='heure_debut',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Question à l'appel : « À quelle heure commence votre journée de travail ? » (0-24 ; vide = pas encore posée).", null=True, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Heure de début de journée'),
        ),
        migrations.AddField(
            model_name='lead',
            name='heure_fin',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Question à l'appel : « Et à quelle heure se termine-t-elle ? » (0-24 ; vide = pas encore posée).", null=True, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Heure de fin de journée'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ice',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Pouvez-vous nous donner l'ICE de l'entreprise ? Il figurera sur le devis et la facture. » (texte libre ; demandé, jamais bloquant au devis — D-CIQ-11).", max_length=30, null=True, verbose_name='ICE'),
        ),
        migrations.AddField(
            model_name='lead',
            name='if_fiscal',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Et l'identifiant fiscal ? » (vide = pas encore posée).", max_length=30, null=True, verbose_name='Identifiant fiscal (IF)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='jours_ouverture',
            field=models.JSONField(blank=True, help_text="Question à l'appel : « Quels jours de la semaine êtes-vous ouverts ou en production ? » (entiers 1 = lundi à 7 = dimanche ; vide = pas encore posée).", null=True, validators=[apps.crm.models.valider_jours_ouverture], verbose_name="Jours d'ouverture"),
        ),
        migrations.AddField(
            model_name='lead',
            name='puissance_souscrite_source',
            field=models.CharField(blank=True, choices=[('declare', 'Déclarée'), ('facture', 'Lue sur la facture'), ('contrat', 'Lue sur le contrat'), ('site_web', 'Saisie sur le site'), ('mesure_visite', 'Mesurée en visite')], max_length=14, null=True, verbose_name='Provenance de la puissance souscrite'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pv_existant_kwc',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Avez-vous déjà des panneaux solaires installés ? De quelle puissance ? » (vide = pas encore posée).", max_digits=9, null=True, verbose_name='Photovoltaïque existant (kWc)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='rc',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Et son numéro de registre de commerce ? » (vide = pas encore posée).", max_length=30, null=True, verbose_name='Registre de commerce (RC)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='regime_equipes',
            field=models.CharField(blank=True, choices=[('1x8', 'Une équipe (1×8)'), ('2x8', 'Deux équipes (2×8)'), ('3x8', 'Trois équipes (3×8)'), ('continu', 'En continu'), ('ne_sait_pas', 'Ne sait pas')], help_text="Question à l'appel : « Travaillez-vous en une équipe de jour, en deux équipes, en trois équipes, ou en continu ? » (vide = pas encore posée).", max_length=12, null=True, verbose_name='Régime des équipes'),
        ),
        migrations.AddField(
            model_name='lead',
            name='releve_conso',
            field=models.JSONField(blank=True, help_text="Question à l'appel : « Pouvez-vous nous envoyer vos dernières factures d'électricité ? Jusqu'à douze mois nous aident à être précis. » (au plus 12 mois, jamais exigés tous les douze ; vide = pas encore posée).", null=True, validators=[apps.crm.models.valider_releve_conso], verbose_name='Relevé mensuel de consommation'),
        ),
        migrations.AddField(
            model_name='lead',
            name='reponses_categorie',
            field=models.JSONField(blank=True, help_text="Question à l'appel : « Les questions propres à votre activité » (chambres, couverts, chambres froides…), posées juste après l'activité. Clés FERMÉES par catégorie (``REPONSES_CATEGORIE_CLES``).", null=True, verbose_name="Réponses propres à l'activité"),
        ),
        migrations.AddField(
            model_name='lead',
            name='secteur_industriel',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Que fabriquez-vous ou que transformez-vous sur ce site ? » (vide = pas encore posée).", max_length=120, null=True, verbose_name='Secteur industriel'),
        ),
        migrations.AddField(
            model_name='lead',
            name='surface_source',
            field=models.CharField(blank=True, choices=[('declare', 'Déclarée'), ('site_web', 'Saisie sur le site'), ('calepinage', 'Calepinage'), ('mesure_visite', 'Mesurée en visite')], max_length=14, null=True, verbose_name='Provenance de la surface'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tension_raccordement',
            field=models.CharField(blank=True, choices=[('bt', 'Basse tension (BT)'), ('mt', 'Moyenne tension (MT)'), ('ne_sait_pas', 'Ne sait pas')], help_text="Question à l'appel : « Votre site est-il raccordé en basse tension, avec un compteur ordinaire, ou en moyenne tension, avec un poste de transformation ? Si vous ne savez pas, ce n'est pas grave. » (vide = pas encore posée).", max_length=12, null=True, verbose_name='Tension de raccordement'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tension_source',
            field=models.CharField(blank=True, choices=[('declare', 'Déclarée'), ('site_web', 'Saisie sur le site'), ('site_defaut_visible', 'Défaut visible du site'), ('facture', 'Lue sur la facture'), ('mesure_visite', 'Mesurée en visite')], max_length=20, null=True, verbose_name='Provenance de la tension'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tva_recuperable',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('ne_sait_pas', 'Ne sait pas')], help_text="Question à l'appel : « Votre entreprise récupère-t-elle la TVA sur ses achats ? » (D-CIQ-3 ; vide = pas encore posée).", max_length=12, null=True, verbose_name='TVA récupérable'),
        ),
        migrations.AddField(
            model_name='lead',
            name='type_surface',
            field=models.CharField(blank=True, choices=[('toiture', 'Toiture'), ('ombriere', 'Ombrière de parking'), ('terrain', 'Terrain')], help_text="Question à l'appel : « Où pourrait-on poser les panneaux : sur la toiture, sur une ombrière de parking, ou sur un terrain ? » (vide = pas encore posée).", max_length=10, null=True, verbose_name='Type de surface'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='compteur_puissance_kva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Quelle est votre puissance souscrite, en kVA ? Elle est écrite sur votre facture ou votre contrat. » (vide = pas encore posée).", max_digits=7, null=True, verbose_name='Puissance souscrite du compteur (kVA)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='conso_mensuelle_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Votre consommation du mois dernier, en kWh ? Elle est sur la facture. » (vide = pas encore posée).", max_digits=10, null=True, verbose_name='Consommation mensuelle (kWh)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='financing_intent',
            field=models.CharField(blank=True, choices=[('cash', 'Comptant'), ('credit', 'Crédit / financement'), ('indecis', 'Pas encore décidé'), ('credit_bail', 'Crédit-bail (interne)')], help_text="Question à l'appel : « Pensez-vous payer comptant, ou passer par un financement ? » (vide = pas encore posée). « Crédit-bail » est une valeur INTERNE, jamais imprimée avant l'avis juridique (D-CIQ-15).", max_length=12, null=True, verbose_name='Financement envisagé'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='raccordement',
            field=models.CharField(blank=True, choices=[('monophase', 'Monophasé'), ('triphase', 'Triphasé'), ('inconnu', 'Je ne sais pas'), ('aucun', 'Non raccordé (site isolé)')], help_text="Question à l'appel : « Votre compteur est-il monophasé ou triphasé ? » (vide = pas encore posée).", max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='societe',
            field=models.CharField(blank=True, help_text="Question à l'appel : « Quelle est la raison sociale de votre entreprise ? » (vide = pas encore posée).", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='surface_toiture_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Question à l'appel : « Quelle surface est libre pour les panneaux, en m² ? » (vide = pas encore posée).", max_digits=10, null=True, verbose_name='Surface disponible pour les panneaux (m²)'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type_toiture',
            field=models.CharField(blank=True, choices=[('terrasse_beton', 'Terrasse béton'), ('tole_metal', 'Tôle/Métal'), ('tuiles', 'Tuiles'), ('bac_acier', 'Bac acier'), ('fibrociment', 'Fibrociment'), ('autre', 'Autre')], help_text="Question à l'appel : « Comment est faite votre toiture : terrasse béton, tôle, tuiles, bac acier, fibrociment ? » (vide = pas encore posée).", max_length=20, null=True),
        ),
    ]
