# Generated by Django 5.1.15 on 2026-10-05 10:00
# CIQ402 — client ENTREPRISE (contrat CIQ8 client_entreprise.json, D-CIQ-11) :
# siège, personne « à l'attention de », TVA récupérable, raison sociale à
# confirmer. ADDITIVE : aucun ancien client n'est modifié.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0123_ciq401_lead_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse_siege',
            field=models.TextField(blank=True, help_text="Sert au document et à la facture quand elle existe ; sinon l'adresse (du site).", null=True, verbose_name='Adresse du siège'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_fonction',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Fonction du contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_nom',
            field=models.CharField(blank=True, help_text="La personne qui représente l'entreprise.", max_length=255, null=True, verbose_name="À l'attention de"),
        ),
        migrations.AddField(
            model_name='client',
            name='raison_sociale_a_confirmer',
            field=models.BooleanField(default=False, help_text='Commerçant en nom propre créé depuis un lead sans raison sociale : le nom est celui de la personne — jamais bloquant.', verbose_name='Raison sociale à confirmer'),
        ),
        migrations.AddField(
            model_name='client',
            name='tva_recuperable',
            field=models.CharField(blank=True, choices=[('oui', 'Oui'), ('non', 'Non'), ('ne_sait_pas', 'Ne sait pas')], help_text='D-CIQ-3 : économies en HT si oui, en TTC sinon.', max_length=12, null=True, verbose_name='TVA récupérable'),
        ),
    ]
