# Generated by Django 5.1.15 on 2026-10-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0126_ciq408_tranche_meta_ouverte'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='gclid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='canal',
            field=models.CharField(blank=True, choices=[('meta_ads', 'Publicité Meta'), ('whatsapp_ctwa', 'WhatsApp/CTWA'), ('site_web', 'Site web'), ('google_ads', 'Google Ads'), ('reference', 'Référence'), ('telephone', 'Téléphone'), ('walk_in', 'Visite/Walk-in'), ('autre', 'Autre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pointcontact',
            name='canal',
            field=models.CharField(choices=[('meta_ads', 'Publicité Meta'), ('whatsapp_ctwa', 'WhatsApp/CTWA'), ('site_web', 'Site web'), ('google_ads', 'Google Ads'), ('reference', 'Référence'), ('telephone', 'Téléphone'), ('walk_in', 'Visite/Walk-in'), ('autre', 'Autre')], max_length=20, verbose_name='Canal'),
        ),
    ]
