# Generated by Django 5.1.15 on 2026-10-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0128_ciq517_playbook_8221_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contrat_electricite',
            field=models.CharField(blank=True, choices=[('bt_domestique', 'BT domestique'), ('bt_patente', 'BT patenté'), ('bt_force_motrice', 'BT force motrice'), ('mt_general', 'MT (Tarif Général)'), ('ne_sait_pas', 'Ne sait pas')], help_text="Question à l'appel : « Quel est votre contrat d'électricité : basse tension patenté, force motrice, domestique, ou moyenne tension ? Il est écrit sur votre facture. » (CIQ666 ; vide = pas encore posée, « ne sait pas » = aucun contrat transmis au devis automatique).", max_length=20, null=True, verbose_name="Contrat d'électricité"),
        ),
        migrations.AddField(
            model_name='lead',
            name='option_tarifaire_bt',
            field=models.CharField(blank=True, choices=[('normale', 'Option normale (tranches)'), ('bi_horaire', 'Option bi-horaire (HP / HN)')], help_text="Question à l'appel : « En force motrice, êtes-vous en option normale ou en option bi-horaire ? » (CIQ666 ; seule la force motrice ouvre le bi-horaire ; vide = pas encore posée).", max_length=12, null=True, verbose_name='Option tarifaire BT'),
        ),
    ]
