# Generated by Django 5.1.15 on 2026-10-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0132_acrm32_lead_whatsapp_normalise_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionpartenaire',
            name='partenaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='crm.partenaire', verbose_name='Partenaire'),
        ),
    ]
