# Generated by Django 5.1.15 on 2026-10-11 00:52
"""ACRM62 (D-ACRM-5 (2)=(a)) — liste d'opposition par empreinte hachée.

Additive et revertable (CreateModel) : aucune donnée existante touchée.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_asec5_totp_dernier_pas'),
        ('crm', '0134_alter_commissionpartenaire_partenaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpreinteOpposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nature', models.CharField(choices=[('email', 'E-mail'), ('telephone', 'Téléphone')], max_length=10)),
                ('empreinte', models.CharField(max_length=64)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Empreinte d'opposition",
                'verbose_name_plural': "Empreintes d'opposition",
                'constraints': [models.UniqueConstraint(fields=('company', 'nature', 'empreinte'), name='crm_empreinte_opposition_uniq')],
            },
        ),
    ]
