# Generated by Django 5.1.15 on 2026-10-11 01:26
"""ACRM55 — une seule touche À FAIRE par barreau (lead, cadence, ordre, devis)
des cadences contact / apres_devis / reveil (filets et gestes à ``cle`` hors
contrainte). Pré-contrôle en lecture du 11/10/2026 : 0 groupe en doublon en
production comme sur la démo. Revertable (RemoveConstraint).
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0135_acrm62_empreinte_opposition'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='relanceetape',
            constraint=models.UniqueConstraint(condition=models.Q(('cadence__in', ('contact', 'apres_devis', 'reveil')), ('cle', ''), ('statut', 'a_faire')), fields=('lead', 'cadence', 'ordre', 'devis'), name='crm_relance_une_ouverte_par_barreau', nulls_distinct=False),
        ),
    ]
