# Generated by Django 5.1.4 on 2026-06-13 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0007_mark_owner_protected'),
        ('crm', '0011_client_type_from_ice'),
        ('installations', '0001_initial'),
        ('stock', '0011_produit_garantie_mois_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=120, null=True)),
                ('date_pose', models.DateField(blank=True, null=True)),
                ('date_fin_garantie', models.DateField(blank=True, null=True)),
                ('date_fin_garantie_production', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_service', 'En service'), ('remplace', 'Remplacé'), ('hors_service', 'Hors service')], default='en_service', max_length=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_crees', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='installations.installation')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipements', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('correctif', 'Correctif'), ('preventif', 'Préventif')], default='correctif', max_length=12)),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('planifie', 'Planifié'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('cloture', 'Clôturé')], default='nouveau', max_length=12)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ouverture', models.DateField(blank=True, null=True)),
                ('date_resolution', models.DateField(blank=True, null=True)),
                ('sous_garantie', models.CharField(choices=[('oui', 'Oui'), ('non', 'Non'), ('a_determiner', 'À déterminer')], default='a_determiner', max_length=12)),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annule', models.BooleanField(default=False)),
                ('motif_annulation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets_sav', to='crm.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_sav', to='authentication.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_crees', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='sav.equipement')),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='installations.installation')),
                ('technicien_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_techniques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket SAV',
                'verbose_name_plural': 'Tickets SAV',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='equipement',
            name='remplace_par_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_remplaces', to='sav.ticket'),
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('creation', 'Création'), ('modification', 'Modification'), ('note', 'Note')], max_length=15)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('field_label', models.CharField(blank=True, max_length=150, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_activities', to='authentication.company')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='sav.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activité ticket',
                'verbose_name_plural': 'Activités ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['company', 'statut'], name='sav_ticket_company_1e1aa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('company', 'reference')},
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['company', 'produit'], name='sav_equipem_company_e60fc3_idx'),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['company', 'date_fin_garantie'], name='sav_equipem_company_3d5cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketactivity',
            index=models.Index(fields=['ticket', '-created_at'], name='sav_ticketa_ticket__765d45_idx'),
        ),
    ]
