# Generated by Django 5.1.4 on 2026-06-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("crm", "0016_client_custom_data_lead_custom_data"),
        ("installations", "0003_typeintervention"),
        ("sav", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodicite",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("trimestriel", "Trimestriel"),
                            ("semestriel", "Semestriel"),
                            ("annuel", "Annuel"),
                        ],
                        default="annuel",
                        max_length=15,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("derniere_visite", models.DateField(blank=True, null=True)),
                (
                    "prix",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrats_maintenance",
                        to="crm.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats_maintenance",
                        to="authentication.company",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contrats_maintenance",
                        to="installations.installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat de maintenance",
                "verbose_name_plural": "Contrats de maintenance",
                "ordering": ["-date_creation"],
            },
        ),
    ]
