# Generated by Django 5.1.4 on 2026-06-16 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("crm", "0013_leadtag_motifperte"),
        ("installations", "0002_intervention_ticket"),
        ("sav", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(blank=True, max_length=150, null=True)),
                ("intervalle_mois", models.PositiveSmallIntegerField(default=12)),
                ("date_debut", models.DateField()),
                ("derniere_visite", models.DateField(blank=True, null=True)),
                ("derniere_echeance_traitee", models.DateField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contrats_maintenance",
                        to="crm.client",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats_maintenance",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contrats_maintenance_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats_maintenance",
                        to="installations.installation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat de maintenance",
                "verbose_name_plural": "Contrats de maintenance",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["company", "actif"],
                        name="sav_contrat_company_f31309_idx",
                    ),
                    models.Index(
                        fields=["company", "installation"],
                        name="sav_contrat_company_4196a1_idx",
                    ),
                ],
            },
        ),
    ]
