# Generated by Django 5.1.4 on 2026-06-16 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("sav", "0002_contratmaintenance"),
        ("stock", "0018_produit_import_batch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contratmaintenance",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contratmaintenance",
            name="duree_mois",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ReclamationGarantie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "resultat",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("accordee", "Accordée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_cours",
                        max_length=12,
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamations_garantie",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reclamations_garantie_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reclamations_garantie",
                        to="sav.equipement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réclamation de garantie",
                "verbose_name_plural": "Réclamations de garantie",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["company", "equipement"],
                        name="sav_reclama_company_55350e_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TicketPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("stock_decremente", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_pieces",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_pieces_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ticket_pieces",
                        to="stock.produit",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="sav.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce ticket",
                "verbose_name_plural": "Pièces ticket",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["company", "ticket"],
                        name="sav_ticketp_company_e30622_idx",
                    )
                ],
            },
        ),
    ]
