# Generated by Django 5.1.4 on 2026-06-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("installations", "0003_typeintervention"),
        ("sav", "0002_contratmaintenance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="installations.installation",
            ),
        ),
    ]
