# Generated by Django 5.1.4 on 2026-06-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0003_contratmaintenance_date_fin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratmaintenance",
            name="montant_mensuel",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
