# Generated by Django 5.1.4 on 2026-06-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0006_equipement_serie_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
