# Generated by Django 5.1.4 on 2026-06-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0006_equipement_serie_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="contratmaintenance",
            name="derniere_facturation",
            field=models.DateField(
                blank=True,
                help_text="Date du dernier cycle de facturation émis. Null = jamais facturé.",
                null=True,
                verbose_name="Dernière facturation",
            ),
        ),
        migrations.AddField(
            model_name="contratmaintenance",
            name="facturation_active",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, `facturer` produit une Facture à chaque période.",
                verbose_name="Facturation récurrente active",
            ),
        ),
    ]
