# Generated by Django 5.1.4 on 2026-06-21 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("crm", "0020_alter_lead_gps_lat_alter_lead_gps_lng"),
        (
            "installations",
            "0010_componentserial_materielconsommation_photoannotation_and_more",
        ),
        ("sav", "0006_equipement_serie_unique"),
        ("stock", "0022_alter_stockemplacement_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KbArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("corps", models.TextField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("categorie", models.CharField(blank=True, default="", max_length=80)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Article KB SAV",
                "verbose_name_plural": "Articles KB SAV",
                "ordering": ["-date_modification"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=60)),
                ("libelle", models.CharField(max_length=180)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Étape de checklist maintenance",
                "verbose_name_plural": "Étapes de checklist maintenance",
                "ordering": ["ordre", "libelle"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceChecklistTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=120)),
                ("actif", models.BooleanField(default=True)),
                ("protege", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Modèle de checklist maintenance",
                "verbose_name_plural": "Modèles de checklist maintenance",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="SavSlaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sla_response_days", models.PositiveIntegerField(default=1)),
                ("sla_resolution_days", models.PositiveIntegerField(default=7)),
                ("sla_par_priorite", models.JSONField(blank=True, null=True)),
                ("sla_breach_enabled", models.BooleanField(default=False)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réglage SLA SAV",
                "verbose_name_plural": "Réglages SLA SAV",
            },
        ),
        migrations.CreateModel(
            name="TicketChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cle", models.CharField(max_length=60)),
                ("libelle", models.CharField(max_length=180)),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("coche", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, default="")),
                ("date_coche", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Item checklist ticket",
                "verbose_name_plural": "Items checklist ticket",
                "ordering": ["ordre", "cle"],
            },
        ),
        migrations.CreateModel(
            name="WarrantyClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fournisseur_id_ext",
                    models.IntegerField(
                        blank=True,
                        help_text="ID du fournisseur stock (sav.selectors.get_fournisseur).",
                        null=True,
                    ),
                ),
                (
                    "fournisseur_nom_cache",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nom du fournisseur mis en cache (dénormalisation lecture).",
                        max_length=120,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ouvert", "Ouvert"),
                            ("envoye", "Envoyé au fournisseur"),
                            ("en_attente", "En attente de retour"),
                            ("resolu", "Résolu"),
                            ("refuse", "Refusé"),
                        ],
                        default="ouvert",
                        max_length=15,
                    ),
                ),
                ("rma_ref", models.CharField(blank=True, default="", max_length=80)),
                ("date_signalement", models.DateField(blank=True, null=True)),
                ("date_envoi_fournisseur", models.DateField(blank=True, null=True)),
                ("date_resolution", models.DateField(blank=True, null=True)),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("remplacement", "Remplacement"),
                            ("avoir", "Avoir"),
                            ("reparation", "Réparation"),
                            ("refuse", "Refusé"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
                (
                    "cout_recupere",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Réclamation garantie fournisseur",
                "verbose_name_plural": "Réclamations garantie fournisseur",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.AddField(
            model_name="equipement",
            name="equipement_token",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Jeton QR pour le scan de l'équipement (EQUIP:<id>).",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="date_premiere_reponse",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_breach",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="sla_due_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["company", "sla_breach"], name="sav_ticket_company_2486bf_idx"
            ),
        ),
        migrations.AddField(
            model_name="kbarticle",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kb_articles",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="kbarticle",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kbarticle",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kb_articles",
                to="stock.produit",
            ),
        ),
        migrations.AddField(
            model_name="maintenancechecklistitem",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_checklist_items",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="maintenancechecklisttemplate",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_checklist_templates",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="maintenancechecklistitem",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sav.maintenancechecklisttemplate",
            ),
        ),
        migrations.AddField(
            model_name="savslasettings",
            name="company",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sav_sla_settings",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="ticketchecklistitem",
            name="coche_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticketchecklistitem",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket_checklist_items",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="ticketchecklistitem",
            name="ticket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checklist_items",
                to="sav.ticket",
            ),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="warranty_claims",
                to="authentication.company",
            ),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="equipement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="warranty_claims",
                to="sav.equipement",
            ),
        ),
        migrations.AddField(
            model_name="warrantyclaim",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warranty_claims",
                to="sav.ticket",
            ),
        ),
        migrations.AddIndex(
            model_name="kbarticle",
            index=models.Index(
                fields=["company", "actif"], name="sav_kbartic_company_68975f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kbarticle",
            index=models.Index(
                fields=["company", "produit"], name="sav_kbartic_company_dce237_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="maintenancechecklistitem",
            unique_together={("company", "template", "cle")},
        ),
        migrations.AlterUniqueTogether(
            name="ticketchecklistitem",
            unique_together={("ticket", "cle")},
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["company", "statut"], name="sav_warrant_company_898838_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="warrantyclaim",
            index=models.Index(
                fields=["company", "equipement"], name="sav_warrant_company_48a463_idx"
            ),
        ),
    ]
