# Generated by Django 5.1.4 on 2026-06-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sav", "0007_fg100_ticket_custom_data"),
        ("sav", "0007_fg40_contrat_facturation"),
        ("sav", "0007_fg81_fg82_fg83_fg85_fg87"),
    ]

    operations = []
