# Generated by Django 5.1.4 on 2026-07-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0019_xsav11_ticket_reopen_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticketsatisfaction',
            new_name='sav_tickets_company_8e0634_idx',
            old_name='sav_ticketsat_co_date_idx',
        ),
        migrations.AlterField(
            model_name='ticketsatisfaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
