# Generated by Django 5.1.4 on 2026-07-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_qw10_lead_dedup_index'),
        ('sav', '0049_zmfg8_piece_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='client_vente',
            field=models.ForeignKey(blank=True, help_text='Client direct pour un équipement vendu au comptoir (sans chantier). Vide si `installation` est renseignée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_vente_directe', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='pieceretiree',
            name='restockee',
            field=models.BooleanField(default=False, help_text='True une fois le MouvementStock ENTRÉE (stock_occasion) appliqué — évite tout double restock.'),
        ),
    ]
