# Generated by Django 5.1.15 on 2026-10-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sav', '0066_ciq640_prestations_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='arret_installation',
            field=models.BooleanField(default=False, help_text="La panne met l'installation à l'arrêt (notification du distributeur pour un site professionnel sous accord ou autorisation, décret 2.25.100 art. 28)."),
        ),
    ]
