# Generated by Django 5.1.15 on 2026-10-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0128_acht36_cloturee_notifiee_le'),
        ('sav', '0070_asav21_sla_echeance_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='installations.installation'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='installations.installation'),
        ),
    ]
