# Generated by Django 5.1.4 on 2026-07-17 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(blank=True, default='', max_length=255)),
                ('poste', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=50, null=True)),
                ('role_achat', models.CharField(choices=[('decideur', 'Décideur'), ('influenceur', 'Influenceur'), ('utilisateur', 'Utilisateur'), ('gatekeeper', 'Gatekeeper'), ('sponsor', 'Sponsor'), ('autre', 'Autre')], default='autre', max_length=15, verbose_name="Rôle d'achat")),
                ('contact_principal', models.BooleanField(default=False, verbose_name='Contact principal')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_multi_roles', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_client', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Contact client',
                'verbose_name_plural': 'Contacts client',
                'ordering': ['-contact_principal', 'nom'],
            },
        ),
    ]
