# Generated by Django 5.1.4 on 2026-07-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_campagneculturale_created_at_and_more'),
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrantagricole',
            name='produit_id',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='intrantagricole',
            constraint=models.UniqueConstraint(fields=('company', 'produit_id'), name='uniq_intrant_produit_par_societe'),
        ),
    ]
