# Generated by Django 5.1.4 on 2026-07-17 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0003_alter_intrantagricole_produit_id_and_more'),
        ('authentication', '0024_ntprt1_customuser_portee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielAgricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255)),
                ('type_materiel', models.CharField(choices=[('tracteur', 'Tracteur'), ('moissonneuse', 'Moissonneuse'), ('pulverisateur', 'Pulvérisateur'), ('outil', 'Outil')], default='tracteur', max_length=20)),
                ('numero_serie', models.CharField(blank=True, default='', max_length=100)),
                ('heures_moteur', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels_agricoles', to='authentication.company')),
                ('parcelle_affectee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_affectes', to='agriculture.parcelle')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='UtilisationMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('heures_utilisees', models.DecimalField(decimal_places=1, max_digits=8)),
                ('cout_carburant_mad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisations_materiel', to='agriculture.campagneculturale')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations_materiel_agricole', to='authentication.company')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='agriculture.materielagricole')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
