# Generated by Django 5.1.4 on 2026-07-17 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_materielagricole_utilisationmateriel'),
        ('authentication', '0024_ntprt1_customuser_portee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_source', models.CharField(choices=[('puits', 'Puits'), ('pompage_solaire', 'Pompage solaire'), ('reseau', 'Réseau')], default='puits', max_length=20)),
                ('installation_id', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_irrigation', to='authentication.company')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_irrigation', to='agriculture.parcelle')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RelevePointIrrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cout_energie_mad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves_irrigation', to='authentication.company')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releves', to='agriculture.pointirrigation')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
