# Generated by Django 5.1.4 on 2026-07-17 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0005_pointirrigation_relevepointirrigation'),
        ('authentication', '0024_ntprt1_customuser_portee'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotRecolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_recolte', models.DateField()),
                ('quantite_qtl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calibre', models.CharField(blank=True, default='', max_length=50)),
                ('qualite', models.CharField(blank=True, default='', max_length=50)),
                ('numero_lot', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('stock_lot_id', models.CharField(blank=True, default='', max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_recolte', to='agriculture.campagneculturale')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots_recolte', to='authentication.company')),
            ],
            options={
                'ordering': ['-date_recolte', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'numero_lot'), name='uniq_lotrecolte_numero_par_societe')],
            },
        ),
    ]
