# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0023_yhard1_encrypt_totp_secret'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Praticien',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'nom',
                    models.CharField(max_length=255, verbose_name='Nom'),
                ),
                (
                    'specialite',
                    models.CharField(
                        blank=True, default='', max_length=150,
                        verbose_name='Spécialité'),
                ),
                (
                    'numero_ordre',
                    models.CharField(
                        blank=True, default='', max_length=50,
                        verbose_name="Numéro d'ordre"),
                ),
                (
                    'couleur_agenda',
                    models.CharField(
                        blank=True, default='#2563eb', max_length=20,
                        verbose_name='Couleur agenda'),
                ),
                (
                    'actif',
                    models.BooleanField(default=True, verbose_name='Actif'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sante_praticien_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sante_praticiens',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Utilisateur lié'),
                ),
            ],
            options={
                'verbose_name': 'Praticien',
                'verbose_name_plural': 'Praticiens',
                'ordering': ['nom'],
            },
        ),
    ]
