# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('consultation', 'Consultation'),
                            ('bloc', 'Bloc opératoire'),
                            ('imagerie', 'Imagerie'),
                            ('labo', 'Laboratoire'),
                        ],
                        default='consultation', max_length=15,
                        verbose_name='Type'),
                ),
                (
                    'capacite',
                    models.PositiveIntegerField(
                        default=1, verbose_name='Capacité'),
                ),
                (
                    'equipements',
                    models.TextField(
                        blank=True, default='', verbose_name='Équipements'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
    ]
