# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0002_salle'),
        ('crm', '0062_lead_web_questionnaire_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                (
                    'prenom',
                    models.CharField(
                        blank=True, default='', max_length=255,
                        verbose_name='Prénom'),
                ),
                (
                    'cin',
                    models.CharField(
                        blank=True, default='', max_length=30,
                        verbose_name='CIN'),
                ),
                (
                    'date_naissance',
                    models.DateField(
                        blank=True, null=True,
                        verbose_name='Date de naissance'),
                ),
                (
                    'sexe',
                    models.CharField(
                        blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')],
                        default='', max_length=1, verbose_name='Sexe'),
                ),
                (
                    'telephone',
                    models.CharField(
                        blank=True, default='', max_length=20,
                        verbose_name='Téléphone'),
                ),
                (
                    'whatsapp',
                    models.CharField(
                        blank=True, default='', max_length=20,
                        verbose_name='WhatsApp'),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True, default='', max_length=254,
                        verbose_name='Email'),
                ),
                (
                    'adresse',
                    models.TextField(
                        blank=True, default='', verbose_name='Adresse'),
                ),
                (
                    'numero_dossier',
                    models.CharField(
                        blank=True, db_index=True, default='', max_length=30,
                        verbose_name='Numéro de dossier'),
                ),
                (
                    'contact_urgence',
                    models.CharField(
                        blank=True, default='', max_length=255,
                        verbose_name="Contact d'urgence"),
                ),
                (
                    'client',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='patients_sante', to='crm.client',
                        verbose_name='Client CRM lié'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(
                condition=models.Q(('numero_dossier', ''), _negated=True),
                fields=('company', 'numero_dossier'),
                name='sante_patient_unique_dossier_par_societe'),
        ),
    ]
