# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0003_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'date_heure_debut',
                    models.DateTimeField(verbose_name='Date et heure de début'),
                ),
                (
                    'duree_min',
                    models.PositiveIntegerField(
                        default=30, verbose_name='Durée (min)'),
                ),
                (
                    'type_acte',
                    models.CharField(
                        blank=True, default='', max_length=255,
                        verbose_name="Type d'acte"),
                ),
                (
                    'statut',
                    models.CharField(
                        choices=[
                            ('planifie', 'Planifié'),
                            ('confirme', 'Confirmé'),
                            ('arrive', 'Arrivé'),
                            ('en_cours', 'En cours'),
                            ('termine', 'Terminé'),
                            ('annule', 'Annulé'),
                            ('absent', 'Absent'),
                        ],
                        default='planifie', max_length=10,
                        verbose_name='Statut'),
                ),
                (
                    'motif_court',
                    models.CharField(
                        blank=True, default='', max_length=255,
                        verbose_name='Motif'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'cree_par',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sante_rdv_crees',
                        to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rendez_vous', to='sante.patient',
                        verbose_name='Patient'),
                ),
                (
                    'praticien',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='rendez_vous', to='sante.praticien',
                        verbose_name='Praticien'),
                ),
                (
                    'salle',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='rendez_vous', to='sante.salle',
                        verbose_name='Salle'),
                ),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_heure_debut'],
            },
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(
                fields=['praticien', 'date_heure_debut'],
                name='sante_rdv_praticien_debut_idx'),
        ),
        migrations.AddIndex(
            model_name='rendezvous',
            index=models.Index(
                fields=['salle', 'date_heure_debut'],
                name='sante_rdv_salle_debut_idx'),
        ),
    ]
