# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0004_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'date_admission',
                    models.DateTimeField(verbose_name="Date d'admission"),
                ),
                (
                    'date_sortie',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='Date de sortie'),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('consultation', 'Consultation'),
                            ('hospitalisation', 'Hospitalisation'),
                            ('acte_technique', 'Acte technique'),
                        ],
                        default='consultation', max_length=20,
                        verbose_name='Type'),
                ),
                (
                    'statut',
                    models.CharField(
                        choices=[
                            ('en_cours', 'En cours'),
                            ('cloturee', 'Clôturée'),
                        ],
                        default='en_cours', max_length=10,
                        verbose_name='Statut'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='admissions', to='sante.patient',
                        verbose_name='Patient'),
                ),
                (
                    'praticien',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='admissions', to='sante.praticien',
                        verbose_name='Praticien'),
                ),
                (
                    'rdv',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='admissions', to='sante.rendezvous',
                        verbose_name='Rendez-vous'),
                ),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
                'ordering': ['-date_admission'],
            },
        ),
    ]
