# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0005_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeMedical',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'code_ngap',
                    models.CharField(
                        blank=True, default='', max_length=30,
                        verbose_name='Code NGAP'),
                ),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                (
                    'categorie',
                    models.CharField(
                        blank=True, default='', max_length=100,
                        verbose_name='Catégorie'),
                ),
                (
                    'tarif_base_ttc',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=10,
                        verbose_name='Tarif de base TTC'),
                ),
                (
                    'cotation_lettre_cle',
                    models.CharField(
                        blank=True, default='', max_length=20,
                        verbose_name='Cotation (lettre clé)'),
                ),
                (
                    'actif',
                    models.BooleanField(default=True, verbose_name='Actif'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sante_actemedical_set',
                        to='authentication.company', verbose_name='Société'),
                ),
            ],
            options={
                'verbose_name': 'Acte médical',
                'verbose_name_plural': 'Actes médicaux',
                'ordering': ['libelle'],
            },
        ),
    ]
