# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0006_actemedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('cnops', 'CNOPS'),
                            ('cnss', 'CNSS'),
                            ('mutuelle_privee', 'Mutuelle privée'),
                            ('cash', 'Cash'),
                            ('autre', 'Autre'),
                        ],
                        default='autre', max_length=20, verbose_name='Type'),
                ),
                (
                    'taux_tiers_payant_pct',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=5,
                        verbose_name='Taux tiers payant par défaut (%)'),
                ),
                (
                    'contact',
                    models.CharField(
                        blank=True, default='', max_length=255,
                        verbose_name='Contact'),
                ),
                (
                    'actif',
                    models.BooleanField(default=True, verbose_name='Actif'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
            ],
            options={
                'verbose_name': 'Convention',
                'verbose_name_plural': 'Conventions',
                'ordering': ['nom'],
            },
        ),
    ]
