# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0007_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='convention',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='patients', to='sante.convention',
                verbose_name='Convention'),
        ),
        migrations.AddField(
            model_name='patient',
            name='numero_affiliation',
            field=models.CharField(
                blank=True, default='', max_length=50,
                verbose_name="Numéro d'affiliation"),
        ),
    ]
