# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0008_patient_convention'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleTarifaire',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'tarif_convention_ttc',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=10,
                        verbose_name='Tarif convention TTC'),
                ),
                (
                    'taux_prise_charge_pct',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=5,
                        verbose_name='Taux de prise en charge (%)'),
                ),
                (
                    'acte',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='grilles_tarifaires',
                        to='sante.actemedical', verbose_name='Acte'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'convention',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='grilles_tarifaires',
                        to='sante.convention', verbose_name='Convention'),
                ),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
                'ordering': ['convention', 'acte'],
            },
        ),
        migrations.AddConstraint(
            model_name='grilletarifaire',
            constraint=models.UniqueConstraint(
                fields=('company', 'convention', 'acte'),
                name='sante_grille_unique_convention_acte'),
        ),
    ]
