# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0009_grilletarifaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeRealise',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'date_realisation',
                    models.DateTimeField(verbose_name='Date de réalisation'),
                ),
                (
                    'quantite',
                    models.PositiveIntegerField(default=1, verbose_name='Quantité'),
                ),
                (
                    'tarif_applique_ttc',
                    models.DecimalField(
                        decimal_places=2, max_digits=10,
                        verbose_name='Tarif appliqué TTC'),
                ),
                (
                    'facturable',
                    models.BooleanField(
                        default=True,
                        help_text="Décoché : l'acte est explicitement marqué "
                                  "non-facturable (n'empêche pas la clôture "
                                  "de l'admission).",
                        verbose_name='Facturable'),
                ),
                (
                    'acte',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='realisations', to='sante.actemedical',
                        verbose_name='Acte'),
                ),
                (
                    'admission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='actes_realises', to='sante.admission',
                        verbose_name='Admission'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sante_acterealise_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='actes_realises', to='sante.patient',
                        verbose_name='Patient'),
                ),
                (
                    'praticien',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='actes_realises', to='sante.praticien',
                        verbose_name='Praticien'),
                ),
            ],
            options={
                'verbose_name': 'Acte réalisé',
                'verbose_name_plural': 'Actes réalisés',
                'ordering': ['-date_realisation'],
            },
        ),
    ]
