# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0010_acterealise'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseEnCharge',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'numero_dossier_convention',
                    models.CharField(
                        blank=True, default='', max_length=50,
                        verbose_name='Numéro de dossier (convention)'),
                ),
                ('date_demande', models.DateField(verbose_name='Date de demande')),
                (
                    'date_reponse',
                    models.DateField(
                        blank=True, null=True, verbose_name='Date de réponse'),
                ),
                (
                    'statut',
                    models.CharField(
                        choices=[
                            ('demandee', 'Demandée'),
                            ('accordee', 'Accordée'),
                            ('refusee', 'Refusée'),
                            ('expiree', 'Expirée'),
                        ],
                        default='demandee', max_length=10,
                        verbose_name='Statut'),
                ),
                (
                    'montant_accorde',
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10,
                        null=True, verbose_name='Montant accordé'),
                ),
                (
                    'motif_refus',
                    models.CharField(
                        blank=True, default='', max_length=255,
                        verbose_name='Motif de refus'),
                ),
                (
                    'date_expiration',
                    models.DateField(
                        blank=True, null=True,
                        verbose_name="Date d'expiration"),
                ),
                (
                    'admission',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='prises_en_charge',
                        to='sante.admission', verbose_name='Admission'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sante_priseencharge_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'convention',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prises_en_charge',
                        to='sante.convention', verbose_name='Convention'),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='prises_en_charge', to='sante.patient',
                        verbose_name='Patient'),
                ),
            ],
            options={
                'verbose_name': 'Prise en charge',
                'verbose_name_plural': 'Prises en charge',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.AddField(
            model_name='acterealise',
            name='prise_en_charge',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='actes_realises', to='sante.priseencharge',
                verbose_name='Prise en charge'),
        ),
    ]
