# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0011_priseencharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureSante',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'sous_total_ttc',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=12,
                        verbose_name='Sous-total TTC'),
                ),
                (
                    'remise_ttc',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=12,
                        verbose_name='Remise TTC'),
                ),
                (
                    'taux_tva',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=5,
                        verbose_name='Taux TVA (%)'),
                ),
                (
                    'montant_tva',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=12,
                        verbose_name='Montant TVA'),
                ),
                (
                    'total_ttc',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=12,
                        verbose_name='Total TTC'),
                ),
                (
                    'part_tiers_payant_ttc',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=12,
                        verbose_name='Part tiers payant TTC'),
                ),
                (
                    'part_patient_ttc',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0'), max_digits=12,
                        verbose_name='Part patient TTC (reste à charge)'),
                ),
                (
                    'statut',
                    models.CharField(
                        choices=[
                            ('brouillon', 'Brouillon'),
                            ('emise', 'Émise'),
                            ('payee_partiel', 'Payée partiellement'),
                            ('payee', 'Payée'),
                            ('impayee', 'Impayée'),
                        ],
                        default='brouillon', max_length=15,
                        verbose_name='Statut'),
                ),
                (
                    'date_emission',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date d'émission"),
                ),
                (
                    'admission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='factures_sante', to='sante.admission',
                        verbose_name='Admission'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sante_facturesante_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'convention',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='factures_sante', to='sante.convention',
                        verbose_name='Convention'),
                ),
                (
                    'patient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='factures_sante', to='sante.patient',
                        verbose_name='Patient'),
                ),
            ],
            options={
                'verbose_name': 'Facture santé',
                'verbose_name_plural': 'Factures santé',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='acterealise',
            name='facture_sante',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lignes_actes', to='sante.facturesante',
                verbose_name='Facture santé'),
        ),
    ]
