# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0012_facturesante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementSante',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'montant',
                    models.DecimalField(
                        decimal_places=2, max_digits=12,
                        verbose_name='Montant'),
                ),
                (
                    'mode',
                    models.CharField(
                        choices=[
                            ('especes', 'Espèces'),
                            ('carte', 'Carte'),
                            ('cheque', 'Chèque'),
                            ('virement', 'Virement'),
                            ('tiers_payant', 'Tiers payant'),
                        ],
                        default='especes', max_length=15,
                        verbose_name='Mode de paiement'),
                ),
                (
                    'date_paiement',
                    models.DateTimeField(verbose_name='Date de paiement'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'encaisse_par',
                    models.ForeignKey(
                        blank=True, null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sante_paiements_encaisses',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Encaissé par'),
                ),
                (
                    'facture_sante',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='paiements', to='sante.facturesante',
                        verbose_name='Facture santé'),
                ),
            ],
            options={
                'verbose_name': 'Paiement santé',
                'verbose_name_plural': 'Paiements santé',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
