# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0013_paiementsante'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireOuverturePraticien',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'jour_semaine',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'),
                            (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'),
                            (6, 'Dimanche'),
                        ],
                        verbose_name='Jour de la semaine'),
                ),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'praticien',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='horaires_ouverture', to='sante.praticien',
                        verbose_name='Praticien'),
                ),
            ],
            options={
                'verbose_name': "Horaire d'ouverture praticien",
                'verbose_name_plural': "Horaires d'ouverture praticien",
                'ordering': ['praticien', 'jour_semaine', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='IndisponibilitePraticien',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'date_debut',
                    models.DateTimeField(verbose_name='Date et heure de début'),
                ),
                (
                    'date_fin',
                    models.DateTimeField(verbose_name='Date et heure de fin'),
                ),
                (
                    'motif',
                    models.CharField(
                        blank=True, default='', max_length=255,
                        verbose_name='Motif'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'praticien',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='indisponibilites', to='sante.praticien',
                        verbose_name='Praticien'),
                ),
            ],
            options={
                'verbose_name': 'Indisponibilité praticien',
                'verbose_name_plural': 'Indisponibilités praticien',
                'ordering': ['-date_debut'],
            },
        ),
    ]
