# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0014_horaireouvertureprati_indisponibiliteprati'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraticienSite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
                (
                    'praticien',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sites', to='sante.praticien',
                        verbose_name='Praticien'),
                ),
                (
                    'salle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='praticiens_associes', to='sante.salle',
                        verbose_name='Site (salle)'),
                ),
            ],
            options={
                'verbose_name': 'Site du praticien',
                'verbose_name_plural': 'Sites du praticien',
                'ordering': ['praticien', 'salle'],
            },
        ),
        migrations.AddConstraint(
            model_name='praticiensite',
            constraint=models.UniqueConstraint(
                fields=('company', 'praticien', 'salle'),
                name='sante_praticien_site_unique'),
        ),
    ]
