# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0015_praticiensite'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='duree_consultation_defaut_min',
            field=models.PositiveIntegerField(
                blank=True, null=True,
                verbose_name='Durée par défaut de consultation (min)'),
        ),
        migrations.CreateModel(
            name='MotifConsultation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('libelle', models.CharField(max_length=255, verbose_name='Libellé')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
            ],
            options={
                'verbose_name': 'Motif de consultation',
                'verbose_name_plural': 'Motifs de consultation',
                'ordering': ['libelle'],
            },
        ),
    ]
