# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0016_praticien_duree_consultation_motifconsultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='annule_par',
            field=models.CharField(
                blank=True, choices=[
                    ('patient', 'Patient'), ('clinique', 'Clinique'),
                ],
                default='', max_length=10, verbose_name='Annulé par'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_annulation',
            field=models.DateTimeField(
                blank=True, null=True,
                verbose_name="Date et heure d'annulation"),
        ),
        migrations.CreateModel(
            name='ParametragePenaliteAnnulation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True,
                        serialize=False, verbose_name='ID'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'actif',
                    models.BooleanField(
                        default=False, verbose_name='Pénalité activée'),
                ),
                (
                    'delai_min_h',
                    models.PositiveIntegerField(
                        default=24,
                        verbose_name=(
                            'Délai minimum avant RDV (heures) pour éviter '
                            'la pénalité')),
                ),
                (
                    'montant_penalite_ttc',
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10,
                        verbose_name='Montant de la pénalité TTC'),
                ),
                (
                    'company',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='%(app_label)s_%(class)s_set',
                        to='authentication.company', verbose_name='Société'),
                ),
            ],
            options={
                'verbose_name': "Paramétrage pénalité d'annulation",
                'verbose_name_plural': "Paramétrages pénalité d'annulation",
            },
        ),
        migrations.AddConstraint(
            model_name='parametragepenaliteannulation',
            constraint=models.UniqueConstraint(
                fields=('company',),
                name='sante_parametrage_penalite_unique_par_societe'),
        ),
    ]
