# Generated by Django 5.1.4 (hand-written — mirrors makemigrations output;
# WeasyPrint's native lib is unavailable in this local shell, so
# `makemigrations` can't import the full app registry here — see
# 0016_praticien_duree_consultation_motifconsultation.py for the same
# hand-written pattern already used in this app).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sante', '0017_rendezvous_annulation_parametragepenalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='praticien',
            name='employe_id',
            field=models.IntegerField(
                blank=True, null=True, verbose_name='Employé RH (id)',
                help_text=(
                    'Lien optionnel vers le dossier employé RH '
                    '(rh.DossierEmploye) — jamais dupliqué.')),
        ),
    ]
