# Generated by Django 5.1.4 on 2026-07-31 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('sante', '0018_praticien_employe_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleSterilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_cycle', models.CharField(max_length=50, verbose_name='Numéro de cycle')),
                ('date_cycle', models.DateTimeField(verbose_name='Date du cycle')),
                ('autoclave_ref', models.CharField(blank=True, default='', max_length=100, verbose_name="Référence de l'autoclave")),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non conforme')], default='conforme', max_length=15, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('operateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycles_sterilisation', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Cycle de stérilisation',
                'verbose_name_plural': 'Cycles de stérilisation',
                'ordering': ['-date_cycle'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentSterilise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument_ref', models.CharField(blank=True, default='', max_length=100, verbose_name="Référence de l'instrument")),
                ('kit_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence du kit')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='sante.cyclesterilisation', verbose_name='Cycle')),
            ],
            options={
                'verbose_name': 'Instrument stérilisé',
                'verbose_name_plural': 'Instruments stérilisés',
                'ordering': ['cycle', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cyclesterilisation',
            constraint=models.UniqueConstraint(fields=('company', 'numero_cycle'), name='sante_cycle_sterilisation_unique_par_societe'),
        ),
        migrations.AddIndex(
            model_name='instrumentsterilise',
            index=models.Index(fields=['company', 'instrument_ref'], name='sante_instr_ster_ref_idx'),
        ),
    ]
