# Generated by Django 5.1.4 on 2026-07-31 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('uxviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(verbose_name='Identifiant de la cible')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Type de la cible')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['ordre', 'id'],
                'indexes': [models.Index(fields=['company', 'owner', 'ordre'], name='uxviews_favori_ordre_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'owner', 'content_type', 'object_id'), name='uxviews_favori_unique_par_utilisateur')],
            },
        ),
    ]
