# Generated by Django 5.1.4 on 2026-07-31 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_company_est_demo_mode_presentation'),
        ('roles', '0001_initial'),
        ('uxviews', '0002_favoriutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='UxParametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duree_hover_peek_ms', models.PositiveIntegerField(default=400, verbose_name='Délai avant aperçu au survol (ms)')),
                ('duree_undo_toast_s', models.PositiveIntegerField(default=10, verbose_name='Durée du bandeau « annuler » (s)')),
                ('permettre_vues_partagees_equipe', models.BooleanField(default=True, verbose_name="Autoriser les vues partagées d'équipe")),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ux_parametres', to='authentication.company', verbose_name='Société')),
                ('roles_autorises_definir_defaut', models.ManyToManyField(blank=True, related_name='ux_parametres_defaut', to='roles.role', verbose_name='Rôles autorisés à définir une vue par défaut')),
            ],
            options={
                'verbose_name': 'Réglages UX',
                'verbose_name_plural': 'Réglages UX',
            },
        ),
    ]
