# Generated by Django 5.1.4 on 2026-07-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0003_innovationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationsettings',
            name='seuil_votes_notification',
            field=models.PositiveIntegerField(default=3, verbose_name="Seuil de votes pour notifier l'auteur"),
        ),
    ]
