# Generated by Django 5.1.4 on 2026-07-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0004_innovationsettings_seuil_votes_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='idee',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Brouillon'),
        ),
    ]
