# Generated by Django 5.1.4 on 2026-07-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovation', '0005_idee_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='idee',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Masquée (modération)'),
        ),
    ]
