# Generated by Django 5.1.4 on 2026-06-30 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Identifiant du document')),
                ('provider', models.CharField(default='cmi', help_text='Code du connecteur de paiement (ex. « cmi », « payzone »).', max_length=60, verbose_name='Fournisseur')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('devise', models.CharField(default='MAD', max_length=3, verbose_name='Devise')),
                ('statut', models.CharField(choices=[('initie', 'Initié'), ('en_attente', 'En attente'), ('paye', 'Payé'), ('echec', 'Échec'), ('annule', 'Annulé'), ('rembourse', 'Remboursé')], default='initie', max_length=16, verbose_name='Statut')),
                ('external_ref', models.CharField(blank=True, default='', help_text='Identifiant retourné par le prestataire de paiement.', max_length=128, verbose_name='Référence PSP')),
                ('redirect_url', models.URLField(blank=True, default='', help_text='URL de la page de paiement hébergée du PSP.', max_length=600, verbose_name='URL de redirection')),
                ('payeur_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email payeur')),
                ('paye_le', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='Détail')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='authentication.company', verbose_name='Société')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Transaction de paiement',
                'verbose_name_plural': 'Transactions de paiement',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'statut'], name='core_pay_co_statut_idx'), models.Index(fields=['provider', 'external_ref'], name='core_pay_ext_idx')],
            },
        ),
    ]
