# Generated by Django 5.1.4 on 2026-06-30 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('core', '0008_paymenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=160, verbose_name='Titre')),
                ('dataset', models.CharField(help_text='Nom du dataset enregistré (core.data_explorer).', max_length=80, verbose_name='Dataset')),
                ('spec', models.JSONField(blank=True, default=dict, help_text='Sélection/filtres/agrégations (opaque pour core).', verbose_name='Spécification')),
                ('partage', models.BooleanField(default=False, help_text='Visible par toute la société (sinon personnelle).', verbose_name='Partagée')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to='authentication.company', verbose_name='Société')),
                ('owner', models.ForeignKey(blank=True, help_text='Vide = requête de société (non personnelle).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
            options={
                'verbose_name': 'Requête sauvegardée',
                'verbose_name_plural': 'Requêtes sauvegardées',
                'ordering': ['titre', 'id'],
                'indexes': [models.Index(fields=['company', 'owner'], name='core_savedq_co_owner_idx'), models.Index(fields=['company', 'dataset'], name='core_savedq_co_ds_idx')],
            },
        ),
    ]
