# Generated by Django 5.1.4 on 2026-06-30 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('core', '0009_savedquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=160, verbose_name='Titre')),
                ('dataset', models.CharField(help_text='Nom du dataset enregistré (core.data_explorer).', max_length=80, verbose_name='Dataset')),
                ('spec', models.JSONField(blank=True, default=dict, help_text='Sélection/filtres (opaque pour core).', verbose_name='Spécification')),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('parquet', 'Parquet')], default='csv', max_length=10, verbose_name='Format')),
                ('destination', models.CharField(choices=[('sftp', 'SFTP'), ('s3', 'Bucket S3')], default='sftp', max_length=20, verbose_name='Destination')),
                ('cron', models.CharField(blank=True, default='', help_text='Expression cron interprétée par Celery Beat (hors core).', max_length=120, verbose_name='Planification (cron)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('derniere_execution_le', models.DateTimeField(blank=True, null=True, verbose_name='Dernière exécution')),
                ('dernier_statut', models.CharField(blank=True, default='', max_length=20, verbose_name='Dernier statut')),
                ('dernier_detail', models.JSONField(blank=True, default=dict, verbose_name='Dernier détail')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_exports', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Extrait planifié',
                'verbose_name_plural': 'Extraits planifiés',
                'ordering': ['titre', 'id'],
                'indexes': [models.Index(fields=['company', 'actif'], name='core_schedexp_co_actif_idx')],
            },
        ),
    ]
