# Generated by Django 5.1.4 on 2026-06-30 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0010_scheduledexport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(verbose_name='Identifiant du document')),
                ('label', models.CharField(blank=True, default='', max_length=255, verbose_name='Libellé')),
                ('restored_at', models.DateTimeField(blank=True, null=True, verbose_name='Restauré le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_records', to='authentication.company', verbose_name='Société')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Type de document')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supprimé par')),
            ],
            options={
                'verbose_name': 'Entrée de corbeille',
                'verbose_name_plural': 'Entrées de corbeille',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'restored_at'], name='core_trash_co_restored_idx'), models.Index(fields=['content_type', 'object_id'], name='core_trash_target_idx')],
            },
        ),
    ]
