# Generated by Django 5.1.4 on 2026-06-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('core', '0011_deletionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(help_text='Clé du module, ex. « sav », « flotte » (libre).', max_length=60, verbose_name='Module')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('raison', models.CharField(blank=True, default='', help_text='Note optionnelle (ex. « hors offre », « en pilote »).', max_length=255, verbose_name='Raison')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_toggles', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Activation de module',
                'verbose_name_plural': 'Activations de modules',
                'ordering': ['module', 'id'],
                'indexes': [models.Index(fields=['company', 'actif'], name='core_modtog_co_actif_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'module'), name='core_moduletoggle_co_mod')],
            },
        ),
    ]
