# Generated by Django 5.1.4 on 2026-06-30 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('core', '0012_moduletoggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo_url', models.CharField(blank=True, default='', help_text='URL ou chemin de stockage du logo white-label.', max_length=500, verbose_name='Logo (URL/chemin)')),
                ('couleur_primaire', models.CharField(blank=True, default='', help_text='Code couleur hex (ex. « #1a3b8c »).', max_length=9, verbose_name='Couleur primaire')),
                ('couleur_secondaire', models.CharField(blank=True, default='', max_length=9, verbose_name='Couleur secondaire')),
                ('domaine', models.CharField(blank=True, default='', help_text='Domaine white-label (ex. « erp.client.ma »).', max_length=255, verbose_name='Domaine personnalisé')),
                ('nom_affichage', models.CharField(blank=True, default='', help_text='Nom de marque affiché (sinon la raison sociale).', max_length=160, verbose_name='Nom affiché')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Jetons de thème additionnels (opaque pour core).', verbose_name='Jetons additionnels')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_theme', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Thème white-label',
                'verbose_name_plural': 'Thèmes white-label',
                'ordering': ['id'],
            },
        ),
    ]
