# Generated by Django 5.1.4 on 2026-06-30 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('core', '0013_tenanttheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandedTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=12, verbose_name='Type')),
                ('code', models.CharField(help_text="Identifiant d'usage, ex. « relance_devis » (libre).", max_length=80, verbose_name='Code')),
                ('nom', models.CharField(max_length=160, verbose_name='Nom')),
                ('sujet', models.CharField(blank=True, default='', help_text='Objet (email) ou titre — supporte les placeholders.', max_length=255, verbose_name='Sujet')),
                ('corps', models.TextField(blank=True, default='', help_text='Texte avec placeholders ``{{ variable }}``.', verbose_name='Corps')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branded_templates', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Modèle brandé',
                'verbose_name_plural': 'Modèles brandés',
                'ordering': ['kind', 'code', 'id'],
                'indexes': [models.Index(fields=['company', 'kind', 'actif'], name='core_brandtpl_co_kind_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'kind', 'code'), name='core_brandtpl_co_kind_code')],
            },
        ),
    ]
