# Generated by Django 5.1.4 on 2026-06-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('core', '0014_brandedtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_identifier', models.CharField(help_text='Email ou téléphone de la personne concernée.', max_length=255, verbose_name='Identifiant de la personne')),
                ('purpose', models.CharField(help_text='Finalité du traitement, ex. « marketing », « whatsapp ».', max_length=80, verbose_name='Finalité')),
                ('granted', models.BooleanField(default=True, verbose_name='Consentement donné')),
                ('source', models.CharField(blank=True, default='', help_text='Origine du consentement (ex. « formulaire site », « devis »).', max_length=120, verbose_name='Source')),
                ('occurred_at', models.DateTimeField(blank=True, help_text='Date/heure du consentement (sur le consent_timestamp existant côté métier).', null=True, verbose_name='Horodatage')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Consentement',
                'verbose_name_plural': 'Registre de consentement',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'subject_identifier'], name='core_consent_co_subj_idx'), models.Index(fields=['company', 'purpose', 'granted'], name='core_consent_co_purp_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_identifier', models.CharField(help_text='Email ou téléphone de la personne concernée.', max_length=255, verbose_name='Identifiant de la personne')),
                ('kind', models.CharField(choices=[('acces', 'Accès (export)'), ('effacement', 'Effacement')], max_length=12, verbose_name='Type')),
                ('statut', models.CharField(choices=[('recue', 'Reçue'), ('traitee', 'Traitée'), ('refusee', 'Refusée')], default='recue', max_length=12, verbose_name='Statut')),
                ('resultat', models.JSONField(blank=True, default=dict, help_text="Payload d'export (accès) ou compte-rendu d'effacement.", verbose_name='Résultat')),
                ('traitee_le', models.DateTimeField(blank=True, null=True, verbose_name='Traitée le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsr_requests', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Demande de personne concernée',
                'verbose_name_plural': 'Demandes de personnes concernées',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'statut'], name='core_dsr_co_statut_idx'), models.Index(fields=['company', 'subject_identifier'], name='core_dsr_co_subj_idx')],
            },
        ),
    ]
