# Generated by Django 5.1.4 on 2026-06-30 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('core', '0015_consentrecord_datasubjectrequest'),
        ('publicapi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, default='gratuit', help_text='Nom du palier (libre, ex. « gratuit », « pro »).', max_length=40, verbose_name='Palier')),
                ('quota_par_minute', models.PositiveIntegerField(default=60, help_text='Requêtes max par minute et par clé (0 = illimité).', verbose_name='Quota / minute')),
                ('quota_par_jour', models.PositiveIntegerField(default=10000, help_text='Requêtes max par jour et par société (0 = illimité).', verbose_name='Quota / jour')),
                ('quota_par_mois', models.PositiveIntegerField(default=300000, help_text='Requêtes max par mois et par société (0 = illimité).', verbose_name='Quota / mois')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_plan', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': "Plan d'usage API",
                'verbose_name_plural': "Plans d'usage API",
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('corps', models.TextField(blank=True, default='', verbose_name='Contenu')),
                ('version', models.CharField(blank=True, default='', help_text='Étiquette de version, ex. « 2026.06 ».', max_length=40, verbose_name='Version')),
                ('categorie', models.CharField(choices=[('nouveaute', 'Nouveauté'), ('amelioration', 'Amélioration'), ('correctif', 'Correctif')], default='nouveaute', max_length=14, verbose_name='Catégorie')),
                ('publie', models.BooleanField(default=False, help_text="Une note non publiée n'apparaît pas dans le fil.", verbose_name='Publié')),
                ('publie_le', models.DateTimeField(blank=True, null=True, verbose_name='Publié le')),
            ],
            options={
                'verbose_name': 'Note de version',
                'verbose_name_plural': 'Notes de version',
                'ordering': ['-publie_le', '-id'],
                'indexes': [models.Index(fields=['publie', 'publie_le'], name='core_changelog_pub_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jour', models.DateField(help_text="Jour d'agrégation (UTC).", verbose_name='Jour')),
                ('nb_requetes', models.PositiveIntegerField(default=0, verbose_name='Requêtes')),
                ('nb_erreurs', models.PositiveIntegerField(default=0, verbose_name='Erreurs')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='publicapi.apikey', verbose_name='Clé API')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_records', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Usage API',
                'verbose_name_plural': 'Usages API',
                'ordering': ['-jour', 'id'],
                'indexes': [models.Index(fields=['company', 'jour'], name='core_apiusage_co_jour_idx')],
                'constraints': [models.UniqueConstraint(fields=('api_key', 'jour'), name='core_apiusage_key_jour')],
            },
        ),
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('export', 'Sauvegarde'), ('restore', 'Restauration')], default='export', max_length=10, verbose_name='Type')),
                ('mode', models.CharField(choices=[('manuel', 'À la demande'), ('planifie', 'Planifié')], default='manuel', max_length=10, verbose_name='Déclenchement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('echec', 'Échec'), ('non_configure', 'Non configuré')], default='en_attente', max_length=14, verbose_name='Statut')),
                ('datasets', models.JSONField(blank=True, default=list, help_text='Liste des datasets inclus (noms du registre data_explorer). Vide = tous les datasets de la société.', verbose_name='Datasets')),
                ('cron', models.CharField(blank=True, default='', help_text='Expression cron interprétée par Celery Beat (hors core).', max_length=120, verbose_name='Planification (cron)')),
                ('artifact_ref', models.CharField(blank=True, default='', help_text='Chemin/URL de stockage du bundle (jamais le contenu).', max_length=500, verbose_name="Référence de l'artefact")),
                ('manifest', models.JSONField(blank=True, default=dict, help_text='Résumé du bundle (datasets + comptes), sans contenu métier.', verbose_name='Manifeste')),
                ('termine_le', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('detail', models.JSONField(blank=True, default=dict, help_text="Compte-rendu d'exécution (erreurs, durées).", verbose_name='Détail')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_runs', to='authentication.company', verbose_name='Société')),
                ('declenche_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Déclenché par')),
            ],
            options={
                'verbose_name': 'Sauvegarde/restauration',
                'verbose_name_plural': 'Sauvegardes/restaurations',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['company', 'kind', 'statut'], name='core_backup_co_kind_st_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChangelogRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.changelogentry', verbose_name='Note de version')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog_reads', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Lecture de note de version',
                'verbose_name_plural': 'Lectures de notes de version',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'entry'), name='core_changelogread_user_entry')],
            },
        ),
    ]
