# Generated by Django 5.1.4 on 2026-07-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_xmkt4_consent_version_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttranslation',
            name='field',
            field=models.CharField(help_text='Nom du champ traduit (ex. « nom », « description », « titre », « corps »).', max_length=100, verbose_name='Champ'),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='rotation_period_days',
            field=models.PositiveIntegerField(blank=True, help_text='Échéance = dernière rotation + cette période. Vide = pas de suivi.', null=True, verbose_name='Période de rotation (jours)'),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='secret_owner',
            field=models.CharField(blank=True, default='', help_text='Texte libre (personne/équipe responsable de la rotation).', max_length=120, verbose_name='Propriétaire du secret'),
        ),
    ]
