# Generated by Django 5.1.15 on 2026-10-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0075_ntwfl29_dossiermodele'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esignrequest',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype', verbose_name='Type de document'),
        ),
    ]
