# Generated by Django 5.1.4 on 2026-08-14 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteDeCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('type_poste', models.CharField(choices=[('machine', 'Machine'), ('ligne', 'Ligne'), ('manuel', 'Poste manuel'), ('sous_traite', 'Sous-traité')], default='machine', max_length=16, verbose_name='Type de poste')),
                ('capacite_heures_jour', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='Capacité (h/jour)')),
                ('cout_horaire', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût horaire (interne)')),
                ('calendrier_travail', models.JSONField(blank=True, default=dict, verbose_name='Calendrier de travail')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Poste de charge',
                'verbose_name_plural': 'Postes de charge',
                'ordering': ['nom'],
                'indexes': [models.Index(fields=['company', 'actif'], name='mrp_poste_co_actif_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='mrp_poste_co_code_uniq')],
            },
        ),
    ]
