# Generated by Django 5.1.4 on 2026-08-14 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('mrp', '0001_initial'),
        ('stock', '0085_ntadm2_produit_entite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_gammes', to='stock.produit', verbose_name='Produit fabriqué')),
            ],
            options={
                'verbose_name': 'Gamme opératoire',
                'verbose_name_plural': 'Gammes opératoires',
                'ordering': ['produit_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='OperationGamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('temps_prepa_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Temps de préparation (min)')),
                ('temps_unitaire_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Temps unitaire (min/pièce)')),
                ('temps_min_par_lot', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Temps minimum par lot (min)')),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='mrp.gamme')),
                ('poste_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_gamme', to='mrp.postedecharge', verbose_name='Poste de charge')),
            ],
            options={
                'verbose_name': 'Opération de gamme',
                'verbose_name_plural': 'Opérations de gamme',
                'ordering': ['gamme_id', 'ordre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='gamme',
            index=models.Index(fields=['company', 'produit', 'actif'], name='mrp_gamme_co_produit_actif_idx'),
        ),
        migrations.AddConstraint(
            model_name='gamme',
            constraint=models.UniqueConstraint(fields=('company', 'produit', 'version'), name='mrp_gamme_co_produit_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='operationgamme',
            index=models.Index(fields=['gamme'], name='mrp_opgamme_gamme_idx'),
        ),
        migrations.AddIndex(
            model_name='operationgamme',
            index=models.Index(fields=['poste_charge'], name='mrp_opgamme_poste_idx'),
        ),
    ]
