# Generated by Django 5.1.4 on 2026-08-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('installations', '0100_photochecklistmeta_tenantmodel_timestamps'),
        ('mrp', '0002_gamme_operationgamme_and_more'),
        ('stock', '0085_ntadm2_produit_entite'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreFabrication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Quantité')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('planifie', 'Planifié'), ('lance', 'Lancé'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('date_debut_planifiee', models.DateTimeField(blank=True, null=True, verbose_name='Début prévu')),
                ('date_fin_planifiee', models.DateTimeField(blank=True, null=True, verbose_name='Fin prévue')),
                ('priorite', models.PositiveSmallIntegerField(default=3, verbose_name='Priorité')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('gamme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_fabrication', to='mrp.gamme', verbose_name='Gamme')),
                ('kit_ordre_assemblage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_ordres_fabrication', to='installations.ordreassemblage', verbose_name="Ordre d'assemblage kitting lié")),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_ordres_fabrication', to='stock.produit', verbose_name='Produit fabriqué')),
            ],
            options={
                'verbose_name': 'Ordre de fabrication',
                'verbose_name_plural': 'Ordres de fabrication',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OperationOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='a_faire', max_length=10)),
                ('date_planifiee', models.DateField(blank=True, null=True, verbose_name='Jour planifié')),
                ('temps_reel_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Temps réel (min)')),
                ('quantite_bonne', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité bonne')),
                ('quantite_rebut', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité rebut')),
                ('operation_gamme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_of', to='mrp.operationgamme')),
                ('poste_charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_of', to='mrp.postedecharge')),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='mrp.ordrefabrication')),
            ],
            options={
                'verbose_name': "Opération d'OF",
                'verbose_name_plural': "Opérations d'OF",
                'ordering': ['ordre_fabrication_id', 'ordre', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='ordrefabrication',
            index=models.Index(fields=['company', 'statut'], name='mrp_of_co_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='ordrefabrication',
            index=models.Index(fields=['company', 'produit'], name='mrp_of_co_produit_idx'),
        ),
        migrations.AddIndex(
            model_name='operationof',
            index=models.Index(fields=['ordre_fabrication'], name='mrp_opof_of_idx'),
        ),
        migrations.AddIndex(
            model_name='operationof',
            index=models.Index(fields=['poste_charge', 'date_planifiee'], name='mrp_opof_poste_date_idx'),
        ),
    ]
