# Generated by Django 5.1.4 on 2026-08-14 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0003_ordrefabrication_operationof_and_more'),
        ('stock', '0085_ntadm2_produit_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamme',
            name='kit_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_gammes_source', to='stock.kitproduit', verbose_name='Nomenclature source (kit)'),
        ),
        migrations.AddField(
            model_name='ordrefabrication',
            name='stock_mouvemente',
            field=models.BooleanField(default=False, verbose_name='Stock mouvementé'),
        ),
    ]
