# Generated by Django 5.1.4 on 2026-08-14 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0004_gamme_kit_source_ordrefabrication_stock_mouvemente'),
        ('stock', '0085_ntadm2_produit_entite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('consomme', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('ordre_fabrication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='mrp.ordrefabrication')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_reservations_of', to='stock.produit')),
            ],
            options={
                'verbose_name': "Réservation d'OF",
                'verbose_name_plural': "Réservations d'OF",
                'ordering': ['ordre_fabrication_id', 'id'],
                'indexes': [models.Index(fields=['ordre_fabrication'], name='mrp_resof_of_idx'), models.Index(fields=['produit'], name='mrp_resof_produit_idx')],
            },
        ),
    ]
