# Generated by Django 5.1.4 on 2026-08-14 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0005_reservationof'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationof',
            name='demarree_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationof',
            name='motif_rebut',
            field=models.CharField(blank=True, choices=[('casse', 'Casse'), ('defaut', 'Défaut'), ('erreur', 'Erreur'), ('autre', 'Autre')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='operationof',
            name='terminee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operationof',
            name='statut',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('en_pause', 'En pause'), ('terminee', 'Terminée')], default='a_faire', max_length=10),
        ),
        migrations.CreateModel(
            name='PauseOperationOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='mrp.operationof')),
            ],
            options={
                'verbose_name': "Pause d'opération",
                'verbose_name_plural': "Pauses d'opération",
                'ordering': ['operation_id', 'debut'],
                'indexes': [models.Index(fields=['operation'], name='mrp_pauseof_op_idx')],
            },
        ),
    ]
