# Generated by Django 5.1.4 on 2026-08-14 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0006_operationof_demarree_le_operationof_motif_rebut_and_more'),
        ('stock', '0085_ntadm2_produit_entite'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationof',
            name='cout_faconnage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coût façon (interne)'),
        ),
        migrations.AddField(
            model_name='postedecharge',
            name='sous_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mrp_postes_charge', to='stock.fournisseur', verbose_name='Sous-traitant'),
        ),
    ]
