# Generated by Django 5.1.4 on 2026-08-14 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('mrp', '0007_operationof_cout_faconnage_and_more'),
        ('stock', '0085_ntadm2_produit_entite'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoutStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('cout_matiere', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût matière standard (1 unité)')),
                ('cout_main_oeuvre', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Coût main-d'œuvre standard (1 unité)")),
                ('cout_indirect_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Coût indirect (%)')),
                ('date_effective', models.DateField(verbose_name="Date d'effectivité")),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mrp_couts_standard', to='stock.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Coût standard',
                'verbose_name_plural': 'Coûts standard',
                'ordering': ['company_id', 'produit_id', '-version'],
                'indexes': [models.Index(fields=['company', 'produit'], name='mrp_coutstd_co_produit_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'produit', 'version'), name='mrp_coutstd_co_produit_version_uniq')],
            },
        ),
    ]
