# Generated by Django 5.1.4 on 2026-08-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('mrp', '0013_ntmfg17_regles_kanban_production'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresMRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('horizon_mrp_jours', models.PositiveIntegerField(default=30, verbose_name='Horizon MRP (jours)')),
                ('stock_securite_pct_defaut', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Stock de sécurité par défaut (%)')),
                ('tolerance_surcharge_poste_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tolérance de surcharge poste (%)')),
                ('blocage_qc_force_motif_obligatoire', models.BooleanField(default=True, verbose_name='Motif obligatoire pour forcer un contrôle qualité bloquant')),
                ('activer_kanban_production', models.BooleanField(default=False, verbose_name='Kanban de production actif')),
                ('retention_prototype_jours', models.PositiveIntegerField(default=180, verbose_name='Rétention des OF prototype (jours)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mrp_parametres', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Paramètres MRP',
                'verbose_name_plural': 'Paramètres MRP',
            },
        ),
    ]
