# Generated by Django 5.1.4 on 2026-08-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrp', '0015_ntmfg31_ordrefabrication_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='echeanceentretienposte',
            name='notifie',
            field=models.BooleanField(default=False, verbose_name='Rappel J-7 envoyé'),
        ),
    ]
