# Generated by Django 5.1.4 on 2026-07-19 02:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsengine', '0030_adsdeep55_instagram'),
        ('authentication', '0025_company_est_demo_mode_presentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssumptionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.CharField(choices=[('creatif', 'Créatif'), ('angle', 'Angle'), ('audience_structure', 'Audience / structure')], max_length=20, verbose_name='Classe')),
                ('enonce_fr', models.TextField(verbose_name='Énoncé (FR)')),
                ('enjeux_s', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Enjeux (S)')),
                ('pertinence_r', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Pertinence-décision (R)')),
                ('tags_saison', models.JSONField(blank=True, default=list, verbose_name="Tags saison (ex. ramadan, ete — posteriors séparés, PAS de l'oubli)")),
                ('alpha', models.FloatField(default=1.0, verbose_name='Posterior α')),
                ('beta', models.FloatField(default=1.0, verbose_name='Posterior β')),
                ('alpha0', models.FloatField(default=1.0, verbose_name='Prior α₀')),
                ('beta0', models.FloatField(default=1.0, verbose_name='Prior β₀')),
                ('demi_vie_semaines', models.PositiveIntegerField(blank=True, null=True, verbose_name='Demi-vie (semaines) — défaut classe, surchargeable')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernier test le')),
                ('statut', models.CharField(choices=[('assumed', 'Supposé'), ('testing', 'En test'), ('validated', 'Validé'), ('stale', 'Périmé'), ('retired', 'Retiré')], default='assumed', max_length=12, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('invalidation_links', models.ManyToManyField(blank=True, related_name='invalidated_by', to='adsengine.assumptionnode', verbose_name="Liens d'invalidation (DAG, hors hiérarchie)")),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='adsengine.assumptionnode', verbose_name='Nœud parent')),
            ],
            options={
                'verbose_name': 'Nœud hypothèse',
                'verbose_name_plural': 'Nœuds hypothèse',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='adseng_asgnode_co_st_idx')],
            },
        ),
    ]
