# Generated by Django 5.1.4 on 2026-07-19 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsengine', '0031_assumptionnode'),
        ('authentication', '0025_company_est_demo_mode_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativegenerationbatch',
            name='claim_verdicts',
            field=models.JSONField(blank=True, default=dict, verbose_name='Verdicts par claim (numérique/groundedness)'),
        ),
        migrations.AddField(
            model_name='creativegenerationbatch',
            name='fact_table_version',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Version de la table de faits utilisée'),
        ),
        migrations.AddField(
            model_name='creativegenerationbatch',
            name='template_quarantined',
            field=models.BooleanField(default=False, verbose_name='Gabarit en quarantaine (rollback AGEN9)'),
        ),
        migrations.CreateModel(
            name='FactTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(verbose_name='Version')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publiee', 'Publiée')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
            ],
            options={
                'verbose_name': 'Table de faits',
                'verbose_name_plural': 'Tables de faits',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='FactEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cle', models.CharField(max_length=100, verbose_name='Clé')),
                ('valeur', models.CharField(max_length=255, verbose_name='Valeur')),
                ('unite', models.CharField(blank=True, default='', max_length=50, verbose_name='Unité')),
                ('source', models.CharField(blank=True, default='', max_length=255, verbose_name='Source')),
                ('verifie_le', models.DateField(verbose_name='Vérifié le')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='adsengine.facttable', verbose_name='Table de faits')),
            ],
            options={
                'verbose_name': 'Fait',
                'verbose_name_plural': 'Faits',
                'ordering': ['cle'],
            },
        ),
        migrations.AddConstraint(
            model_name='facttable',
            constraint=models.UniqueConstraint(fields=('company', 'version'), name='uniq_adseng_facttable_co_version'),
        ),
        migrations.AddConstraint(
            model_name='facttable',
            constraint=models.UniqueConstraint(condition=models.Q(('statut', 'publiee')), fields=('company',), name='uniq_adseng_facttable_one_published'),
        ),
        migrations.AddConstraint(
            model_name='factentry',
            constraint=models.UniqueConstraint(fields=('table', 'cle'), name='uniq_adseng_factentry_table_cle'),
        ),
    ]
