# Generated by Django 5.1.4 on 2026-07-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsengine', '0032_creativegenerationbatch_claim_verdicts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardrailconfig',
            name='health_creative_weight_ctr',
            field=models.PositiveIntegerField(default=60, verbose_name='Santé créatif — poids CTR'),
        ),
        migrations.AddField(
            model_name='guardrailconfig',
            name='health_creative_weight_freshness',
            field=models.PositiveIntegerField(default=40, verbose_name='Santé créatif — poids fraîcheur'),
        ),
        migrations.AddField(
            model_name='guardrailconfig',
            name='health_ops_weight_cpl',
            field=models.PositiveIntegerField(default=60, verbose_name='Santé opérations — poids CPL'),
        ),
        migrations.AddField(
            model_name='guardrailconfig',
            name='health_ops_weight_delivery',
            field=models.PositiveIntegerField(default=40, verbose_name='Santé opérations — poids livraison'),
        ),
    ]
