# Generated by Django 5.1.4 on 2026-06-21 00:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParametrePaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_effet", models.DateField(verbose_name="Date d'effet")),
                (
                    "smig",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="SMIG",
                    ),
                ),
                (
                    "smag",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="SMAG",
                    ),
                ),
                (
                    "plafond_cnss",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("6000"),
                        max_digits=14,
                        verbose_name="Plafond CNSS",
                    ),
                ),
                (
                    "taux_cnss_salarial",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("4.48"),
                        max_digits=6,
                        verbose_name="Taux CNSS salarial",
                    ),
                ),
                (
                    "taux_cnss_patronal",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("8.98"),
                        max_digits=6,
                        verbose_name="Taux CNSS patronal",
                    ),
                ),
                (
                    "taux_amo_salarial",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("2.26"),
                        max_digits=6,
                        verbose_name="Taux AMO salarial",
                    ),
                ),
                (
                    "taux_amo_patronal",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("2.26"),
                        max_digits=6,
                        verbose_name="Taux AMO patronal",
                    ),
                ),
                (
                    "taux_formation_pro",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.6"),
                        max_digits=6,
                        verbose_name="Taux formation professionnelle",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paie_parametres",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre de paie",
                "verbose_name_plural": "Paramètres de paie",
                "ordering": ["-date_effet"],
            },
        ),
        migrations.CreateModel(
            name="BaremeIR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        default="Barème IR", max_length=120, verbose_name="Libellé"
                    ),
                ),
                ("date_effet", models.DateField(verbose_name="Date d'effet")),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paie_baremes_ir",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Barème IR",
                "verbose_name_plural": "Barèmes IR",
                "ordering": ["-date_effet"],
            },
        ),
        migrations.CreateModel(
            name="TrancheIR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borne_min",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Borne minimale",
                    ),
                ),
                (
                    "borne_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Borne maximale",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Taux",
                    ),
                ),
                (
                    "somme_a_deduire",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Somme à déduire",
                    ),
                ),
                (
                    "ordre",
                    models.PositiveIntegerField(default=0, verbose_name="Ordre"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paie_tranches_ir",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "bareme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tranches",
                        to="paie.baremeir",
                        verbose_name="Barème",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tranche IR",
                "verbose_name_plural": "Tranches IR",
                "ordering": ["ordre"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="parametrepaie",
            unique_together={("company", "date_effet")},
        ),
        migrations.AlterUniqueTogether(
            name="baremeir",
            unique_together={("company", "date_effet")},
        ),
    ]
