# Generated by Django 5.1.4 on 2026-06-22 09:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baremeir",
            name="valide_par_fondateur",
            field=models.BooleanField(
                default=False, verbose_name="Validé par le fondateur"
            ),
        ),
        migrations.AddField(
            model_name="parametrepaie",
            name="plafond_frais_pro_bas",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2500"),
                max_digits=14,
                verbose_name="Plafond frais professionnels (brut ≤ seuil)",
            ),
        ),
        migrations.AddField(
            model_name="parametrepaie",
            name="plafond_frais_pro_haut",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2916.67"),
                max_digits=14,
                verbose_name="Plafond frais professionnels (brut > seuil)",
            ),
        ),
        migrations.AddField(
            model_name="parametrepaie",
            name="seuil_frais_pro",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("6500"),
                max_digits=14,
                verbose_name="Seuil brut frais professionnels",
            ),
        ),
        migrations.AddField(
            model_name="parametrepaie",
            name="taux_frais_pro_bas",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("35"),
                max_digits=6,
                verbose_name="Taux frais professionnels (brut ≤ seuil)",
            ),
        ),
        migrations.AddField(
            model_name="parametrepaie",
            name="taux_frais_pro_haut",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("25"),
                max_digits=6,
                verbose_name="Taux frais professionnels (brut > seuil)",
            ),
        ),
        migrations.AddField(
            model_name="parametrepaie",
            name="valide_par_fondateur",
            field=models.BooleanField(
                default=False, verbose_name="Validé par le fondateur"
            ),
        ),
    ]
