# Generated by Django 5.1.4 on 2026-06-22 10:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("paie", "0002_baremeir_valide_par_fondateur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametrepaie",
            name="deduction_par_personne_a_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("30"),
                max_digits=14,
                verbose_name="Déduction mensuelle par personne à charge",
            ),
        ),
        migrations.AddField(
            model_name="parametrepaie",
            name="plafond_personnes_a_charge",
            field=models.PositiveIntegerField(
                default=6, verbose_name="Plafond du nombre de personnes à charge"
            ),
        ),
    ]
