# Generated by Django 5.1.4 on 2026-06-22 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("paie", "0003_parametrepaie_deduction_par_personne_a_charge_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rubrique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, verbose_name="Code")),
                ("libelle", models.CharField(max_length=120, verbose_name="Libellé")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("gain", "Gain"),
                            ("retenue", "Retenue"),
                            ("cotisation", "Cotisation"),
                        ],
                        default="gain",
                        max_length=12,
                        verbose_name="Type",
                    ),
                ),
                (
                    "imposable",
                    models.BooleanField(default=False, verbose_name="Imposable (IR)"),
                ),
                (
                    "soumis_cnss",
                    models.BooleanField(default=False, verbose_name="Soumis CNSS"),
                ),
                (
                    "soumis_amo",
                    models.BooleanField(default=False, verbose_name="Soumis AMO"),
                ),
                (
                    "soumis_cimr",
                    models.BooleanField(default=False, verbose_name="Soumis CIMR"),
                ),
                (
                    "compte",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Compte comptable",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("brut", "Brut"),
                            ("brut_imposable", "Brut imposable"),
                            ("net_imposable", "Net imposable"),
                            ("plafonnee_cnss", "Assiette plafonnée CNSS"),
                            ("autre", "Autre / manuelle"),
                        ],
                        default="brut",
                        max_length=20,
                        verbose_name="Assiette",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Taux (%)",
                    ),
                ),
                (
                    "montant_fixe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant fixe",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0, verbose_name="Ordre")),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paie_rubriques",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubrique de paie",
                "verbose_name_plural": "Rubriques de paie",
                "ordering": ["ordre", "code"],
                "unique_together": {("company", "code")},
            },
        ),
    ]
