# Generated by Django 5.1.4 on 2026-06-22 14:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("paie", "0004_rubrique"),
        ("rh", "0006_documentemploye"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodePaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField(verbose_name="Année")),
                ("mois", models.PositiveSmallIntegerField(verbose_name="Mois")),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Libellé"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("calculee", "Calculée"),
                            ("validee", "Validée"),
                            ("cloturee", "Clôturée"),
                        ],
                        default="brouillon",
                        max_length=12,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_paiement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "date_cloture",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Clôturée le"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paie_periodes",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
            ],
            options={
                "verbose_name": "Période de paie",
                "verbose_name_plural": "Périodes de paie",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("company", "annee", "mois")},
            },
        ),
        migrations.CreateModel(
            name="ProfilPaie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_remuneration",
                    models.CharField(
                        choices=[
                            ("mensuel", "Mensuel"),
                            ("journalier", "Journalier"),
                            ("forfait", "Forfait"),
                            ("horaire", "Horaire"),
                        ],
                        default="mensuel",
                        max_length=12,
                        verbose_name="Type de rémunération",
                    ),
                ),
                (
                    "salaire_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Salaire de base",
                    ),
                ),
                (
                    "affilie_cnss",
                    models.BooleanField(default=True, verbose_name="Affilié CNSS"),
                ),
                (
                    "affilie_amo",
                    models.BooleanField(default=True, verbose_name="Affilié AMO"),
                ),
                (
                    "affilie_cimr",
                    models.BooleanField(default=False, verbose_name="Affilié CIMR"),
                ),
                (
                    "taux_cimr_salarial",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Taux CIMR salarial",
                    ),
                ),
                (
                    "numero_cnss",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="N° CNSS"
                    ),
                ),
                (
                    "numero_amo",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="N° AMO"
                    ),
                ),
                (
                    "numero_cimr",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="N° CIMR"
                    ),
                ),
                (
                    "rib",
                    models.CharField(
                        blank=True, default="", max_length=40, verbose_name="RIB"
                    ),
                ),
                (
                    "banque",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Banque"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paie_profils",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "employe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profil_paie",
                        to="rh.dossieremploye",
                        verbose_name="Dossier employé",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil de paie",
                "verbose_name_plural": "Profils de paie",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ElementVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("heures", "Heures travaillées"),
                            ("heures_sup", "Heures supplémentaires"),
                            ("absence", "Absence"),
                            ("prime", "Prime"),
                            ("retenue", "Retenue"),
                        ],
                        default="prime",
                        max_length=12,
                        verbose_name="Type",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Libellé"
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manuel", "Saisie manuelle"), ("rh", "Import RH")],
                        default="manuel",
                        max_length=10,
                        verbose_name="Source",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paie_elements_variables",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "rubrique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elements_variables",
                        to="paie.rubrique",
                        verbose_name="Rubrique",
                    ),
                ),
                (
                    "periode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements_variables",
                        to="paie.periodepaie",
                        verbose_name="Période",
                    ),
                ),
                (
                    "profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elements_variables",
                        to="paie.profilpaie",
                        verbose_name="Profil de paie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Élément variable",
                "verbose_name_plural": "Éléments variables",
                "ordering": ["periode", "profil", "id"],
            },
        ),
        migrations.CreateModel(
            name="RubriqueEmploye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant (surcharge)",
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        verbose_name="Taux % (surcharge)",
                    ),
                ),
                (
                    "date_debut",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "date_fin",
                    models.DateField(blank=True, null=True, verbose_name="Date de fin"),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paie_rubriques_employe",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "profil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubriques",
                        to="paie.profilpaie",
                        verbose_name="Profil de paie",
                    ),
                ),
                (
                    "rubrique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rattachements",
                        to="paie.rubrique",
                        verbose_name="Rubrique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rubrique employé",
                "verbose_name_plural": "Rubriques employé",
                "ordering": ["rubrique__ordre", "id"],
                "unique_together": {("profil", "rubrique")},
            },
        ),
    ]
