# Generated by Django 5.1.4 on 2026-06-24

from django.db import migrations, models


class Migration(migrations.Migration):
    """PAIE13 — Normes de travail sur ProfilPaie (journalier / horaire / proration).

    Ajoute ``jours_travail_mensuel`` et ``heures_travail_mensuel`` au
    ``ProfilPaie``. Ces champs portent les normes contractuelles de l'employé
    utilisées pour calculer le salaire proraté (types mensuel/journalier/horaire).
    Migration purement additive, réversible.
    """

    dependencies = [
        ("paie", "0005_periodepaie_profilpaie_elementvariable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilpaie",
            name="jours_travail_mensuel",
            field=models.PositiveSmallIntegerField(
                default=26,
                verbose_name="Jours de travail par mois (norme)",
            ),
        ),
        migrations.AddField(
            model_name="profilpaie",
            name="heures_travail_mensuel",
            field=models.PositiveSmallIntegerField(
                default=191,
                verbose_name="Heures de travail par mois (norme)",
            ),
        ),
    ]
