# Generated by Django 5.1.4 on 2026-06-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compta', '0023_entiteconsolidation'),
        ('paie', '0019_bulletin_rectificatif'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrevirement',
            name='compte_emetteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_virement_paie', to='compta.comptetresorerie', verbose_name='Compte émetteur (trésorerie)'),
        ),
    ]
