# Generated by Django 5.1.4 on 2026-06-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('compta', '0023_entiteconsolidation'),
        ('paie', '0020_ordrevirement_compte_emetteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrevirement',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Référence'),
        ),
        migrations.AddConstraint(
            model_name='ordrevirement',
            constraint=models.UniqueConstraint(condition=models.Q(('reference__isnull', False), models.Q(('reference', ''), _negated=True)), fields=('company', 'reference'), name='uniq_ordrevirement_ref_par_societe'),
        ),
    ]
