# Generated by Django 5.1.4 on 2026-07-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0041_zpai12_periode_alerte_cloture_retard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinpaie',
            name='type_bulletin',
            field=models.CharField(choices=[('normal', 'Normal'), ('rectificatif', 'Rectificatif'), ('rappel', 'Rappel'), ('stc', 'Solde de tout compte'), ('gratification', '13e mois / gratification'), ('annulation', 'Annulation (extourne)')], default='normal', max_length=14, verbose_name='Nature du bulletin'),
        ),
    ]
