# Generated by Django 5.2.14 on 2026-05-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_mouvementstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='seuil_alerte',
            field=models.IntegerField(default=0),
        ),
    ]
