# Generated by Django 5.2.14 on 2026-05-19 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_alter_customuser_groups_and_more'),
        ('stock', '0003_add_seuil_alerte_to_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fournisseurs', to='authentication.company'),
        ),
        migrations.AddField(
            model_name='produit',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='authentication.company'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('company', 'nom')},
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('company', 'sku')},
        ),
    ]
