# Generated by Django 5.2.14 on 2026-05-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_categorie_company_fournisseur_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
