# Generated by Django 5.1.4 on 2026-06-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_mouvementstock_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='debit_m3j',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Débit max indicatif (m³/jour).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='garantie',
            field=models.CharField(blank=True, help_text='Texte garantie constructeur / performance.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='hmt_m',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur manométrique totale max (m).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='pompe_cv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puissance pompe en chevaux (CV).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, help_text='Lignes descriptives affichées sous la désignation dans les PDF (une par ligne).', null=True),
        ),
    ]
