# Generated by Django 5.1.4 on 2026-06-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_produit_debit_m3j_produit_garantie_produit_hmt_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='courbe_pompe',
            field=models.JSONField(blank=True, help_text='Courbe de performance constructeur : {"debits_m3h": [0, 12, ...], "hmt_m": [91, 85, ...]} (HMT délivrée à chaque débit).', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='pompe_kw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puissance nominale (kW) — pompes ET variateurs.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='tension_v',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Tension nominale (V) : 220 ou 380.', null=True),
        ),
    ]
