# Generated by Django 5.1.4 on 2026-06-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_produit_courbe_pompe_produit_pompe_kw_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['ordre', 'nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='ordre',
            field=models.PositiveSmallIntegerField(default=100, help_text="Ordre d'affichage délibéré (plus petit = plus haut)."),
        ),
    ]
