# Generated by Django 5.1.4 on 2026-06-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_categorie_options_categorie_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='garantie_mois',
            field=models.PositiveIntegerField(blank=True, help_text='Garantie équipement en mois (laisser vide si non renseignée).', null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='garantie_production_mois',
            field=models.PositiveIntegerField(blank=True, help_text='Garantie production (panneaux) en mois — souvent 300 à 360.', null=True),
        ),
    ]
