# Generated by Django 5.1.4 on 2026-06-16 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("stock", "0013_backfill_garantie_onduleurs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("archived", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marques",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marque",
                "ordering": ["nom"],
                "unique_together": {("company", "nom")},
            },
        ),
    ]
