# Generated by Django 5.1.4 on 2026-06-16 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("stock", "0014_produitauditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marques",
                        to="authentication.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Marque",
                "verbose_name_plural": "Marques",
                "ordering": ["nom"],
                "unique_together": {("company", "nom")},
            },
        ),
        migrations.AddField(
            model_name="produit",
            name="marque_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produits",
                to="stock.marque",
            ),
        ),
    ]
