# Generated by Django 5.1.4 on 2026-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0014_marque"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
