# Generated by Django 5.1.4 on 2026-06-16 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        ("stock", "0015_produit_custom_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonCommandeFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoye", "Envoyé"),
                            ("recu", "Reçu"),
                            ("annule", "Annulé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_commande", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bons_commande_fournisseur",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_commande_fournisseur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bons_commande",
                        to="stock.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de commande fournisseur",
                "verbose_name_plural": "Bons de commande fournisseur",
                "ordering": ["-date_creation"],
                "unique_together": {("company", "reference")},
            },
        ),
        migrations.CreateModel(
            name="LigneBonCommandeFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                (
                    "prix_achat_unitaire",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("quantite_recue", models.IntegerField(default=0)),
                (
                    "bon_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.boncommandefournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_bon_commande_fournisseur",
                        to="stock.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de bon de commande fournisseur",
                "verbose_name_plural": "Lignes de bon de commande fournisseur",
            },
        ),
    ]
