# Generated by Django 5.1.4 on 2026-06-17 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_avatar_key_customuser_poste'),
        ('stock', '0016_boncommandefournisseur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmplacementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('is_principal', models.BooleanField(default=False, help_text='Le dépôt principal détient le stock non ventilé (un seul par société).')),
                ('ordre', models.PositiveSmallIntegerField(default=100)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emplacements_stock', to='authentication.company')),
            ],
            options={
                'verbose_name': 'Emplacement de stock',
                'verbose_name_plural': 'Emplacements de stock',
                'ordering': ['-is_principal', 'ordre', 'nom'],
                'unique_together': {('company', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferts_stock', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_stock', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_entrants', to='stock.emplacementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts', to='stock.produit')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferts_sortants', to='stock.emplacementstock')),
            ],
            options={
                'verbose_name': 'Transfert de stock',
                'verbose_name_plural': 'Transferts de stock',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockEmplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks_emplacement', to='authentication.company')),
                ('emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.emplacementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_emplacement', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Stock par emplacement',
                'verbose_name_plural': 'Stocks par emplacement',
                'unique_together': {('produit', 'emplacement')},
            },
        ),
    ]
