# Generated by Django 5.1.4 on 2026-06-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0016_backfill_marque"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
