# Generated by Django 5.1.4 on 2026-06-17 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_avatar_key_customuser_poste'),
        ('stock', '0017_emplacementstock_transfertstock_stockemplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrixFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_dernier_achat', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prix_fournisseurs', to='authentication.company')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_produits', to='stock.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_fournisseurs', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Prix fournisseur',
                'verbose_name_plural': 'Prix fournisseurs',
                'ordering': ['prix_achat'],
                'unique_together': {('produit', 'fournisseur')},
            },
        ),
    ]
