# Generated by Django 5.1.4 on 2026-06-16 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
        ("stock", "0017_produit_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produits",
                to="imports.importbatch",
            ),
        ),
    ]
