# Generated by Django 5.1.4 on 2026-06-17 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_avatar_key_customuser_poste'),
        ('stock', '0018_prixfournisseur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('annule', 'Annulé')], default='brouillon', max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('bon_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours', to='stock.boncommandefournisseur')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retours_fournisseur', to='authentication.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_fournisseur', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours', to='stock.fournisseur')),
            ],
            options={
                'verbose_name': 'Retour fournisseur',
                'verbose_name_plural': 'Retours fournisseur',
                'ordering': ['-date_creation'],
                'unique_together': {('company', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='LigneRetourFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('motif', models.CharField(blank=True, max_length=255, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour_fournisseur', to='stock.produit')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.retourfournisseur')),
            ],
            options={
                'verbose_name': 'Ligne de retour fournisseur',
                'verbose_name_plural': 'Lignes de retour fournisseur',
            },
        ),
    ]
