# Generated by Django 5.1.4 on 2026-06-20 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
        ("stock", "0020_categorie_type_equipement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FactureFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50)),
                (
                    "ref_fournisseur",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_facture", models.DateField(blank=True, null=True)),
                ("date_echeance", models.DateField(blank=True, null=True)),
                (
                    "montant_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "montant_tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_payer", "À payer"),
                            ("partiellement_payee", "Partiellement payée"),
                            ("payee", "Payée"),
                        ],
                        default="a_payer",
                        max_length=24,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "bon_commande",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_fournisseur",
                        to="stock.boncommandefournisseur",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="factures_fournisseur",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_fournisseur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures_fournisseur",
                        to="stock.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture fournisseur",
                "verbose_name_plural": "Factures fournisseur",
                "ordering": ["-date_creation"],
                "unique_together": {("company", "reference")},
            },
        ),
        migrations.CreateModel(
            name="LigneFactureFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation", models.CharField(max_length=255)),
                (
                    "quantite",
                    models.DecimalField(decimal_places=2, default=1, max_digits=12),
                ),
                (
                    "prix_unitaire_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.facturefournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lignes_facture_fournisseur",
                        to="stock.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de facture fournisseur",
                "verbose_name_plural": "Lignes de facture fournisseur",
            },
        ),
        migrations.CreateModel(
            name="PaiementFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=14)),
                ("date_paiement", models.DateField(blank=True, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                            ("especes", "Espèces"),
                            ("carte", "Carte"),
                            ("effet", "Effet / traite"),
                            ("autre", "Autre"),
                        ],
                        default="virement",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements_fournisseur",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_fournisseur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="stock.facturefournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement fournisseur",
                "verbose_name_plural": "Paiements fournisseur",
                "ordering": ["-date_paiement", "-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="ReceptionFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("confirme", "Confirmé"),
                            ("annule", "Annulé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_reception", models.DateField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "bon_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receptions",
                        to="stock.boncommandefournisseur",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receptions_fournisseur",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receptions_fournisseur_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recu_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receptions_fournisseur",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Réception fournisseur",
                "verbose_name_plural": "Réceptions fournisseur",
                "ordering": ["-date_creation"],
                "unique_together": {("company", "reference")},
            },
        ),
        migrations.CreateModel(
            name="LigneReceptionFournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.IntegerField()),
                (
                    "ligne_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_reception",
                        to="stock.ligneboncommandefournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_reception_fournisseur",
                        to="stock.produit",
                    ),
                ),
                (
                    "reception",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.receptionfournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de réception fournisseur",
                "verbose_name_plural": "Lignes de réception fournisseur",
            },
        ),
    ]
