# Generated by Django 5.1.4 on 2026-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_customuser_totp_enabled_and_more"),
        ("stock", "0021_facturefournisseur_lignefacturefournisseur_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stockemplacement",
            unique_together={("company", "produit", "emplacement")},
        ),
        migrations.AddConstraint(
            model_name="stockemplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantite__gte", 0)),
                name="stockemplacement_quantite_non_negative",
            ),
        ),
    ]
