# Generated by Django 5.1.4 on 2026-06-21 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_customuser_must_change_password_and_more"),
        ("stock", "0022_alter_stockemplacement_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lignereceptionfournisseur",
            name="date_peremption",
            field=models.DateField(
                blank=True,
                help_text="Date de péremption / fin de vie (optionnel).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lignereceptionfournisseur",
            name="numero_lot",
            field=models.CharField(
                blank=True,
                help_text="Numéro de lot ou batch (optionnel).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lignereceptionfournisseur",
            name="numeros_serie",
            field=models.JSONField(
                blank=True,
                help_text="Numéros de série reçus lors de cette ligne (liste de chaînes). Optionnel ; aucune série = null.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="quantite_reappro_cible",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantité cible à commander lors d'un réapprovisionnement (facultatif ; défaut = seuil_alerte × 2).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockemplacement",
            name="seuil_max",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Seuil maximum de stock pour cet emplacement (optionnel).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockemplacement",
            name="seuil_min",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Seuil minimum de stock pour cet emplacement (optionnel).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="InventaireSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Validé"),
                            ("annule", "Annulé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("motif", models.TextField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventaire_sessions",
                        to="authentication.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventaire_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Session d'inventaire",
                "verbose_name_plural": "Sessions d'inventaire",
                "ordering": ["-date_creation"],
                "unique_together": {("company", "reference")},
            },
        ),
        migrations.CreateModel(
            name="LigneInventaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite_theorique",
                    models.IntegerField(
                        help_text="Stock théorique au moment du comptage (snapshot)."
                    ),
                ),
                (
                    "quantite_comptee",
                    models.IntegerField(
                        help_text="Quantité réellement comptée physiquement."
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_inventaire",
                        to="stock.produit",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.inventairesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'inventaire",
                "verbose_name_plural": "Lignes d'inventaire",
            },
        ),
    ]
