# Generated by Django 5.1.4 on 2026-06-30 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('stock', '0026_fg67_frais_annexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmax_wc', models.DecimalField(blank=True, decimal_places=2, help_text='Puissance crête Pmax (Wc).', max_digits=8, null=True)),
                ('voc_v', models.DecimalField(blank=True, decimal_places=2, help_text='Tension circuit ouvert Voc (V).', max_digits=8, null=True)),
                ('isc_a', models.DecimalField(blank=True, decimal_places=2, help_text='Courant court-circuit Isc (A).', max_digits=8, null=True)),
                ('vmp_v', models.DecimalField(blank=True, decimal_places=2, help_text='Tension au point de puissance max Vmp (V).', max_digits=8, null=True)),
                ('imp_a', models.DecimalField(blank=True, decimal_places=2, help_text='Courant au point de puissance max Imp (A).', max_digits=8, null=True)),
                ('rendement_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Rendement du module (%).', max_digits=5, null=True)),
                ('pdf', models.FileField(blank=True, help_text='Fiche technique PDF du constructeur.', null=True, upload_to='stock/fiches_techniques/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiches_techniques', to='authentication.company')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_technique', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Fiche technique',
                'verbose_name_plural': 'Fiches techniques',
                'ordering': ['-date_mise_a_jour'],
            },
        ),
    ]
