# Generated by Django 5.1.4 on 2026-07-05 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('installations', '0090_remove_astreinte_idx_astreinte_co_dates_and_more'),
        ('stock', '0071_zstk12_nomenclature_code_barres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produit',
            name='stock_produit_company_code_barres_uniq',
        ),
        migrations.AlterField(
            model_name='boncommandefournisseur',
            name='acheteur',
            field=models.ForeignKey(blank=True, help_text='Acheteur responsable du BCF (défaut = created_by).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_fournisseur_acheteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boncommandefournisseur',
            name='chantier_livraison',
            field=models.ForeignKey(blank=True, help_text="Chantier de LIVRAISON DIRECTE (distinct de chantier_origine/YPROC10, qui trace la demande d'origine) : la réception est suivie d'une affectation chantier tracée (n'entre jamais en stock libre). Vide = comportement historique.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_livraison_directe', to='installations.installation'),
        ),
        migrations.AlterField(
            model_name='boncommandefournisseur',
            name='chantier_origine',
            field=models.ForeignKey(blank=True, help_text="Chantier D'ORIGINE du besoin matériel (distinct de chantier_livraison, qui trace la LIVRAISON) : réceptionner ce BCF réserve automatiquement les quantités reçues pour ce chantier. Vide = comportement historique (stock libre).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_besoin_origine', to='installations.installation'),
        ),
        migrations.AlterField(
            model_name='boncommandefournisseur',
            name='conditions_paiement',
            field=models.CharField(blank=True, help_text='Conditions de paiement reportées du fournisseur (éditables au document), dérivées de delai_paiement_jours.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='boncommandefournisseur',
            name='emplacement_destination',
            field=models.ForeignKey(blank=True, help_text='Emplacement crédité à la réception (vide = dépôt principal, comportement historique).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_destination', to='stock.emplacementstock'),
        ),
        migrations.AlterField(
            model_name='boncommandefournisseur',
            name='note_bas_page',
            field=models.TextField(blank=True, help_text='Mentions imprimées en bas de page du PDF BCF.', null=True),
        ),
        migrations.AlterField(
            model_name='boncommandefournisseur',
            name='ref_fournisseur',
            field=models.CharField(blank=True, help_text='Référence de la commande côté fournisseur (texte libre).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ligneboncommandefournisseur',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Désignation libre (obligatoire quand produit est vide — ex. « Transport Casablanca »).', max_length=255),
        ),
        migrations.AlterField(
            model_name='ligneboncommandefournisseur',
            name='sans_stock',
            field=models.BooleanField(default=False, help_text='Ligne libre/service : jamais de mouvement de stock à la réception. Toujours vrai quand produit est vide.'),
        ),
        migrations.AlterField(
            model_name='lignefacturefournisseur',
            name='taux_tva',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, help_text='Taux TVA de la ligne (%). Vide = taux global de la facture (comportement historique).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='lotentrepot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modeleboncommandefournisseur',
            name='fournisseur',
            field=models.ForeignKey(blank=True, help_text='Fournisseur par défaut du BCF généré (optionnel — peut être choisi/changé à la génération si absent ici).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_bcf', to='stock.fournisseur'),
        ),
        migrations.AlterField(
            model_name='nomenclaturecodebarres',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='palierprixfournisseur',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='portailfournisseurtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prixfournisseur',
            name='ref_produit_fournisseur',
            field=models.CharField(blank=True, default='', help_text='Code article chez le fournisseur (imprimé sur le PDF BCF).', max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='code_sh',
            field=models.CharField(blank=True, help_text="Code du Système Harmonisé (nomenclature douanière) — utilisé pour pré-remplir le dossier d'import ADII.", max_length=20, null=True, verbose_name='Code SH (HS)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pays_origine',
            field=models.CharField(blank=True, help_text="Pays d'origine du produit — utilisé pour pré-remplir le dossier d'import ADII.", max_length=100, null=True, verbose_name="Pays d'origine"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='politique_facturation_achat',
            field=models.CharField(choices=[('sur_reception', 'Sur réception'), ('sur_commande', 'Sur commande')], default='sur_reception', help_text='« Sur réception » = comportement historique (FG56, facturé depuis la réception). « Sur commande » = peut être facturé directement depuis le BCF, sans exiger de réception préalable (ZPUR1).', max_length=20, verbose_name="Politique de facturation d'achat"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='suivi_serie',
            field=models.BooleanField(default=False, help_text="Active la saisie du n° de série à la vente comptoir et la création automatique de l'équipement SAV garanti (onduleur, batterie…).", verbose_name='Suivi par n° de série'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='unite_stock',
            field=models.CharField(default='unité', help_text='Unité dans laquelle le stock est compté (unité/m/kg…).', max_length=20, verbose_name='Unité de stock'),
        ),
        migrations.AlterField(
            model_name='profilsaisonnier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profilsaisonnier',
            name='mois_debut',
            field=models.PositiveSmallIntegerField(help_text='Mois de début de la saison (1-12).'),
        ),
        migrations.AlterField(
            model_name='profilsaisonnier',
            name='mois_fin',
            field=models.PositiveSmallIntegerField(help_text='Mois de fin de la saison (1-12, inclus). Peut être < mois_debut (fenêtre à cheval sur le nouvel an).'),
        ),
        migrations.AlterField(
            model_name='profilsaisonnier',
            name='nom',
            field=models.CharField(blank=True, help_text='Libellé libre (ex. « Saison pompage »).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profilsaisonnier',
            name='quantite_cible',
            field=models.PositiveIntegerField(blank=True, help_text='Quantité cible de remplacement pendant la saison (remplace quantite_reappro_cible).', null=True),
        ),
        migrations.AlterField(
            model_name='profilsaisonnier',
            name='seuil_min',
            field=models.PositiveIntegerField(blank=True, help_text='Seuil minimum de saison (remplace seuil_alerte pendant la fenêtre).', null=True),
        ),
        migrations.AlterField(
            model_name='reglecodebarres',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='produit',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('code_barres__isnull', True), _negated=True), models.Q(('code_barres', ''), _negated=True)), fields=('company', 'code_barres'), name='stock_produit_company_code_barres_uniq'),
        ),
    ]
