# Generated by Django 5.1.4 on 2026-07-09 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0072_remove_produit_stock_produit_company_code_barres_uniq_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kitcomposant',
            unique_together={('kit', 'produit')},
        ),
        migrations.AddField(
            model_name='kitcomposant',
            name='composant_kit',
            field=models.ForeignKey(blank=True, help_text='Sous-kit utilisé comme composant (XOR avec produit).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utilise_comme_sous_kit_dans', to='stock.kitproduit'),
        ),
        migrations.AlterField(
            model_name='kitcomposant',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='composants_kit', to='stock.produit'),
        ),
        migrations.AlterField(
            model_name='kitcomposant',
            name='quantite',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantité de ce produit (ou sous-kit) dans une unité de kit.', max_digits=12),
        ),
        migrations.AlterUniqueTogether(
            name='kitcomposant',
            unique_together={('kit', 'composant_kit'), ('kit', 'produit')},
        ),
        migrations.AddConstraint(
            model_name='kitcomposant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('composant_kit__isnull', True), ('produit__isnull', False)), models.Q(('composant_kit__isnull', False), ('produit__isnull', True)), _connector='OR'), name='kitcomposant_produit_xor_composant_kit'),
        ),
    ]
