# Generated by Django 5.1.4 on 2026-07-10 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('stock', '0073_alter_kitcomposant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('composition', models.JSONField(default=list, help_text='Snapshot des composants : produit_id/composant_kit_id, désignation, quantité, taux de perte.')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions_kit_produit', to='authentication.company')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='stock.kitproduit')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions_kit_produit_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Révision de kit',
                'verbose_name_plural': 'Révisions de kit',
                'ordering': ['kit_id', '-numero'],
                'indexes': [models.Index(fields=['company', 'kit'], name='stock_revkit_co_kit_idx')],
                'constraints': [models.UniqueConstraint(fields=('kit', 'numero'), name='stock_revkit_kit_numero_uniq')],
            },
        ),
    ]
