# Generated by Django 5.1.4 on 2026-07-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0074_revisionkit'),
        ('tiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='tiers',
            field=models.ForeignKey(blank=True, help_text='Fiche du répertoire unifié des parties prenantes reflétant ce fournisseur. Renseignée automatiquement (miroir).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs', to='tiers.tiers', verbose_name='Tiers (répertoire unifié)'),
        ),
    ]
