# Generated by Django 5.1.4 on 2026-07-10 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0057_conditionpaiement'),
        ('stock', '0075_fournisseur_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='condition_paiement_ref',
            field=models.ForeignKey(blank=True, help_text='Condition du référentiel Paramètres reflétant le délai/escompte de ce fournisseur (miroir).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseurs', to='parametres.conditionpaiement', verbose_name='Condition de paiement (référentiel)'),
        ),
    ]
