# Generated by Django 5.1.4 on 2026-07-10 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametres', '0058_unitemesure'),
        ('stock', '0076_fournisseur_condition_paiement_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.ForeignKey(blank=True, help_text='Unité du référentiel Paramètres reflétant ``unite_stock`` (miroir — source du libellé affiché).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='parametres.unitemesure', verbose_name='Unité (référentiel)'),
        ),
    ]
