# Generated by Django 5.1.4 on 2026-07-31 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0080_odx19_achats_split_repoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetechnique',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiche_technique', to='stock.produit'),
        ),
        migrations.AlterField(
            model_name='lotentrepot',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots_entrepot', to='stock.produit'),
        ),
        migrations.AlterField(
            model_name='stockemplacement',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks_emplacement', to='stock.produit'),
        ),
    ]
