# Generated by Django 5.1.4 on 2026-08-14 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_ntadm22_customuser_is_taqinor_support'),
        ('stock', '0088_ntp2p37_sod_stricte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavorisCatalogueAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('produit_ids', models.JSONField(blank=True, default=list, verbose_name='Ids produits épinglés')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris_catalogue_achat', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Favoris du catalogue d'achat",
                'verbose_name_plural': "Favoris du catalogue d'achat",
                'ordering': ['-updated_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'utilisateur'), name='uniq_favoris_cat_achat_user')],
            },
        ),
    ]
