# Generated by Django 5.1.4 on 2026-08-14 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_protect_fournisseur_prix'),
        ('authentication', '0028_company_tours_actifs'),
        ('stock', '0095_ntwms13_plan_comptage_tournant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationCrossDock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('ligne_picking', models.ForeignKey(blank=True, help_text='Ligne de vague en attente qui a justifié le cross-dock.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_cross_dock', to='stock.lignepicking')),
                ('ligne_reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_cross_dock', to='achats.lignereceptionfournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations_cross_dock', to='stock.produit')),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_cross_dock', to='achats.receptionfournisseur')),
                ('unite_logistique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_cross_dock', to='stock.unitelogistique')),
            ],
            options={
                'verbose_name': 'Affectation cross-dock',
                'verbose_name_plural': 'Affectations cross-dock',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'reception'], name='idx_crossdock_co_reception')],
                'constraints': [models.UniqueConstraint(fields=('company', 'ligne_reception'), name='stock_crossdock_company_ligne_uniq')],
            },
        ),
    ]
