# Generated by Django 5.1.4 on 2026-08-14 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('stock', '0096_ntwms15_cross_dock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteRappel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motif', models.TextField()),
                ('date_declenchement', models.DateTimeField(default=django.utils.timezone.now, help_text='Horodatage du déclenchement (aware, jamais naïf).')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('clos', 'Clos')], default='en_cours', max_length=20)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('declenchee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_rappel_declenchees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, help_text='Lot concerné. Vide = le rappel porte sur TOUT le produit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_rappel', to='stock.lotentrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertes_rappel', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Alerte de rappel produit',
                'verbose_name_plural': 'Alertes de rappel produit',
                'ordering': ['-date_declenchement', '-id'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_alerterappel_co_statut')],
            },
        ),
    ]
