# Generated by Django 5.1.4 on 2026-08-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0097_ntwms17_alerte_rappel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplacementstock',
            name='tiers_nom',
            field=models.CharField(blank=True, default='', help_text='Nom du dépositaire (CHEZ_TIERS) ou du propriétaire du stock (DE_TIERS). Vide pour un emplacement interne.', max_length=150),
        ),
        migrations.AddField(
            model_name='emplacementstock',
            name='type_proprietaire',
            field=models.CharField(choices=[('interne', 'Interne (notre stock, nos murs)'), ('chez_tiers', 'Notre stock chez un tiers (3PL, dépôt loué)'), ('de_tiers', "Stock d'un tiers dans nos murs (dépôt-vente)")], default='interne', max_length=20),
        ),
    ]
