# Generated by Django 5.1.4 on 2026-08-14 10:43

import apps.stock.models_wms
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('stock', '0098_ntwms19_stock_tiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortailTiersToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tiers_nom', models.CharField(help_text="Dépositaire propriétaire du stock (NTWMS19 : le `tiers_nom` des emplacements DE_TIERS qu'il possède).", max_length=150)),
                ('token', models.CharField(default=apps.stock.models_wms._default_portail_tiers_token, editable=False, max_length=64)),
                ('expires_at', models.DateTimeField(default=apps.stock.models_wms._default_portail_tiers_expiry)),
                ('revoked', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portails_tiers_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jeton portail 3PL',
                'verbose_name_plural': 'Jetons portail 3PL',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='idx_portailtiers_token')],
                'constraints': [models.UniqueConstraint(fields=('company', 'token'), name='stock_portailtiers_company_token_uniq')],
            },
        ),
    ]
