# Generated by Django 5.1.4 on 2026-08-14 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('stock', '0099_ntwms20_portail_tiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='achatsparametres',
            name='seuil_approbation_transfert',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NTWMS21 — valeur MAD au-dessus de laquelle un transfert exige une approbation. 0 = désactivé.', max_digits=14),
        ),
        migrations.CreateModel(
            name='DemandeTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('approuve', 'Approuvé'), ('execute', 'Exécuté'), ('rejete', 'Rejeté')], default='demande', max_length=20)),
                ('motif', models.TextField(blank=True, default='')),
                ('valeur_estimee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_transfert_approuvees', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('demande_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_transfert_demandees', to=settings.AUTH_USER_MODEL)),
                ('emplacement_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert_destination', to='stock.emplacementstock')),
                ('emplacement_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert_source', to='stock.emplacementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_transfert', to='stock.produit')),
                ('transfert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='stock.transfertstock')),
            ],
            options={
                'verbose_name': 'Demande de transfert',
                'verbose_name_plural': 'Demandes de transfert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_demtransf_co_statut')],
            },
        ),
    ]
