# Generated by Django 5.1.4 on 2026-08-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('crm', '0075_playbook_condition'),
        ('installations', '0100_photochecklistmeta_tenantmodel_timestamps'),
        ('sav', '0050_alter_equipement_client_vente_and_more'),
        ('stock', '0100_ntwms21_seuil_approbation_transfert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('en_transit', 'En transit'), ('receptionne', 'Réceptionné'), ('inspecte', 'Inspecté'), ('clos', 'Clos')], default='demande', max_length=20)),
                ('motif', models.TextField(blank=True, default='')),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('date_inspection', models.DateTimeField(blank=True, null=True)),
                ('chantier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_entrepot', to='installations.installation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retours_entrepot', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_client_crees', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_entrepot', to='sav.ticket')),
            ],
            options={
                'verbose_name': 'Retour client (RMA)',
                'verbose_name_plural': 'Retours client (RMA)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneRetourClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('etat_constate', models.CharField(choices=[('revendable', 'Revendable'), ('a_reparer', 'À réparer'), ('rebut', 'Rebut')], default='revendable', max_length=20)),
                ('stock_mouvemente', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_retour_client', to='installations.binlocation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_retour_client', to='stock.produit')),
                ('retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.retourclient')),
            ],
            options={
                'verbose_name': 'Ligne de retour client',
                'verbose_name_plural': 'Lignes de retour client',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='retourclient',
            index=models.Index(fields=['company', 'statut'], name='idx_retourclient_co_statut'),
        ),
        migrations.AddConstraint(
            model_name='retourclient',
            constraint=models.UniqueConstraint(fields=('company', 'reference'), name='stock_retourclient_company_reference_uniq'),
        ),
        migrations.AddIndex(
            model_name='ligneretourclient',
            index=models.Index(fields=['company', 'retour'], name='idx_ligneretcli_co_retour'),
        ),
    ]
