# Generated by Django 5.1.4 on 2026-08-14 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('installations', '0100_photochecklistmeta_tenantmodel_timestamps'),
        ('stock', '0101_ntwms23_retour_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementRebut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('motif', models.CharField(choices=[('casse', 'Casse'), ('perime', 'Périmé'), ('vol', 'Vol'), ('erreur_reception', 'Erreur de réception')], max_length=20)),
                ('valeur_perte', models.DecimalField(decimal_places=2, default=0, help_text='Coût moyen × quantité au moment de la déclaration (INTERNE, jamais client-facing).', max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('bin', models.ForeignKey(blank=True, help_text="Casier d'où sort la marchandise perdue.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_rebut', to='installations.binlocation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('declare_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_rebut_declares', to=settings.AUTH_USER_MODEL)),
                ('mouvement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebuts_declares', to='stock.mouvementstock')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_rebut', to='stock.produit')),
            ],
            options={
                'verbose_name': 'Déclaration de rebut',
                'verbose_name_plural': 'Déclarations de rebut',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'motif'], name='idx_mvtrebut_co_motif')],
            },
        ),
    ]
