# Generated by Django 5.1.4 on 2026-08-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0100_photochecklistmeta_tenantmodel_timestamps'),
        ('stock', '0102_ntwms24_mouvement_rebut'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementstock',
            name='unite_logistique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='stock.unitelogistique'),
        ),
        migrations.AddField(
            model_name='unitelogistique',
            name='bin_actuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_logistiques', to='installations.binlocation'),
        ),
    ]
