# Generated by Django 5.1.4 on 2026-08-14 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_company_tours_actifs'),
        ('flotte', '0058_garage_contratvehicule_fournisseur_id_ref'),
        ('installations', '0100_photochecklistmeta_tenantmodel_timestamps'),
        ('stock', '0103_ntwms25_unite_logistique_mouvement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50)),
                ('capacite_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Charge utile du véhicule (kg). Vide = capacité inconnue, aucun dépassement ne peut être signalé.', max_digits=10, null=True)),
                ('capacite_m3', models.DecimalField(blank=True, decimal_places=3, help_text='Volume utile du véhicule (m³). Optionnel.', max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('charge', 'Chargé')], default='brouillon', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_chargement_crees', to=settings.AUTH_USER_MODEL)),
                ('expedition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_chargement', to='stock.expeditiontransporteur')),
                ('livraison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_chargement', to='installations.livraison')),
                ('unites_logistiques', models.ManyToManyField(blank=True, related_name='plans_chargement', to='stock.unitelogistique')),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_chargement_stock', to='flotte.vehicule')),
            ],
            options={
                'verbose_name': 'Plan de chargement',
                'verbose_name_plural': 'Plans de chargement',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_plancharg_co_statut')],
                'constraints': [models.UniqueConstraint(fields=('company', 'reference'), name='stock_planchargement_company_reference_uniq')],
            },
        ),
    ]
