# Generated by Django 5.1.4 on 2026-08-14 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0003_protect_fournisseur_prix'),
        ('authentication', '0028_company_tours_actifs'),
        ('installations', '0100_photochecklistmeta_tenantmodel_timestamps'),
        ('qhse', '0057_ntsan23_ncr_cycle_sterilisation'),
        ('stock', '0104_ntwms26_plan_chargement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocageQualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('en_quarantaine', 'En quarantaine'), ('levee', 'Levée'), ('rebutee', 'Rebutée')], default='en_quarantaine', max_length=20)),
                ('motif', models.TextField(blank=True, default='')),
                ('date_levee', models.DateTimeField(blank=True, null=True)),
                ('bin', models.ForeignKey(blank=True, help_text='Casier de quarantaine où la marchandise est isolée.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_qualite', to='installations.binlocation')),
                ('bloque_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_qualite_poses', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='authentication.company', verbose_name='Société')),
                ('leve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_qualite_leves', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_qualite', to='stock.lotentrepot')),
                ('non_conformite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_qualite_stock', to='qhse.nonconformite')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocages_qualite', to='stock.produit')),
                ('reception', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocages_qualite', to='achats.receptionfournisseur')),
            ],
            options={
                'verbose_name': 'Blocage qualité (quarantaine)',
                'verbose_name_plural': 'Blocages qualité (quarantaine)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'statut'], name='idx_blocqual_co_statut'), models.Index(fields=['company', 'produit'], name='idx_blocqual_co_produit')],
            },
        ),
    ]
