# Generated by Django 5.1.4 on 2026-08-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0096_pv5_fiche_technique_specs'),
        ('stock', '0105_ntwms31_blocage_qualite'),
    ]

    operations = [
    ]
