# Generated by Django 5.1.4 on 2026-09-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0140_aud233_rapprochement_3voies_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetechnique',
            name='pdf_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nom du fichier'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pdf_key',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Clé de stockage'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pdf_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Type MIME'),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pdf_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Taille (octets)'),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='pdf',
            field=models.FileField(blank=True, help_text='Fiche technique PDF du constructeur (legacy, hors MinIO).', null=True, upload_to='stock/fiches_techniques/%Y/%m/'),
        ),
    ]
