# Generated by Django 5.1.15 on 2026-10-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0160_agr100_produit_pompage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichetechnique',
            name='pompe_diametre_ext_mm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pompe — diamètre extérieur (mm). Vide = non publié.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pompe_hmt_nominale_m',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pompe — HMT au débit nominal (m). Vide = non publié.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pompe_i_nominal_a',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pompe — courant nominal (A). Vide = non publié.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pompe_immersion_min_m',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pompe — immersion minimale (m). Vide = non publié.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pompe_nb_etages',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Pompe — nombre d'étages. Vide = non publié.", null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pompe_q_nominal_m3h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pompe — débit nominal (m³/h). Vide = non publié.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='pompe_rendement_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pompe — rendement au point nominal (%). Vide = non publié.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='var_i_sortie_nominal_a',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Variateur — courant de sortie nominal (A).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='var_protection_marche_a_sec',
            field=models.BooleanField(blank=True, help_text='Variateur — protection marche à sec intégrée (vide = non publié).', null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='var_rendement_mppt_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Variateur — rendement MPPT (%). Vide = non publié.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='var_v_sortie_v',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Variateur — tension de sortie vers la pompe (V).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='var_voc_reco_max_v',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Variateur — Voc recommandée maxi du champ (V).', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='fichetechnique',
            name='var_voc_reco_min_v',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Variateur — Voc recommandée mini du champ (V).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fichetechnique',
            name='type_fiche',
            field=models.CharField(blank=True, choices=[('module', 'Module (panneau)'), ('onduleur', 'Onduleur'), ('batterie', 'Batterie'), ('optimiseur', 'Optimiseur / micro-onduleur'), ('pompe', 'Pompe'), ('variateur_pompage', 'Variateur de pompage'), ('autre', 'Autre')], default='', help_text='Type de fiche technique (détermine les champs applicables).', max_length=24),
        ),
    ]
