# Generated by Django 5.1.15 on 2026-10-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achats', '0007_astk59_quantite_appliquee'),
        ('stock', '0169_mouvementstock_mouvementstock_quantite_non_negative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imputationavoirfournisseur',
            name='avoir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputations', to='stock.avoirfournisseur'),
        ),
        migrations.AlterField(
            model_name='imputationavoirfournisseur',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avoirs_imputes', to='achats.facturefournisseur'),
        ),
    ]
