# Generated by Django 5.1.4 on 2026-06-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0008_customuser_avatar_key_customuser_poste"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KbArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "corps",
                    models.TextField(blank=True, default="", verbose_name="Contenu"),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Catégorie",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Tags"
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("obsolete", "Obsolète"),
                        ],
                        default="brouillon",
                        max_length=15,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "date_modification",
                    models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kb_app_articles",
                        to="authentication.company",
                        verbose_name="Société",
                    ),
                ),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="kb_app_articles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Auteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-id"],
            },
        ),
    ]
