# Generated by Django 5.1.4 on 2026-06-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_kbarticlelien'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kbarticlelien',
            new_name='kb_kbarticl_company_f82478_idx',
            old_name='kb_kbarticl_company_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='kbarticleversion',
            new_name='kb_kbarticl_company_cfbaf3_idx',
            old_name='kb_kbarticl_company_idx',
        ),
        migrations.RenameIndex(
            model_name='kbarticleversion',
            new_name='kb_kbarticl_article_edaf37_idx',
            old_name='kb_kbarticl_article_idx',
        ),
    ]
