# Generated by Django 5.1.4 on 2026-07-03 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
        ('kb', '0015_kb_stats_recherches_vides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kbarticleacl',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='kbarticleacl',
            constraint=models.UniqueConstraint(condition=models.Q(('role', ''), _negated=True), fields=('article', 'role', 'niveau'), name='kb_acl_role_niveau_uniq'),
        ),
        migrations.AddConstraint(
            model_name='kbarticleacl',
            constraint=models.UniqueConstraint(condition=models.Q(('utilisateur__isnull', False)), fields=('article', 'utilisateur', 'niveau'), name='kb_acl_user_niveau_uniq'),
        ),
    ]
