# Generated by Django 5.1.4 on 2026-07-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataimport', '0002_importmapping_importjob_importjobrow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='externalref',
            new_name='dataimport__content_15caa2_idx',
            old_name='dataimport__content_45a3e1_idx',
        ),
        migrations.RenameIndex(
            model_name='importjob',
            new_name='dataimport__company_d66bc3_idx',
            old_name='dataimport__company_5d1e2a_idx',
        ),
        migrations.RenameIndex(
            model_name='importjobrow',
            new_name='dataimport__job_id_cef325_idx',
            old_name='dataimport__job_id_9b1c3a_idx',
        ),
    ]
