# Generated by Django 5.2.14 on 2026-05-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('responsable', 'Utilisateur Responsable'), ('normal', 'Utilisateur Normal')], default='normal', max_length=20),
        ),
    ]
