# Generated by Django 5.2.14 on 2026-05-19 18:46

from django.db import migrations, models


def copy_role_to_legacy(apps, schema_editor):
    """Copy existing role CharField value into role_legacy before FK change."""
    CustomUser = apps.get_model('authentication', 'CustomUser')
    CustomUser.objects.filter(
        role_legacy='normal'
    ).update(role_legacy=models.F('role'))


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_company_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_legacy',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrateur'),
                    ('responsable', 'Utilisateur Responsable'),
                    ('normal', 'Utilisateur Normal'),
                ],
                default='normal',
                max_length=20,
            ),
        ),
        migrations.RunPython(
            copy_role_to_legacy,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
