# Generated by Django 5.2.14 on 2026-05-19 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Change CustomUser.role from CharField to ForeignKey(roles.Role).

    PostgreSQL cannot cast VARCHAR values ('admin', 'normal', ...) to bigint,
    so we use SeparateDatabaseAndState to:
      - DB: drop the old VARCHAR column and add a fresh nullable bigint FK
      - State: record the field change in Django's migration graph
    Data was already preserved in role_legacy by migration 0004.
    """

    dependencies = [
        ('authentication', '0004_customuser_role_legacy'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE "authentication_customuser" DROP COLUMN "role";
                        ALTER TABLE "authentication_customuser"
                            ADD COLUMN "role_id" bigint NULL
                            REFERENCES "roles_role"("id")
                            DEFERRABLE INITIALLY DEFERRED;
                        CREATE INDEX "authentication_customuser_role_id_idx"
                            ON "authentication_customuser" ("role_id");
                    """,
                    reverse_sql="""
                        DROP INDEX IF EXISTS
                            "authentication_customuser_role_id_idx";
                        ALTER TABLE "authentication_customuser"
                            DROP COLUMN IF EXISTS "role_id";
                        ALTER TABLE "authentication_customuser"
                            ADD COLUMN "role" varchar(20) NOT NULL DEFAULT 'normal';
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='customuser',
                    name='role',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='users',
                        to='roles.role',
                    ),
                ),
            ],
        ),
    ]
