# Generated by Django 5.1.4 on 2026-06-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
