# Generated by Django 5.1.4 on 2026-06-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_mark_owner_protected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='customuser',
            name='poste',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
