# Generated by Django 5.1.4 on 2026-06-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0010_customuser_supervisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="totp_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="totp_recovery_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customuser",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
