# Generated by Django 5.1.4 on 2026-07-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_customuser_account_lockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='societes_autorisees',
            field=models.ManyToManyField(blank=True, related_name='membres_autorises', to='authentication.company', verbose_name='Sociétés autorisées'),
        ),
    ]
