# Generated by Django 5.1.4 on 2026-07-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_backfill_societes_autorisees'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_fermeture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise en fermeture'),
        ),
        migrations.AddField(
            model_name='company',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('fermeture', 'En fermeture')], default='actif', help_text="Cycle de vie du tenant : seul « actif » autorise login/API. « suspendu »/« en fermeture » bloquent l'accès (rule SCA18).", max_length=12, verbose_name='Statut du compte'),
        ),
    ]
