# Generated by Django 5.1.4 on 2026-07-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_backfill_company_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='plan_flag',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Note de plan (fondateur)'),
        ),
    ]
