# Generated by Django 5.1.4 on 2026-07-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_company_plan_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='benchmarking_opt_in',
            field=models.BooleanField(default=False, verbose_name='Consentement benchmarking anonymisé'),
        ),
    ]
